package kntr.app.ad.common.model;

import com.bapis.bilibili.app.dynamic.v2.AdditionVote2;
import java.util.List;
import kntr.app.game.base.ui.widget.gameaction.state.GameActionStateKt;
import kntr.app.live.room.recommend.RoomRecommendViewModel;
import kotlin.Deprecated;
import kotlin.DeprecationLevel;
import kotlin.Lazy;
import kotlin.Metadata;
import kotlin.Unit;
import kotlin.jvm.internal.Intrinsics;
import kotlinx.serialization.DeserializationStrategy;
import kotlinx.serialization.KSerializer;
import kotlinx.serialization.UnknownFieldException;
import kotlinx.serialization.builtins.BuiltinSerializersKt;
import kotlinx.serialization.descriptors.SerialDescriptor;
import kotlinx.serialization.encoding.CompositeDecoder;
import kotlinx.serialization.encoding.CompositeEncoder;
import kotlinx.serialization.encoding.Decoder;
import kotlinx.serialization.encoding.Encoder;
import kotlinx.serialization.internal.BooleanSerializer;
import kotlinx.serialization.internal.GeneratedSerializer;
import kotlinx.serialization.internal.LongSerializer;
import kotlinx.serialization.internal.PluginGeneratedSerialDescriptor;
import kotlinx.serialization.internal.StringSerializer;

/* compiled from: AdSubCardModule.kt */
@Metadata(d1 = {"\u00006\n\u0000\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\b\u0003\n\u0002\u0010\u0011\n\u0002\u0018\u0002\n\u0002\b\u0003\n\u0002\u0018\u0002\n\u0000\n\u0002\u0010\u0002\n\u0000\n\u0002\u0018\u0002\n\u0002\b\u0002\n\u0002\u0018\u0002\n\u0002\b\u0003\bÇ\u0002\u0018\u00002\b\u0012\u0004\u0012\u00020\u00020\u0001B\t\b\u0002¢\u0006\u0004\b\u0003\u0010\u0004J\u0015\u0010\u0005\u001a\f\u0012\b\u0012\u0006\u0012\u0002\b\u00030\u00070\u0006¢\u0006\u0002\u0010\bJ\u000e\u0010\t\u001a\u00020\u00022\u0006\u0010\n\u001a\u00020\u000bJ\u0016\u0010\f\u001a\u00020\r2\u0006\u0010\u000e\u001a\u00020\u000f2\u0006\u0010\u0010\u001a\u00020\u0002R\u0011\u0010\u0011\u001a\u00020\u0012¢\u0006\b\n\u0000\u001a\u0004\b\u0013\u0010\u0014¨\u0006\u0015"}, d2 = {"kntr/app/ad/common/model/AdSubCardModule.$serializer", "Lkotlinx/serialization/internal/GeneratedSerializer;", "Lkntr/app/ad/common/model/AdSubCardModule;", "<init>", "()V", "childSerializers", RoomRecommendViewModel.EMPTY_CURSOR, "Lkotlinx/serialization/KSerializer;", "()[Lkotlinx/serialization/KSerializer;", "deserialize", "decoder", "Lkotlinx/serialization/encoding/Decoder;", "serialize", RoomRecommendViewModel.EMPTY_CURSOR, "encoder", "Lkotlinx/serialization/encoding/Encoder;", "value", "descriptor", "Lkotlinx/serialization/descriptors/SerialDescriptor;", "getDescriptor", "()Lkotlinx/serialization/descriptors/SerialDescriptor;", "dto_debug"}, k = 1, mv = {2, 2, 0}, xi = 48)
@Deprecated(level = DeprecationLevel.HIDDEN, message = "This synthesized declaration should not be used directly")
public final /* synthetic */ class AdSubCardModule$$serializer implements GeneratedSerializer<AdSubCardModule> {
    public static final AdSubCardModule$$serializer INSTANCE = new AdSubCardModule$$serializer();
    private static final SerialDescriptor descriptor;

    public final SerialDescriptor getDescriptor() {
        return descriptor;
    }

    static {
        SerialDescriptor pluginGeneratedSerialDescriptor = new PluginGeneratedSerialDescriptor("kntr.app.ad.common.model.AdSubCardModule", INSTANCE, 32);
        pluginGeneratedSerialDescriptor.addElement("next_subcard", true);
        pluginGeneratedSerialDescriptor.addElement("subcard_type", true);
        pluginGeneratedSerialDescriptor.addElement("icon", true);
        pluginGeneratedSerialDescriptor.addElement("nightIcon", true);
        pluginGeneratedSerialDescriptor.addElement("avatar", true);
        pluginGeneratedSerialDescriptor.addElement("title", true);
        pluginGeneratedSerialDescriptor.addElement("desc", true);
        pluginGeneratedSerialDescriptor.addElement("tagInfos", true);
        pluginGeneratedSerialDescriptor.addElement("rankStars", true);
        pluginGeneratedSerialDescriptor.addElement("amountNumber", true);
        pluginGeneratedSerialDescriptor.addElement("button", true);
        pluginGeneratedSerialDescriptor.addElement("qualityInfos", true);
        pluginGeneratedSerialDescriptor.addElement("subDesc", true);
        pluginGeneratedSerialDescriptor.addElement("starRating", true);
        pluginGeneratedSerialDescriptor.addElement("priceDesc", true);
        pluginGeneratedSerialDescriptor.addElement("priceSymbol", true);
        pluginGeneratedSerialDescriptor.addElement("ori_price", true);
        pluginGeneratedSerialDescriptor.addElement("goodsPrice", true);
        pluginGeneratedSerialDescriptor.addElement("comment_list", true);
        pluginGeneratedSerialDescriptor.addElement("giftCardInfo", true);
        pluginGeneratedSerialDescriptor.addElement("extraImg", true);
        pluginGeneratedSerialDescriptor.addElement("choose_button_list", true);
        pluginGeneratedSerialDescriptor.addElement("popDelayTime", true);
        pluginGeneratedSerialDescriptor.addElement("jumpUrl", true);
        pluginGeneratedSerialDescriptor.addElement("callup_url", true);
        pluginGeneratedSerialDescriptor.addElement("adImgTag", true);
        pluginGeneratedSerialDescriptor.addElement("fullText", true);
        pluginGeneratedSerialDescriptor.addElement("wxProgramInfo", true);
        pluginGeneratedSerialDescriptor.addElement("forwardReply", true);
        pluginGeneratedSerialDescriptor.addElement("animDelayTime", true);
        pluginGeneratedSerialDescriptor.addElement("showCloseButton", true);
        pluginGeneratedSerialDescriptor.addElement("easterEggVideo", true);
        descriptor = pluginGeneratedSerialDescriptor;
    }

    private AdSubCardModule$$serializer() {
    }

    public final KSerializer<?>[] childSerializers() {
        Lazy[] lazyArr;
        lazyArr = AdSubCardModule.$childSerializers;
        return new KSerializer[]{BuiltinSerializersKt.getNullable(INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable((KSerializer) lazyArr[7].getValue()), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(AdButton$$serializer.INSTANCE), BuiltinSerializersKt.getNullable((KSerializer) lazyArr[11].getValue()), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable((KSerializer) lazyArr[18].getValue()), BuiltinSerializersKt.getNullable(AdGiftCardInfo$$serializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable((KSerializer) lazyArr[21].getValue()), LongSerializer.INSTANCE, BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(AdFullText$$serializer.INSTANCE), BuiltinSerializersKt.getNullable(AdWxProgramInfo$$serializer.INSTANCE), BuiltinSerializersKt.getNullable(AdForwardReply$$serializer.INSTANCE), LongSerializer.INSTANCE, BuiltinSerializersKt.getNullable(BooleanSerializer.INSTANCE), BuiltinSerializersKt.getNullable(AdVideo$$serializer.INSTANCE)};
    }

    public final AdSubCardModule deserialize(Decoder decoder) {
        Lazy[] lazyArr;
        Boolean bool;
        AdWxProgramInfo adWxProgramInfo;
        List list;
        AdForwardReply adForwardReply;
        String str;
        String str2;
        String str3;
        AdVideo adVideo;
        AdFullText adFullText;
        String str4;
        String str5;
        String str6;
        String str7;
        List list2;
        String str8;
        String str9;
        long j2;
        long j3;
        List list3;
        AdGiftCardInfo adGiftCardInfo;
        String str10;
        String str11;
        int i;
        String str12;
        String str13;
        String str14;
        String str15;
        AdSubCardModule adSubCardModule;
        AdButton adButton;
        String str16;
        String str17;
        List list4;
        String str18;
        String str19;
        Lazy[] lazyArr2;
        AdFullText adFullText2;
        String str20;
        AdGiftCardInfo adGiftCardInfo2;
        String str21;
        String str22;
        String str23;
        String str24;
        String str25;
        String str26;
        List list5;
        String str27;
        String str28;
        AdButton adButton2;
        List list6;
        String str29;
        String str30;
        String str31;
        String str32;
        String str33;
        String str34;
        AdGiftCardInfo adGiftCardInfo3;
        String str35;
        String str36;
        AdButton adButton3;
        String str37;
        AdGiftCardInfo adGiftCardInfo4;
        AdGiftCardInfo adGiftCardInfo5;
        int i2;
        Intrinsics.checkNotNullParameter(decoder, "decoder");
        SerialDescriptor serialDescriptor = descriptor;
        CompositeDecoder beginStructure = decoder.beginStructure(serialDescriptor);
        lazyArr = AdSubCardModule.$childSerializers;
        if (beginStructure.decodeSequentially()) {
            AdButton adButton4 = (AdButton) beginStructure.decodeNullableSerializableElement(serialDescriptor, 10, AdButton$$serializer.INSTANCE, (Object) null);
            List list7 = (List) beginStructure.decodeNullableSerializableElement(serialDescriptor, 11, (DeserializationStrategy) lazyArr[11].getValue(), (Object) null);
            String str38 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 12, StringSerializer.INSTANCE, (Object) null);
            String str39 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 13, StringSerializer.INSTANCE, (Object) null);
            String str40 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 14, StringSerializer.INSTANCE, (Object) null);
            String str41 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 15, StringSerializer.INSTANCE, (Object) null);
            String str42 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 16, StringSerializer.INSTANCE, (Object) null);
            String str43 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 17, StringSerializer.INSTANCE, (Object) null);
            List list8 = (List) beginStructure.decodeNullableSerializableElement(serialDescriptor, 18, (DeserializationStrategy) lazyArr[18].getValue(), (Object) null);
            AdGiftCardInfo adGiftCardInfo6 = (AdGiftCardInfo) beginStructure.decodeNullableSerializableElement(serialDescriptor, 19, AdGiftCardInfo$$serializer.INSTANCE, (Object) null);
            String str44 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 20, StringSerializer.INSTANCE, (Object) null);
            long decodeLongElement = beginStructure.decodeLongElement(serialDescriptor, 22);
            String str45 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 23, StringSerializer.INSTANCE, (Object) null);
            String str46 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 24, StringSerializer.INSTANCE, (Object) null);
            String str47 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 25, StringSerializer.INSTANCE, (Object) null);
            AdFullText adFullText3 = (AdFullText) beginStructure.decodeNullableSerializableElement(serialDescriptor, 26, AdFullText$$serializer.INSTANCE, (Object) null);
            AdWxProgramInfo adWxProgramInfo2 = (AdWxProgramInfo) beginStructure.decodeNullableSerializableElement(serialDescriptor, 27, AdWxProgramInfo$$serializer.INSTANCE, (Object) null);
            AdForwardReply adForwardReply2 = (AdForwardReply) beginStructure.decodeNullableSerializableElement(serialDescriptor, 28, AdForwardReply$$serializer.INSTANCE, (Object) null);
            long decodeLongElement2 = beginStructure.decodeLongElement(serialDescriptor, 29);
            Boolean bool2 = (Boolean) beginStructure.decodeNullableSerializableElement(serialDescriptor, 30, BooleanSerializer.INSTANCE, (Object) null);
            adVideo = (AdVideo) beginStructure.decodeNullableSerializableElement(serialDescriptor, 31, AdVideo$$serializer.INSTANCE, (Object) null);
            list = (List) beginStructure.decodeNullableSerializableElement(serialDescriptor, 21, (DeserializationStrategy) lazyArr[21].getValue(), (Object) null);
            str2 = str44;
            adGiftCardInfo = adGiftCardInfo6;
            j2 = decodeLongElement;
            str9 = str45;
            str = str46;
            str10 = str47;
            adFullText = adFullText3;
            adWxProgramInfo = adWxProgramInfo2;
            j3 = decodeLongElement2;
            adForwardReply = adForwardReply2;
            bool = bool2;
            str11 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 8, StringSerializer.INSTANCE, (Object) null);
            str5 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 1, StringSerializer.INSTANCE, (Object) null);
            list2 = (List) beginStructure.decodeNullableSerializableElement(serialDescriptor, 7, (DeserializationStrategy) lazyArr[7].getValue(), (Object) null);
            str8 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 9, StringSerializer.INSTANCE, (Object) null);
            list3 = list8;
            str12 = str42;
            str13 = str41;
            str4 = str40;
            str3 = str43;
            str14 = str39;
            str16 = str38;
            list4 = list7;
            adButton = adButton4;
            adSubCardModule = (AdSubCardModule) beginStructure.decodeNullableSerializableElement(serialDescriptor, 0, INSTANCE, (Object) null);
            str6 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 2, StringSerializer.INSTANCE, (Object) null);
            str7 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 3, StringSerializer.INSTANCE, (Object) null);
            i = -1;
            str18 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 6, StringSerializer.INSTANCE, (Object) null);
            str17 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 5, StringSerializer.INSTANCE, (Object) null);
            str15 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 4, StringSerializer.INSTANCE, (Object) null);
        } else {
            boolean z = true;
            String str48 = null;
            AdFullText adFullText4 = null;
            String str49 = null;
            Boolean bool3 = null;
            List list9 = null;
            AdForwardReply adForwardReply3 = null;
            String str50 = null;
            String str51 = null;
            AdGiftCardInfo adGiftCardInfo7 = null;
            AdVideo adVideo2 = null;
            List list10 = null;
            AdSubCardModule adSubCardModule2 = null;
            String str52 = null;
            String str53 = null;
            String str54 = null;
            String str55 = null;
            String str56 = null;
            String str57 = null;
            List list11 = null;
            String str58 = null;
            String str59 = null;
            AdButton adButton5 = null;
            List list12 = null;
            String str60 = null;
            String str61 = null;
            String str62 = null;
            String str63 = null;
            String str64 = null;
            String str65 = null;
            long j4 = 0;
            long j5 = 0;
            int i3 = 0;
            AdWxProgramInfo adWxProgramInfo3 = null;
            while (z) {
                List list13 = list10;
                int decodeElementIndex = beginStructure.decodeElementIndex(serialDescriptor);
                switch (decodeElementIndex) {
                    case GameActionStateKt.ACTION_UNDEFINE /* -1 */:
                        str19 = str48;
                        lazyArr2 = lazyArr;
                        adFullText2 = adFullText4;
                        str20 = str49;
                        adGiftCardInfo2 = adGiftCardInfo7;
                        str21 = str52;
                        str22 = str53;
                        str23 = str54;
                        str24 = str55;
                        str25 = str56;
                        str26 = str57;
                        list5 = list11;
                        str27 = str58;
                        str28 = str59;
                        adButton2 = adButton5;
                        list6 = list12;
                        str29 = str60;
                        str30 = str61;
                        str31 = str62;
                        str32 = str63;
                        str33 = str64;
                        Unit unit = Unit.INSTANCE;
                        z = false;
                        adFullText4 = adFullText2;
                        adGiftCardInfo7 = adGiftCardInfo2;
                        str48 = str19;
                        str35 = str27;
                        str49 = str20;
                        break;
                    case 0:
                        str19 = str48;
                        lazyArr2 = lazyArr;
                        adFullText2 = adFullText4;
                        str20 = str49;
                        adGiftCardInfo2 = adGiftCardInfo7;
                        str22 = str53;
                        str23 = str54;
                        str24 = str55;
                        str25 = str56;
                        str26 = str57;
                        list5 = list11;
                        str27 = str58;
                        str28 = str59;
                        adButton2 = adButton5;
                        list6 = list12;
                        str29 = str60;
                        str30 = str61;
                        str31 = str62;
                        str32 = str63;
                        str33 = str64;
                        str21 = str52;
                        i3 |= 1;
                        Unit unit2 = Unit.INSTANCE;
                        adSubCardModule2 = (AdSubCardModule) beginStructure.decodeNullableSerializableElement(serialDescriptor, 0, INSTANCE, adSubCardModule2);
                        adFullText4 = adFullText2;
                        adGiftCardInfo7 = adGiftCardInfo2;
                        str48 = str19;
                        str35 = str27;
                        str49 = str20;
                        break;
                    case 1:
                        str34 = str48;
                        lazyArr2 = lazyArr;
                        str20 = str49;
                        adGiftCardInfo3 = adGiftCardInfo7;
                        str23 = str54;
                        str24 = str55;
                        str25 = str56;
                        str26 = str57;
                        list5 = list11;
                        str27 = str58;
                        str28 = str59;
                        adButton2 = adButton5;
                        list6 = list12;
                        str29 = str60;
                        str30 = str61;
                        str31 = str62;
                        str32 = str63;
                        str33 = str64;
                        str22 = str53;
                        i3 |= 2;
                        Unit unit3 = Unit.INSTANCE;
                        str21 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 1, StringSerializer.INSTANCE, str52);
                        adFullText4 = adFullText4;
                        adGiftCardInfo7 = adGiftCardInfo3;
                        str48 = str34;
                        str35 = str27;
                        str49 = str20;
                        break;
                    case 2:
                        str34 = str48;
                        lazyArr2 = lazyArr;
                        AdFullText adFullText5 = adFullText4;
                        str20 = str49;
                        adGiftCardInfo3 = adGiftCardInfo7;
                        str24 = str55;
                        str25 = str56;
                        str26 = str57;
                        list5 = list11;
                        str27 = str58;
                        str28 = str59;
                        adButton2 = adButton5;
                        list6 = list12;
                        str29 = str60;
                        str30 = str61;
                        str31 = str62;
                        str32 = str63;
                        str33 = str64;
                        str23 = str54;
                        i3 |= 4;
                        Unit unit4 = Unit.INSTANCE;
                        str22 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 2, StringSerializer.INSTANCE, str53);
                        adFullText4 = adFullText5;
                        str21 = str52;
                        adGiftCardInfo7 = adGiftCardInfo3;
                        str48 = str34;
                        str35 = str27;
                        str49 = str20;
                        break;
                    case 3:
                        str34 = str48;
                        lazyArr2 = lazyArr;
                        str20 = str49;
                        adGiftCardInfo3 = adGiftCardInfo7;
                        str25 = str56;
                        str26 = str57;
                        list5 = list11;
                        str27 = str58;
                        str28 = str59;
                        adButton2 = adButton5;
                        list6 = list12;
                        str29 = str60;
                        str30 = str61;
                        str31 = str62;
                        str32 = str63;
                        str33 = str64;
                        str24 = str55;
                        i3 |= 8;
                        Unit unit5 = Unit.INSTANCE;
                        str23 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 3, StringSerializer.INSTANCE, str54);
                        adFullText4 = adFullText4;
                        str21 = str52;
                        str22 = str53;
                        adGiftCardInfo7 = adGiftCardInfo3;
                        str48 = str34;
                        str35 = str27;
                        str49 = str20;
                        break;
                    case 4:
                        str34 = str48;
                        lazyArr2 = lazyArr;
                        AdFullText adFullText6 = adFullText4;
                        str20 = str49;
                        adGiftCardInfo3 = adGiftCardInfo7;
                        str26 = str57;
                        list5 = list11;
                        str27 = str58;
                        str28 = str59;
                        adButton2 = adButton5;
                        list6 = list12;
                        str29 = str60;
                        str30 = str61;
                        str31 = str62;
                        str32 = str63;
                        str33 = str64;
                        str25 = str56;
                        i3 |= 16;
                        Unit unit6 = Unit.INSTANCE;
                        str24 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 4, StringSerializer.INSTANCE, str55);
                        adFullText4 = adFullText6;
                        str21 = str52;
                        str22 = str53;
                        str23 = str54;
                        adGiftCardInfo7 = adGiftCardInfo3;
                        str48 = str34;
                        str35 = str27;
                        str49 = str20;
                        break;
                    case 5:
                        str34 = str48;
                        lazyArr2 = lazyArr;
                        str20 = str49;
                        adGiftCardInfo3 = adGiftCardInfo7;
                        list5 = list11;
                        str27 = str58;
                        str28 = str59;
                        adButton2 = adButton5;
                        list6 = list12;
                        str29 = str60;
                        str30 = str61;
                        str31 = str62;
                        str32 = str63;
                        str33 = str64;
                        str26 = str57;
                        i3 |= 32;
                        Unit unit7 = Unit.INSTANCE;
                        str25 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 5, StringSerializer.INSTANCE, str56);
                        adFullText4 = adFullText4;
                        str21 = str52;
                        str22 = str53;
                        str23 = str54;
                        str24 = str55;
                        adGiftCardInfo7 = adGiftCardInfo3;
                        str48 = str34;
                        str35 = str27;
                        str49 = str20;
                        break;
                    case 6:
                        str34 = str48;
                        lazyArr2 = lazyArr;
                        AdFullText adFullText7 = adFullText4;
                        str20 = str49;
                        adGiftCardInfo3 = adGiftCardInfo7;
                        str27 = str58;
                        str28 = str59;
                        adButton2 = adButton5;
                        list6 = list12;
                        str29 = str60;
                        str30 = str61;
                        str31 = str62;
                        str32 = str63;
                        str33 = str64;
                        list5 = list11;
                        i3 |= 64;
                        Unit unit8 = Unit.INSTANCE;
                        str26 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 6, StringSerializer.INSTANCE, str57);
                        adFullText4 = adFullText7;
                        str21 = str52;
                        str22 = str53;
                        str23 = str54;
                        str24 = str55;
                        str25 = str56;
                        adGiftCardInfo7 = adGiftCardInfo3;
                        str48 = str34;
                        str35 = str27;
                        str49 = str20;
                        break;
                    case 7:
                        str34 = str48;
                        str20 = str49;
                        adGiftCardInfo3 = adGiftCardInfo7;
                        str27 = str58;
                        str28 = str59;
                        adButton2 = adButton5;
                        list6 = list12;
                        str29 = str60;
                        str30 = str61;
                        str31 = str62;
                        str32 = str63;
                        str33 = str64;
                        DeserializationStrategy deserializationStrategy = (DeserializationStrategy) lazyArr[7].getValue();
                        lazyArr2 = lazyArr;
                        i3 |= 128;
                        Unit unit9 = Unit.INSTANCE;
                        list5 = (List) beginStructure.decodeNullableSerializableElement(serialDescriptor, 7, deserializationStrategy, list11);
                        adFullText4 = adFullText4;
                        str21 = str52;
                        str22 = str53;
                        str23 = str54;
                        str24 = str55;
                        str25 = str56;
                        str26 = str57;
                        adGiftCardInfo7 = adGiftCardInfo3;
                        str48 = str34;
                        str35 = str27;
                        str49 = str20;
                        break;
                    case 8:
                        String str66 = str49;
                        list6 = list12;
                        str29 = str60;
                        str30 = str61;
                        str31 = str62;
                        str32 = str63;
                        str28 = str59;
                        i3 |= 256;
                        Unit unit10 = Unit.INSTANCE;
                        lazyArr2 = lazyArr;
                        str49 = str66;
                        str21 = str52;
                        str22 = str53;
                        str23 = str54;
                        str24 = str55;
                        str25 = str56;
                        str26 = str57;
                        list5 = list11;
                        adGiftCardInfo7 = adGiftCardInfo7;
                        str48 = str48;
                        str36 = str64;
                        adButton3 = adButton5;
                        list10 = list13;
                        str35 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 8, StringSerializer.INSTANCE, str58);
                        adFullText4 = adFullText4;
                        continue;
                        str58 = str35;
                        adButton5 = adButton3;
                        str63 = str32;
                        str62 = str31;
                        str61 = str30;
                        str60 = str29;
                        list12 = list6;
                        str52 = str21;
                        str53 = str22;
                        str54 = str23;
                        str55 = str24;
                        str56 = str25;
                        str57 = str26;
                        list11 = list5;
                        lazyArr = lazyArr2;
                        str59 = str28;
                        str64 = str36;
                    case 9:
                        AdFullText adFullText8 = adFullText4;
                        adButton2 = adButton5;
                        list6 = list12;
                        str29 = str60;
                        str30 = str61;
                        str31 = str62;
                        str32 = str63;
                        str33 = str64;
                        i3 |= 512;
                        Unit unit11 = Unit.INSTANCE;
                        str28 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 9, StringSerializer.INSTANCE, str59);
                        lazyArr2 = lazyArr;
                        adFullText4 = adFullText8;
                        str49 = str49;
                        str21 = str52;
                        str22 = str53;
                        str23 = str54;
                        str24 = str55;
                        str25 = str56;
                        str26 = str57;
                        list5 = list11;
                        str35 = str58;
                        adGiftCardInfo7 = adGiftCardInfo7;
                        str48 = str48;
                        break;
                    case 10:
                        str29 = str60;
                        str30 = str61;
                        str31 = str62;
                        str32 = str63;
                        list6 = list12;
                        i3 |= 1024;
                        Unit unit12 = Unit.INSTANCE;
                        lazyArr2 = lazyArr;
                        str36 = str64;
                        str21 = str52;
                        str22 = str53;
                        str23 = str54;
                        str24 = str55;
                        str25 = str56;
                        str26 = str57;
                        list5 = list11;
                        str28 = str59;
                        list10 = list13;
                        adGiftCardInfo7 = adGiftCardInfo7;
                        str48 = str48;
                        adButton3 = (AdButton) beginStructure.decodeNullableSerializableElement(serialDescriptor, 10, AdButton$$serializer.INSTANCE, adButton5);
                        adFullText4 = adFullText4;
                        str35 = str58;
                        continue;
                        str58 = str35;
                        adButton5 = adButton3;
                        str63 = str32;
                        str62 = str31;
                        str61 = str30;
                        str60 = str29;
                        list12 = list6;
                        str52 = str21;
                        str53 = str22;
                        str54 = str23;
                        str55 = str24;
                        str56 = str25;
                        str57 = str26;
                        list11 = list5;
                        lazyArr = lazyArr2;
                        str59 = str28;
                        str64 = str36;
                    case AdditionVote2.ADDITION_VOTE_PIC_FIELD_NUMBER /* 11 */:
                        str37 = str48;
                        AdFullText adFullText9 = adFullText4;
                        adGiftCardInfo4 = adGiftCardInfo7;
                        str30 = str61;
                        str31 = str62;
                        str32 = str63;
                        DeserializationStrategy deserializationStrategy2 = (DeserializationStrategy) lazyArr[11].getValue();
                        str29 = str60;
                        i3 |= 2048;
                        Unit unit13 = Unit.INSTANCE;
                        list6 = (List) beginStructure.decodeNullableSerializableElement(serialDescriptor, 11, deserializationStrategy2, list12);
                        lazyArr2 = lazyArr;
                        adFullText4 = adFullText9;
                        str36 = str64;
                        str21 = str52;
                        str22 = str53;
                        str23 = str54;
                        str24 = str55;
                        str25 = str56;
                        str26 = str57;
                        list5 = list11;
                        str35 = str58;
                        str28 = str59;
                        adButton3 = adButton5;
                        list10 = list13;
                        adGiftCardInfo7 = adGiftCardInfo4;
                        str48 = str37;
                        str58 = str35;
                        adButton5 = adButton3;
                        str63 = str32;
                        str62 = str31;
                        str61 = str30;
                        str60 = str29;
                        list12 = list6;
                        str52 = str21;
                        str53 = str22;
                        str54 = str23;
                        str55 = str24;
                        str56 = str25;
                        str57 = str26;
                        list11 = list5;
                        lazyArr = lazyArr2;
                        str59 = str28;
                        str64 = str36;
                    case AdditionVote2.ADDITION_VOTE_DEFAULE_FIELD_NUMBER /* 12 */:
                        str37 = str48;
                        adGiftCardInfo4 = adGiftCardInfo7;
                        str31 = str62;
                        str32 = str63;
                        str30 = str61;
                        i3 |= 4096;
                        Unit unit14 = Unit.INSTANCE;
                        str29 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 12, StringSerializer.INSTANCE, str60);
                        lazyArr2 = lazyArr;
                        adFullText4 = adFullText4;
                        str36 = str64;
                        str21 = str52;
                        str22 = str53;
                        str23 = str54;
                        str24 = str55;
                        str25 = str56;
                        str26 = str57;
                        list5 = list11;
                        str35 = str58;
                        str28 = str59;
                        adButton3 = adButton5;
                        list6 = list12;
                        list10 = list13;
                        adGiftCardInfo7 = adGiftCardInfo4;
                        str48 = str37;
                        str58 = str35;
                        adButton5 = adButton3;
                        str63 = str32;
                        str62 = str31;
                        str61 = str30;
                        str60 = str29;
                        list12 = list6;
                        str52 = str21;
                        str53 = str22;
                        str54 = str23;
                        str55 = str24;
                        str56 = str25;
                        str57 = str26;
                        list11 = list5;
                        lazyArr = lazyArr2;
                        str59 = str28;
                        str64 = str36;
                    case AdditionVote2.BIZ_TYPE_FIELD_NUMBER /* 13 */:
                        str37 = str48;
                        adGiftCardInfo4 = adGiftCardInfo7;
                        str32 = str63;
                        str31 = str62;
                        i3 |= 8192;
                        Unit unit15 = Unit.INSTANCE;
                        lazyArr2 = lazyArr;
                        str30 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 13, StringSerializer.INSTANCE, str61);
                        adFullText4 = adFullText4;
                        str36 = str64;
                        str21 = str52;
                        str22 = str53;
                        str23 = str54;
                        str24 = str55;
                        str25 = str56;
                        str26 = str57;
                        list5 = list11;
                        str35 = str58;
                        str28 = str59;
                        adButton3 = adButton5;
                        list6 = list12;
                        str29 = str60;
                        list10 = list13;
                        adGiftCardInfo7 = adGiftCardInfo4;
                        str48 = str37;
                        str58 = str35;
                        adButton5 = adButton3;
                        str63 = str32;
                        str62 = str31;
                        str61 = str30;
                        str60 = str29;
                        list12 = list6;
                        str52 = str21;
                        str53 = str22;
                        str54 = str23;
                        str55 = str24;
                        str56 = str25;
                        str57 = str26;
                        list11 = list5;
                        lazyArr = lazyArr2;
                        str59 = str28;
                        str64 = str36;
                    case AdditionVote2.TOTAL_FIELD_NUMBER /* 14 */:
                        str37 = str48;
                        adGiftCardInfo4 = adGiftCardInfo7;
                        str32 = str63;
                        i3 |= 16384;
                        Unit unit16 = Unit.INSTANCE;
                        str31 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 14, StringSerializer.INSTANCE, str62);
                        lazyArr2 = lazyArr;
                        adFullText4 = adFullText4;
                        str36 = str64;
                        str21 = str52;
                        str22 = str53;
                        str23 = str54;
                        str24 = str55;
                        str25 = str56;
                        str26 = str57;
                        list5 = list11;
                        str35 = str58;
                        str28 = str59;
                        adButton3 = adButton5;
                        list6 = list12;
                        str29 = str60;
                        str30 = str61;
                        list10 = list13;
                        adGiftCardInfo7 = adGiftCardInfo4;
                        str48 = str37;
                        str58 = str35;
                        adButton5 = adButton3;
                        str63 = str32;
                        str62 = str31;
                        str61 = str30;
                        str60 = str29;
                        list12 = list6;
                        str52 = str21;
                        str53 = str22;
                        str54 = str23;
                        str55 = str24;
                        str56 = str25;
                        str57 = str26;
                        list11 = list5;
                        lazyArr = lazyArr2;
                        str59 = str28;
                        str64 = str36;
                    case AdditionVote2.CARD_TYPE_FIELD_NUMBER /* 15 */:
                        str37 = str48;
                        adGiftCardInfo4 = adGiftCardInfo7;
                        i3 |= 32768;
                        Unit unit17 = Unit.INSTANCE;
                        lazyArr2 = lazyArr;
                        str32 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 15, StringSerializer.INSTANCE, str63);
                        adFullText4 = adFullText4;
                        str36 = str64;
                        str21 = str52;
                        str22 = str53;
                        str23 = str54;
                        str24 = str55;
                        str25 = str56;
                        str26 = str57;
                        list5 = list11;
                        str35 = str58;
                        str28 = str59;
                        adButton3 = adButton5;
                        list6 = list12;
                        str29 = str60;
                        str30 = str61;
                        str31 = str62;
                        list10 = list13;
                        adGiftCardInfo7 = adGiftCardInfo4;
                        str48 = str37;
                        str58 = str35;
                        adButton5 = adButton3;
                        str63 = str32;
                        str62 = str31;
                        str61 = str30;
                        str60 = str29;
                        list12 = list6;
                        str52 = str21;
                        str53 = str22;
                        str54 = str23;
                        str55 = str24;
                        str56 = str25;
                        str57 = str26;
                        list11 = list5;
                        lazyArr = lazyArr2;
                        str59 = str28;
                        str64 = str36;
                    case AdditionVote2.TIPS_FIELD_NUMBER /* 16 */:
                        str37 = str48;
                        adGiftCardInfo4 = adGiftCardInfo7;
                        i3 |= 65536;
                        Unit unit18 = Unit.INSTANCE;
                        str36 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 16, StringSerializer.INSTANCE, str64);
                        lazyArr2 = lazyArr;
                        adFullText4 = adFullText4;
                        str21 = str52;
                        str22 = str53;
                        str23 = str54;
                        str24 = str55;
                        str25 = str56;
                        str26 = str57;
                        list5 = list11;
                        str35 = str58;
                        str28 = str59;
                        adButton3 = adButton5;
                        list6 = list12;
                        str29 = str60;
                        str30 = str61;
                        str31 = str62;
                        str32 = str63;
                        list10 = list13;
                        adGiftCardInfo7 = adGiftCardInfo4;
                        str48 = str37;
                        str58 = str35;
                        adButton5 = adButton3;
                        str63 = str32;
                        str62 = str31;
                        str61 = str30;
                        str60 = str29;
                        list12 = list6;
                        str52 = str21;
                        str53 = str22;
                        str54 = str23;
                        str55 = str24;
                        str56 = str25;
                        str57 = str26;
                        list11 = list5;
                        lazyArr = lazyArr2;
                        str59 = str28;
                        str64 = str36;
                    case AdditionVote2.URI_FIELD_NUMBER /* 17 */:
                        str37 = str48;
                        adGiftCardInfo4 = adGiftCardInfo7;
                        i3 |= 131072;
                        Unit unit19 = Unit.INSTANCE;
                        lazyArr2 = lazyArr;
                        str65 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 17, StringSerializer.INSTANCE, str65);
                        str21 = str52;
                        str22 = str53;
                        str23 = str54;
                        str24 = str55;
                        str25 = str56;
                        str26 = str57;
                        list5 = list11;
                        str35 = str58;
                        str28 = str59;
                        adButton3 = adButton5;
                        list6 = list12;
                        str29 = str60;
                        str30 = str61;
                        str31 = str62;
                        str32 = str63;
                        str36 = str64;
                        list10 = list13;
                        adGiftCardInfo7 = adGiftCardInfo4;
                        str48 = str37;
                        str58 = str35;
                        adButton5 = adButton3;
                        str63 = str32;
                        str62 = str31;
                        str61 = str30;
                        str60 = str29;
                        list12 = list6;
                        str52 = str21;
                        str53 = str22;
                        str54 = str23;
                        str55 = str24;
                        str56 = str25;
                        str57 = str26;
                        list11 = list5;
                        lazyArr = lazyArr2;
                        str59 = str28;
                        str64 = str36;
                    case AdditionVote2.IS_VOTED_FIELD_NUMBER /* 18 */:
                        str37 = str48;
                        adGiftCardInfo4 = adGiftCardInfo7;
                        i3 |= 262144;
                        Unit unit20 = Unit.INSTANCE;
                        list10 = (List) beginStructure.decodeNullableSerializableElement(serialDescriptor, 18, (DeserializationStrategy) lazyArr[18].getValue(), list13);
                        lazyArr2 = lazyArr;
                        str21 = str52;
                        str22 = str53;
                        str23 = str54;
                        str24 = str55;
                        str25 = str56;
                        str26 = str57;
                        list5 = list11;
                        str35 = str58;
                        str28 = str59;
                        adButton3 = adButton5;
                        list6 = list12;
                        str29 = str60;
                        str30 = str61;
                        str31 = str62;
                        str32 = str63;
                        str36 = str64;
                        adGiftCardInfo7 = adGiftCardInfo4;
                        str48 = str37;
                        str58 = str35;
                        adButton5 = adButton3;
                        str63 = str32;
                        str62 = str31;
                        str61 = str30;
                        str60 = str29;
                        list12 = list6;
                        str52 = str21;
                        str53 = str22;
                        str54 = str23;
                        str55 = str24;
                        str56 = str25;
                        str57 = str26;
                        list11 = list5;
                        lazyArr = lazyArr2;
                        str59 = str28;
                        str64 = str36;
                    case AdditionVote2.CHOICE_CNT_FIELD_NUMBER /* 19 */:
                        AdGiftCardInfo adGiftCardInfo8 = adGiftCardInfo7;
                        str37 = str48;
                        i3 |= 524288;
                        Unit unit21 = Unit.INSTANCE;
                        adGiftCardInfo7 = (AdGiftCardInfo) beginStructure.decodeNullableSerializableElement(serialDescriptor, 19, AdGiftCardInfo$$serializer.INSTANCE, adGiftCardInfo8);
                        lazyArr2 = lazyArr;
                        str21 = str52;
                        str22 = str53;
                        str23 = str54;
                        str24 = str55;
                        str25 = str56;
                        str26 = str57;
                        list5 = list11;
                        str35 = str58;
                        str28 = str59;
                        adButton3 = adButton5;
                        list6 = list12;
                        str29 = str60;
                        str30 = str61;
                        str31 = str62;
                        str32 = str63;
                        str36 = str64;
                        list10 = list13;
                        str48 = str37;
                        str58 = str35;
                        adButton5 = adButton3;
                        str63 = str32;
                        str62 = str31;
                        str61 = str30;
                        str60 = str29;
                        list12 = list6;
                        str52 = str21;
                        str53 = str22;
                        str54 = str23;
                        str55 = str24;
                        str56 = str25;
                        str57 = str26;
                        list11 = list5;
                        lazyArr = lazyArr2;
                        str59 = str28;
                        str64 = str36;
                    case AdditionVote2.DEFAULE_SELECT_SHARE_FIELD_NUMBER /* 20 */:
                        adGiftCardInfo5 = adGiftCardInfo7;
                        str51 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 20, StringSerializer.INSTANCE, str51);
                        i2 = 1048576;
                        i3 |= i2;
                        Unit unit22 = Unit.INSTANCE;
                        lazyArr2 = lazyArr;
                        str21 = str52;
                        str22 = str53;
                        str23 = str54;
                        str24 = str55;
                        str25 = str56;
                        str26 = str57;
                        list5 = list11;
                        str35 = str58;
                        str28 = str59;
                        adButton3 = adButton5;
                        list6 = list12;
                        str29 = str60;
                        str30 = str61;
                        str31 = str62;
                        str32 = str63;
                        str36 = str64;
                        list10 = list13;
                        adGiftCardInfo7 = adGiftCardInfo5;
                        str58 = str35;
                        adButton5 = adButton3;
                        str63 = str32;
                        str62 = str31;
                        str61 = str30;
                        str60 = str29;
                        list12 = list6;
                        str52 = str21;
                        str53 = str22;
                        str54 = str23;
                        str55 = str24;
                        str56 = str25;
                        str57 = str26;
                        list11 = list5;
                        lazyArr = lazyArr2;
                        str59 = str28;
                        str64 = str36;
                    case AdditionVote2.ONLY_FANS_VOTE_FIELD_NUMBER /* 21 */:
                        adGiftCardInfo5 = adGiftCardInfo7;
                        list9 = (List) beginStructure.decodeNullableSerializableElement(serialDescriptor, 21, (DeserializationStrategy) lazyArr[21].getValue(), list9);
                        i3 |= 2097152;
                        Unit unit23 = Unit.INSTANCE;
                        lazyArr2 = lazyArr;
                        str21 = str52;
                        str22 = str53;
                        str23 = str54;
                        str24 = str55;
                        str25 = str56;
                        str26 = str57;
                        list5 = list11;
                        str35 = str58;
                        str28 = str59;
                        adButton3 = adButton5;
                        list6 = list12;
                        str29 = str60;
                        str30 = str61;
                        str31 = str62;
                        str32 = str63;
                        str36 = str64;
                        list10 = list13;
                        adGiftCardInfo7 = adGiftCardInfo5;
                        str58 = str35;
                        adButton5 = adButton3;
                        str63 = str32;
                        str62 = str31;
                        str61 = str30;
                        str60 = str29;
                        list12 = list6;
                        str52 = str21;
                        str53 = str22;
                        str54 = str23;
                        str55 = str24;
                        str56 = str25;
                        str57 = str26;
                        list11 = list5;
                        lazyArr = lazyArr2;
                        str59 = str28;
                        str64 = str36;
                    case AdditionVote2.VOTE_OWNER_MID_FIELD_NUMBER /* 22 */:
                        adGiftCardInfo5 = adGiftCardInfo7;
                        j4 = beginStructure.decodeLongElement(serialDescriptor, 22);
                        i2 = 4194304;
                        i3 |= i2;
                        Unit unit222 = Unit.INSTANCE;
                        lazyArr2 = lazyArr;
                        str21 = str52;
                        str22 = str53;
                        str23 = str54;
                        str24 = str55;
                        str25 = str56;
                        str26 = str57;
                        list5 = list11;
                        str35 = str58;
                        str28 = str59;
                        adButton3 = adButton5;
                        list6 = list12;
                        str29 = str60;
                        str30 = str61;
                        str31 = str62;
                        str32 = str63;
                        str36 = str64;
                        list10 = list13;
                        adGiftCardInfo7 = adGiftCardInfo5;
                        str58 = str35;
                        adButton5 = adButton3;
                        str63 = str32;
                        str62 = str31;
                        str61 = str30;
                        str60 = str29;
                        list12 = list6;
                        str52 = str21;
                        str53 = str22;
                        str54 = str23;
                        str55 = str24;
                        str56 = str25;
                        str57 = str26;
                        list11 = list5;
                        lazyArr = lazyArr2;
                        str59 = str28;
                        str64 = str36;
                    case 23:
                        adGiftCardInfo5 = adGiftCardInfo7;
                        str49 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 23, StringSerializer.INSTANCE, str49);
                        i2 = 8388608;
                        i3 |= i2;
                        Unit unit2222 = Unit.INSTANCE;
                        lazyArr2 = lazyArr;
                        str21 = str52;
                        str22 = str53;
                        str23 = str54;
                        str24 = str55;
                        str25 = str56;
                        str26 = str57;
                        list5 = list11;
                        str35 = str58;
                        str28 = str59;
                        adButton3 = adButton5;
                        list6 = list12;
                        str29 = str60;
                        str30 = str61;
                        str31 = str62;
                        str32 = str63;
                        str36 = str64;
                        list10 = list13;
                        adGiftCardInfo7 = adGiftCardInfo5;
                        str58 = str35;
                        adButton5 = adButton3;
                        str63 = str32;
                        str62 = str31;
                        str61 = str30;
                        str60 = str29;
                        list12 = list6;
                        str52 = str21;
                        str53 = str22;
                        str54 = str23;
                        str55 = str24;
                        str56 = str25;
                        str57 = str26;
                        list11 = list5;
                        lazyArr = lazyArr2;
                        str59 = str28;
                        str64 = str36;
                    case 24:
                        adGiftCardInfo5 = adGiftCardInfo7;
                        str50 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 24, StringSerializer.INSTANCE, str50);
                        i2 = 16777216;
                        i3 |= i2;
                        Unit unit22222 = Unit.INSTANCE;
                        lazyArr2 = lazyArr;
                        str21 = str52;
                        str22 = str53;
                        str23 = str54;
                        str24 = str55;
                        str25 = str56;
                        str26 = str57;
                        list5 = list11;
                        str35 = str58;
                        str28 = str59;
                        adButton3 = adButton5;
                        list6 = list12;
                        str29 = str60;
                        str30 = str61;
                        str31 = str62;
                        str32 = str63;
                        str36 = str64;
                        list10 = list13;
                        adGiftCardInfo7 = adGiftCardInfo5;
                        str58 = str35;
                        adButton5 = adButton3;
                        str63 = str32;
                        str62 = str31;
                        str61 = str30;
                        str60 = str29;
                        list12 = list6;
                        str52 = str21;
                        str53 = str22;
                        str54 = str23;
                        str55 = str24;
                        str56 = str25;
                        str57 = str26;
                        list11 = list5;
                        lazyArr = lazyArr2;
                        str59 = str28;
                        str64 = str36;
                    case 25:
                        adGiftCardInfo5 = adGiftCardInfo7;
                        str48 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 25, StringSerializer.INSTANCE, str48);
                        i2 = 33554432;
                        i3 |= i2;
                        Unit unit222222 = Unit.INSTANCE;
                        lazyArr2 = lazyArr;
                        str21 = str52;
                        str22 = str53;
                        str23 = str54;
                        str24 = str55;
                        str25 = str56;
                        str26 = str57;
                        list5 = list11;
                        str35 = str58;
                        str28 = str59;
                        adButton3 = adButton5;
                        list6 = list12;
                        str29 = str60;
                        str30 = str61;
                        str31 = str62;
                        str32 = str63;
                        str36 = str64;
                        list10 = list13;
                        adGiftCardInfo7 = adGiftCardInfo5;
                        str58 = str35;
                        adButton5 = adButton3;
                        str63 = str32;
                        str62 = str31;
                        str61 = str30;
                        str60 = str29;
                        list12 = list6;
                        str52 = str21;
                        str53 = str22;
                        str54 = str23;
                        str55 = str24;
                        str56 = str25;
                        str57 = str26;
                        list11 = list5;
                        lazyArr = lazyArr2;
                        str59 = str28;
                        str64 = str36;
                    case 26:
                        adGiftCardInfo5 = adGiftCardInfo7;
                        adFullText4 = (AdFullText) beginStructure.decodeNullableSerializableElement(serialDescriptor, 26, AdFullText$$serializer.INSTANCE, adFullText4);
                        i2 = 67108864;
                        i3 |= i2;
                        Unit unit2222222 = Unit.INSTANCE;
                        lazyArr2 = lazyArr;
                        str21 = str52;
                        str22 = str53;
                        str23 = str54;
                        str24 = str55;
                        str25 = str56;
                        str26 = str57;
                        list5 = list11;
                        str35 = str58;
                        str28 = str59;
                        adButton3 = adButton5;
                        list6 = list12;
                        str29 = str60;
                        str30 = str61;
                        str31 = str62;
                        str32 = str63;
                        str36 = str64;
                        list10 = list13;
                        adGiftCardInfo7 = adGiftCardInfo5;
                        str58 = str35;
                        adButton5 = adButton3;
                        str63 = str32;
                        str62 = str31;
                        str61 = str30;
                        str60 = str29;
                        list12 = list6;
                        str52 = str21;
                        str53 = str22;
                        str54 = str23;
                        str55 = str24;
                        str56 = str25;
                        str57 = str26;
                        list11 = list5;
                        lazyArr = lazyArr2;
                        str59 = str28;
                        str64 = str36;
                    case 27:
                        adGiftCardInfo5 = adGiftCardInfo7;
                        adWxProgramInfo3 = (AdWxProgramInfo) beginStructure.decodeNullableSerializableElement(serialDescriptor, 27, AdWxProgramInfo$$serializer.INSTANCE, adWxProgramInfo3);
                        i2 = 134217728;
                        i3 |= i2;
                        Unit unit22222222 = Unit.INSTANCE;
                        lazyArr2 = lazyArr;
                        str21 = str52;
                        str22 = str53;
                        str23 = str54;
                        str24 = str55;
                        str25 = str56;
                        str26 = str57;
                        list5 = list11;
                        str35 = str58;
                        str28 = str59;
                        adButton3 = adButton5;
                        list6 = list12;
                        str29 = str60;
                        str30 = str61;
                        str31 = str62;
                        str32 = str63;
                        str36 = str64;
                        list10 = list13;
                        adGiftCardInfo7 = adGiftCardInfo5;
                        str58 = str35;
                        adButton5 = adButton3;
                        str63 = str32;
                        str62 = str31;
                        str61 = str30;
                        str60 = str29;
                        list12 = list6;
                        str52 = str21;
                        str53 = str22;
                        str54 = str23;
                        str55 = str24;
                        str56 = str25;
                        str57 = str26;
                        list11 = list5;
                        lazyArr = lazyArr2;
                        str59 = str28;
                        str64 = str36;
                    case 28:
                        adGiftCardInfo5 = adGiftCardInfo7;
                        adForwardReply3 = (AdForwardReply) beginStructure.decodeNullableSerializableElement(serialDescriptor, 28, AdForwardReply$$serializer.INSTANCE, adForwardReply3);
                        i2 = 268435456;
                        i3 |= i2;
                        Unit unit222222222 = Unit.INSTANCE;
                        lazyArr2 = lazyArr;
                        str21 = str52;
                        str22 = str53;
                        str23 = str54;
                        str24 = str55;
                        str25 = str56;
                        str26 = str57;
                        list5 = list11;
                        str35 = str58;
                        str28 = str59;
                        adButton3 = adButton5;
                        list6 = list12;
                        str29 = str60;
                        str30 = str61;
                        str31 = str62;
                        str32 = str63;
                        str36 = str64;
                        list10 = list13;
                        adGiftCardInfo7 = adGiftCardInfo5;
                        str58 = str35;
                        adButton5 = adButton3;
                        str63 = str32;
                        str62 = str31;
                        str61 = str30;
                        str60 = str29;
                        list12 = list6;
                        str52 = str21;
                        str53 = str22;
                        str54 = str23;
                        str55 = str24;
                        str56 = str25;
                        str57 = str26;
                        list11 = list5;
                        lazyArr = lazyArr2;
                        str59 = str28;
                        str64 = str36;
                    case 29:
                        adGiftCardInfo5 = adGiftCardInfo7;
                        j5 = beginStructure.decodeLongElement(serialDescriptor, 29);
                        i2 = 536870912;
                        i3 |= i2;
                        Unit unit2222222222 = Unit.INSTANCE;
                        lazyArr2 = lazyArr;
                        str21 = str52;
                        str22 = str53;
                        str23 = str54;
                        str24 = str55;
                        str25 = str56;
                        str26 = str57;
                        list5 = list11;
                        str35 = str58;
                        str28 = str59;
                        adButton3 = adButton5;
                        list6 = list12;
                        str29 = str60;
                        str30 = str61;
                        str31 = str62;
                        str32 = str63;
                        str36 = str64;
                        list10 = list13;
                        adGiftCardInfo7 = adGiftCardInfo5;
                        str58 = str35;
                        adButton5 = adButton3;
                        str63 = str32;
                        str62 = str31;
                        str61 = str30;
                        str60 = str29;
                        list12 = list6;
                        str52 = str21;
                        str53 = str22;
                        str54 = str23;
                        str55 = str24;
                        str56 = str25;
                        str57 = str26;
                        list11 = list5;
                        lazyArr = lazyArr2;
                        str59 = str28;
                        str64 = str36;
                    case 30:
                        adGiftCardInfo5 = adGiftCardInfo7;
                        bool3 = (Boolean) beginStructure.decodeNullableSerializableElement(serialDescriptor, 30, BooleanSerializer.INSTANCE, bool3);
                        i2 = 1073741824;
                        i3 |= i2;
                        Unit unit22222222222 = Unit.INSTANCE;
                        lazyArr2 = lazyArr;
                        str21 = str52;
                        str22 = str53;
                        str23 = str54;
                        str24 = str55;
                        str25 = str56;
                        str26 = str57;
                        list5 = list11;
                        str35 = str58;
                        str28 = str59;
                        adButton3 = adButton5;
                        list6 = list12;
                        str29 = str60;
                        str30 = str61;
                        str31 = str62;
                        str32 = str63;
                        str36 = str64;
                        list10 = list13;
                        adGiftCardInfo7 = adGiftCardInfo5;
                        str58 = str35;
                        adButton5 = adButton3;
                        str63 = str32;
                        str62 = str31;
                        str61 = str30;
                        str60 = str29;
                        list12 = list6;
                        str52 = str21;
                        str53 = str22;
                        str54 = str23;
                        str55 = str24;
                        str56 = str25;
                        str57 = str26;
                        list11 = list5;
                        lazyArr = lazyArr2;
                        str59 = str28;
                        str64 = str36;
                    case 31:
                        adGiftCardInfo5 = adGiftCardInfo7;
                        i3 |= Integer.MIN_VALUE;
                        Unit unit24 = Unit.INSTANCE;
                        lazyArr2 = lazyArr;
                        adVideo2 = (AdVideo) beginStructure.decodeNullableSerializableElement(serialDescriptor, 31, AdVideo$$serializer.INSTANCE, adVideo2);
                        str21 = str52;
                        str22 = str53;
                        str23 = str54;
                        str24 = str55;
                        str25 = str56;
                        str26 = str57;
                        list5 = list11;
                        str35 = str58;
                        str28 = str59;
                        adButton3 = adButton5;
                        list6 = list12;
                        str29 = str60;
                        str30 = str61;
                        str31 = str62;
                        str32 = str63;
                        str36 = str64;
                        list10 = list13;
                        adGiftCardInfo7 = adGiftCardInfo5;
                        str58 = str35;
                        adButton5 = adButton3;
                        str63 = str32;
                        str62 = str31;
                        str61 = str30;
                        str60 = str29;
                        list12 = list6;
                        str52 = str21;
                        str53 = str22;
                        str54 = str23;
                        str55 = str24;
                        str56 = str25;
                        str57 = str26;
                        list11 = list5;
                        lazyArr = lazyArr2;
                        str59 = str28;
                        str64 = str36;
                    default:
                        throw new UnknownFieldException(decodeElementIndex);
                }
                str36 = str33;
                adButton3 = adButton2;
                list10 = list13;
                str58 = str35;
                adButton5 = adButton3;
                str63 = str32;
                str62 = str31;
                str61 = str30;
                str60 = str29;
                list12 = list6;
                str52 = str21;
                str53 = str22;
                str54 = str23;
                str55 = str24;
                str56 = str25;
                str57 = str26;
                list11 = list5;
                lazyArr = lazyArr2;
                str59 = str28;
                str64 = str36;
            }
            AdFullText adFullText10 = adFullText4;
            String str67 = str49;
            List list14 = list10;
            AdSubCardModule adSubCardModule3 = adSubCardModule2;
            String str68 = str54;
            String str69 = str55;
            String str70 = str56;
            String str71 = str58;
            AdButton adButton6 = adButton5;
            List list15 = list12;
            String str72 = str60;
            String str73 = str61;
            String str74 = str63;
            String str75 = str64;
            bool = bool3;
            adWxProgramInfo = adWxProgramInfo3;
            list = list9;
            adForwardReply = adForwardReply3;
            str = str50;
            str2 = str51;
            str3 = str65;
            adVideo = adVideo2;
            adFullText = adFullText10;
            str4 = str62;
            str5 = str52;
            str6 = str53;
            str7 = str68;
            list2 = list11;
            str8 = str59;
            str9 = str67;
            j2 = j4;
            j3 = j5;
            list3 = list14;
            adGiftCardInfo = adGiftCardInfo7;
            str10 = str48;
            str11 = str71;
            i = i3;
            str12 = str75;
            str13 = str74;
            str14 = str73;
            str15 = str69;
            adSubCardModule = adSubCardModule3;
            adButton = adButton6;
            str16 = str72;
            str17 = str70;
            list4 = list15;
            str18 = str57;
        }
        beginStructure.endStructure(serialDescriptor);
        return new AdSubCardModule(i, 0, adSubCardModule, str5, str6, str7, str15, str17, str18, list2, str11, str8, adButton, list4, str16, str14, str4, str13, str12, str3, list3, adGiftCardInfo, str2, list, j2, str9, str, str10, adFullText, adWxProgramInfo, adForwardReply, j3, bool, adVideo, null);
    }

    public final void serialize(Encoder encoder, AdSubCardModule value) {
        Intrinsics.checkNotNullParameter(encoder, "encoder");
        Intrinsics.checkNotNullParameter(value, "value");
        SerialDescriptor serialDescriptor = descriptor;
        CompositeEncoder beginStructure = encoder.beginStructure(serialDescriptor);
        AdSubCardModule.write$Self$dto_debug(value, beginStructure, serialDescriptor);
        beginStructure.endStructure(serialDescriptor);
    }

    public /* bridge */ KSerializer<?>[] typeParametersSerializers() {
        return GeneratedSerializer.DefaultImpls.typeParametersSerializers(this);
    }
}