package kntr.app.ad.common.model;

import com.bapis.bilibili.app.dynamic.v2.AdditionVote2;
import java.util.List;
import kntr.app.ad.domain.alarm.AdAlarmExtraKey;
import kntr.app.ad.protocol.report.SubmitActionFrom;
import kntr.app.game.base.ui.widget.gameaction.state.GameActionStateKt;
import kntr.app.live.room.recommend.RoomRecommendViewModel;
import kotlin.Deprecated;
import kotlin.DeprecationLevel;
import kotlin.Lazy;
import kotlin.Metadata;
import kotlin.Unit;
import kotlin.jvm.internal.Intrinsics;
import kotlinx.serialization.DeserializationStrategy;
import kotlinx.serialization.KSerializer;
import kotlinx.serialization.UnknownFieldException;
import kotlinx.serialization.builtins.BuiltinSerializersKt;
import kotlinx.serialization.descriptors.SerialDescriptor;
import kotlinx.serialization.encoding.CompositeDecoder;
import kotlinx.serialization.encoding.CompositeEncoder;
import kotlinx.serialization.encoding.Decoder;
import kotlinx.serialization.encoding.Encoder;
import kotlinx.serialization.internal.BooleanSerializer;
import kotlinx.serialization.internal.GeneratedSerializer;
import kotlinx.serialization.internal.IntSerializer;
import kotlinx.serialization.internal.PluginGeneratedSerialDescriptor;
import kotlinx.serialization.internal.SerializationConstructorMarker;
import kotlinx.serialization.internal.StringSerializer;

/* compiled from: AdVideo.kt */
@Metadata(d1 = {"\u00006\n\u0000\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\b\u0003\n\u0002\u0010\u0011\n\u0002\u0018\u0002\n\u0002\b\u0003\n\u0002\u0018\u0002\n\u0000\n\u0002\u0010\u0002\n\u0000\n\u0002\u0018\u0002\n\u0002\b\u0002\n\u0002\u0018\u0002\n\u0002\b\u0003\bÇ\u0002\u0018\u00002\b\u0012\u0004\u0012\u00020\u00020\u0001B\t\b\u0002¢\u0006\u0004\b\u0003\u0010\u0004J\u0015\u0010\u0005\u001a\f\u0012\b\u0012\u0006\u0012\u0002\b\u00030\u00070\u0006¢\u0006\u0002\u0010\bJ\u000e\u0010\t\u001a\u00020\u00022\u0006\u0010\n\u001a\u00020\u000bJ\u0016\u0010\f\u001a\u00020\r2\u0006\u0010\u000e\u001a\u00020\u000f2\u0006\u0010\u0010\u001a\u00020\u0002R\u0011\u0010\u0011\u001a\u00020\u0012¢\u0006\b\n\u0000\u001a\u0004\b\u0013\u0010\u0014¨\u0006\u0015"}, d2 = {"kntr/app/ad/common/model/AdVideo.$serializer", "Lkotlinx/serialization/internal/GeneratedSerializer;", "Lkntr/app/ad/common/model/AdVideo;", "<init>", "()V", "childSerializers", RoomRecommendViewModel.EMPTY_CURSOR, "Lkotlinx/serialization/KSerializer;", "()[Lkotlinx/serialization/KSerializer;", "deserialize", "decoder", "Lkotlinx/serialization/encoding/Decoder;", "serialize", RoomRecommendViewModel.EMPTY_CURSOR, "encoder", "Lkotlinx/serialization/encoding/Encoder;", "value", "descriptor", "Lkotlinx/serialization/descriptors/SerialDescriptor;", "getDescriptor", "()Lkotlinx/serialization/descriptors/SerialDescriptor;", "dto_debug"}, k = 1, mv = {2, 2, 0}, xi = 48)
@Deprecated(level = DeprecationLevel.HIDDEN, message = "This synthesized declaration should not be used directly")
public final /* synthetic */ class AdVideo$$serializer implements GeneratedSerializer<AdVideo> {
    public static final AdVideo$$serializer INSTANCE = new AdVideo$$serializer();
    private static final SerialDescriptor descriptor;

    public final SerialDescriptor getDescriptor() {
        return descriptor;
    }

    static {
        SerialDescriptor pluginGeneratedSerialDescriptor = new PluginGeneratedSerialDescriptor("kntr.app.ad.common.model.AdVideo", INSTANCE, 30);
        pluginGeneratedSerialDescriptor.addElement("avid", true);
        pluginGeneratedSerialDescriptor.addElement(AdAlarmExtraKey.CID, true);
        pluginGeneratedSerialDescriptor.addElement("page", true);
        pluginGeneratedSerialDescriptor.addElement("from", true);
        pluginGeneratedSerialDescriptor.addElement("url", true);
        pluginGeneratedSerialDescriptor.addElement("cover", true);
        pluginGeneratedSerialDescriptor.addElement("auto_play", true);
        pluginGeneratedSerialDescriptor.addElement("btnDycColor", true);
        pluginGeneratedSerialDescriptor.addElement("btnDycTime", true);
        pluginGeneratedSerialDescriptor.addElement("bizId", true);
        pluginGeneratedSerialDescriptor.addElement(SubmitActionFrom.MMA_KEY_PROCESS0_URLS, true);
        pluginGeneratedSerialDescriptor.addElement("play3sUrls", true);
        pluginGeneratedSerialDescriptor.addElement("play5sUrls", true);
        pluginGeneratedSerialDescriptor.addElement("play10sUrls", true);
        pluginGeneratedSerialDescriptor.addElement("play15sUrls", true);
        pluginGeneratedSerialDescriptor.addElement(SubmitActionFrom.MMA_KEY_PROCESS1_URLS, true);
        pluginGeneratedSerialDescriptor.addElement(SubmitActionFrom.MMA_KEY_PROCESS2_URLS, true);
        pluginGeneratedSerialDescriptor.addElement(SubmitActionFrom.MMA_KEY_PROCESS3_URLS, true);
        pluginGeneratedSerialDescriptor.addElement(SubmitActionFrom.MMA_KEY_PROCESS4_URLS, true);
        pluginGeneratedSerialDescriptor.addElement("muteButton", true);
        pluginGeneratedSerialDescriptor.addElement("progressBar", true);
        pluginGeneratedSerialDescriptor.addElement("mutePlay", true);
        pluginGeneratedSerialDescriptor.addElement("has_endpage", true);
        pluginGeneratedSerialDescriptor.addElement("endplay", true);
        pluginGeneratedSerialDescriptor.addElement("fromSpmid", true);
        pluginGeneratedSerialDescriptor.addElement("autoPlayValue", true);
        pluginGeneratedSerialDescriptor.addElement("eggStartTime", true);
        pluginGeneratedSerialDescriptor.addElement("eggEndTime", true);
        pluginGeneratedSerialDescriptor.addElement("pressTriggerTime", true);
        pluginGeneratedSerialDescriptor.addElement("customPlayUrls", true);
        descriptor = pluginGeneratedSerialDescriptor;
    }

    private AdVideo$$serializer() {
    }

    public final KSerializer<?>[] childSerializers() {
        Lazy[] lazyArr;
        lazyArr = AdVideo.$childSerializers;
        return new KSerializer[]{BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(BooleanSerializer.INSTANCE), BuiltinSerializersKt.getNullable(BooleanSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable((KSerializer) lazyArr[10].getValue()), BuiltinSerializersKt.getNullable((KSerializer) lazyArr[11].getValue()), BuiltinSerializersKt.getNullable((KSerializer) lazyArr[12].getValue()), BuiltinSerializersKt.getNullable((KSerializer) lazyArr[13].getValue()), BuiltinSerializersKt.getNullable((KSerializer) lazyArr[14].getValue()), BuiltinSerializersKt.getNullable((KSerializer) lazyArr[15].getValue()), BuiltinSerializersKt.getNullable((KSerializer) lazyArr[16].getValue()), BuiltinSerializersKt.getNullable((KSerializer) lazyArr[17].getValue()), BuiltinSerializersKt.getNullable((KSerializer) lazyArr[18].getValue()), IntSerializer.INSTANCE, IntSerializer.INSTANCE, IntSerializer.INSTANCE, IntSerializer.INSTANCE, BuiltinSerializersKt.getNullable(AdVideoEndPage$$serializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), IntSerializer.INSTANCE, IntSerializer.INSTANCE, IntSerializer.INSTANCE, IntSerializer.INSTANCE, BuiltinSerializersKt.getNullable((KSerializer) lazyArr[29].getValue())};
    }

    public final AdVideo deserialize(Decoder decoder) {
        Lazy[] lazyArr;
        String str;
        List list;
        List list2;
        List list3;
        List list4;
        List list5;
        List list6;
        String str2;
        int i;
        String str3;
        String str4;
        String str5;
        Boolean bool;
        Boolean bool2;
        String str6;
        List list7;
        List list8;
        int i2;
        int i3;
        int i4;
        String str7;
        AdVideoEndPage adVideoEndPage;
        List list9;
        int i5;
        int i6;
        String str8;
        int i7;
        int i8;
        int i9;
        List list10;
        String str9;
        Lazy[] lazyArr2;
        List list11;
        List list12;
        String str10;
        String str11;
        String str12;
        String str13;
        String str14;
        Boolean bool3;
        Boolean bool4;
        String str15;
        String str16;
        List list13;
        String str17;
        List list14;
        List list15;
        List list16;
        int i10;
        Intrinsics.checkNotNullParameter(decoder, "decoder");
        SerialDescriptor serialDescriptor = descriptor;
        CompositeDecoder beginStructure = decoder.beginStructure(serialDescriptor);
        lazyArr = AdVideo.$childSerializers;
        if (beginStructure.decodeSequentially()) {
            String str18 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 0, StringSerializer.INSTANCE, (Object) null);
            String str19 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 1, StringSerializer.INSTANCE, (Object) null);
            List list17 = (List) beginStructure.decodeNullableSerializableElement(serialDescriptor, 10, (DeserializationStrategy) lazyArr[10].getValue(), (Object) null);
            List list18 = (List) beginStructure.decodeNullableSerializableElement(serialDescriptor, 11, (DeserializationStrategy) lazyArr[11].getValue(), (Object) null);
            List list19 = (List) beginStructure.decodeNullableSerializableElement(serialDescriptor, 12, (DeserializationStrategy) lazyArr[12].getValue(), (Object) null);
            list5 = (List) beginStructure.decodeNullableSerializableElement(serialDescriptor, 13, (DeserializationStrategy) lazyArr[13].getValue(), (Object) null);
            List list20 = (List) beginStructure.decodeNullableSerializableElement(serialDescriptor, 14, (DeserializationStrategy) lazyArr[14].getValue(), (Object) null);
            list3 = (List) beginStructure.decodeNullableSerializableElement(serialDescriptor, 15, (DeserializationStrategy) lazyArr[15].getValue(), (Object) null);
            List list21 = (List) beginStructure.decodeNullableSerializableElement(serialDescriptor, 16, (DeserializationStrategy) lazyArr[16].getValue(), (Object) null);
            List list22 = (List) beginStructure.decodeNullableSerializableElement(serialDescriptor, 17, (DeserializationStrategy) lazyArr[17].getValue(), (Object) null);
            List list23 = (List) beginStructure.decodeNullableSerializableElement(serialDescriptor, 18, (DeserializationStrategy) lazyArr[18].getValue(), (Object) null);
            int decodeIntElement = beginStructure.decodeIntElement(serialDescriptor, 19);
            int decodeIntElement2 = beginStructure.decodeIntElement(serialDescriptor, 20);
            int decodeIntElement3 = beginStructure.decodeIntElement(serialDescriptor, 21);
            int decodeIntElement4 = beginStructure.decodeIntElement(serialDescriptor, 22);
            AdVideoEndPage adVideoEndPage2 = (AdVideoEndPage) beginStructure.decodeNullableSerializableElement(serialDescriptor, 23, AdVideoEndPage$$serializer.INSTANCE, (Object) null);
            String str20 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 24, StringSerializer.INSTANCE, (Object) null);
            int decodeIntElement5 = beginStructure.decodeIntElement(serialDescriptor, 25);
            int decodeIntElement6 = beginStructure.decodeIntElement(serialDescriptor, 26);
            int decodeIntElement7 = beginStructure.decodeIntElement(serialDescriptor, 27);
            int decodeIntElement8 = beginStructure.decodeIntElement(serialDescriptor, 28);
            list9 = (List) beginStructure.decodeNullableSerializableElement(serialDescriptor, 29, (DeserializationStrategy) lazyArr[29].getValue(), (Object) null);
            i = decodeIntElement6;
            bool = (Boolean) beginStructure.decodeNullableSerializableElement(serialDescriptor, 6, BooleanSerializer.INSTANCE, (Object) null);
            list10 = list23;
            i3 = decodeIntElement7;
            i5 = decodeIntElement8;
            i9 = 1073741823;
            i6 = decodeIntElement5;
            str6 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 8, StringSerializer.INSTANCE, (Object) null);
            str8 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 2, StringSerializer.INSTANCE, (Object) null);
            str7 = str20;
            str4 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 4, StringSerializer.INSTANCE, (Object) null);
            adVideoEndPage = adVideoEndPage2;
            str3 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 3, StringSerializer.INSTANCE, (Object) null);
            i7 = decodeIntElement4;
            str2 = str19;
            i8 = decodeIntElement2;
            i2 = decodeIntElement3;
            str = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 9, StringSerializer.INSTANCE, (Object) null);
            str5 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 5, StringSerializer.INSTANCE, (Object) null);
            str9 = str18;
            i4 = decodeIntElement;
            bool2 = (Boolean) beginStructure.decodeNullableSerializableElement(serialDescriptor, 7, BooleanSerializer.INSTANCE, (Object) null);
            list2 = list22;
            list8 = list17;
            list = list21;
            list7 = list18;
            list6 = list20;
            list4 = list19;
        } else {
            int i11 = 0;
            List list24 = null;
            int i12 = 0;
            int i13 = 0;
            int i14 = 0;
            int i15 = 0;
            int i16 = 0;
            int i17 = 0;
            int i18 = 0;
            int i19 = 0;
            boolean z = true;
            List list25 = null;
            List list26 = null;
            List list27 = null;
            String str21 = null;
            AdVideoEndPage adVideoEndPage3 = null;
            List list28 = null;
            List list29 = null;
            List list30 = null;
            List list31 = null;
            List list32 = null;
            List list33 = null;
            String str22 = null;
            String str23 = null;
            String str24 = null;
            String str25 = null;
            String str26 = null;
            String str27 = null;
            Boolean bool5 = null;
            Boolean bool6 = null;
            String str28 = null;
            String str29 = null;
            while (z) {
                List list34 = list27;
                int decodeElementIndex = beginStructure.decodeElementIndex(serialDescriptor);
                switch (decodeElementIndex) {
                    case GameActionStateKt.ACTION_UNDEFINE /* -1 */:
                        lazyArr2 = lazyArr;
                        list11 = list25;
                        list12 = list26;
                        str10 = str23;
                        str11 = str24;
                        str12 = str25;
                        str13 = str26;
                        str14 = str27;
                        bool3 = bool5;
                        bool4 = bool6;
                        str15 = str28;
                        str16 = str29;
                        list13 = list34;
                        Unit unit = Unit.INSTANCE;
                        z = false;
                        str17 = str16;
                        list25 = list11;
                        list27 = list13;
                        str29 = str17;
                        list26 = list12;
                        lazyArr = lazyArr2;
                        str23 = str10;
                        str24 = str11;
                        str25 = str12;
                        str26 = str13;
                        str27 = str14;
                        bool5 = bool3;
                        bool6 = bool4;
                        str28 = str15;
                    case 0:
                        lazyArr2 = lazyArr;
                        list11 = list25;
                        list12 = list26;
                        str11 = str24;
                        str12 = str25;
                        str13 = str26;
                        str14 = str27;
                        bool3 = bool5;
                        bool4 = bool6;
                        str15 = str28;
                        str16 = str29;
                        list13 = list34;
                        str10 = str23;
                        i11 |= 1;
                        Unit unit2 = Unit.INSTANCE;
                        str22 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 0, StringSerializer.INSTANCE, str22);
                        str17 = str16;
                        list25 = list11;
                        list27 = list13;
                        str29 = str17;
                        list26 = list12;
                        lazyArr = lazyArr2;
                        str23 = str10;
                        str24 = str11;
                        str25 = str12;
                        str26 = str13;
                        str27 = str14;
                        bool5 = bool3;
                        bool6 = bool4;
                        str28 = str15;
                    case 1:
                        lazyArr2 = lazyArr;
                        list14 = list25;
                        list12 = list26;
                        str12 = str25;
                        str13 = str26;
                        str14 = str27;
                        bool3 = bool5;
                        bool4 = bool6;
                        str15 = str28;
                        list15 = list34;
                        str11 = str24;
                        i11 |= 2;
                        Unit unit3 = Unit.INSTANCE;
                        str10 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 1, StringSerializer.INSTANCE, str23);
                        str17 = str29;
                        list25 = list14;
                        list27 = list15;
                        str29 = str17;
                        list26 = list12;
                        lazyArr = lazyArr2;
                        str23 = str10;
                        str24 = str11;
                        str25 = str12;
                        str26 = str13;
                        str27 = str14;
                        bool5 = bool3;
                        bool6 = bool4;
                        str28 = str15;
                    case 2:
                        lazyArr2 = lazyArr;
                        list14 = list25;
                        list12 = list26;
                        str13 = str26;
                        str14 = str27;
                        bool3 = bool5;
                        bool4 = bool6;
                        str15 = str28;
                        list15 = list34;
                        str12 = str25;
                        i11 |= 4;
                        Unit unit4 = Unit.INSTANCE;
                        str11 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 2, StringSerializer.INSTANCE, str24);
                        str17 = str29;
                        str10 = str23;
                        list25 = list14;
                        list27 = list15;
                        str29 = str17;
                        list26 = list12;
                        lazyArr = lazyArr2;
                        str23 = str10;
                        str24 = str11;
                        str25 = str12;
                        str26 = str13;
                        str27 = str14;
                        bool5 = bool3;
                        bool6 = bool4;
                        str28 = str15;
                    case 3:
                        lazyArr2 = lazyArr;
                        list12 = list26;
                        str14 = str27;
                        bool3 = bool5;
                        bool4 = bool6;
                        str15 = str28;
                        str13 = str26;
                        i11 |= 8;
                        Unit unit5 = Unit.INSTANCE;
                        str12 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 3, StringSerializer.INSTANCE, str25);
                        str17 = str29;
                        str10 = str23;
                        list25 = list25;
                        list27 = list34;
                        str11 = str24;
                        str29 = str17;
                        list26 = list12;
                        lazyArr = lazyArr2;
                        str23 = str10;
                        str24 = str11;
                        str25 = str12;
                        str26 = str13;
                        str27 = str14;
                        bool5 = bool3;
                        bool6 = bool4;
                        str28 = str15;
                    case 4:
                        lazyArr2 = lazyArr;
                        List list35 = list25;
                        list12 = list26;
                        bool3 = bool5;
                        bool4 = bool6;
                        str15 = str28;
                        str14 = str27;
                        i11 |= 16;
                        Unit unit6 = Unit.INSTANCE;
                        str13 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 4, StringSerializer.INSTANCE, str26);
                        str17 = str29;
                        str10 = str23;
                        list25 = list35;
                        list27 = list34;
                        str11 = str24;
                        str12 = str25;
                        str29 = str17;
                        list26 = list12;
                        lazyArr = lazyArr2;
                        str23 = str10;
                        str24 = str11;
                        str25 = str12;
                        str26 = str13;
                        str27 = str14;
                        bool5 = bool3;
                        bool6 = bool4;
                        str28 = str15;
                    case 5:
                        lazyArr2 = lazyArr;
                        list12 = list26;
                        bool4 = bool6;
                        str15 = str28;
                        bool3 = bool5;
                        i11 |= 32;
                        Unit unit7 = Unit.INSTANCE;
                        str14 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 5, StringSerializer.INSTANCE, str27);
                        str17 = str29;
                        str10 = str23;
                        list25 = list25;
                        list27 = list34;
                        str11 = str24;
                        str12 = str25;
                        str13 = str26;
                        str29 = str17;
                        list26 = list12;
                        lazyArr = lazyArr2;
                        str23 = str10;
                        str24 = str11;
                        str25 = str12;
                        str26 = str13;
                        str27 = str14;
                        bool5 = bool3;
                        bool6 = bool4;
                        str28 = str15;
                    case 6:
                        lazyArr2 = lazyArr;
                        List list36 = list25;
                        list12 = list26;
                        str15 = str28;
                        bool4 = bool6;
                        i11 |= 64;
                        Unit unit8 = Unit.INSTANCE;
                        bool3 = (Boolean) beginStructure.decodeNullableSerializableElement(serialDescriptor, 6, BooleanSerializer.INSTANCE, bool5);
                        str17 = str29;
                        str10 = str23;
                        list25 = list36;
                        list27 = list34;
                        str11 = str24;
                        str12 = str25;
                        str13 = str26;
                        str14 = str27;
                        str29 = str17;
                        list26 = list12;
                        lazyArr = lazyArr2;
                        str23 = str10;
                        str24 = str11;
                        str25 = str12;
                        str26 = str13;
                        str27 = str14;
                        bool5 = bool3;
                        bool6 = bool4;
                        str28 = str15;
                    case 7:
                        lazyArr2 = lazyArr;
                        list12 = list26;
                        str15 = str28;
                        i11 |= 128;
                        Unit unit9 = Unit.INSTANCE;
                        bool4 = (Boolean) beginStructure.decodeNullableSerializableElement(serialDescriptor, 7, BooleanSerializer.INSTANCE, bool6);
                        str17 = str29;
                        str10 = str23;
                        list25 = list25;
                        list27 = list34;
                        str11 = str24;
                        str12 = str25;
                        str13 = str26;
                        str14 = str27;
                        bool3 = bool5;
                        str29 = str17;
                        list26 = list12;
                        lazyArr = lazyArr2;
                        str23 = str10;
                        str24 = str11;
                        str25 = str12;
                        str26 = str13;
                        str27 = str14;
                        bool5 = bool3;
                        bool6 = bool4;
                        str28 = str15;
                    case 8:
                        lazyArr2 = lazyArr;
                        list12 = list26;
                        List list37 = list25;
                        i11 |= 256;
                        Unit unit10 = Unit.INSTANCE;
                        str15 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 8, StringSerializer.INSTANCE, str28);
                        str17 = str29;
                        str10 = str23;
                        list25 = list37;
                        list27 = list34;
                        str11 = str24;
                        str12 = str25;
                        str13 = str26;
                        str14 = str27;
                        bool3 = bool5;
                        bool4 = bool6;
                        str29 = str17;
                        list26 = list12;
                        lazyArr = lazyArr2;
                        str23 = str10;
                        str24 = str11;
                        str25 = str12;
                        str26 = str13;
                        str27 = str14;
                        bool5 = bool3;
                        bool6 = bool4;
                        str28 = str15;
                    case 9:
                        lazyArr2 = lazyArr;
                        list12 = list26;
                        i11 |= 512;
                        Unit unit11 = Unit.INSTANCE;
                        str17 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 9, StringSerializer.INSTANCE, str29);
                        list25 = list25;
                        str10 = str23;
                        list27 = list34;
                        str11 = str24;
                        str12 = str25;
                        str13 = str26;
                        str14 = str27;
                        bool3 = bool5;
                        bool4 = bool6;
                        str15 = str28;
                        str29 = str17;
                        list26 = list12;
                        lazyArr = lazyArr2;
                        str23 = str10;
                        str24 = str11;
                        str25 = str12;
                        str26 = str13;
                        str27 = str14;
                        bool5 = bool3;
                        bool6 = bool4;
                        str28 = str15;
                    case 10:
                        list12 = list26;
                        List list38 = list25;
                        DeserializationStrategy deserializationStrategy = (DeserializationStrategy) lazyArr[10].getValue();
                        lazyArr2 = lazyArr;
                        i11 |= 1024;
                        Unit unit12 = Unit.INSTANCE;
                        list27 = (List) beginStructure.decodeNullableSerializableElement(serialDescriptor, 10, deserializationStrategy, list34);
                        list25 = list38;
                        str10 = str23;
                        str11 = str24;
                        str12 = str25;
                        str13 = str26;
                        str14 = str27;
                        bool3 = bool5;
                        bool4 = bool6;
                        str15 = str28;
                        str17 = str29;
                        str29 = str17;
                        list26 = list12;
                        lazyArr = lazyArr2;
                        str23 = str10;
                        str24 = str11;
                        str25 = str12;
                        str26 = str13;
                        str27 = str14;
                        bool5 = bool3;
                        bool6 = bool4;
                        str28 = str15;
                    case AdditionVote2.ADDITION_VOTE_PIC_FIELD_NUMBER /* 11 */:
                        DeserializationStrategy deserializationStrategy2 = (DeserializationStrategy) lazyArr[11].getValue();
                        list12 = list26;
                        i11 |= 2048;
                        Unit unit13 = Unit.INSTANCE;
                        lazyArr2 = lazyArr;
                        list25 = (List) beginStructure.decodeNullableSerializableElement(serialDescriptor, 11, deserializationStrategy2, list25);
                        str10 = str23;
                        str11 = str24;
                        str12 = str25;
                        str13 = str26;
                        str14 = str27;
                        bool3 = bool5;
                        bool4 = bool6;
                        str15 = str28;
                        str17 = str29;
                        list27 = list34;
                        str29 = str17;
                        list26 = list12;
                        lazyArr = lazyArr2;
                        str23 = str10;
                        str24 = str11;
                        str25 = str12;
                        str26 = str13;
                        str27 = str14;
                        bool5 = bool3;
                        bool6 = bool4;
                        str28 = str15;
                    case AdditionVote2.ADDITION_VOTE_DEFAULE_FIELD_NUMBER /* 12 */:
                        list16 = list25;
                        i11 |= 4096;
                        Unit unit14 = Unit.INSTANCE;
                        lazyArr2 = lazyArr;
                        list33 = (List) beginStructure.decodeNullableSerializableElement(serialDescriptor, 12, (DeserializationStrategy) lazyArr[12].getValue(), list33);
                        list12 = list26;
                        str10 = str23;
                        str11 = str24;
                        str12 = str25;
                        str13 = str26;
                        str14 = str27;
                        bool3 = bool5;
                        bool4 = bool6;
                        str15 = str28;
                        str17 = str29;
                        list27 = list34;
                        list25 = list16;
                        str29 = str17;
                        list26 = list12;
                        lazyArr = lazyArr2;
                        str23 = str10;
                        str24 = str11;
                        str25 = str12;
                        str26 = str13;
                        str27 = str14;
                        bool5 = bool3;
                        bool6 = bool4;
                        str28 = str15;
                    case AdditionVote2.BIZ_TYPE_FIELD_NUMBER /* 13 */:
                        list16 = list25;
                        i11 |= 8192;
                        Unit unit15 = Unit.INSTANCE;
                        lazyArr2 = lazyArr;
                        list12 = list26;
                        list24 = (List) beginStructure.decodeNullableSerializableElement(serialDescriptor, 13, (DeserializationStrategy) lazyArr[13].getValue(), list24);
                        str10 = str23;
                        str11 = str24;
                        str12 = str25;
                        str13 = str26;
                        str14 = str27;
                        bool3 = bool5;
                        bool4 = bool6;
                        str15 = str28;
                        str17 = str29;
                        list27 = list34;
                        list25 = list16;
                        str29 = str17;
                        list26 = list12;
                        lazyArr = lazyArr2;
                        str23 = str10;
                        str24 = str11;
                        str25 = str12;
                        str26 = str13;
                        str27 = str14;
                        bool5 = bool3;
                        bool6 = bool4;
                        str28 = str15;
                    case AdditionVote2.TOTAL_FIELD_NUMBER /* 14 */:
                        list16 = list25;
                        i11 |= 16384;
                        Unit unit16 = Unit.INSTANCE;
                        lazyArr2 = lazyArr;
                        list12 = (List) beginStructure.decodeNullableSerializableElement(serialDescriptor, 14, (DeserializationStrategy) lazyArr[14].getValue(), list26);
                        str10 = str23;
                        str11 = str24;
                        str12 = str25;
                        str13 = str26;
                        str14 = str27;
                        bool3 = bool5;
                        bool4 = bool6;
                        str15 = str28;
                        str17 = str29;
                        list27 = list34;
                        list25 = list16;
                        str29 = str17;
                        list26 = list12;
                        lazyArr = lazyArr2;
                        str23 = str10;
                        str24 = str11;
                        str25 = str12;
                        str26 = str13;
                        str27 = str14;
                        bool5 = bool3;
                        bool6 = bool4;
                        str28 = str15;
                    case AdditionVote2.CARD_TYPE_FIELD_NUMBER /* 15 */:
                        list16 = list25;
                        i11 |= 32768;
                        Unit unit17 = Unit.INSTANCE;
                        lazyArr2 = lazyArr;
                        list12 = list26;
                        list32 = (List) beginStructure.decodeNullableSerializableElement(serialDescriptor, 15, (DeserializationStrategy) lazyArr[15].getValue(), list32);
                        str10 = str23;
                        str11 = str24;
                        str12 = str25;
                        str13 = str26;
                        str14 = str27;
                        bool3 = bool5;
                        bool4 = bool6;
                        str15 = str28;
                        str17 = str29;
                        list27 = list34;
                        list25 = list16;
                        str29 = str17;
                        list26 = list12;
                        lazyArr = lazyArr2;
                        str23 = str10;
                        str24 = str11;
                        str25 = str12;
                        str26 = str13;
                        str27 = str14;
                        bool5 = bool3;
                        bool6 = bool4;
                        str28 = str15;
                    case AdditionVote2.TIPS_FIELD_NUMBER /* 16 */:
                        list16 = list25;
                        i11 |= 65536;
                        Unit unit18 = Unit.INSTANCE;
                        lazyArr2 = lazyArr;
                        list29 = (List) beginStructure.decodeNullableSerializableElement(serialDescriptor, 16, (DeserializationStrategy) lazyArr[16].getValue(), list29);
                        list12 = list26;
                        str10 = str23;
                        str11 = str24;
                        str12 = str25;
                        str13 = str26;
                        str14 = str27;
                        bool3 = bool5;
                        bool4 = bool6;
                        str15 = str28;
                        str17 = str29;
                        list27 = list34;
                        list25 = list16;
                        str29 = str17;
                        list26 = list12;
                        lazyArr = lazyArr2;
                        str23 = str10;
                        str24 = str11;
                        str25 = str12;
                        str26 = str13;
                        str27 = str14;
                        bool5 = bool3;
                        bool6 = bool4;
                        str28 = str15;
                    case AdditionVote2.URI_FIELD_NUMBER /* 17 */:
                        list16 = list25;
                        i11 |= 131072;
                        Unit unit19 = Unit.INSTANCE;
                        lazyArr2 = lazyArr;
                        list12 = list26;
                        list31 = (List) beginStructure.decodeNullableSerializableElement(serialDescriptor, 17, (DeserializationStrategy) lazyArr[17].getValue(), list31);
                        str10 = str23;
                        str11 = str24;
                        str12 = str25;
                        str13 = str26;
                        str14 = str27;
                        bool3 = bool5;
                        bool4 = bool6;
                        str15 = str28;
                        str17 = str29;
                        list27 = list34;
                        list25 = list16;
                        str29 = str17;
                        list26 = list12;
                        lazyArr = lazyArr2;
                        str23 = str10;
                        str24 = str11;
                        str25 = str12;
                        str26 = str13;
                        str27 = str14;
                        bool5 = bool3;
                        bool6 = bool4;
                        str28 = str15;
                    case AdditionVote2.IS_VOTED_FIELD_NUMBER /* 18 */:
                        list16 = list25;
                        i11 |= 262144;
                        Unit unit20 = Unit.INSTANCE;
                        lazyArr2 = lazyArr;
                        list28 = (List) beginStructure.decodeNullableSerializableElement(serialDescriptor, 18, (DeserializationStrategy) lazyArr[18].getValue(), list28);
                        list12 = list26;
                        str10 = str23;
                        str11 = str24;
                        str12 = str25;
                        str13 = str26;
                        str14 = str27;
                        bool3 = bool5;
                        bool4 = bool6;
                        str15 = str28;
                        str17 = str29;
                        list27 = list34;
                        list25 = list16;
                        str29 = str17;
                        list26 = list12;
                        lazyArr = lazyArr2;
                        str23 = str10;
                        str24 = str11;
                        str25 = str12;
                        str26 = str13;
                        str27 = str14;
                        bool5 = bool3;
                        bool6 = bool4;
                        str28 = str15;
                    case AdditionVote2.CHOICE_CNT_FIELD_NUMBER /* 19 */:
                        list16 = list25;
                        i19 = beginStructure.decodeIntElement(serialDescriptor, 19);
                        i11 |= 524288;
                        Unit unit21 = Unit.INSTANCE;
                        lazyArr2 = lazyArr;
                        list12 = list26;
                        str10 = str23;
                        str11 = str24;
                        str12 = str25;
                        str13 = str26;
                        str14 = str27;
                        bool3 = bool5;
                        bool4 = bool6;
                        str15 = str28;
                        str17 = str29;
                        list27 = list34;
                        list25 = list16;
                        str29 = str17;
                        list26 = list12;
                        lazyArr = lazyArr2;
                        str23 = str10;
                        str24 = str11;
                        str25 = str12;
                        str26 = str13;
                        str27 = str14;
                        bool5 = bool3;
                        bool6 = bool4;
                        str28 = str15;
                    case AdditionVote2.DEFAULE_SELECT_SHARE_FIELD_NUMBER /* 20 */:
                        list16 = list25;
                        i18 = beginStructure.decodeIntElement(serialDescriptor, 20);
                        i10 = 1048576;
                        i11 |= i10;
                        Unit unit22 = Unit.INSTANCE;
                        lazyArr2 = lazyArr;
                        list12 = list26;
                        str10 = str23;
                        str11 = str24;
                        str12 = str25;
                        str13 = str26;
                        str14 = str27;
                        bool3 = bool5;
                        bool4 = bool6;
                        str15 = str28;
                        str17 = str29;
                        list27 = list34;
                        list25 = list16;
                        str29 = str17;
                        list26 = list12;
                        lazyArr = lazyArr2;
                        str23 = str10;
                        str24 = str11;
                        str25 = str12;
                        str26 = str13;
                        str27 = str14;
                        bool5 = bool3;
                        bool6 = bool4;
                        str28 = str15;
                    case AdditionVote2.ONLY_FANS_VOTE_FIELD_NUMBER /* 21 */:
                        list16 = list25;
                        int decodeIntElement9 = beginStructure.decodeIntElement(serialDescriptor, 21);
                        i11 |= 2097152;
                        Unit unit23 = Unit.INSTANCE;
                        lazyArr2 = lazyArr;
                        i15 = decodeIntElement9;
                        list12 = list26;
                        str10 = str23;
                        str11 = str24;
                        str12 = str25;
                        str13 = str26;
                        str14 = str27;
                        bool3 = bool5;
                        bool4 = bool6;
                        str15 = str28;
                        str17 = str29;
                        list27 = list34;
                        list25 = list16;
                        str29 = str17;
                        list26 = list12;
                        lazyArr = lazyArr2;
                        str23 = str10;
                        str24 = str11;
                        str25 = str12;
                        str26 = str13;
                        str27 = str14;
                        bool5 = bool3;
                        bool6 = bool4;
                        str28 = str15;
                    case AdditionVote2.VOTE_OWNER_MID_FIELD_NUMBER /* 22 */:
                        list16 = list25;
                        int decodeIntElement10 = beginStructure.decodeIntElement(serialDescriptor, 22);
                        i11 |= 4194304;
                        Unit unit24 = Unit.INSTANCE;
                        lazyArr2 = lazyArr;
                        i16 = decodeIntElement10;
                        list12 = list26;
                        str10 = str23;
                        str11 = str24;
                        str12 = str25;
                        str13 = str26;
                        str14 = str27;
                        bool3 = bool5;
                        bool4 = bool6;
                        str15 = str28;
                        str17 = str29;
                        list27 = list34;
                        list25 = list16;
                        str29 = str17;
                        list26 = list12;
                        lazyArr = lazyArr2;
                        str23 = str10;
                        str24 = str11;
                        str25 = str12;
                        str26 = str13;
                        str27 = str14;
                        bool5 = bool3;
                        bool6 = bool4;
                        str28 = str15;
                    case 23:
                        list16 = list25;
                        i11 |= 8388608;
                        Unit unit25 = Unit.INSTANCE;
                        lazyArr2 = lazyArr;
                        adVideoEndPage3 = (AdVideoEndPage) beginStructure.decodeNullableSerializableElement(serialDescriptor, 23, AdVideoEndPage$$serializer.INSTANCE, adVideoEndPage3);
                        list12 = list26;
                        str10 = str23;
                        str11 = str24;
                        str12 = str25;
                        str13 = str26;
                        str14 = str27;
                        bool3 = bool5;
                        bool4 = bool6;
                        str15 = str28;
                        str17 = str29;
                        list27 = list34;
                        list25 = list16;
                        str29 = str17;
                        list26 = list12;
                        lazyArr = lazyArr2;
                        str23 = str10;
                        str24 = str11;
                        str25 = str12;
                        str26 = str13;
                        str27 = str14;
                        bool5 = bool3;
                        bool6 = bool4;
                        str28 = str15;
                    case 24:
                        list16 = list25;
                        i11 |= 16777216;
                        Unit unit26 = Unit.INSTANCE;
                        lazyArr2 = lazyArr;
                        str21 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 24, StringSerializer.INSTANCE, str21);
                        list12 = list26;
                        str10 = str23;
                        str11 = str24;
                        str12 = str25;
                        str13 = str26;
                        str14 = str27;
                        bool3 = bool5;
                        bool4 = bool6;
                        str15 = str28;
                        str17 = str29;
                        list27 = list34;
                        list25 = list16;
                        str29 = str17;
                        list26 = list12;
                        lazyArr = lazyArr2;
                        str23 = str10;
                        str24 = str11;
                        str25 = str12;
                        str26 = str13;
                        str27 = str14;
                        bool5 = bool3;
                        bool6 = bool4;
                        str28 = str15;
                    case 25:
                        list16 = list25;
                        i13 = beginStructure.decodeIntElement(serialDescriptor, 25);
                        i10 = 33554432;
                        i11 |= i10;
                        Unit unit222 = Unit.INSTANCE;
                        lazyArr2 = lazyArr;
                        list12 = list26;
                        str10 = str23;
                        str11 = str24;
                        str12 = str25;
                        str13 = str26;
                        str14 = str27;
                        bool3 = bool5;
                        bool4 = bool6;
                        str15 = str28;
                        str17 = str29;
                        list27 = list34;
                        list25 = list16;
                        str29 = str17;
                        list26 = list12;
                        lazyArr = lazyArr2;
                        str23 = str10;
                        str24 = str11;
                        str25 = str12;
                        str26 = str13;
                        str27 = str14;
                        bool5 = bool3;
                        bool6 = bool4;
                        str28 = str15;
                    case 26:
                        list16 = list25;
                        i14 = beginStructure.decodeIntElement(serialDescriptor, 26);
                        i10 = 67108864;
                        i11 |= i10;
                        Unit unit2222 = Unit.INSTANCE;
                        lazyArr2 = lazyArr;
                        list12 = list26;
                        str10 = str23;
                        str11 = str24;
                        str12 = str25;
                        str13 = str26;
                        str14 = str27;
                        bool3 = bool5;
                        bool4 = bool6;
                        str15 = str28;
                        str17 = str29;
                        list27 = list34;
                        list25 = list16;
                        str29 = str17;
                        list26 = list12;
                        lazyArr = lazyArr2;
                        str23 = str10;
                        str24 = str11;
                        str25 = str12;
                        str26 = str13;
                        str27 = str14;
                        bool5 = bool3;
                        bool6 = bool4;
                        str28 = str15;
                    case 27:
                        list16 = list25;
                        int decodeIntElement11 = beginStructure.decodeIntElement(serialDescriptor, 27);
                        i11 |= 134217728;
                        Unit unit27 = Unit.INSTANCE;
                        lazyArr2 = lazyArr;
                        i17 = decodeIntElement11;
                        list12 = list26;
                        str10 = str23;
                        str11 = str24;
                        str12 = str25;
                        str13 = str26;
                        str14 = str27;
                        bool3 = bool5;
                        bool4 = bool6;
                        str15 = str28;
                        str17 = str29;
                        list27 = list34;
                        list25 = list16;
                        str29 = str17;
                        list26 = list12;
                        lazyArr = lazyArr2;
                        str23 = str10;
                        str24 = str11;
                        str25 = str12;
                        str26 = str13;
                        str27 = str14;
                        bool5 = bool3;
                        bool6 = bool4;
                        str28 = str15;
                    case 28:
                        list16 = list25;
                        i12 = beginStructure.decodeIntElement(serialDescriptor, 28);
                        i10 = 268435456;
                        i11 |= i10;
                        Unit unit22222 = Unit.INSTANCE;
                        lazyArr2 = lazyArr;
                        list12 = list26;
                        str10 = str23;
                        str11 = str24;
                        str12 = str25;
                        str13 = str26;
                        str14 = str27;
                        bool3 = bool5;
                        bool4 = bool6;
                        str15 = str28;
                        str17 = str29;
                        list27 = list34;
                        list25 = list16;
                        str29 = str17;
                        list26 = list12;
                        lazyArr = lazyArr2;
                        str23 = str10;
                        str24 = str11;
                        str25 = str12;
                        str26 = str13;
                        str27 = str14;
                        bool5 = bool3;
                        bool6 = bool4;
                        str28 = str15;
                    case 29:
                        list16 = list25;
                        i11 |= 536870912;
                        Unit unit28 = Unit.INSTANCE;
                        lazyArr2 = lazyArr;
                        list30 = (List) beginStructure.decodeNullableSerializableElement(serialDescriptor, 29, (DeserializationStrategy) lazyArr[29].getValue(), list30);
                        list12 = list26;
                        str10 = str23;
                        str11 = str24;
                        str12 = str25;
                        str13 = str26;
                        str14 = str27;
                        bool3 = bool5;
                        bool4 = bool6;
                        str15 = str28;
                        str17 = str29;
                        list27 = list34;
                        list25 = list16;
                        str29 = str17;
                        list26 = list12;
                        lazyArr = lazyArr2;
                        str23 = str10;
                        str24 = str11;
                        str25 = str12;
                        str26 = str13;
                        str27 = str14;
                        bool5 = bool3;
                        bool6 = bool4;
                        str28 = str15;
                    default:
                        throw new UnknownFieldException(decodeElementIndex);
                }
            }
            String str30 = str22;
            str = str29;
            list = list29;
            list2 = list31;
            list3 = list32;
            list4 = list33;
            list5 = list24;
            list6 = list26;
            str2 = str23;
            i = i14;
            str3 = str25;
            str4 = str26;
            str5 = str27;
            bool = bool5;
            bool2 = bool6;
            str6 = str28;
            list7 = list25;
            list8 = list27;
            i2 = i15;
            i3 = i17;
            i4 = i19;
            str7 = str21;
            adVideoEndPage = adVideoEndPage3;
            list9 = list30;
            i5 = i12;
            i6 = i13;
            str8 = str24;
            i7 = i16;
            i8 = i18;
            i9 = i11;
            list10 = list28;
            str9 = str30;
        }
        beginStructure.endStructure(serialDescriptor);
        return new AdVideo(i9, str9, str2, str8, str3, str4, str5, bool, bool2, str6, str, list8, list7, list4, list5, list6, list3, list, list2, list10, i4, i8, i2, i7, adVideoEndPage, str7, i6, i, i3, i5, list9, (SerializationConstructorMarker) null);
    }

    public final void serialize(Encoder encoder, AdVideo value) {
        Intrinsics.checkNotNullParameter(encoder, "encoder");
        Intrinsics.checkNotNullParameter(value, "value");
        SerialDescriptor serialDescriptor = descriptor;
        CompositeEncoder beginStructure = encoder.beginStructure(serialDescriptor);
        AdVideo.write$Self$dto_debug(value, beginStructure, serialDescriptor);
        beginStructure.endStructure(serialDescriptor);
    }

    public /* bridge */ KSerializer<?>[] typeParametersSerializers() {
        return GeneratedSerializer.DefaultImpls.typeParametersSerializers(this);
    }
}