package kntr.app.mall.product.details.page.api.model;

import com.bapis.bilibili.app.dynamic.v2.AdditionalButton;
import kntr.app.mall.product.details.page.api.model.ActivityInfoFloor;
import kntr.app.upcomingEpisode.ConstantsKt;
import kntr.watch.later.watchlater.edit.MediaAttrUtils;
import kotlin.Deprecated;
import kotlin.DeprecationLevel;
import kotlin.Metadata;
import kotlin.Unit;
import kotlin.jvm.internal.Intrinsics;
import kotlinx.serialization.KSerializer;
import kotlinx.serialization.UnknownFieldException;
import kotlinx.serialization.builtins.BuiltinSerializersKt;
import kotlinx.serialization.descriptors.SerialDescriptor;
import kotlinx.serialization.encoding.CompositeDecoder;
import kotlinx.serialization.encoding.CompositeEncoder;
import kotlinx.serialization.encoding.Decoder;
import kotlinx.serialization.encoding.Encoder;
import kotlinx.serialization.internal.BooleanSerializer;
import kotlinx.serialization.internal.ByteSerializer;
import kotlinx.serialization.internal.DoubleSerializer;
import kotlinx.serialization.internal.GeneratedSerializer;
import kotlinx.serialization.internal.IntSerializer;
import kotlinx.serialization.internal.PluginGeneratedSerialDescriptor;
import kotlinx.serialization.internal.SerializationConstructorMarker;
import kotlinx.serialization.internal.StringSerializer;

/* compiled from: ActivityInfoFloor.kt */
@Metadata(d1 = {"\u00006\n\u0000\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\b\u0003\n\u0002\u0010\u0011\n\u0002\u0018\u0002\n\u0002\b\u0003\n\u0002\u0018\u0002\n\u0000\n\u0002\u0010\u0002\n\u0000\n\u0002\u0018\u0002\n\u0002\b\u0002\n\u0002\u0018\u0002\n\u0002\b\u0003\bÇ\u0002\u0018\u00002\b\u0012\u0004\u0012\u00020\u00020\u0001B\t\b\u0002¢\u0006\u0004\b\u0003\u0010\u0004J\u0015\u0010\u0005\u001a\f\u0012\b\u0012\u0006\u0012\u0002\b\u00030\u00070\u0006¢\u0006\u0002\u0010\bJ\u000e\u0010\t\u001a\u00020\u00022\u0006\u0010\n\u001a\u00020\u000bJ\u0016\u0010\f\u001a\u00020\r2\u0006\u0010\u000e\u001a\u00020\u000f2\u0006\u0010\u0010\u001a\u00020\u0002R\u0011\u0010\u0011\u001a\u00020\u0012¢\u0006\b\n\u0000\u001a\u0004\b\u0013\u0010\u0014¨\u0006\u0015"}, d2 = {"kntr/app/mall/product/details/page/api/model/ActivityInfoFloor.ActivityExtInfo.NewUserCoupon.$serializer", "Lkotlinx/serialization/internal/GeneratedSerializer;", "Lkntr/app/mall/product/details/page/api/model/ActivityInfoFloor$ActivityExtInfo$NewUserCoupon;", "<init>", "()V", "childSerializers", "", "Lkotlinx/serialization/KSerializer;", "()[Lkotlinx/serialization/KSerializer;", "deserialize", "decoder", "Lkotlinx/serialization/encoding/Decoder;", "serialize", "", "encoder", "Lkotlinx/serialization/encoding/Encoder;", "value", "descriptor", "Lkotlinx/serialization/descriptors/SerialDescriptor;", "getDescriptor", "()Lkotlinx/serialization/descriptors/SerialDescriptor;", "product-details-page_debug"}, k = 1, mv = {2, 2, 0}, xi = ConstantsKt.OGV_UPDATE_CALENDAR_CARD_COVER_WIDTH)
@Deprecated(level = DeprecationLevel.HIDDEN, message = "This synthesized declaration should not be used directly")
public final /* synthetic */ class ActivityInfoFloor$ActivityExtInfo$NewUserCoupon$$serializer implements GeneratedSerializer<ActivityInfoFloor.ActivityExtInfo.NewUserCoupon> {
    public static final int $stable;
    public static final ActivityInfoFloor$ActivityExtInfo$NewUserCoupon$$serializer INSTANCE = new ActivityInfoFloor$ActivityExtInfo$NewUserCoupon$$serializer();
    private static final SerialDescriptor descriptor;

    public final SerialDescriptor getDescriptor() {
        return descriptor;
    }

    static {
        SerialDescriptor pluginGeneratedSerialDescriptor = new PluginGeneratedSerialDescriptor("kntr.app.mall.product.details.page.api.model.ActivityInfoFloor.ActivityExtInfo.NewUserCoupon", INSTANCE, 35);
        pluginGeneratedSerialDescriptor.addElement("couponId", true);
        pluginGeneratedSerialDescriptor.addElement("couponName", true);
        pluginGeneratedSerialDescriptor.addElement("couponStatus", true);
        pluginGeneratedSerialDescriptor.addElement("couponStatusMsg", true);
        pluginGeneratedSerialDescriptor.addElement("couponType", true);
        pluginGeneratedSerialDescriptor.addElement("couponTypeComb", true);
        pluginGeneratedSerialDescriptor.addElement("couponTypeDesc", true);
        pluginGeneratedSerialDescriptor.addElement("couponTypeName", true);
        pluginGeneratedSerialDescriptor.addElement("discount", true);
        pluginGeneratedSerialDescriptor.addElement("discountCondition", true);
        pluginGeneratedSerialDescriptor.addElement("discountLayer", true);
        pluginGeneratedSerialDescriptor.addElement("discountLimit", true);
        pluginGeneratedSerialDescriptor.addElement("discountY", true);
        pluginGeneratedSerialDescriptor.addElement("extraInfo", true);
        pluginGeneratedSerialDescriptor.addElement("hasNewUserCoupon", true);
        pluginGeneratedSerialDescriptor.addElement("maxNumPerUser", true);
        pluginGeneratedSerialDescriptor.addElement("newUserLimit", true);
        pluginGeneratedSerialDescriptor.addElement("owners", true);
        pluginGeneratedSerialDescriptor.addElement("ownersName", true);
        pluginGeneratedSerialDescriptor.addElement("receiveChannel", true);
        pluginGeneratedSerialDescriptor.addElement("receiveEndTime", true);
        pluginGeneratedSerialDescriptor.addElement("receiveStartTime", true);
        pluginGeneratedSerialDescriptor.addElement("regTime", true);
        pluginGeneratedSerialDescriptor.addElement("sceneId", true);
        pluginGeneratedSerialDescriptor.addElement("shopLabel", true);
        pluginGeneratedSerialDescriptor.addElement("showName", true);
        pluginGeneratedSerialDescriptor.addElement("sourceAuthorityId", true);
        pluginGeneratedSerialDescriptor.addElement("sourceId", true);
        pluginGeneratedSerialDescriptor.addElement("useEffectDays", true);
        pluginGeneratedSerialDescriptor.addElement("useEffectUnit", true);
        pluginGeneratedSerialDescriptor.addElement("useEndTime", true);
        pluginGeneratedSerialDescriptor.addElement("useStartTime", true);
        pluginGeneratedSerialDescriptor.addElement("userCouponReceiveStatus", true);
        pluginGeneratedSerialDescriptor.addElement("userLevel", true);
        pluginGeneratedSerialDescriptor.addElement("vipType", true);
        descriptor = pluginGeneratedSerialDescriptor;
        $stable = 8;
    }

    private ActivityInfoFloor$ActivityExtInfo$NewUserCoupon$$serializer() {
    }

    public final KSerializer<?>[] childSerializers() {
        return new KSerializer[]{BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(ByteSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(IntSerializer.INSTANCE), BuiltinSerializersKt.getNullable(IntSerializer.INSTANCE), BuiltinSerializersKt.getNullable(ByteSerializer.INSTANCE), BuiltinSerializersKt.getNullable(IntSerializer.INSTANCE), BuiltinSerializersKt.getNullable(DoubleSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(BooleanSerializer.INSTANCE), BuiltinSerializersKt.getNullable(IntSerializer.INSTANCE), BuiltinSerializersKt.getNullable(ByteSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(IntSerializer.INSTANCE), BuiltinSerializersKt.getNullable(IntSerializer.INSTANCE), BuiltinSerializersKt.getNullable(IntSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(IntSerializer.INSTANCE), BuiltinSerializersKt.getNullable(ByteSerializer.INSTANCE), BuiltinSerializersKt.getNullable(IntSerializer.INSTANCE), BuiltinSerializersKt.getNullable(IntSerializer.INSTANCE), BuiltinSerializersKt.getNullable(IntSerializer.INSTANCE), BuiltinSerializersKt.getNullable(ByteSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE)};
    }

    public final ActivityInfoFloor.ActivityExtInfo.NewUserCoupon deserialize(Decoder decoder) {
        String str;
        Integer num;
        Integer num2;
        Byte b;
        Integer num3;
        Integer num4;
        Byte b2;
        String str2;
        String str3;
        String str4;
        String str5;
        Integer num5;
        String str6;
        Integer num6;
        int i;
        Integer num7;
        String str7;
        String str8;
        int i2;
        String str9;
        String str10;
        Integer num8;
        Integer num9;
        Byte b3;
        String str11;
        Integer num10;
        String str12;
        String str13;
        Byte b4;
        Integer num11;
        Byte b5;
        Double d;
        String str14;
        Boolean bool;
        String str15;
        String str16;
        String str17;
        String str18;
        String str19;
        String str20;
        String str21;
        String str22;
        String str23;
        Byte b6;
        String str24;
        String str25;
        String str26;
        Integer num12;
        Integer num13;
        Byte b7;
        Integer num14;
        Double d2;
        String str27;
        Boolean bool2;
        Integer num15;
        Byte b8;
        String str28;
        String str29;
        String str30;
        String str31;
        String str32;
        String str33;
        String str34;
        String str35;
        String str36;
        int i3;
        Intrinsics.checkNotNullParameter(decoder, "decoder");
        SerialDescriptor serialDescriptor = descriptor;
        CompositeDecoder beginStructure = decoder.beginStructure(serialDescriptor);
        if (beginStructure.decodeSequentially()) {
            Integer num16 = (Integer) beginStructure.decodeNullableSerializableElement(serialDescriptor, 11, IntSerializer.INSTANCE, (Object) null);
            Double d3 = (Double) beginStructure.decodeNullableSerializableElement(serialDescriptor, 12, DoubleSerializer.INSTANCE, (Object) null);
            String str37 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 13, StringSerializer.INSTANCE, (Object) null);
            Boolean bool3 = (Boolean) beginStructure.decodeNullableSerializableElement(serialDescriptor, 14, BooleanSerializer.INSTANCE, (Object) null);
            Integer num17 = (Integer) beginStructure.decodeNullableSerializableElement(serialDescriptor, 15, IntSerializer.INSTANCE, (Object) null);
            Byte b9 = (Byte) beginStructure.decodeNullableSerializableElement(serialDescriptor, 16, ByteSerializer.INSTANCE, (Object) null);
            String str38 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 17, StringSerializer.INSTANCE, (Object) null);
            String str39 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 18, StringSerializer.INSTANCE, (Object) null);
            String str40 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 19, StringSerializer.INSTANCE, (Object) null);
            Integer num18 = (Integer) beginStructure.decodeNullableSerializableElement(serialDescriptor, 20, IntSerializer.INSTANCE, (Object) null);
            Integer num19 = (Integer) beginStructure.decodeNullableSerializableElement(serialDescriptor, 21, IntSerializer.INSTANCE, (Object) null);
            Integer num20 = (Integer) beginStructure.decodeNullableSerializableElement(serialDescriptor, 22, IntSerializer.INSTANCE, (Object) null);
            String str41 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 23, StringSerializer.INSTANCE, (Object) null);
            String str42 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 24, StringSerializer.INSTANCE, (Object) null);
            String str43 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 25, StringSerializer.INSTANCE, (Object) null);
            String str44 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 26, StringSerializer.INSTANCE, (Object) null);
            String str45 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 27, StringSerializer.INSTANCE, (Object) null);
            Integer num21 = (Integer) beginStructure.decodeNullableSerializableElement(serialDescriptor, 28, IntSerializer.INSTANCE, (Object) null);
            Byte b10 = (Byte) beginStructure.decodeNullableSerializableElement(serialDescriptor, 29, ByteSerializer.INSTANCE, (Object) null);
            Integer num22 = (Integer) beginStructure.decodeNullableSerializableElement(serialDescriptor, 30, IntSerializer.INSTANCE, (Object) null);
            Integer num23 = (Integer) beginStructure.decodeNullableSerializableElement(serialDescriptor, 31, IntSerializer.INSTANCE, (Object) null);
            Integer num24 = (Integer) beginStructure.decodeNullableSerializableElement(serialDescriptor, 32, IntSerializer.INSTANCE, (Object) null);
            Byte b11 = (Byte) beginStructure.decodeNullableSerializableElement(serialDescriptor, 33, ByteSerializer.INSTANCE, (Object) null);
            str5 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 34, StringSerializer.INSTANCE, (Object) null);
            num9 = (Integer) beginStructure.decodeNullableSerializableElement(serialDescriptor, 9, IntSerializer.INSTANCE, (Object) null);
            num = num24;
            num7 = num20;
            str7 = str41;
            str3 = str42;
            str2 = str43;
            str8 = str44;
            str6 = str45;
            num2 = num21;
            b2 = b10;
            num4 = num22;
            num3 = num23;
            b = b11;
            str = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 0, StringSerializer.INSTANCE, (Object) null);
            str4 = str40;
            str9 = str39;
            str12 = str38;
            b3 = b9;
            num11 = num17;
            bool = bool3;
            str16 = str37;
            d = d3;
            num10 = num16;
            num5 = num18;
            num6 = num19;
            i = 7;
            str11 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 3, StringSerializer.INSTANCE, (Object) null);
            num8 = (Integer) beginStructure.decodeNullableSerializableElement(serialDescriptor, 8, IntSerializer.INSTANCE, (Object) null);
            b5 = (Byte) beginStructure.decodeNullableSerializableElement(serialDescriptor, 4, ByteSerializer.INSTANCE, (Object) null);
            str13 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 2, StringSerializer.INSTANCE, (Object) null);
            str10 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 1, StringSerializer.INSTANCE, (Object) null);
            str15 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 5, StringSerializer.INSTANCE, (Object) null);
            i2 = -1;
            b4 = (Byte) beginStructure.decodeNullableSerializableElement(serialDescriptor, 10, ByteSerializer.INSTANCE, (Object) null);
            str17 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 6, StringSerializer.INSTANCE, (Object) null);
            str14 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 7, StringSerializer.INSTANCE, (Object) null);
        } else {
            boolean z = true;
            int i4 = 0;
            String str46 = null;
            String str47 = null;
            Integer num25 = null;
            Integer num26 = null;
            String str48 = null;
            Byte b12 = null;
            Integer num27 = null;
            Integer num28 = null;
            String str49 = null;
            String str50 = null;
            Integer num29 = null;
            String str51 = null;
            String str52 = null;
            String str53 = null;
            String str54 = null;
            String str55 = null;
            Byte b13 = null;
            String str56 = null;
            String str57 = null;
            String str58 = null;
            Integer num30 = null;
            Integer num31 = null;
            Byte b14 = null;
            Integer num32 = null;
            Double d4 = null;
            String str59 = null;
            Boolean bool4 = null;
            Integer num33 = null;
            Byte b15 = null;
            String str60 = null;
            String str61 = null;
            String str62 = null;
            Integer num34 = null;
            Integer num35 = null;
            Byte b16 = null;
            int i5 = 0;
            while (z) {
                Integer num36 = num29;
                int decodeElementIndex = beginStructure.decodeElementIndex(serialDescriptor);
                switch (decodeElementIndex) {
                    case -1:
                        str18 = str46;
                        str19 = str47;
                        str20 = str48;
                        str21 = str53;
                        str22 = str54;
                        str23 = str55;
                        b6 = b13;
                        str24 = str56;
                        str25 = str57;
                        str26 = str58;
                        num12 = num30;
                        num13 = num31;
                        b7 = b14;
                        num14 = num32;
                        d2 = d4;
                        str27 = str59;
                        bool2 = bool4;
                        num15 = num33;
                        b8 = b15;
                        str28 = str60;
                        str29 = str61;
                        str30 = str62;
                        Unit unit = Unit.INSTANCE;
                        z = false;
                        str48 = str20;
                        str46 = str18;
                        str33 = str30;
                        num29 = num36;
                        break;
                    case 0:
                        str18 = str46;
                        str19 = str47;
                        str20 = str48;
                        str22 = str54;
                        str23 = str55;
                        b6 = b13;
                        str24 = str56;
                        str25 = str57;
                        str26 = str58;
                        num12 = num30;
                        num13 = num31;
                        b7 = b14;
                        num14 = num32;
                        d2 = d4;
                        str27 = str59;
                        bool2 = bool4;
                        num15 = num33;
                        b8 = b15;
                        str28 = str60;
                        str29 = str61;
                        str30 = str62;
                        str21 = str53;
                        i5 |= 1;
                        Unit unit2 = Unit.INSTANCE;
                        str52 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 0, StringSerializer.INSTANCE, str52);
                        str48 = str20;
                        str46 = str18;
                        str33 = str30;
                        num29 = num36;
                        break;
                    case 1:
                        str31 = str46;
                        str19 = str47;
                        str32 = str48;
                        str23 = str55;
                        b6 = b13;
                        str24 = str56;
                        str25 = str57;
                        str26 = str58;
                        num12 = num30;
                        num13 = num31;
                        b7 = b14;
                        num14 = num32;
                        d2 = d4;
                        str27 = str59;
                        bool2 = bool4;
                        num15 = num33;
                        b8 = b15;
                        str28 = str60;
                        str29 = str61;
                        str30 = str62;
                        str22 = str54;
                        i5 |= 2;
                        Unit unit3 = Unit.INSTANCE;
                        str21 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 1, StringSerializer.INSTANCE, str53);
                        str48 = str32;
                        str46 = str31;
                        str33 = str30;
                        num29 = num36;
                        break;
                    case 2:
                        str31 = str46;
                        str19 = str47;
                        str32 = str48;
                        b6 = b13;
                        str24 = str56;
                        str25 = str57;
                        str26 = str58;
                        num12 = num30;
                        num13 = num31;
                        b7 = b14;
                        num14 = num32;
                        d2 = d4;
                        str27 = str59;
                        bool2 = bool4;
                        num15 = num33;
                        b8 = b15;
                        str28 = str60;
                        str29 = str61;
                        str30 = str62;
                        str23 = str55;
                        i5 |= 4;
                        Unit unit4 = Unit.INSTANCE;
                        str22 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 2, StringSerializer.INSTANCE, str54);
                        str21 = str53;
                        str48 = str32;
                        str46 = str31;
                        str33 = str30;
                        num29 = num36;
                        break;
                    case 3:
                        str31 = str46;
                        str19 = str47;
                        str32 = str48;
                        str24 = str56;
                        str25 = str57;
                        str26 = str58;
                        num12 = num30;
                        num13 = num31;
                        b7 = b14;
                        num14 = num32;
                        d2 = d4;
                        str27 = str59;
                        bool2 = bool4;
                        num15 = num33;
                        b8 = b15;
                        str28 = str60;
                        str29 = str61;
                        str30 = str62;
                        b6 = b13;
                        i5 |= 8;
                        Unit unit5 = Unit.INSTANCE;
                        str23 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 3, StringSerializer.INSTANCE, str55);
                        str21 = str53;
                        str22 = str54;
                        str48 = str32;
                        str46 = str31;
                        str33 = str30;
                        num29 = num36;
                        break;
                    case 4:
                        str31 = str46;
                        str19 = str47;
                        str32 = str48;
                        str25 = str57;
                        str26 = str58;
                        num12 = num30;
                        num13 = num31;
                        b7 = b14;
                        num14 = num32;
                        d2 = d4;
                        str27 = str59;
                        bool2 = bool4;
                        num15 = num33;
                        b8 = b15;
                        str28 = str60;
                        str29 = str61;
                        str30 = str62;
                        str24 = str56;
                        i5 |= 16;
                        Unit unit6 = Unit.INSTANCE;
                        b6 = (Byte) beginStructure.decodeNullableSerializableElement(serialDescriptor, 4, ByteSerializer.INSTANCE, b13);
                        str21 = str53;
                        str22 = str54;
                        str23 = str55;
                        str48 = str32;
                        str46 = str31;
                        str33 = str30;
                        num29 = num36;
                        break;
                    case 5:
                        str31 = str46;
                        str19 = str47;
                        str32 = str48;
                        str26 = str58;
                        num12 = num30;
                        num13 = num31;
                        b7 = b14;
                        num14 = num32;
                        d2 = d4;
                        str27 = str59;
                        bool2 = bool4;
                        num15 = num33;
                        b8 = b15;
                        str28 = str60;
                        str29 = str61;
                        str30 = str62;
                        str25 = str57;
                        i5 |= 32;
                        Unit unit7 = Unit.INSTANCE;
                        str24 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 5, StringSerializer.INSTANCE, str56);
                        str21 = str53;
                        str22 = str54;
                        str23 = str55;
                        b6 = b13;
                        str48 = str32;
                        str46 = str31;
                        str33 = str30;
                        num29 = num36;
                        break;
                    case 6:
                        str31 = str46;
                        str19 = str47;
                        str32 = str48;
                        num12 = num30;
                        num13 = num31;
                        b7 = b14;
                        num14 = num32;
                        d2 = d4;
                        str27 = str59;
                        bool2 = bool4;
                        num15 = num33;
                        b8 = b15;
                        str28 = str60;
                        str29 = str61;
                        str30 = str62;
                        str26 = str58;
                        i5 |= 64;
                        Unit unit8 = Unit.INSTANCE;
                        str25 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 6, StringSerializer.INSTANCE, str57);
                        str21 = str53;
                        str22 = str54;
                        str23 = str55;
                        b6 = b13;
                        str24 = str56;
                        str48 = str32;
                        str46 = str31;
                        str33 = str30;
                        num29 = num36;
                        break;
                    case AdditionalButton.CLICK_TYPE_FIELD_NUMBER /* 7 */:
                        str31 = str46;
                        str19 = str47;
                        str32 = str48;
                        num13 = num31;
                        b7 = b14;
                        num14 = num32;
                        d2 = d4;
                        str27 = str59;
                        bool2 = bool4;
                        num15 = num33;
                        b8 = b15;
                        str28 = str60;
                        str29 = str61;
                        str30 = str62;
                        num12 = num30;
                        i5 |= 128;
                        Unit unit9 = Unit.INSTANCE;
                        str26 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 7, StringSerializer.INSTANCE, str58);
                        str21 = str53;
                        str22 = str54;
                        str23 = str55;
                        b6 = b13;
                        str24 = str56;
                        str25 = str57;
                        str48 = str32;
                        str46 = str31;
                        str33 = str30;
                        num29 = num36;
                        break;
                    case 8:
                        str31 = str46;
                        str19 = str47;
                        str32 = str48;
                        b7 = b14;
                        num14 = num32;
                        d2 = d4;
                        str27 = str59;
                        bool2 = bool4;
                        num15 = num33;
                        b8 = b15;
                        str28 = str60;
                        str29 = str61;
                        str30 = str62;
                        num13 = num31;
                        i5 |= 256;
                        Unit unit10 = Unit.INSTANCE;
                        num12 = (Integer) beginStructure.decodeNullableSerializableElement(serialDescriptor, 8, IntSerializer.INSTANCE, num30);
                        str21 = str53;
                        str22 = str54;
                        str23 = str55;
                        b6 = b13;
                        str24 = str56;
                        str25 = str57;
                        str26 = str58;
                        str48 = str32;
                        str46 = str31;
                        str33 = str30;
                        num29 = num36;
                        break;
                    case ConstantsKt.SPACER_9 /* 9 */:
                        str31 = str46;
                        str19 = str47;
                        str32 = str48;
                        num14 = num32;
                        d2 = d4;
                        str27 = str59;
                        bool2 = bool4;
                        num15 = num33;
                        b8 = b15;
                        str28 = str60;
                        str29 = str61;
                        str30 = str62;
                        b7 = b14;
                        i5 |= 512;
                        Unit unit11 = Unit.INSTANCE;
                        num13 = (Integer) beginStructure.decodeNullableSerializableElement(serialDescriptor, 9, IntSerializer.INSTANCE, num31);
                        str21 = str53;
                        str22 = str54;
                        str23 = str55;
                        b6 = b13;
                        str24 = str56;
                        str25 = str57;
                        str26 = str58;
                        num12 = num30;
                        str48 = str32;
                        str46 = str31;
                        str33 = str30;
                        num29 = num36;
                        break;
                    case 10:
                        str31 = str46;
                        str19 = str47;
                        str32 = str48;
                        d2 = d4;
                        str27 = str59;
                        bool2 = bool4;
                        num15 = num33;
                        b8 = b15;
                        str28 = str60;
                        str29 = str61;
                        str30 = str62;
                        num14 = num32;
                        i5 |= 1024;
                        Unit unit12 = Unit.INSTANCE;
                        b7 = (Byte) beginStructure.decodeNullableSerializableElement(serialDescriptor, 10, ByteSerializer.INSTANCE, b14);
                        str21 = str53;
                        str22 = str54;
                        str23 = str55;
                        b6 = b13;
                        str24 = str56;
                        str25 = str57;
                        str26 = str58;
                        num12 = num30;
                        num13 = num31;
                        str48 = str32;
                        str46 = str31;
                        str33 = str30;
                        num29 = num36;
                        break;
                    case MediaAttrUtils.TYPE_MENU /* 11 */:
                        str31 = str46;
                        str19 = str47;
                        str32 = str48;
                        str27 = str59;
                        bool2 = bool4;
                        num15 = num33;
                        b8 = b15;
                        str28 = str60;
                        str29 = str61;
                        str30 = str62;
                        d2 = d4;
                        i5 |= 2048;
                        Unit unit13 = Unit.INSTANCE;
                        num14 = (Integer) beginStructure.decodeNullableSerializableElement(serialDescriptor, 11, IntSerializer.INSTANCE, num32);
                        str21 = str53;
                        str22 = str54;
                        str23 = str55;
                        b6 = b13;
                        str24 = str56;
                        str25 = str57;
                        str26 = str58;
                        num12 = num30;
                        num13 = num31;
                        b7 = b14;
                        str48 = str32;
                        str46 = str31;
                        str33 = str30;
                        num29 = num36;
                        break;
                    case 12:
                        str31 = str46;
                        str19 = str47;
                        str32 = str48;
                        bool2 = bool4;
                        num15 = num33;
                        b8 = b15;
                        str28 = str60;
                        str29 = str61;
                        str30 = str62;
                        str27 = str59;
                        i5 |= 4096;
                        Unit unit14 = Unit.INSTANCE;
                        d2 = (Double) beginStructure.decodeNullableSerializableElement(serialDescriptor, 12, DoubleSerializer.INSTANCE, d4);
                        str21 = str53;
                        str22 = str54;
                        str23 = str55;
                        b6 = b13;
                        str24 = str56;
                        str25 = str57;
                        str26 = str58;
                        num12 = num30;
                        num13 = num31;
                        b7 = b14;
                        num14 = num32;
                        str48 = str32;
                        str46 = str31;
                        str33 = str30;
                        num29 = num36;
                        break;
                    case 13:
                        str31 = str46;
                        str19 = str47;
                        str32 = str48;
                        num15 = num33;
                        b8 = b15;
                        str28 = str60;
                        str29 = str61;
                        str30 = str62;
                        bool2 = bool4;
                        i5 |= 8192;
                        Unit unit15 = Unit.INSTANCE;
                        str27 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 13, StringSerializer.INSTANCE, str59);
                        str21 = str53;
                        str22 = str54;
                        str23 = str55;
                        b6 = b13;
                        str24 = str56;
                        str25 = str57;
                        str26 = str58;
                        num12 = num30;
                        num13 = num31;
                        b7 = b14;
                        num14 = num32;
                        d2 = d4;
                        str48 = str32;
                        str46 = str31;
                        str33 = str30;
                        num29 = num36;
                        break;
                    case ConstantsKt.SPACER_14 /* 14 */:
                        str31 = str46;
                        str19 = str47;
                        str32 = str48;
                        b8 = b15;
                        str28 = str60;
                        str29 = str61;
                        str30 = str62;
                        num15 = num33;
                        i5 |= 16384;
                        Unit unit16 = Unit.INSTANCE;
                        bool2 = (Boolean) beginStructure.decodeNullableSerializableElement(serialDescriptor, 14, BooleanSerializer.INSTANCE, bool4);
                        str21 = str53;
                        str22 = str54;
                        str23 = str55;
                        b6 = b13;
                        str24 = str56;
                        str25 = str57;
                        str26 = str58;
                        num12 = num30;
                        num13 = num31;
                        b7 = b14;
                        num14 = num32;
                        d2 = d4;
                        str27 = str59;
                        str48 = str32;
                        str46 = str31;
                        str33 = str30;
                        num29 = num36;
                        break;
                    case 15:
                        str31 = str46;
                        str19 = str47;
                        str32 = str48;
                        str28 = str60;
                        str29 = str61;
                        str30 = str62;
                        b8 = b15;
                        i5 |= 32768;
                        Unit unit17 = Unit.INSTANCE;
                        num15 = (Integer) beginStructure.decodeNullableSerializableElement(serialDescriptor, 15, IntSerializer.INSTANCE, num33);
                        str21 = str53;
                        str22 = str54;
                        str23 = str55;
                        b6 = b13;
                        str24 = str56;
                        str25 = str57;
                        str26 = str58;
                        num12 = num30;
                        num13 = num31;
                        b7 = b14;
                        num14 = num32;
                        d2 = d4;
                        str27 = str59;
                        bool2 = bool4;
                        str48 = str32;
                        str46 = str31;
                        str33 = str30;
                        num29 = num36;
                        break;
                    case 16:
                        str31 = str46;
                        str19 = str47;
                        str32 = str48;
                        str29 = str61;
                        str30 = str62;
                        str28 = str60;
                        i5 |= 65536;
                        Unit unit18 = Unit.INSTANCE;
                        b8 = (Byte) beginStructure.decodeNullableSerializableElement(serialDescriptor, 16, ByteSerializer.INSTANCE, b15);
                        str21 = str53;
                        str22 = str54;
                        str23 = str55;
                        b6 = b13;
                        str24 = str56;
                        str25 = str57;
                        str26 = str58;
                        num12 = num30;
                        num13 = num31;
                        b7 = b14;
                        num14 = num32;
                        d2 = d4;
                        str27 = str59;
                        bool2 = bool4;
                        num15 = num33;
                        str48 = str32;
                        str46 = str31;
                        str33 = str30;
                        num29 = num36;
                        break;
                    case 17:
                        str31 = str46;
                        str19 = str47;
                        str32 = str48;
                        str30 = str62;
                        str29 = str61;
                        i5 |= 131072;
                        Unit unit19 = Unit.INSTANCE;
                        str28 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 17, StringSerializer.INSTANCE, str60);
                        str21 = str53;
                        str22 = str54;
                        str23 = str55;
                        b6 = b13;
                        str24 = str56;
                        str25 = str57;
                        str26 = str58;
                        num12 = num30;
                        num13 = num31;
                        b7 = b14;
                        num14 = num32;
                        d2 = d4;
                        str27 = str59;
                        bool2 = bool4;
                        num15 = num33;
                        b8 = b15;
                        str48 = str32;
                        str46 = str31;
                        str33 = str30;
                        num29 = num36;
                        break;
                    case 18:
                        str31 = str46;
                        str32 = str48;
                        str30 = str62;
                        str19 = str47;
                        i5 |= 262144;
                        Unit unit20 = Unit.INSTANCE;
                        str29 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 18, StringSerializer.INSTANCE, str61);
                        str21 = str53;
                        str22 = str54;
                        str23 = str55;
                        b6 = b13;
                        str24 = str56;
                        str25 = str57;
                        str26 = str58;
                        num12 = num30;
                        num13 = num31;
                        b7 = b14;
                        num14 = num32;
                        d2 = d4;
                        str27 = str59;
                        bool2 = bool4;
                        num15 = num33;
                        b8 = b15;
                        str28 = str60;
                        str48 = str32;
                        str46 = str31;
                        str33 = str30;
                        num29 = num36;
                        break;
                    case 19:
                        i5 |= 524288;
                        Unit unit21 = Unit.INSTANCE;
                        str19 = str47;
                        num34 = num34;
                        str21 = str53;
                        str22 = str54;
                        str23 = str55;
                        b6 = b13;
                        str24 = str56;
                        str25 = str57;
                        str26 = str58;
                        num12 = num30;
                        num13 = num31;
                        b7 = b14;
                        num14 = num32;
                        d2 = d4;
                        str27 = str59;
                        bool2 = bool4;
                        num15 = num33;
                        b8 = b15;
                        str28 = str60;
                        str29 = str61;
                        num29 = num36;
                        str46 = str46;
                        str33 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 19, StringSerializer.INSTANCE, str62);
                        str48 = str48;
                        break;
                    case 20:
                        str34 = str46;
                        str35 = str48;
                        i5 |= 1048576;
                        Unit unit22 = Unit.INSTANCE;
                        num34 = (Integer) beginStructure.decodeNullableSerializableElement(serialDescriptor, 20, IntSerializer.INSTANCE, num34);
                        str19 = str47;
                        str21 = str53;
                        str22 = str54;
                        str23 = str55;
                        b6 = b13;
                        str24 = str56;
                        str25 = str57;
                        str26 = str58;
                        num12 = num30;
                        num13 = num31;
                        b7 = b14;
                        num14 = num32;
                        d2 = d4;
                        str27 = str59;
                        bool2 = bool4;
                        num15 = num33;
                        b8 = b15;
                        str28 = str60;
                        str29 = str61;
                        str33 = str62;
                        num29 = num36;
                        str48 = str35;
                        str46 = str34;
                        break;
                    case 21:
                        str34 = str46;
                        str35 = str48;
                        i5 |= 2097152;
                        Unit unit23 = Unit.INSTANCE;
                        num35 = (Integer) beginStructure.decodeNullableSerializableElement(serialDescriptor, 21, IntSerializer.INSTANCE, num35);
                        str19 = str47;
                        str21 = str53;
                        str22 = str54;
                        str23 = str55;
                        b6 = b13;
                        str24 = str56;
                        str25 = str57;
                        str26 = str58;
                        num12 = num30;
                        num13 = num31;
                        b7 = b14;
                        num14 = num32;
                        d2 = d4;
                        str27 = str59;
                        bool2 = bool4;
                        num15 = num33;
                        b8 = b15;
                        str28 = str60;
                        str29 = str61;
                        str33 = str62;
                        num29 = num36;
                        str48 = str35;
                        str46 = str34;
                        break;
                    case 22:
                        str34 = str46;
                        str35 = str48;
                        i5 |= 4194304;
                        Unit unit24 = Unit.INSTANCE;
                        num29 = (Integer) beginStructure.decodeNullableSerializableElement(serialDescriptor, 22, IntSerializer.INSTANCE, num36);
                        str19 = str47;
                        str21 = str53;
                        str22 = str54;
                        str23 = str55;
                        b6 = b13;
                        str24 = str56;
                        str25 = str57;
                        str26 = str58;
                        num12 = num30;
                        num13 = num31;
                        b7 = b14;
                        num14 = num32;
                        d2 = d4;
                        str27 = str59;
                        bool2 = bool4;
                        num15 = num33;
                        b8 = b15;
                        str28 = str60;
                        str29 = str61;
                        str33 = str62;
                        str48 = str35;
                        str46 = str34;
                        break;
                    case 23:
                        String str63 = str48;
                        str34 = str46;
                        i5 |= 8388608;
                        Unit unit25 = Unit.INSTANCE;
                        str48 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 23, StringSerializer.INSTANCE, str63);
                        str19 = str47;
                        str21 = str53;
                        str22 = str54;
                        str23 = str55;
                        b6 = b13;
                        str24 = str56;
                        str25 = str57;
                        str26 = str58;
                        num12 = num30;
                        num13 = num31;
                        b7 = b14;
                        num14 = num32;
                        d2 = d4;
                        str27 = str59;
                        bool2 = bool4;
                        num15 = num33;
                        b8 = b15;
                        str28 = str60;
                        str29 = str61;
                        str33 = str62;
                        num29 = num36;
                        str46 = str34;
                        break;
                    case 24:
                        str36 = str48;
                        i5 |= 16777216;
                        Unit unit26 = Unit.INSTANCE;
                        str19 = str47;
                        str50 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 24, StringSerializer.INSTANCE, str50);
                        str21 = str53;
                        str22 = str54;
                        str23 = str55;
                        b6 = b13;
                        str24 = str56;
                        str25 = str57;
                        str26 = str58;
                        num12 = num30;
                        num13 = num31;
                        b7 = b14;
                        num14 = num32;
                        d2 = d4;
                        str27 = str59;
                        bool2 = bool4;
                        num15 = num33;
                        b8 = b15;
                        str28 = str60;
                        str29 = str61;
                        str33 = str62;
                        num29 = num36;
                        str48 = str36;
                        break;
                    case 25:
                        str36 = str48;
                        i5 |= 33554432;
                        Unit unit27 = Unit.INSTANCE;
                        str19 = str47;
                        str49 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 25, StringSerializer.INSTANCE, str49);
                        str21 = str53;
                        str22 = str54;
                        str23 = str55;
                        b6 = b13;
                        str24 = str56;
                        str25 = str57;
                        str26 = str58;
                        num12 = num30;
                        num13 = num31;
                        b7 = b14;
                        num14 = num32;
                        d2 = d4;
                        str27 = str59;
                        bool2 = bool4;
                        num15 = num33;
                        b8 = b15;
                        str28 = str60;
                        str29 = str61;
                        str33 = str62;
                        num29 = num36;
                        str48 = str36;
                        break;
                    case 26:
                        str36 = str48;
                        str46 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 26, StringSerializer.INSTANCE, str46);
                        i3 = 67108864;
                        i5 |= i3;
                        Unit unit28 = Unit.INSTANCE;
                        str19 = str47;
                        str21 = str53;
                        str22 = str54;
                        str23 = str55;
                        b6 = b13;
                        str24 = str56;
                        str25 = str57;
                        str26 = str58;
                        num12 = num30;
                        num13 = num31;
                        b7 = b14;
                        num14 = num32;
                        d2 = d4;
                        str27 = str59;
                        bool2 = bool4;
                        num15 = num33;
                        b8 = b15;
                        str28 = str60;
                        str29 = str61;
                        str33 = str62;
                        num29 = num36;
                        str48 = str36;
                        break;
                    case 27:
                        str36 = str48;
                        str47 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 27, StringSerializer.INSTANCE, str47);
                        i3 = 134217728;
                        i5 |= i3;
                        Unit unit282 = Unit.INSTANCE;
                        str19 = str47;
                        str21 = str53;
                        str22 = str54;
                        str23 = str55;
                        b6 = b13;
                        str24 = str56;
                        str25 = str57;
                        str26 = str58;
                        num12 = num30;
                        num13 = num31;
                        b7 = b14;
                        num14 = num32;
                        d2 = d4;
                        str27 = str59;
                        bool2 = bool4;
                        num15 = num33;
                        b8 = b15;
                        str28 = str60;
                        str29 = str61;
                        str33 = str62;
                        num29 = num36;
                        str48 = str36;
                        break;
                    case 28:
                        str36 = str48;
                        num26 = (Integer) beginStructure.decodeNullableSerializableElement(serialDescriptor, 28, IntSerializer.INSTANCE, num26);
                        i3 = 268435456;
                        i5 |= i3;
                        Unit unit2822 = Unit.INSTANCE;
                        str19 = str47;
                        str21 = str53;
                        str22 = str54;
                        str23 = str55;
                        b6 = b13;
                        str24 = str56;
                        str25 = str57;
                        str26 = str58;
                        num12 = num30;
                        num13 = num31;
                        b7 = b14;
                        num14 = num32;
                        d2 = d4;
                        str27 = str59;
                        bool2 = bool4;
                        num15 = num33;
                        b8 = b15;
                        str28 = str60;
                        str29 = str61;
                        str33 = str62;
                        num29 = num36;
                        str48 = str36;
                        break;
                    case 29:
                        str36 = str48;
                        i5 |= 536870912;
                        Unit unit29 = Unit.INSTANCE;
                        str19 = str47;
                        b16 = (Byte) beginStructure.decodeNullableSerializableElement(serialDescriptor, 29, ByteSerializer.INSTANCE, b16);
                        str21 = str53;
                        str22 = str54;
                        str23 = str55;
                        b6 = b13;
                        str24 = str56;
                        str25 = str57;
                        str26 = str58;
                        num12 = num30;
                        num13 = num31;
                        b7 = b14;
                        num14 = num32;
                        d2 = d4;
                        str27 = str59;
                        bool2 = bool4;
                        num15 = num33;
                        b8 = b15;
                        str28 = str60;
                        str29 = str61;
                        str33 = str62;
                        num29 = num36;
                        str48 = str36;
                        break;
                    case 30:
                        str36 = str48;
                        i5 |= 1073741824;
                        Unit unit30 = Unit.INSTANCE;
                        str19 = str47;
                        num28 = (Integer) beginStructure.decodeNullableSerializableElement(serialDescriptor, 30, IntSerializer.INSTANCE, num28);
                        str21 = str53;
                        str22 = str54;
                        str23 = str55;
                        b6 = b13;
                        str24 = str56;
                        str25 = str57;
                        str26 = str58;
                        num12 = num30;
                        num13 = num31;
                        b7 = b14;
                        num14 = num32;
                        d2 = d4;
                        str27 = str59;
                        bool2 = bool4;
                        num15 = num33;
                        b8 = b15;
                        str28 = str60;
                        str29 = str61;
                        str33 = str62;
                        num29 = num36;
                        str48 = str36;
                        break;
                    case ConstantsKt.UPDATE_CALENDAR_CARD_VIDEO_DURATION_WIDTH /* 31 */:
                        str36 = str48;
                        i5 |= Integer.MIN_VALUE;
                        Unit unit31 = Unit.INSTANCE;
                        str19 = str47;
                        num27 = (Integer) beginStructure.decodeNullableSerializableElement(serialDescriptor, 31, IntSerializer.INSTANCE, num27);
                        str21 = str53;
                        str22 = str54;
                        str23 = str55;
                        b6 = b13;
                        str24 = str56;
                        str25 = str57;
                        str26 = str58;
                        num12 = num30;
                        num13 = num31;
                        b7 = b14;
                        num14 = num32;
                        d2 = d4;
                        str27 = str59;
                        bool2 = bool4;
                        num15 = num33;
                        b8 = b15;
                        str28 = str60;
                        str29 = str61;
                        str33 = str62;
                        num29 = num36;
                        str48 = str36;
                        break;
                    case 32:
                        str36 = str48;
                        num25 = (Integer) beginStructure.decodeNullableSerializableElement(serialDescriptor, 32, IntSerializer.INSTANCE, num25);
                        i4 |= 1;
                        Unit unit28222 = Unit.INSTANCE;
                        str19 = str47;
                        str21 = str53;
                        str22 = str54;
                        str23 = str55;
                        b6 = b13;
                        str24 = str56;
                        str25 = str57;
                        str26 = str58;
                        num12 = num30;
                        num13 = num31;
                        b7 = b14;
                        num14 = num32;
                        d2 = d4;
                        str27 = str59;
                        bool2 = bool4;
                        num15 = num33;
                        b8 = b15;
                        str28 = str60;
                        str29 = str61;
                        str33 = str62;
                        num29 = num36;
                        str48 = str36;
                        break;
                    case 33:
                        str36 = str48;
                        i4 |= 2;
                        Unit unit32 = Unit.INSTANCE;
                        str19 = str47;
                        b12 = (Byte) beginStructure.decodeNullableSerializableElement(serialDescriptor, 33, ByteSerializer.INSTANCE, b12);
                        str21 = str53;
                        str22 = str54;
                        str23 = str55;
                        b6 = b13;
                        str24 = str56;
                        str25 = str57;
                        str26 = str58;
                        num12 = num30;
                        num13 = num31;
                        b7 = b14;
                        num14 = num32;
                        d2 = d4;
                        str27 = str59;
                        bool2 = bool4;
                        num15 = num33;
                        b8 = b15;
                        str28 = str60;
                        str29 = str61;
                        str33 = str62;
                        num29 = num36;
                        str48 = str36;
                        break;
                    case 34:
                        str36 = str48;
                        i4 |= 4;
                        Unit unit33 = Unit.INSTANCE;
                        str19 = str47;
                        str51 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 34, StringSerializer.INSTANCE, str51);
                        str21 = str53;
                        str22 = str54;
                        str23 = str55;
                        b6 = b13;
                        str24 = str56;
                        str25 = str57;
                        str26 = str58;
                        num12 = num30;
                        num13 = num31;
                        b7 = b14;
                        num14 = num32;
                        d2 = d4;
                        str27 = str59;
                        bool2 = bool4;
                        num15 = num33;
                        b8 = b15;
                        str28 = str60;
                        str29 = str61;
                        str33 = str62;
                        num29 = num36;
                        str48 = str36;
                        break;
                    default:
                        throw new UnknownFieldException(decodeElementIndex);
                }
                str62 = str33;
                str47 = str19;
                str61 = str29;
                str60 = str28;
                b15 = b8;
                num33 = num15;
                bool4 = bool2;
                str59 = str27;
                d4 = d2;
                str53 = str21;
                num30 = num12;
                str54 = str22;
                str55 = str23;
                b13 = b6;
                str56 = str24;
                str57 = str25;
                str58 = str26;
                num31 = num13;
                b14 = b7;
                num32 = num14;
            }
            String str64 = str53;
            String str65 = str54;
            String str66 = str55;
            Byte b17 = b13;
            String str67 = str56;
            String str68 = str57;
            String str69 = str58;
            Integer num37 = num30;
            Integer num38 = num31;
            Byte b18 = b14;
            Integer num39 = num32;
            Double d5 = d4;
            String str70 = str59;
            Boolean bool5 = bool4;
            Integer num40 = num33;
            str = str52;
            num = num25;
            num2 = num26;
            b = b12;
            num3 = num27;
            num4 = num28;
            b2 = b16;
            str2 = str49;
            str3 = str50;
            str4 = str62;
            str5 = str51;
            num5 = num34;
            str6 = str47;
            num6 = num35;
            i = i4;
            num7 = num29;
            str7 = str48;
            str8 = str46;
            i2 = i5;
            str9 = str61;
            str10 = str64;
            num8 = num37;
            num9 = num38;
            b3 = b15;
            str11 = str66;
            num10 = num39;
            str12 = str60;
            str13 = str65;
            b4 = b18;
            num11 = num40;
            b5 = b17;
            d = d5;
            str14 = str69;
            bool = bool5;
            str15 = str67;
            str16 = str70;
            str17 = str68;
        }
        beginStructure.endStructure(serialDescriptor);
        return new ActivityInfoFloor.ActivityExtInfo.NewUserCoupon(i2, i, str, str10, str13, str11, b5, str15, str17, str14, num8, num9, b4, num10, d, str16, bool, num11, b3, str12, str9, str4, num5, num6, num7, str7, str3, str2, str8, str6, num2, b2, num4, num3, num, b, str5, (SerializationConstructorMarker) null);
    }

    public final void serialize(Encoder encoder, ActivityInfoFloor.ActivityExtInfo.NewUserCoupon value) {
        Intrinsics.checkNotNullParameter(encoder, "encoder");
        Intrinsics.checkNotNullParameter(value, "value");
        SerialDescriptor serialDescriptor = descriptor;
        CompositeEncoder beginStructure = encoder.beginStructure(serialDescriptor);
        ActivityInfoFloor.ActivityExtInfo.NewUserCoupon.write$Self$product_details_page_debug(value, beginStructure, serialDescriptor);
        beginStructure.endStructure(serialDescriptor);
    }

    public /* bridge */ KSerializer<?>[] typeParametersSerializers() {
        return GeneratedSerializer.DefaultImpls.typeParametersSerializers(this);
    }
}