package kntr.app.mall.product.details.page.api.model;

import com.bapis.bilibili.app.dynamic.v2.AdditionalButton;
import java.util.List;
import kntr.app.mall.product.details.page.api.model.BasicInfoFloor;
import kntr.app.upcomingEpisode.ConstantsKt;
import kntr.watch.later.watchlater.edit.MediaAttrUtils;
import kotlin.Deprecated;
import kotlin.DeprecationLevel;
import kotlin.Lazy;
import kotlin.Metadata;
import kotlin.Unit;
import kotlin.jvm.internal.Intrinsics;
import kotlinx.serialization.DeserializationStrategy;
import kotlinx.serialization.KSerializer;
import kotlinx.serialization.UnknownFieldException;
import kotlinx.serialization.builtins.BuiltinSerializersKt;
import kotlinx.serialization.descriptors.SerialDescriptor;
import kotlinx.serialization.encoding.CompositeDecoder;
import kotlinx.serialization.encoding.CompositeEncoder;
import kotlinx.serialization.encoding.Decoder;
import kotlinx.serialization.encoding.Encoder;
import kotlinx.serialization.internal.BooleanSerializer;
import kotlinx.serialization.internal.GeneratedSerializer;
import kotlinx.serialization.internal.IntSerializer;
import kotlinx.serialization.internal.LongSerializer;
import kotlinx.serialization.internal.PluginGeneratedSerialDescriptor;
import kotlinx.serialization.internal.SerializationConstructorMarker;
import kotlinx.serialization.internal.StringSerializer;

/* compiled from: BasicInfoFloor.kt */
@Metadata(d1 = {"\u00006\n\u0000\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\b\u0003\n\u0002\u0010\u0011\n\u0002\u0018\u0002\n\u0002\b\u0003\n\u0002\u0018\u0002\n\u0000\n\u0002\u0010\u0002\n\u0000\n\u0002\u0018\u0002\n\u0002\b\u0002\n\u0002\u0018\u0002\n\u0002\b\u0003\bÇ\u0002\u0018\u00002\b\u0012\u0004\u0012\u00020\u00020\u0001B\t\b\u0002¢\u0006\u0004\b\u0003\u0010\u0004J\u0015\u0010\u0005\u001a\f\u0012\b\u0012\u0006\u0012\u0002\b\u00030\u00070\u0006¢\u0006\u0002\u0010\bJ\u000e\u0010\t\u001a\u00020\u00022\u0006\u0010\n\u001a\u00020\u000bJ\u0016\u0010\f\u001a\u00020\r2\u0006\u0010\u000e\u001a\u00020\u000f2\u0006\u0010\u0010\u001a\u00020\u0002R\u0011\u0010\u0011\u001a\u00020\u0012¢\u0006\b\n\u0000\u001a\u0004\b\u0013\u0010\u0014¨\u0006\u0015"}, d2 = {"kntr/app/mall/product/details/page/api/model/BasicInfoFloor.$serializer", "Lkotlinx/serialization/internal/GeneratedSerializer;", "Lkntr/app/mall/product/details/page/api/model/BasicInfoFloor;", "<init>", "()V", "childSerializers", "", "Lkotlinx/serialization/KSerializer;", "()[Lkotlinx/serialization/KSerializer;", "deserialize", "decoder", "Lkotlinx/serialization/encoding/Decoder;", "serialize", "", "encoder", "Lkotlinx/serialization/encoding/Encoder;", "value", "descriptor", "Lkotlinx/serialization/descriptors/SerialDescriptor;", "getDescriptor", "()Lkotlinx/serialization/descriptors/SerialDescriptor;", "product-details-page_debug"}, k = 1, mv = {2, 2, 0}, xi = ConstantsKt.OGV_UPDATE_CALENDAR_CARD_COVER_WIDTH)
@Deprecated(level = DeprecationLevel.HIDDEN, message = "This synthesized declaration should not be used directly")
public final /* synthetic */ class BasicInfoFloor$$serializer implements GeneratedSerializer<BasicInfoFloor> {
    public static final int $stable;
    public static final BasicInfoFloor$$serializer INSTANCE = new BasicInfoFloor$$serializer();
    private static final SerialDescriptor descriptor;

    public final SerialDescriptor getDescriptor() {
        return descriptor;
    }

    static {
        SerialDescriptor pluginGeneratedSerialDescriptor = new PluginGeneratedSerialDescriptor("kntr.app.mall.product.details.page.api.model.BasicInfoFloor", INSTANCE, 31);
        pluginGeneratedSerialDescriptor.addElement("floorKey", true);
        pluginGeneratedSerialDescriptor.addElement("floorIcon", true);
        pluginGeneratedSerialDescriptor.addElement("bgImgUrl", true);
        pluginGeneratedSerialDescriptor.addElement("atmosphereImgList", true);
        pluginGeneratedSerialDescriptor.addElement("benefitInfos", true);
        pluginGeneratedSerialDescriptor.addElement("brief", true);
        pluginGeneratedSerialDescriptor.addElement("commentBgUrl", true);
        pluginGeneratedSerialDescriptor.addElement("commitmentTags", true);
        pluginGeneratedSerialDescriptor.addElement("couponReceiveAble", true);
        pluginGeneratedSerialDescriptor.addElement("crowdFundingBulletScreenVO", true);
        pluginGeneratedSerialDescriptor.addElement("extBrief", true);
        pluginGeneratedSerialDescriptor.addElement("headAvDTO", true);
        pluginGeneratedSerialDescriptor.addElement("imageList", true);
        pluginGeneratedSerialDescriptor.addElement("shopId", true);
        pluginGeneratedSerialDescriptor.addElement("oneShopId", true);
        pluginGeneratedSerialDescriptor.addElement("itemsId", true);
        pluginGeneratedSerialDescriptor.addElement("itemsBenefitsInfo", true);
        pluginGeneratedSerialDescriptor.addElement("itemsName", true);
        pluginGeneratedSerialDescriptor.addElement("itemsStatus", true);
        pluginGeneratedSerialDescriptor.addElement("liveInfo", true);
        pluginGeneratedSerialDescriptor.addElement("mainImgScale", true);
        pluginGeneratedSerialDescriptor.addElement("newUpSayVO", true);
        pluginGeneratedSerialDescriptor.addElement("promoInfoVOS", true);
        pluginGeneratedSerialDescriptor.addElement("reserveAble", true);
        pluginGeneratedSerialDescriptor.addElement("salePoint", true);
        pluginGeneratedSerialDescriptor.addElement("serviceRightTag", true);
        pluginGeneratedSerialDescriptor.addElement("titlePrefix", true);
        pluginGeneratedSerialDescriptor.addElement("verticalHeadAvDTO", true);
        pluginGeneratedSerialDescriptor.addElement("newCustomer", true);
        pluginGeneratedSerialDescriptor.addElement("guideIndexUrl", true);
        pluginGeneratedSerialDescriptor.addElement("retainDaysFreq", true);
        descriptor = pluginGeneratedSerialDescriptor;
        $stable = 8;
    }

    private BasicInfoFloor$$serializer() {
    }

    public final KSerializer<?>[] childSerializers() {
        Lazy[] lazyArr;
        lazyArr = BasicInfoFloor.$childSerializers;
        return new KSerializer[]{BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable((KSerializer) lazyArr[3].getValue()), BuiltinSerializersKt.getNullable((KSerializer) lazyArr[4].getValue()), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable((KSerializer) lazyArr[7].getValue()), BuiltinSerializersKt.getNullable(BooleanSerializer.INSTANCE), BuiltinSerializersKt.getNullable(BasicInfoFloor$BulletScreen$$serializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(BasicInfoFloor$HeadAvModel$$serializer.INSTANCE), BuiltinSerializersKt.getNullable((KSerializer) lazyArr[12].getValue()), BuiltinSerializersKt.getNullable(LongSerializer.INSTANCE), BuiltinSerializersKt.getNullable(LongSerializer.INSTANCE), BuiltinSerializersKt.getNullable(LongSerializer.INSTANCE), BuiltinSerializersKt.getNullable(BasicInfoFloor$ItemsBenefitsInfo$$serializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(IntSerializer.INSTANCE), BuiltinSerializersKt.getNullable(BasicInfoFloor$LiveInfo$$serializer.INSTANCE), BuiltinSerializersKt.getNullable(BasicInfoFloor$MainImageScale$$serializer.INSTANCE), BuiltinSerializersKt.getNullable(BasicInfoFloor$NewUpSayModel$$serializer.INSTANCE), BuiltinSerializersKt.getNullable((KSerializer) lazyArr[22].getValue()), BuiltinSerializersKt.getNullable(BooleanSerializer.INSTANCE), BuiltinSerializersKt.getNullable((KSerializer) lazyArr[24].getValue()), BuiltinSerializersKt.getNullable(LabelObject$$serializer.INSTANCE), BuiltinSerializersKt.getNullable(TextColorModel$$serializer.INSTANCE), BuiltinSerializersKt.getNullable(BasicInfoFloor$HeadAvModel$$serializer.INSTANCE), BuiltinSerializersKt.getNullable(BooleanSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(IntSerializer.INSTANCE)};
    }

    public final BasicInfoFloor deserialize(Decoder decoder) {
        Lazy[] lazyArr;
        String str;
        Boolean bool;
        BasicInfoFloor.NewUpSayModel newUpSayModel;
        String str2;
        Integer num;
        TextColorModel textColorModel;
        int i;
        Boolean bool2;
        BasicInfoFloor.HeadAvModel headAvModel;
        BasicInfoFloor.HeadAvModel headAvModel2;
        LabelObject labelObject;
        List list;
        List list2;
        BasicInfoFloor.BulletScreen bulletScreen;
        BasicInfoFloor.MainImageScale mainImageScale;
        List list3;
        String str3;
        Integer num2;
        List list4;
        Boolean bool3;
        String str4;
        String str5;
        String str6;
        BasicInfoFloor.LiveInfo liveInfo;
        BasicInfoFloor.ItemsBenefitsInfo itemsBenefitsInfo;
        List list5;
        Long l;
        List list6;
        Long l2;
        String str7;
        Long l3;
        String str8;
        List list7;
        Lazy[] lazyArr2;
        LabelObject labelObject2;
        List list8;
        BasicInfoFloor.MainImageScale mainImageScale2;
        String str9;
        String str10;
        List list9;
        List list10;
        String str11;
        String str12;
        List list11;
        Boolean bool4;
        BasicInfoFloor.BulletScreen bulletScreen2;
        String str13;
        BasicInfoFloor.HeadAvModel headAvModel3;
        List list12;
        Long l4;
        Long l5;
        Long l6;
        BasicInfoFloor.ItemsBenefitsInfo itemsBenefitsInfo2;
        String str14;
        String str15;
        BasicInfoFloor.HeadAvModel headAvModel4;
        BasicInfoFloor.MainImageScale mainImageScale3;
        int i2;
        int i3;
        Intrinsics.checkNotNullParameter(decoder, "decoder");
        SerialDescriptor serialDescriptor = descriptor;
        CompositeDecoder beginStructure = decoder.beginStructure(serialDescriptor);
        lazyArr = BasicInfoFloor.$childSerializers;
        if (beginStructure.decodeSequentially()) {
            String str16 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 10, StringSerializer.INSTANCE, (Object) null);
            BasicInfoFloor.HeadAvModel headAvModel5 = (BasicInfoFloor.HeadAvModel) beginStructure.decodeNullableSerializableElement(serialDescriptor, 11, BasicInfoFloor$HeadAvModel$$serializer.INSTANCE, (Object) null);
            List list13 = (List) beginStructure.decodeNullableSerializableElement(serialDescriptor, 12, (DeserializationStrategy) lazyArr[12].getValue(), (Object) null);
            Long l7 = (Long) beginStructure.decodeNullableSerializableElement(serialDescriptor, 13, LongSerializer.INSTANCE, (Object) null);
            Long l8 = (Long) beginStructure.decodeNullableSerializableElement(serialDescriptor, 14, LongSerializer.INSTANCE, (Object) null);
            Long l9 = (Long) beginStructure.decodeNullableSerializableElement(serialDescriptor, 15, LongSerializer.INSTANCE, (Object) null);
            BasicInfoFloor.ItemsBenefitsInfo itemsBenefitsInfo3 = (BasicInfoFloor.ItemsBenefitsInfo) beginStructure.decodeNullableSerializableElement(serialDescriptor, 16, BasicInfoFloor$ItemsBenefitsInfo$$serializer.INSTANCE, (Object) null);
            String str17 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 17, StringSerializer.INSTANCE, (Object) null);
            Integer num3 = (Integer) beginStructure.decodeNullableSerializableElement(serialDescriptor, 18, IntSerializer.INSTANCE, (Object) null);
            BasicInfoFloor.LiveInfo liveInfo2 = (BasicInfoFloor.LiveInfo) beginStructure.decodeNullableSerializableElement(serialDescriptor, 19, BasicInfoFloor$LiveInfo$$serializer.INSTANCE, (Object) null);
            BasicInfoFloor.MainImageScale mainImageScale4 = (BasicInfoFloor.MainImageScale) beginStructure.decodeNullableSerializableElement(serialDescriptor, 20, BasicInfoFloor$MainImageScale$$serializer.INSTANCE, (Object) null);
            BasicInfoFloor.NewUpSayModel newUpSayModel2 = (BasicInfoFloor.NewUpSayModel) beginStructure.decodeNullableSerializableElement(serialDescriptor, 21, BasicInfoFloor$NewUpSayModel$$serializer.INSTANCE, (Object) null);
            List list14 = (List) beginStructure.decodeNullableSerializableElement(serialDescriptor, 22, (DeserializationStrategy) lazyArr[22].getValue(), (Object) null);
            Boolean bool5 = (Boolean) beginStructure.decodeNullableSerializableElement(serialDescriptor, 23, BooleanSerializer.INSTANCE, (Object) null);
            LabelObject labelObject3 = (LabelObject) beginStructure.decodeNullableSerializableElement(serialDescriptor, 25, LabelObject$$serializer.INSTANCE, (Object) null);
            TextColorModel textColorModel2 = (TextColorModel) beginStructure.decodeNullableSerializableElement(serialDescriptor, 26, TextColorModel$$serializer.INSTANCE, (Object) null);
            BasicInfoFloor.HeadAvModel headAvModel6 = (BasicInfoFloor.HeadAvModel) beginStructure.decodeNullableSerializableElement(serialDescriptor, 27, BasicInfoFloor$HeadAvModel$$serializer.INSTANCE, (Object) null);
            Boolean bool6 = (Boolean) beginStructure.decodeNullableSerializableElement(serialDescriptor, 28, BooleanSerializer.INSTANCE, (Object) null);
            String str18 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 29, StringSerializer.INSTANCE, (Object) null);
            num = (Integer) beginStructure.decodeNullableSerializableElement(serialDescriptor, 30, IntSerializer.INSTANCE, (Object) null);
            list3 = (List) beginStructure.decodeNullableSerializableElement(serialDescriptor, 24, (DeserializationStrategy) lazyArr[24].getValue(), (Object) null);
            num2 = num3;
            bool2 = bool5;
            list = list14;
            liveInfo = liveInfo2;
            mainImageScale = mainImageScale4;
            newUpSayModel = newUpSayModel2;
            labelObject = labelObject3;
            textColorModel = textColorModel2;
            headAvModel2 = headAvModel6;
            bool = bool6;
            str2 = str18;
            str = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 2, StringSerializer.INSTANCE, (Object) null);
            list2 = (List) beginStructure.decodeNullableSerializableElement(serialDescriptor, 3, (DeserializationStrategy) lazyArr[3].getValue(), (Object) null);
            i = Integer.MAX_VALUE;
            str4 = str17;
            itemsBenefitsInfo = itemsBenefitsInfo3;
            l2 = l9;
            l3 = l8;
            l = l7;
            list4 = list13;
            headAvModel = headAvModel5;
            str6 = str16;
            str3 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 0, StringSerializer.INSTANCE, (Object) null);
            bool3 = (Boolean) beginStructure.decodeNullableSerializableElement(serialDescriptor, 8, BooleanSerializer.INSTANCE, (Object) null);
            list6 = (List) beginStructure.decodeNullableSerializableElement(serialDescriptor, 7, (DeserializationStrategy) lazyArr[7].getValue(), (Object) null);
            list5 = (List) beginStructure.decodeNullableSerializableElement(serialDescriptor, 4, (DeserializationStrategy) lazyArr[4].getValue(), (Object) null);
            str5 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 1, StringSerializer.INSTANCE, (Object) null);
            bulletScreen = (BasicInfoFloor.BulletScreen) beginStructure.decodeNullableSerializableElement(serialDescriptor, 9, BasicInfoFloor$BulletScreen$$serializer.INSTANCE, (Object) null);
            str8 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 6, StringSerializer.INSTANCE, (Object) null);
            str7 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 5, StringSerializer.INSTANCE, (Object) null);
        } else {
            List list15 = null;
            LabelObject labelObject4 = null;
            List list16 = null;
            Boolean bool7 = null;
            BasicInfoFloor.NewUpSayModel newUpSayModel3 = null;
            String str19 = null;
            Integer num4 = null;
            Boolean bool8 = null;
            BasicInfoFloor.MainImageScale mainImageScale5 = null;
            BasicInfoFloor.LiveInfo liveInfo3 = null;
            String str20 = null;
            String str21 = null;
            String str22 = null;
            List list17 = null;
            List list18 = null;
            String str23 = null;
            String str24 = null;
            List list19 = null;
            Boolean bool9 = null;
            BasicInfoFloor.BulletScreen bulletScreen3 = null;
            String str25 = null;
            BasicInfoFloor.HeadAvModel headAvModel7 = null;
            List list20 = null;
            Long l10 = null;
            Long l11 = null;
            Long l12 = null;
            BasicInfoFloor.ItemsBenefitsInfo itemsBenefitsInfo4 = null;
            String str26 = null;
            Integer num5 = null;
            boolean z = true;
            int i4 = 0;
            TextColorModel textColorModel3 = null;
            BasicInfoFloor.HeadAvModel headAvModel8 = null;
            while (z) {
                BasicInfoFloor.LiveInfo liveInfo4 = liveInfo3;
                int decodeElementIndex = beginStructure.decodeElementIndex(serialDescriptor);
                switch (decodeElementIndex) {
                    case -1:
                        list7 = list15;
                        lazyArr2 = lazyArr;
                        labelObject2 = labelObject4;
                        list8 = list16;
                        mainImageScale2 = mainImageScale5;
                        str9 = str21;
                        str10 = str22;
                        list9 = list17;
                        list10 = list18;
                        str11 = str23;
                        str12 = str24;
                        list11 = list19;
                        bool4 = bool9;
                        bulletScreen2 = bulletScreen3;
                        str13 = str25;
                        headAvModel3 = headAvModel7;
                        list12 = list20;
                        l4 = l10;
                        l5 = l11;
                        l6 = l12;
                        itemsBenefitsInfo2 = itemsBenefitsInfo4;
                        str14 = str26;
                        Unit unit = Unit.INSTANCE;
                        z = false;
                        str15 = str10;
                        labelObject4 = labelObject2;
                        list16 = list8;
                        liveInfo3 = liveInfo4;
                        headAvModel4 = headAvModel3;
                        mainImageScale5 = mainImageScale2;
                        str22 = str15;
                        headAvModel7 = headAvModel4;
                        str26 = str14;
                        itemsBenefitsInfo4 = itemsBenefitsInfo2;
                        l12 = l6;
                        l11 = l5;
                        l10 = l4;
                        list20 = list12;
                        str21 = str9;
                        lazyArr = lazyArr2;
                        list17 = list9;
                        list18 = list10;
                        str23 = str11;
                        str24 = str12;
                        list19 = list11;
                        bool9 = bool4;
                        bulletScreen3 = bulletScreen2;
                        str25 = str13;
                        list15 = list7;
                    case 0:
                        list7 = list15;
                        lazyArr2 = lazyArr;
                        labelObject2 = labelObject4;
                        list8 = list16;
                        mainImageScale2 = mainImageScale5;
                        str10 = str22;
                        list9 = list17;
                        list10 = list18;
                        str11 = str23;
                        str12 = str24;
                        list11 = list19;
                        bool4 = bool9;
                        bulletScreen2 = bulletScreen3;
                        str13 = str25;
                        headAvModel3 = headAvModel7;
                        list12 = list20;
                        l4 = l10;
                        l5 = l11;
                        l6 = l12;
                        itemsBenefitsInfo2 = itemsBenefitsInfo4;
                        str14 = str26;
                        str9 = str21;
                        i4 |= 1;
                        Unit unit2 = Unit.INSTANCE;
                        str20 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 0, StringSerializer.INSTANCE, str20);
                        str15 = str10;
                        labelObject4 = labelObject2;
                        list16 = list8;
                        liveInfo3 = liveInfo4;
                        headAvModel4 = headAvModel3;
                        mainImageScale5 = mainImageScale2;
                        str22 = str15;
                        headAvModel7 = headAvModel4;
                        str26 = str14;
                        itemsBenefitsInfo4 = itemsBenefitsInfo2;
                        l12 = l6;
                        l11 = l5;
                        l10 = l4;
                        list20 = list12;
                        str21 = str9;
                        lazyArr = lazyArr2;
                        list17 = list9;
                        list18 = list10;
                        str23 = str11;
                        str24 = str12;
                        list19 = list11;
                        bool9 = bool4;
                        bulletScreen3 = bulletScreen2;
                        str25 = str13;
                        list15 = list7;
                    case 1:
                        list7 = list15;
                        List list21 = list16;
                        mainImageScale2 = mainImageScale5;
                        list9 = list17;
                        list10 = list18;
                        str11 = str23;
                        str12 = str24;
                        list11 = list19;
                        bool4 = bool9;
                        bulletScreen2 = bulletScreen3;
                        str13 = str25;
                        headAvModel3 = headAvModel7;
                        list12 = list20;
                        l4 = l10;
                        l5 = l11;
                        l6 = l12;
                        itemsBenefitsInfo2 = itemsBenefitsInfo4;
                        str14 = str26;
                        lazyArr2 = lazyArr;
                        i4 |= 2;
                        Unit unit3 = Unit.INSTANCE;
                        str9 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 1, StringSerializer.INSTANCE, str21);
                        str15 = str22;
                        labelObject4 = labelObject4;
                        list16 = list21;
                        liveInfo3 = liveInfo4;
                        headAvModel4 = headAvModel3;
                        mainImageScale5 = mainImageScale2;
                        str22 = str15;
                        headAvModel7 = headAvModel4;
                        str26 = str14;
                        itemsBenefitsInfo4 = itemsBenefitsInfo2;
                        l12 = l6;
                        l11 = l5;
                        l10 = l4;
                        list20 = list12;
                        str21 = str9;
                        lazyArr = lazyArr2;
                        list17 = list9;
                        list18 = list10;
                        str23 = str11;
                        str24 = str12;
                        list19 = list11;
                        bool9 = bool4;
                        bulletScreen3 = bulletScreen2;
                        str25 = str13;
                        list15 = list7;
                    case 2:
                        list7 = list15;
                        List list22 = list16;
                        mainImageScale2 = mainImageScale5;
                        list10 = list18;
                        str11 = str23;
                        str12 = str24;
                        list11 = list19;
                        bool4 = bool9;
                        bulletScreen2 = bulletScreen3;
                        str13 = str25;
                        headAvModel3 = headAvModel7;
                        list12 = list20;
                        l4 = l10;
                        l5 = l11;
                        l6 = l12;
                        itemsBenefitsInfo2 = itemsBenefitsInfo4;
                        str14 = str26;
                        list9 = list17;
                        i4 |= 4;
                        Unit unit4 = Unit.INSTANCE;
                        lazyArr2 = lazyArr;
                        str15 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 2, StringSerializer.INSTANCE, str22);
                        labelObject4 = labelObject4;
                        list16 = list22;
                        str9 = str21;
                        liveInfo3 = liveInfo4;
                        headAvModel4 = headAvModel3;
                        mainImageScale5 = mainImageScale2;
                        str22 = str15;
                        headAvModel7 = headAvModel4;
                        str26 = str14;
                        itemsBenefitsInfo4 = itemsBenefitsInfo2;
                        l12 = l6;
                        l11 = l5;
                        l10 = l4;
                        list20 = list12;
                        str21 = str9;
                        lazyArr = lazyArr2;
                        list17 = list9;
                        list18 = list10;
                        str23 = str11;
                        str24 = str12;
                        list19 = list11;
                        bool9 = bool4;
                        bulletScreen3 = bulletScreen2;
                        str25 = str13;
                        list15 = list7;
                    case 3:
                        list7 = list15;
                        List list23 = list16;
                        mainImageScale2 = mainImageScale5;
                        str11 = str23;
                        str12 = str24;
                        list11 = list19;
                        bool4 = bool9;
                        bulletScreen2 = bulletScreen3;
                        str13 = str25;
                        headAvModel3 = headAvModel7;
                        list12 = list20;
                        l4 = l10;
                        l5 = l11;
                        l6 = l12;
                        itemsBenefitsInfo2 = itemsBenefitsInfo4;
                        str14 = str26;
                        DeserializationStrategy deserializationStrategy = (DeserializationStrategy) lazyArr[3].getValue();
                        list10 = list18;
                        i4 |= 8;
                        Unit unit5 = Unit.INSTANCE;
                        list9 = (List) beginStructure.decodeNullableSerializableElement(serialDescriptor, 3, deserializationStrategy, list17);
                        lazyArr2 = lazyArr;
                        labelObject4 = labelObject4;
                        list16 = list23;
                        str9 = str21;
                        str15 = str22;
                        liveInfo3 = liveInfo4;
                        headAvModel4 = headAvModel3;
                        mainImageScale5 = mainImageScale2;
                        str22 = str15;
                        headAvModel7 = headAvModel4;
                        str26 = str14;
                        itemsBenefitsInfo4 = itemsBenefitsInfo2;
                        l12 = l6;
                        l11 = l5;
                        l10 = l4;
                        list20 = list12;
                        str21 = str9;
                        lazyArr = lazyArr2;
                        list17 = list9;
                        list18 = list10;
                        str23 = str11;
                        str24 = str12;
                        list19 = list11;
                        bool9 = bool4;
                        bulletScreen3 = bulletScreen2;
                        str25 = str13;
                        list15 = list7;
                    case 4:
                        list7 = list15;
                        LabelObject labelObject5 = labelObject4;
                        mainImageScale2 = mainImageScale5;
                        str12 = str24;
                        list11 = list19;
                        bool4 = bool9;
                        bulletScreen2 = bulletScreen3;
                        str13 = str25;
                        headAvModel3 = headAvModel7;
                        list12 = list20;
                        l4 = l10;
                        l5 = l11;
                        l6 = l12;
                        itemsBenefitsInfo2 = itemsBenefitsInfo4;
                        str14 = str26;
                        DeserializationStrategy deserializationStrategy2 = (DeserializationStrategy) lazyArr[4].getValue();
                        str11 = str23;
                        i4 |= 16;
                        Unit unit6 = Unit.INSTANCE;
                        list10 = (List) beginStructure.decodeNullableSerializableElement(serialDescriptor, 4, deserializationStrategy2, list18);
                        lazyArr2 = lazyArr;
                        labelObject4 = labelObject5;
                        list16 = list16;
                        str9 = str21;
                        str15 = str22;
                        list9 = list17;
                        liveInfo3 = liveInfo4;
                        headAvModel4 = headAvModel3;
                        mainImageScale5 = mainImageScale2;
                        str22 = str15;
                        headAvModel7 = headAvModel4;
                        str26 = str14;
                        itemsBenefitsInfo4 = itemsBenefitsInfo2;
                        l12 = l6;
                        l11 = l5;
                        l10 = l4;
                        list20 = list12;
                        str21 = str9;
                        lazyArr = lazyArr2;
                        list17 = list9;
                        list18 = list10;
                        str23 = str11;
                        str24 = str12;
                        list19 = list11;
                        bool9 = bool4;
                        bulletScreen3 = bulletScreen2;
                        str25 = str13;
                        list15 = list7;
                    case 5:
                        list7 = list15;
                        List list24 = list16;
                        mainImageScale2 = mainImageScale5;
                        list11 = list19;
                        bool4 = bool9;
                        bulletScreen2 = bulletScreen3;
                        str13 = str25;
                        headAvModel3 = headAvModel7;
                        list12 = list20;
                        l4 = l10;
                        l5 = l11;
                        l6 = l12;
                        itemsBenefitsInfo2 = itemsBenefitsInfo4;
                        str14 = str26;
                        str12 = str24;
                        i4 |= 32;
                        Unit unit7 = Unit.INSTANCE;
                        str11 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 5, StringSerializer.INSTANCE, str23);
                        lazyArr2 = lazyArr;
                        labelObject4 = labelObject4;
                        list16 = list24;
                        str9 = str21;
                        str15 = str22;
                        list9 = list17;
                        list10 = list18;
                        liveInfo3 = liveInfo4;
                        headAvModel4 = headAvModel3;
                        mainImageScale5 = mainImageScale2;
                        str22 = str15;
                        headAvModel7 = headAvModel4;
                        str26 = str14;
                        itemsBenefitsInfo4 = itemsBenefitsInfo2;
                        l12 = l6;
                        l11 = l5;
                        l10 = l4;
                        list20 = list12;
                        str21 = str9;
                        lazyArr = lazyArr2;
                        list17 = list9;
                        list18 = list10;
                        str23 = str11;
                        str24 = str12;
                        list19 = list11;
                        bool9 = bool4;
                        bulletScreen3 = bulletScreen2;
                        str25 = str13;
                        list15 = list7;
                    case 6:
                        list7 = list15;
                        List list25 = list16;
                        mainImageScale2 = mainImageScale5;
                        bool4 = bool9;
                        bulletScreen2 = bulletScreen3;
                        str13 = str25;
                        headAvModel3 = headAvModel7;
                        list12 = list20;
                        l4 = l10;
                        l5 = l11;
                        l6 = l12;
                        itemsBenefitsInfo2 = itemsBenefitsInfo4;
                        str14 = str26;
                        list11 = list19;
                        i4 |= 64;
                        Unit unit8 = Unit.INSTANCE;
                        lazyArr2 = lazyArr;
                        str12 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 6, StringSerializer.INSTANCE, str24);
                        labelObject4 = labelObject4;
                        list16 = list25;
                        str9 = str21;
                        str15 = str22;
                        list9 = list17;
                        list10 = list18;
                        str11 = str23;
                        liveInfo3 = liveInfo4;
                        headAvModel4 = headAvModel3;
                        mainImageScale5 = mainImageScale2;
                        str22 = str15;
                        headAvModel7 = headAvModel4;
                        str26 = str14;
                        itemsBenefitsInfo4 = itemsBenefitsInfo2;
                        l12 = l6;
                        l11 = l5;
                        l10 = l4;
                        list20 = list12;
                        str21 = str9;
                        lazyArr = lazyArr2;
                        list17 = list9;
                        list18 = list10;
                        str23 = str11;
                        str24 = str12;
                        list19 = list11;
                        bool9 = bool4;
                        bulletScreen3 = bulletScreen2;
                        str25 = str13;
                        list15 = list7;
                    case AdditionalButton.CLICK_TYPE_FIELD_NUMBER /* 7 */:
                        list7 = list15;
                        List list26 = list16;
                        mainImageScale2 = mainImageScale5;
                        bulletScreen2 = bulletScreen3;
                        str13 = str25;
                        headAvModel3 = headAvModel7;
                        list12 = list20;
                        l4 = l10;
                        l5 = l11;
                        l6 = l12;
                        itemsBenefitsInfo2 = itemsBenefitsInfo4;
                        str14 = str26;
                        DeserializationStrategy deserializationStrategy3 = (DeserializationStrategy) lazyArr[7].getValue();
                        bool4 = bool9;
                        i4 |= 128;
                        Unit unit9 = Unit.INSTANCE;
                        list11 = (List) beginStructure.decodeNullableSerializableElement(serialDescriptor, 7, deserializationStrategy3, list19);
                        lazyArr2 = lazyArr;
                        labelObject4 = labelObject4;
                        list16 = list26;
                        str9 = str21;
                        str15 = str22;
                        list9 = list17;
                        list10 = list18;
                        str11 = str23;
                        str12 = str24;
                        liveInfo3 = liveInfo4;
                        headAvModel4 = headAvModel3;
                        mainImageScale5 = mainImageScale2;
                        str22 = str15;
                        headAvModel7 = headAvModel4;
                        str26 = str14;
                        itemsBenefitsInfo4 = itemsBenefitsInfo2;
                        l12 = l6;
                        l11 = l5;
                        l10 = l4;
                        list20 = list12;
                        str21 = str9;
                        lazyArr = lazyArr2;
                        list17 = list9;
                        list18 = list10;
                        str23 = str11;
                        str24 = str12;
                        list19 = list11;
                        bool9 = bool4;
                        bulletScreen3 = bulletScreen2;
                        str25 = str13;
                        list15 = list7;
                    case 8:
                        list7 = list15;
                        LabelObject labelObject6 = labelObject4;
                        mainImageScale2 = mainImageScale5;
                        str13 = str25;
                        headAvModel3 = headAvModel7;
                        list12 = list20;
                        l4 = l10;
                        l5 = l11;
                        l6 = l12;
                        itemsBenefitsInfo2 = itemsBenefitsInfo4;
                        str14 = str26;
                        bulletScreen2 = bulletScreen3;
                        i4 |= 256;
                        Unit unit10 = Unit.INSTANCE;
                        bool4 = (Boolean) beginStructure.decodeNullableSerializableElement(serialDescriptor, 8, BooleanSerializer.INSTANCE, bool9);
                        lazyArr2 = lazyArr;
                        labelObject4 = labelObject6;
                        list16 = list16;
                        str9 = str21;
                        str15 = str22;
                        list9 = list17;
                        list10 = list18;
                        str11 = str23;
                        str12 = str24;
                        list11 = list19;
                        liveInfo3 = liveInfo4;
                        headAvModel4 = headAvModel3;
                        mainImageScale5 = mainImageScale2;
                        str22 = str15;
                        headAvModel7 = headAvModel4;
                        str26 = str14;
                        itemsBenefitsInfo4 = itemsBenefitsInfo2;
                        l12 = l6;
                        l11 = l5;
                        l10 = l4;
                        list20 = list12;
                        str21 = str9;
                        lazyArr = lazyArr2;
                        list17 = list9;
                        list18 = list10;
                        str23 = str11;
                        str24 = str12;
                        list19 = list11;
                        bool9 = bool4;
                        bulletScreen3 = bulletScreen2;
                        str25 = str13;
                        list15 = list7;
                    case ConstantsKt.SPACER_9 /* 9 */:
                        list7 = list15;
                        List list27 = list16;
                        mainImageScale2 = mainImageScale5;
                        headAvModel3 = headAvModel7;
                        list12 = list20;
                        l4 = l10;
                        l5 = l11;
                        l6 = l12;
                        itemsBenefitsInfo2 = itemsBenefitsInfo4;
                        str14 = str26;
                        str13 = str25;
                        i4 |= 512;
                        Unit unit11 = Unit.INSTANCE;
                        lazyArr2 = lazyArr;
                        bulletScreen2 = (BasicInfoFloor.BulletScreen) beginStructure.decodeNullableSerializableElement(serialDescriptor, 9, BasicInfoFloor$BulletScreen$$serializer.INSTANCE, bulletScreen3);
                        labelObject4 = labelObject4;
                        list16 = list27;
                        str9 = str21;
                        str15 = str22;
                        list9 = list17;
                        list10 = list18;
                        str11 = str23;
                        str12 = str24;
                        list11 = list19;
                        bool4 = bool9;
                        liveInfo3 = liveInfo4;
                        headAvModel4 = headAvModel3;
                        mainImageScale5 = mainImageScale2;
                        str22 = str15;
                        headAvModel7 = headAvModel4;
                        str26 = str14;
                        itemsBenefitsInfo4 = itemsBenefitsInfo2;
                        l12 = l6;
                        l11 = l5;
                        l10 = l4;
                        list20 = list12;
                        str21 = str9;
                        lazyArr = lazyArr2;
                        list17 = list9;
                        list18 = list10;
                        str23 = str11;
                        str24 = str12;
                        list19 = list11;
                        bool9 = bool4;
                        bulletScreen3 = bulletScreen2;
                        str25 = str13;
                        list15 = list7;
                    case 10:
                        list7 = list15;
                        LabelObject labelObject7 = labelObject4;
                        mainImageScale2 = mainImageScale5;
                        headAvModel3 = headAvModel7;
                        list12 = list20;
                        l4 = l10;
                        l5 = l11;
                        l6 = l12;
                        itemsBenefitsInfo2 = itemsBenefitsInfo4;
                        str14 = str26;
                        i4 |= 1024;
                        Unit unit12 = Unit.INSTANCE;
                        str13 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 10, StringSerializer.INSTANCE, str25);
                        lazyArr2 = lazyArr;
                        labelObject4 = labelObject7;
                        list16 = list16;
                        str9 = str21;
                        str15 = str22;
                        list9 = list17;
                        list10 = list18;
                        str11 = str23;
                        str12 = str24;
                        list11 = list19;
                        bool4 = bool9;
                        bulletScreen2 = bulletScreen3;
                        liveInfo3 = liveInfo4;
                        headAvModel4 = headAvModel3;
                        mainImageScale5 = mainImageScale2;
                        str22 = str15;
                        headAvModel7 = headAvModel4;
                        str26 = str14;
                        itemsBenefitsInfo4 = itemsBenefitsInfo2;
                        l12 = l6;
                        l11 = l5;
                        l10 = l4;
                        list20 = list12;
                        str21 = str9;
                        lazyArr = lazyArr2;
                        list17 = list9;
                        list18 = list10;
                        str23 = str11;
                        str24 = str12;
                        list19 = list11;
                        bool9 = bool4;
                        bulletScreen3 = bulletScreen2;
                        str25 = str13;
                        list15 = list7;
                    case MediaAttrUtils.TYPE_MENU /* 11 */:
                        list7 = list15;
                        BasicInfoFloor.MainImageScale mainImageScale6 = mainImageScale5;
                        l4 = l10;
                        l5 = l11;
                        l6 = l12;
                        itemsBenefitsInfo2 = itemsBenefitsInfo4;
                        str14 = str26;
                        list12 = list20;
                        i4 |= 2048;
                        Unit unit13 = Unit.INSTANCE;
                        lazyArr2 = lazyArr;
                        str9 = str21;
                        str15 = str22;
                        list9 = list17;
                        list10 = list18;
                        str11 = str23;
                        str12 = str24;
                        list11 = list19;
                        bool4 = bool9;
                        bulletScreen2 = bulletScreen3;
                        str13 = str25;
                        liveInfo3 = liveInfo4;
                        mainImageScale5 = mainImageScale6;
                        headAvModel4 = (BasicInfoFloor.HeadAvModel) beginStructure.decodeNullableSerializableElement(serialDescriptor, 11, BasicInfoFloor$HeadAvModel$$serializer.INSTANCE, headAvModel7);
                        labelObject4 = labelObject4;
                        continue;
                        str22 = str15;
                        headAvModel7 = headAvModel4;
                        str26 = str14;
                        itemsBenefitsInfo4 = itemsBenefitsInfo2;
                        l12 = l6;
                        l11 = l5;
                        l10 = l4;
                        list20 = list12;
                        str21 = str9;
                        lazyArr = lazyArr2;
                        list17 = list9;
                        list18 = list10;
                        str23 = str11;
                        str24 = str12;
                        list19 = list11;
                        bool9 = bool4;
                        bulletScreen3 = bulletScreen2;
                        str25 = str13;
                        list15 = list7;
                    case 12:
                        list7 = list15;
                        LabelObject labelObject8 = labelObject4;
                        mainImageScale3 = mainImageScale5;
                        l5 = l11;
                        l6 = l12;
                        itemsBenefitsInfo2 = itemsBenefitsInfo4;
                        str14 = str26;
                        DeserializationStrategy deserializationStrategy4 = (DeserializationStrategy) lazyArr[12].getValue();
                        l4 = l10;
                        i4 |= 4096;
                        Unit unit14 = Unit.INSTANCE;
                        list12 = (List) beginStructure.decodeNullableSerializableElement(serialDescriptor, 12, deserializationStrategy4, list20);
                        lazyArr2 = lazyArr;
                        labelObject4 = labelObject8;
                        str9 = str21;
                        str15 = str22;
                        list9 = list17;
                        list10 = list18;
                        str11 = str23;
                        str12 = str24;
                        list11 = list19;
                        bool4 = bool9;
                        bulletScreen2 = bulletScreen3;
                        str13 = str25;
                        headAvModel4 = headAvModel7;
                        liveInfo3 = liveInfo4;
                        mainImageScale5 = mainImageScale3;
                        break;
                    case 13:
                        list7 = list15;
                        mainImageScale3 = mainImageScale5;
                        l6 = l12;
                        itemsBenefitsInfo2 = itemsBenefitsInfo4;
                        str14 = str26;
                        l5 = l11;
                        i4 |= 8192;
                        Unit unit15 = Unit.INSTANCE;
                        l4 = (Long) beginStructure.decodeNullableSerializableElement(serialDescriptor, 13, LongSerializer.INSTANCE, l10);
                        lazyArr2 = lazyArr;
                        labelObject4 = labelObject4;
                        str9 = str21;
                        str15 = str22;
                        list9 = list17;
                        list10 = list18;
                        str11 = str23;
                        str12 = str24;
                        list11 = list19;
                        bool4 = bool9;
                        bulletScreen2 = bulletScreen3;
                        str13 = str25;
                        headAvModel4 = headAvModel7;
                        list12 = list20;
                        liveInfo3 = liveInfo4;
                        mainImageScale5 = mainImageScale3;
                        break;
                    case ConstantsKt.SPACER_14 /* 14 */:
                        list7 = list15;
                        mainImageScale3 = mainImageScale5;
                        itemsBenefitsInfo2 = itemsBenefitsInfo4;
                        str14 = str26;
                        l6 = l12;
                        i4 |= 16384;
                        Unit unit16 = Unit.INSTANCE;
                        lazyArr2 = lazyArr;
                        l5 = (Long) beginStructure.decodeNullableSerializableElement(serialDescriptor, 14, LongSerializer.INSTANCE, l11);
                        labelObject4 = labelObject4;
                        str9 = str21;
                        str15 = str22;
                        list9 = list17;
                        list10 = list18;
                        str11 = str23;
                        str12 = str24;
                        list11 = list19;
                        bool4 = bool9;
                        bulletScreen2 = bulletScreen3;
                        str13 = str25;
                        headAvModel4 = headAvModel7;
                        list12 = list20;
                        l4 = l10;
                        liveInfo3 = liveInfo4;
                        mainImageScale5 = mainImageScale3;
                        break;
                    case 15:
                        list7 = list15;
                        mainImageScale3 = mainImageScale5;
                        str14 = str26;
                        itemsBenefitsInfo2 = itemsBenefitsInfo4;
                        i4 |= 32768;
                        Unit unit17 = Unit.INSTANCE;
                        l6 = (Long) beginStructure.decodeNullableSerializableElement(serialDescriptor, 15, LongSerializer.INSTANCE, l12);
                        lazyArr2 = lazyArr;
                        labelObject4 = labelObject4;
                        str9 = str21;
                        str15 = str22;
                        list9 = list17;
                        list10 = list18;
                        str11 = str23;
                        str12 = str24;
                        list11 = list19;
                        bool4 = bool9;
                        bulletScreen2 = bulletScreen3;
                        str13 = str25;
                        headAvModel4 = headAvModel7;
                        list12 = list20;
                        l4 = l10;
                        l5 = l11;
                        liveInfo3 = liveInfo4;
                        mainImageScale5 = mainImageScale3;
                        break;
                    case 16:
                        list7 = list15;
                        mainImageScale3 = mainImageScale5;
                        str14 = str26;
                        i4 |= 65536;
                        Unit unit18 = Unit.INSTANCE;
                        lazyArr2 = lazyArr;
                        itemsBenefitsInfo2 = (BasicInfoFloor.ItemsBenefitsInfo) beginStructure.decodeNullableSerializableElement(serialDescriptor, 16, BasicInfoFloor$ItemsBenefitsInfo$$serializer.INSTANCE, itemsBenefitsInfo4);
                        labelObject4 = labelObject4;
                        str9 = str21;
                        str15 = str22;
                        list9 = list17;
                        list10 = list18;
                        str11 = str23;
                        str12 = str24;
                        list11 = list19;
                        bool4 = bool9;
                        bulletScreen2 = bulletScreen3;
                        str13 = str25;
                        headAvModel4 = headAvModel7;
                        list12 = list20;
                        l4 = l10;
                        l5 = l11;
                        l6 = l12;
                        liveInfo3 = liveInfo4;
                        mainImageScale5 = mainImageScale3;
                        break;
                    case 17:
                        list7 = list15;
                        mainImageScale3 = mainImageScale5;
                        i4 |= 131072;
                        Unit unit19 = Unit.INSTANCE;
                        str14 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 17, StringSerializer.INSTANCE, str26);
                        lazyArr2 = lazyArr;
                        labelObject4 = labelObject4;
                        str9 = str21;
                        str15 = str22;
                        list9 = list17;
                        list10 = list18;
                        str11 = str23;
                        str12 = str24;
                        list11 = list19;
                        bool4 = bool9;
                        bulletScreen2 = bulletScreen3;
                        str13 = str25;
                        headAvModel4 = headAvModel7;
                        list12 = list20;
                        l4 = l10;
                        l5 = l11;
                        l6 = l12;
                        itemsBenefitsInfo2 = itemsBenefitsInfo4;
                        liveInfo3 = liveInfo4;
                        mainImageScale5 = mainImageScale3;
                        break;
                    case 18:
                        list7 = list15;
                        mainImageScale3 = mainImageScale5;
                        i4 |= 262144;
                        Unit unit20 = Unit.INSTANCE;
                        lazyArr2 = lazyArr;
                        num5 = (Integer) beginStructure.decodeNullableSerializableElement(serialDescriptor, 18, IntSerializer.INSTANCE, num5);
                        str9 = str21;
                        str15 = str22;
                        list9 = list17;
                        list10 = list18;
                        str11 = str23;
                        str12 = str24;
                        list11 = list19;
                        bool4 = bool9;
                        bulletScreen2 = bulletScreen3;
                        str13 = str25;
                        headAvModel4 = headAvModel7;
                        list12 = list20;
                        l4 = l10;
                        l5 = l11;
                        l6 = l12;
                        itemsBenefitsInfo2 = itemsBenefitsInfo4;
                        str14 = str26;
                        liveInfo3 = liveInfo4;
                        mainImageScale5 = mainImageScale3;
                        break;
                    case 19:
                        list7 = list15;
                        mainImageScale3 = mainImageScale5;
                        i4 |= 524288;
                        Unit unit21 = Unit.INSTANCE;
                        liveInfo3 = (BasicInfoFloor.LiveInfo) beginStructure.decodeNullableSerializableElement(serialDescriptor, 19, BasicInfoFloor$LiveInfo$$serializer.INSTANCE, liveInfo4);
                        lazyArr2 = lazyArr;
                        str9 = str21;
                        str15 = str22;
                        list9 = list17;
                        list10 = list18;
                        str11 = str23;
                        str12 = str24;
                        list11 = list19;
                        bool4 = bool9;
                        bulletScreen2 = bulletScreen3;
                        str13 = str25;
                        headAvModel4 = headAvModel7;
                        list12 = list20;
                        l4 = l10;
                        l5 = l11;
                        l6 = l12;
                        itemsBenefitsInfo2 = itemsBenefitsInfo4;
                        str14 = str26;
                        mainImageScale5 = mainImageScale3;
                        break;
                    case 20:
                        BasicInfoFloor.MainImageScale mainImageScale7 = mainImageScale5;
                        list7 = list15;
                        i4 |= 1048576;
                        Unit unit22 = Unit.INSTANCE;
                        mainImageScale5 = (BasicInfoFloor.MainImageScale) beginStructure.decodeNullableSerializableElement(serialDescriptor, 20, BasicInfoFloor$MainImageScale$$serializer.INSTANCE, mainImageScale7);
                        lazyArr2 = lazyArr;
                        str9 = str21;
                        str15 = str22;
                        list9 = list17;
                        list10 = list18;
                        str11 = str23;
                        str12 = str24;
                        list11 = list19;
                        bool4 = bool9;
                        bulletScreen2 = bulletScreen3;
                        str13 = str25;
                        headAvModel4 = headAvModel7;
                        list12 = list20;
                        l4 = l10;
                        l5 = l11;
                        l6 = l12;
                        itemsBenefitsInfo2 = itemsBenefitsInfo4;
                        str14 = str26;
                        liveInfo3 = liveInfo4;
                        break;
                    case 21:
                        mainImageScale3 = mainImageScale5;
                        newUpSayModel3 = (BasicInfoFloor.NewUpSayModel) beginStructure.decodeNullableSerializableElement(serialDescriptor, 21, BasicInfoFloor$NewUpSayModel$$serializer.INSTANCE, newUpSayModel3);
                        i2 = 2097152;
                        i4 |= i2;
                        Unit unit23 = Unit.INSTANCE;
                        list7 = list15;
                        lazyArr2 = lazyArr;
                        str9 = str21;
                        str15 = str22;
                        list9 = list17;
                        list10 = list18;
                        str11 = str23;
                        str12 = str24;
                        list11 = list19;
                        bool4 = bool9;
                        bulletScreen2 = bulletScreen3;
                        str13 = str25;
                        headAvModel4 = headAvModel7;
                        list12 = list20;
                        l4 = l10;
                        l5 = l11;
                        l6 = l12;
                        itemsBenefitsInfo2 = itemsBenefitsInfo4;
                        str14 = str26;
                        liveInfo3 = liveInfo4;
                        mainImageScale5 = mainImageScale3;
                        break;
                    case 22:
                        mainImageScale3 = mainImageScale5;
                        list16 = (List) beginStructure.decodeNullableSerializableElement(serialDescriptor, 22, (DeserializationStrategy) lazyArr[22].getValue(), list16);
                        i3 = 4194304;
                        i4 |= i3;
                        Unit unit24 = Unit.INSTANCE;
                        list7 = list15;
                        lazyArr2 = lazyArr;
                        str9 = str21;
                        str15 = str22;
                        list9 = list17;
                        list10 = list18;
                        str11 = str23;
                        str12 = str24;
                        list11 = list19;
                        bool4 = bool9;
                        bulletScreen2 = bulletScreen3;
                        str13 = str25;
                        headAvModel4 = headAvModel7;
                        list12 = list20;
                        l4 = l10;
                        l5 = l11;
                        l6 = l12;
                        itemsBenefitsInfo2 = itemsBenefitsInfo4;
                        str14 = str26;
                        liveInfo3 = liveInfo4;
                        mainImageScale5 = mainImageScale3;
                        break;
                    case 23:
                        mainImageScale3 = mainImageScale5;
                        bool8 = (Boolean) beginStructure.decodeNullableSerializableElement(serialDescriptor, 23, BooleanSerializer.INSTANCE, bool8);
                        i2 = 8388608;
                        i4 |= i2;
                        Unit unit232 = Unit.INSTANCE;
                        list7 = list15;
                        lazyArr2 = lazyArr;
                        str9 = str21;
                        str15 = str22;
                        list9 = list17;
                        list10 = list18;
                        str11 = str23;
                        str12 = str24;
                        list11 = list19;
                        bool4 = bool9;
                        bulletScreen2 = bulletScreen3;
                        str13 = str25;
                        headAvModel4 = headAvModel7;
                        list12 = list20;
                        l4 = l10;
                        l5 = l11;
                        l6 = l12;
                        itemsBenefitsInfo2 = itemsBenefitsInfo4;
                        str14 = str26;
                        liveInfo3 = liveInfo4;
                        mainImageScale5 = mainImageScale3;
                        break;
                    case 24:
                        mainImageScale3 = mainImageScale5;
                        list15 = (List) beginStructure.decodeNullableSerializableElement(serialDescriptor, 24, (DeserializationStrategy) lazyArr[24].getValue(), list15);
                        i3 = 16777216;
                        i4 |= i3;
                        Unit unit242 = Unit.INSTANCE;
                        list7 = list15;
                        lazyArr2 = lazyArr;
                        str9 = str21;
                        str15 = str22;
                        list9 = list17;
                        list10 = list18;
                        str11 = str23;
                        str12 = str24;
                        list11 = list19;
                        bool4 = bool9;
                        bulletScreen2 = bulletScreen3;
                        str13 = str25;
                        headAvModel4 = headAvModel7;
                        list12 = list20;
                        l4 = l10;
                        l5 = l11;
                        l6 = l12;
                        itemsBenefitsInfo2 = itemsBenefitsInfo4;
                        str14 = str26;
                        liveInfo3 = liveInfo4;
                        mainImageScale5 = mainImageScale3;
                        break;
                    case 25:
                        mainImageScale3 = mainImageScale5;
                        labelObject4 = (LabelObject) beginStructure.decodeNullableSerializableElement(serialDescriptor, 25, LabelObject$$serializer.INSTANCE, labelObject4);
                        i2 = 33554432;
                        i4 |= i2;
                        Unit unit2322 = Unit.INSTANCE;
                        list7 = list15;
                        lazyArr2 = lazyArr;
                        str9 = str21;
                        str15 = str22;
                        list9 = list17;
                        list10 = list18;
                        str11 = str23;
                        str12 = str24;
                        list11 = list19;
                        bool4 = bool9;
                        bulletScreen2 = bulletScreen3;
                        str13 = str25;
                        headAvModel4 = headAvModel7;
                        list12 = list20;
                        l4 = l10;
                        l5 = l11;
                        l6 = l12;
                        itemsBenefitsInfo2 = itemsBenefitsInfo4;
                        str14 = str26;
                        liveInfo3 = liveInfo4;
                        mainImageScale5 = mainImageScale3;
                        break;
                    case 26:
                        mainImageScale3 = mainImageScale5;
                        textColorModel3 = (TextColorModel) beginStructure.decodeNullableSerializableElement(serialDescriptor, 26, TextColorModel$$serializer.INSTANCE, textColorModel3);
                        i2 = 67108864;
                        i4 |= i2;
                        Unit unit23222 = Unit.INSTANCE;
                        list7 = list15;
                        lazyArr2 = lazyArr;
                        str9 = str21;
                        str15 = str22;
                        list9 = list17;
                        list10 = list18;
                        str11 = str23;
                        str12 = str24;
                        list11 = list19;
                        bool4 = bool9;
                        bulletScreen2 = bulletScreen3;
                        str13 = str25;
                        headAvModel4 = headAvModel7;
                        list12 = list20;
                        l4 = l10;
                        l5 = l11;
                        l6 = l12;
                        itemsBenefitsInfo2 = itemsBenefitsInfo4;
                        str14 = str26;
                        liveInfo3 = liveInfo4;
                        mainImageScale5 = mainImageScale3;
                        break;
                    case 27:
                        mainImageScale3 = mainImageScale5;
                        i4 |= 134217728;
                        Unit unit25 = Unit.INSTANCE;
                        list7 = list15;
                        lazyArr2 = lazyArr;
                        headAvModel8 = (BasicInfoFloor.HeadAvModel) beginStructure.decodeNullableSerializableElement(serialDescriptor, 27, BasicInfoFloor$HeadAvModel$$serializer.INSTANCE, headAvModel8);
                        str9 = str21;
                        str15 = str22;
                        list9 = list17;
                        list10 = list18;
                        str11 = str23;
                        str12 = str24;
                        list11 = list19;
                        bool4 = bool9;
                        bulletScreen2 = bulletScreen3;
                        str13 = str25;
                        headAvModel4 = headAvModel7;
                        list12 = list20;
                        l4 = l10;
                        l5 = l11;
                        l6 = l12;
                        itemsBenefitsInfo2 = itemsBenefitsInfo4;
                        str14 = str26;
                        liveInfo3 = liveInfo4;
                        mainImageScale5 = mainImageScale3;
                        break;
                    case 28:
                        mainImageScale3 = mainImageScale5;
                        bool7 = (Boolean) beginStructure.decodeNullableSerializableElement(serialDescriptor, 28, BooleanSerializer.INSTANCE, bool7);
                        i2 = 268435456;
                        i4 |= i2;
                        Unit unit232222 = Unit.INSTANCE;
                        list7 = list15;
                        lazyArr2 = lazyArr;
                        str9 = str21;
                        str15 = str22;
                        list9 = list17;
                        list10 = list18;
                        str11 = str23;
                        str12 = str24;
                        list11 = list19;
                        bool4 = bool9;
                        bulletScreen2 = bulletScreen3;
                        str13 = str25;
                        headAvModel4 = headAvModel7;
                        list12 = list20;
                        l4 = l10;
                        l5 = l11;
                        l6 = l12;
                        itemsBenefitsInfo2 = itemsBenefitsInfo4;
                        str14 = str26;
                        liveInfo3 = liveInfo4;
                        mainImageScale5 = mainImageScale3;
                        break;
                    case 29:
                        mainImageScale3 = mainImageScale5;
                        str19 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 29, StringSerializer.INSTANCE, str19);
                        i2 = 536870912;
                        i4 |= i2;
                        Unit unit2322222 = Unit.INSTANCE;
                        list7 = list15;
                        lazyArr2 = lazyArr;
                        str9 = str21;
                        str15 = str22;
                        list9 = list17;
                        list10 = list18;
                        str11 = str23;
                        str12 = str24;
                        list11 = list19;
                        bool4 = bool9;
                        bulletScreen2 = bulletScreen3;
                        str13 = str25;
                        headAvModel4 = headAvModel7;
                        list12 = list20;
                        l4 = l10;
                        l5 = l11;
                        l6 = l12;
                        itemsBenefitsInfo2 = itemsBenefitsInfo4;
                        str14 = str26;
                        liveInfo3 = liveInfo4;
                        mainImageScale5 = mainImageScale3;
                        break;
                    case 30:
                        mainImageScale3 = mainImageScale5;
                        num4 = (Integer) beginStructure.decodeNullableSerializableElement(serialDescriptor, 30, IntSerializer.INSTANCE, num4);
                        i2 = 1073741824;
                        i4 |= i2;
                        Unit unit23222222 = Unit.INSTANCE;
                        list7 = list15;
                        lazyArr2 = lazyArr;
                        str9 = str21;
                        str15 = str22;
                        list9 = list17;
                        list10 = list18;
                        str11 = str23;
                        str12 = str24;
                        list11 = list19;
                        bool4 = bool9;
                        bulletScreen2 = bulletScreen3;
                        str13 = str25;
                        headAvModel4 = headAvModel7;
                        list12 = list20;
                        l4 = l10;
                        l5 = l11;
                        l6 = l12;
                        itemsBenefitsInfo2 = itemsBenefitsInfo4;
                        str14 = str26;
                        liveInfo3 = liveInfo4;
                        mainImageScale5 = mainImageScale3;
                        break;
                    default:
                        throw new UnknownFieldException(decodeElementIndex);
                }
                str22 = str15;
                headAvModel7 = headAvModel4;
                str26 = str14;
                itemsBenefitsInfo4 = itemsBenefitsInfo2;
                l12 = l6;
                l11 = l5;
                l10 = l4;
                list20 = list12;
                str21 = str9;
                lazyArr = lazyArr2;
                list17 = list9;
                list18 = list10;
                str23 = str11;
                str24 = str12;
                list19 = list11;
                bool9 = bool4;
                bulletScreen3 = bulletScreen2;
                str25 = str13;
                list15 = list7;
            }
            String str27 = str20;
            String str28 = str21;
            List list28 = list17;
            List list29 = list18;
            String str29 = str23;
            String str30 = str24;
            List list30 = list19;
            Boolean bool10 = bool9;
            BasicInfoFloor.BulletScreen bulletScreen4 = bulletScreen3;
            String str31 = str25;
            str = str22;
            bool = bool7;
            newUpSayModel = newUpSayModel3;
            str2 = str19;
            num = num4;
            textColorModel = textColorModel3;
            i = i4;
            bool2 = bool8;
            headAvModel = headAvModel7;
            headAvModel2 = headAvModel8;
            labelObject = labelObject4;
            list = list16;
            list2 = list28;
            bulletScreen = bulletScreen4;
            mainImageScale = mainImageScale5;
            list3 = list15;
            str3 = str27;
            num2 = num5;
            list4 = list20;
            bool3 = bool10;
            str4 = str26;
            str5 = str28;
            str6 = str31;
            liveInfo = liveInfo3;
            itemsBenefitsInfo = itemsBenefitsInfo4;
            list5 = list29;
            l = l10;
            list6 = list30;
            l2 = l12;
            str7 = str29;
            l3 = l11;
            str8 = str30;
        }
        beginStructure.endStructure(serialDescriptor);
        return new BasicInfoFloor(i, str3, str5, str, list2, list5, str7, str8, list6, bool3, bulletScreen, str6, headAvModel, list4, l, l3, l2, itemsBenefitsInfo, str4, num2, liveInfo, mainImageScale, newUpSayModel, list, bool2, list3, labelObject, textColorModel, headAvModel2, bool, str2, num, (SerializationConstructorMarker) null);
    }

    public final void serialize(Encoder encoder, BasicInfoFloor value) {
        Intrinsics.checkNotNullParameter(encoder, "encoder");
        Intrinsics.checkNotNullParameter(value, "value");
        SerialDescriptor serialDescriptor = descriptor;
        CompositeEncoder beginStructure = encoder.beginStructure(serialDescriptor);
        BasicInfoFloor.write$Self$product_details_page_debug(value, beginStructure, serialDescriptor);
        beginStructure.endStructure(serialDescriptor);
    }

    public /* bridge */ KSerializer<?>[] typeParametersSerializers() {
        return GeneratedSerializer.DefaultImpls.typeParametersSerializers(this);
    }
}