package kntr.app.mall.product.details.page.api.model;

import com.bapis.bilibili.app.dynamic.v2.AdditionalButton;
import java.util.List;
import kntr.app.mall.product.details.page.api.model.FooterFloor;
import kntr.app.upcomingEpisode.ConstantsKt;
import kntr.watch.later.watchlater.edit.MediaAttrUtils;
import kotlin.Deprecated;
import kotlin.DeprecationLevel;
import kotlin.Lazy;
import kotlin.Metadata;
import kotlin.Unit;
import kotlin.jvm.internal.Intrinsics;
import kotlinx.serialization.DeserializationStrategy;
import kotlinx.serialization.KSerializer;
import kotlinx.serialization.UnknownFieldException;
import kotlinx.serialization.builtins.BuiltinSerializersKt;
import kotlinx.serialization.descriptors.SerialDescriptor;
import kotlinx.serialization.encoding.CompositeDecoder;
import kotlinx.serialization.encoding.CompositeEncoder;
import kotlinx.serialization.encoding.Decoder;
import kotlinx.serialization.encoding.Encoder;
import kotlinx.serialization.internal.BooleanSerializer;
import kotlinx.serialization.internal.GeneratedSerializer;
import kotlinx.serialization.internal.IntSerializer;
import kotlinx.serialization.internal.LongSerializer;
import kotlinx.serialization.internal.PluginGeneratedSerialDescriptor;
import kotlinx.serialization.internal.SerializationConstructorMarker;
import kotlinx.serialization.internal.StringSerializer;
import kotlinx.serialization.json.JsonObject;
import kotlinx.serialization.json.JsonObjectSerializer;

/* compiled from: FooterFloor.kt */
@Metadata(d1 = {"\u00006\n\u0000\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\b\u0003\n\u0002\u0010\u0011\n\u0002\u0018\u0002\n\u0002\b\u0003\n\u0002\u0018\u0002\n\u0000\n\u0002\u0010\u0002\n\u0000\n\u0002\u0018\u0002\n\u0002\b\u0002\n\u0002\u0018\u0002\n\u0002\b\u0003\bÇ\u0002\u0018\u00002\b\u0012\u0004\u0012\u00020\u00020\u0001B\t\b\u0002¢\u0006\u0004\b\u0003\u0010\u0004J\u0015\u0010\u0005\u001a\f\u0012\b\u0012\u0006\u0012\u0002\b\u00030\u00070\u0006¢\u0006\u0002\u0010\bJ\u000e\u0010\t\u001a\u00020\u00022\u0006\u0010\n\u001a\u00020\u000bJ\u0016\u0010\f\u001a\u00020\r2\u0006\u0010\u000e\u001a\u00020\u000f2\u0006\u0010\u0010\u001a\u00020\u0002R\u0011\u0010\u0011\u001a\u00020\u0012¢\u0006\b\n\u0000\u001a\u0004\b\u0013\u0010\u0014¨\u0006\u0015"}, d2 = {"kntr/app/mall/product/details/page/api/model/FooterFloor.PurchaseButton.$serializer", "Lkotlinx/serialization/internal/GeneratedSerializer;", "Lkntr/app/mall/product/details/page/api/model/FooterFloor$PurchaseButton;", "<init>", "()V", "childSerializers", "", "Lkotlinx/serialization/KSerializer;", "()[Lkotlinx/serialization/KSerializer;", "deserialize", "decoder", "Lkotlinx/serialization/encoding/Decoder;", "serialize", "", "encoder", "Lkotlinx/serialization/encoding/Encoder;", "value", "descriptor", "Lkotlinx/serialization/descriptors/SerialDescriptor;", "getDescriptor", "()Lkotlinx/serialization/descriptors/SerialDescriptor;", "product-details-page_debug"}, k = 1, mv = {2, 2, 0}, xi = ConstantsKt.OGV_UPDATE_CALENDAR_CARD_COVER_WIDTH)
@Deprecated(level = DeprecationLevel.HIDDEN, message = "This synthesized declaration should not be used directly")
public final /* synthetic */ class FooterFloor$PurchaseButton$$serializer implements GeneratedSerializer<FooterFloor.PurchaseButton> {
    public static final int $stable;
    public static final FooterFloor$PurchaseButton$$serializer INSTANCE = new FooterFloor$PurchaseButton$$serializer();
    private static final SerialDescriptor descriptor;

    public final SerialDescriptor getDescriptor() {
        return descriptor;
    }

    static {
        SerialDescriptor pluginGeneratedSerialDescriptor = new PluginGeneratedSerialDescriptor("kntr.app.mall.product.details.page.api.model.FooterFloor.PurchaseButton", INSTANCE, 28);
        pluginGeneratedSerialDescriptor.addElement("buttonSubCountDownInfo", true);
        pluginGeneratedSerialDescriptor.addElement("addCartJumpUrl", true);
        pluginGeneratedSerialDescriptor.addElement("addCartType", true);
        pluginGeneratedSerialDescriptor.addElement("buttonDayColor", true);
        pluginGeneratedSerialDescriptor.addElement("buttonNightColor", true);
        pluginGeneratedSerialDescriptor.addElement("buttonState", true);
        pluginGeneratedSerialDescriptor.addElement("buttonSubText", true);
        pluginGeneratedSerialDescriptor.addElement("buttonText", true);
        pluginGeneratedSerialDescriptor.addElement("itemsId", true);
        pluginGeneratedSerialDescriptor.addElement("buttonPriceDescVO", true);
        pluginGeneratedSerialDescriptor.addElement("calendarRemind", true);
        pluginGeneratedSerialDescriptor.addElement("jumpType", true);
        pluginGeneratedSerialDescriptor.addElement("jumpUrl", true);
        pluginGeneratedSerialDescriptor.addElement("merchantId", true);
        pluginGeneratedSerialDescriptor.addElement("mergeCartBuyButton", true);
        pluginGeneratedSerialDescriptor.addElement("mergeCartBuyButtonType", true);
        pluginGeneratedSerialDescriptor.addElement("realtimeRequest", false);
        pluginGeneratedSerialDescriptor.addElement("remindMessage", true);
        pluginGeneratedSerialDescriptor.addElement("remindTime", true);
        pluginGeneratedSerialDescriptor.addElement("shopId", true);
        pluginGeneratedSerialDescriptor.addElement("showAddCart", true);
        pluginGeneratedSerialDescriptor.addElement("showQuickOrder", true);
        pluginGeneratedSerialDescriptor.addElement("skuIds", true);
        pluginGeneratedSerialDescriptor.addElement("sourceQuery", true);
        pluginGeneratedSerialDescriptor.addElement("type", true);
        pluginGeneratedSerialDescriptor.addElement("bgColors", true);
        pluginGeneratedSerialDescriptor.addElement("fontColor", true);
        pluginGeneratedSerialDescriptor.addElement("shadingImgs", true);
        descriptor = pluginGeneratedSerialDescriptor;
        $stable = 8;
    }

    private FooterFloor$PurchaseButton$$serializer() {
    }

    public final KSerializer<?>[] childSerializers() {
        Lazy[] lazyArr;
        lazyArr = FooterFloor.PurchaseButton.$childSerializers;
        return new KSerializer[]{BuiltinSerializersKt.getNullable(CountDownInfoVO$$serializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(IntSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(IntSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(LongSerializer.INSTANCE), BuiltinSerializersKt.getNullable(PriceDescVO$$serializer.INSTANCE), BuiltinSerializersKt.getNullable(CalendarRemindModel$$serializer.INSTANCE), BuiltinSerializersKt.getNullable(IntSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(IntSerializer.INSTANCE), BuiltinSerializersKt.getNullable(BooleanSerializer.INSTANCE), BuiltinSerializersKt.getNullable(IntSerializer.INSTANCE), BuiltinSerializersKt.getNullable(JsonObjectSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(IntSerializer.INSTANCE), BuiltinSerializersKt.getNullable(IntSerializer.INSTANCE), BuiltinSerializersKt.getNullable(BooleanSerializer.INSTANCE), BuiltinSerializersKt.getNullable(BooleanSerializer.INSTANCE), BuiltinSerializersKt.getNullable((KSerializer) lazyArr[22].getValue()), BuiltinSerializersKt.getNullable(JsonObjectSerializer.INSTANCE), BuiltinSerializersKt.getNullable(IntSerializer.INSTANCE), BuiltinSerializersKt.getNullable((KSerializer) lazyArr[25].getValue()), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable((KSerializer) lazyArr[27].getValue())};
    }

    public final FooterFloor.PurchaseButton deserialize(Decoder decoder) {
        Lazy[] lazyArr;
        List list;
        String str;
        int i;
        Integer num;
        String str2;
        Integer num2;
        String str3;
        CalendarRemindModel calendarRemindModel;
        CountDownInfoVO countDownInfoVO;
        List list2;
        List list3;
        Integer num3;
        Boolean bool;
        Long l;
        PriceDescVO priceDescVO;
        JsonObject jsonObject;
        Integer num4;
        String str4;
        Integer num5;
        Boolean bool2;
        JsonObject jsonObject2;
        String str5;
        String str6;
        Integer num6;
        Boolean bool3;
        Integer num7;
        String str7;
        Integer num8;
        String str8;
        Integer num9;
        Lazy[] lazyArr2;
        String str9;
        String str10;
        Integer num10;
        String str11;
        String str12;
        Integer num11;
        String str13;
        String str14;
        Long l2;
        PriceDescVO priceDescVO2;
        CalendarRemindModel calendarRemindModel2;
        Integer num12;
        String str15;
        Integer num13;
        Boolean bool4;
        Integer num14;
        JsonObject jsonObject3;
        String str16;
        int i2;
        Intrinsics.checkNotNullParameter(decoder, "decoder");
        SerialDescriptor serialDescriptor = descriptor;
        CompositeDecoder beginStructure = decoder.beginStructure(serialDescriptor);
        lazyArr = FooterFloor.PurchaseButton.$childSerializers;
        if (beginStructure.decodeSequentially()) {
            CalendarRemindModel calendarRemindModel3 = (CalendarRemindModel) beginStructure.decodeNullableSerializableElement(serialDescriptor, 10, CalendarRemindModel$$serializer.INSTANCE, (Object) null);
            Integer num15 = (Integer) beginStructure.decodeNullableSerializableElement(serialDescriptor, 11, IntSerializer.INSTANCE, (Object) null);
            String str17 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 12, StringSerializer.INSTANCE, (Object) null);
            Integer num16 = (Integer) beginStructure.decodeNullableSerializableElement(serialDescriptor, 13, IntSerializer.INSTANCE, (Object) null);
            Boolean bool5 = (Boolean) beginStructure.decodeNullableSerializableElement(serialDescriptor, 14, BooleanSerializer.INSTANCE, (Object) null);
            Integer num17 = (Integer) beginStructure.decodeNullableSerializableElement(serialDescriptor, 15, IntSerializer.INSTANCE, (Object) null);
            JsonObject jsonObject4 = (JsonObject) beginStructure.decodeNullableSerializableElement(serialDescriptor, 16, JsonObjectSerializer.INSTANCE, (Object) null);
            String str18 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 17, StringSerializer.INSTANCE, (Object) null);
            Integer num18 = (Integer) beginStructure.decodeNullableSerializableElement(serialDescriptor, 18, IntSerializer.INSTANCE, (Object) null);
            Integer num19 = (Integer) beginStructure.decodeNullableSerializableElement(serialDescriptor, 19, IntSerializer.INSTANCE, (Object) null);
            Boolean bool6 = (Boolean) beginStructure.decodeNullableSerializableElement(serialDescriptor, 20, BooleanSerializer.INSTANCE, (Object) null);
            Boolean bool7 = (Boolean) beginStructure.decodeNullableSerializableElement(serialDescriptor, 21, BooleanSerializer.INSTANCE, (Object) null);
            List list4 = (List) beginStructure.decodeNullableSerializableElement(serialDescriptor, 22, (DeserializationStrategy) lazyArr[22].getValue(), (Object) null);
            JsonObject jsonObject5 = (JsonObject) beginStructure.decodeNullableSerializableElement(serialDescriptor, 23, JsonObjectSerializer.INSTANCE, (Object) null);
            Integer num20 = (Integer) beginStructure.decodeNullableSerializableElement(serialDescriptor, 24, IntSerializer.INSTANCE, (Object) null);
            List list5 = (List) beginStructure.decodeNullableSerializableElement(serialDescriptor, 25, (DeserializationStrategy) lazyArr[25].getValue(), (Object) null);
            str = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 26, StringSerializer.INSTANCE, (Object) null);
            list = (List) beginStructure.decodeNullableSerializableElement(serialDescriptor, 27, (DeserializationStrategy) lazyArr[27].getValue(), (Object) null);
            str8 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 4, StringSerializer.INSTANCE, (Object) null);
            list2 = list5;
            list3 = list4;
            num2 = num15;
            jsonObject = jsonObject5;
            num4 = num20;
            bool = bool5;
            num = num16;
            str2 = str17;
            calendarRemindModel = calendarRemindModel3;
            bool2 = bool6;
            bool3 = bool7;
            l = (Long) beginStructure.decodeNullableSerializableElement(serialDescriptor, 8, LongSerializer.INSTANCE, (Object) null);
            priceDescVO = (PriceDescVO) beginStructure.decodeNullableSerializableElement(serialDescriptor, 9, PriceDescVO$$serializer.INSTANCE, (Object) null);
            num3 = num17;
            num6 = num18;
            num8 = num19;
            str4 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 1, StringSerializer.INSTANCE, (Object) null);
            str6 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 6, StringSerializer.INSTANCE, (Object) null);
            str7 = str18;
            jsonObject2 = jsonObject4;
            str5 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 3, StringSerializer.INSTANCE, (Object) null);
            num5 = (Integer) beginStructure.decodeNullableSerializableElement(serialDescriptor, 5, IntSerializer.INSTANCE, (Object) null);
            i = 268435455;
            str3 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 7, StringSerializer.INSTANCE, (Object) null);
            countDownInfoVO = (CountDownInfoVO) beginStructure.decodeNullableSerializableElement(serialDescriptor, 0, CountDownInfoVO$$serializer.INSTANCE, (Object) null);
            num7 = (Integer) beginStructure.decodeNullableSerializableElement(serialDescriptor, 2, IntSerializer.INSTANCE, (Object) null);
        } else {
            boolean z = true;
            Integer num21 = null;
            List list6 = null;
            String str19 = null;
            List list7 = null;
            Integer num22 = null;
            JsonObject jsonObject6 = null;
            List list8 = null;
            JsonObject jsonObject7 = null;
            Boolean bool8 = null;
            Boolean bool9 = null;
            Integer num23 = null;
            CountDownInfoVO countDownInfoVO2 = null;
            String str20 = null;
            Integer num24 = null;
            String str21 = null;
            String str22 = null;
            Integer num25 = null;
            String str23 = null;
            String str24 = null;
            Long l3 = null;
            PriceDescVO priceDescVO3 = null;
            CalendarRemindModel calendarRemindModel4 = null;
            Integer num26 = null;
            String str25 = null;
            Integer num27 = null;
            Boolean bool10 = null;
            Integer num28 = null;
            int i3 = 0;
            String str26 = null;
            while (z) {
                JsonObject jsonObject8 = jsonObject6;
                int decodeElementIndex = beginStructure.decodeElementIndex(serialDescriptor);
                switch (decodeElementIndex) {
                    case -1:
                        num9 = num21;
                        lazyArr2 = lazyArr;
                        str9 = str19;
                        str10 = str20;
                        num10 = num24;
                        str11 = str21;
                        str12 = str22;
                        num11 = num25;
                        str13 = str23;
                        str14 = str24;
                        l2 = l3;
                        priceDescVO2 = priceDescVO3;
                        calendarRemindModel2 = calendarRemindModel4;
                        num12 = num26;
                        str15 = str25;
                        num13 = num27;
                        bool4 = bool10;
                        num14 = num28;
                        jsonObject3 = jsonObject8;
                        Unit unit = Unit.INSTANCE;
                        z = false;
                        str19 = str9;
                        num21 = num9;
                        jsonObject6 = jsonObject3;
                        break;
                    case 0:
                        num9 = num21;
                        lazyArr2 = lazyArr;
                        str9 = str19;
                        num10 = num24;
                        str11 = str21;
                        str12 = str22;
                        num11 = num25;
                        str13 = str23;
                        str14 = str24;
                        l2 = l3;
                        priceDescVO2 = priceDescVO3;
                        calendarRemindModel2 = calendarRemindModel4;
                        num12 = num26;
                        str15 = str25;
                        num13 = num27;
                        bool4 = bool10;
                        num14 = num28;
                        jsonObject3 = jsonObject8;
                        str10 = str20;
                        i3 |= 1;
                        Unit unit2 = Unit.INSTANCE;
                        countDownInfoVO2 = (CountDownInfoVO) beginStructure.decodeNullableSerializableElement(serialDescriptor, 0, CountDownInfoVO$$serializer.INSTANCE, countDownInfoVO2);
                        str19 = str9;
                        num21 = num9;
                        jsonObject6 = jsonObject3;
                        break;
                    case 1:
                        lazyArr2 = lazyArr;
                        String str27 = str19;
                        str11 = str21;
                        str12 = str22;
                        num11 = num25;
                        str13 = str23;
                        str14 = str24;
                        l2 = l3;
                        priceDescVO2 = priceDescVO3;
                        calendarRemindModel2 = calendarRemindModel4;
                        num12 = num26;
                        str15 = str25;
                        num13 = num27;
                        bool4 = bool10;
                        num14 = num28;
                        num10 = num24;
                        i3 |= 2;
                        Unit unit3 = Unit.INSTANCE;
                        str10 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 1, StringSerializer.INSTANCE, str20);
                        str19 = str27;
                        num21 = num21;
                        jsonObject6 = jsonObject8;
                        break;
                    case 2:
                        lazyArr2 = lazyArr;
                        String str28 = str19;
                        str12 = str22;
                        num11 = num25;
                        str13 = str23;
                        str14 = str24;
                        l2 = l3;
                        priceDescVO2 = priceDescVO3;
                        calendarRemindModel2 = calendarRemindModel4;
                        num12 = num26;
                        str15 = str25;
                        num13 = num27;
                        bool4 = bool10;
                        num14 = num28;
                        str11 = str21;
                        i3 |= 4;
                        Unit unit4 = Unit.INSTANCE;
                        num10 = (Integer) beginStructure.decodeNullableSerializableElement(serialDescriptor, 2, IntSerializer.INSTANCE, num24);
                        str19 = str28;
                        num21 = num21;
                        jsonObject6 = jsonObject8;
                        str10 = str20;
                        break;
                    case 3:
                        lazyArr2 = lazyArr;
                        String str29 = str19;
                        num11 = num25;
                        str13 = str23;
                        str14 = str24;
                        l2 = l3;
                        priceDescVO2 = priceDescVO3;
                        calendarRemindModel2 = calendarRemindModel4;
                        num12 = num26;
                        str15 = str25;
                        num13 = num27;
                        bool4 = bool10;
                        num14 = num28;
                        str12 = str22;
                        i3 |= 8;
                        Unit unit5 = Unit.INSTANCE;
                        str11 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 3, StringSerializer.INSTANCE, str21);
                        str19 = str29;
                        num21 = num21;
                        jsonObject6 = jsonObject8;
                        str10 = str20;
                        num10 = num24;
                        break;
                    case 4:
                        lazyArr2 = lazyArr;
                        String str30 = str19;
                        str13 = str23;
                        str14 = str24;
                        l2 = l3;
                        priceDescVO2 = priceDescVO3;
                        calendarRemindModel2 = calendarRemindModel4;
                        num12 = num26;
                        str15 = str25;
                        num13 = num27;
                        bool4 = bool10;
                        num14 = num28;
                        num11 = num25;
                        i3 |= 16;
                        Unit unit6 = Unit.INSTANCE;
                        str12 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 4, StringSerializer.INSTANCE, str22);
                        str19 = str30;
                        num21 = num21;
                        jsonObject6 = jsonObject8;
                        str10 = str20;
                        num10 = num24;
                        str11 = str21;
                        break;
                    case 5:
                        lazyArr2 = lazyArr;
                        String str31 = str19;
                        str14 = str24;
                        l2 = l3;
                        priceDescVO2 = priceDescVO3;
                        calendarRemindModel2 = calendarRemindModel4;
                        num12 = num26;
                        str15 = str25;
                        num13 = num27;
                        bool4 = bool10;
                        num14 = num28;
                        str13 = str23;
                        i3 |= 32;
                        Unit unit7 = Unit.INSTANCE;
                        num11 = (Integer) beginStructure.decodeNullableSerializableElement(serialDescriptor, 5, IntSerializer.INSTANCE, num25);
                        str19 = str31;
                        num21 = num21;
                        jsonObject6 = jsonObject8;
                        str10 = str20;
                        num10 = num24;
                        str11 = str21;
                        str12 = str22;
                        break;
                    case 6:
                        lazyArr2 = lazyArr;
                        String str32 = str19;
                        l2 = l3;
                        priceDescVO2 = priceDescVO3;
                        calendarRemindModel2 = calendarRemindModel4;
                        num12 = num26;
                        str15 = str25;
                        num13 = num27;
                        bool4 = bool10;
                        num14 = num28;
                        str14 = str24;
                        i3 |= 64;
                        Unit unit8 = Unit.INSTANCE;
                        str13 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 6, StringSerializer.INSTANCE, str23);
                        str19 = str32;
                        num21 = num21;
                        jsonObject6 = jsonObject8;
                        str10 = str20;
                        num10 = num24;
                        str11 = str21;
                        str12 = str22;
                        num11 = num25;
                        break;
                    case AdditionalButton.CLICK_TYPE_FIELD_NUMBER /* 7 */:
                        lazyArr2 = lazyArr;
                        String str33 = str19;
                        priceDescVO2 = priceDescVO3;
                        calendarRemindModel2 = calendarRemindModel4;
                        num12 = num26;
                        str15 = str25;
                        num13 = num27;
                        bool4 = bool10;
                        num14 = num28;
                        l2 = l3;
                        i3 |= 128;
                        Unit unit9 = Unit.INSTANCE;
                        str14 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 7, StringSerializer.INSTANCE, str24);
                        str19 = str33;
                        num21 = num21;
                        jsonObject6 = jsonObject8;
                        str10 = str20;
                        num10 = num24;
                        str11 = str21;
                        str12 = str22;
                        num11 = num25;
                        str13 = str23;
                        break;
                    case 8:
                        lazyArr2 = lazyArr;
                        String str34 = str19;
                        calendarRemindModel2 = calendarRemindModel4;
                        num12 = num26;
                        str15 = str25;
                        num13 = num27;
                        bool4 = bool10;
                        num14 = num28;
                        priceDescVO2 = priceDescVO3;
                        i3 |= 256;
                        Unit unit10 = Unit.INSTANCE;
                        l2 = (Long) beginStructure.decodeNullableSerializableElement(serialDescriptor, 8, LongSerializer.INSTANCE, l3);
                        str19 = str34;
                        num21 = num21;
                        jsonObject6 = jsonObject8;
                        str10 = str20;
                        num10 = num24;
                        str11 = str21;
                        str12 = str22;
                        num11 = num25;
                        str13 = str23;
                        str14 = str24;
                        break;
                    case ConstantsKt.SPACER_9 /* 9 */:
                        lazyArr2 = lazyArr;
                        String str35 = str19;
                        num12 = num26;
                        str15 = str25;
                        num13 = num27;
                        bool4 = bool10;
                        num14 = num28;
                        calendarRemindModel2 = calendarRemindModel4;
                        i3 |= 512;
                        Unit unit11 = Unit.INSTANCE;
                        priceDescVO2 = (PriceDescVO) beginStructure.decodeNullableSerializableElement(serialDescriptor, 9, PriceDescVO$$serializer.INSTANCE, priceDescVO3);
                        str19 = str35;
                        num21 = num21;
                        jsonObject6 = jsonObject8;
                        str10 = str20;
                        num10 = num24;
                        str11 = str21;
                        str12 = str22;
                        num11 = num25;
                        str13 = str23;
                        str14 = str24;
                        l2 = l3;
                        break;
                    case 10:
                        lazyArr2 = lazyArr;
                        String str36 = str19;
                        str15 = str25;
                        num13 = num27;
                        bool4 = bool10;
                        num14 = num28;
                        num12 = num26;
                        i3 |= 1024;
                        Unit unit12 = Unit.INSTANCE;
                        calendarRemindModel2 = (CalendarRemindModel) beginStructure.decodeNullableSerializableElement(serialDescriptor, 10, CalendarRemindModel$$serializer.INSTANCE, calendarRemindModel4);
                        str19 = str36;
                        num21 = num21;
                        jsonObject6 = jsonObject8;
                        str10 = str20;
                        num10 = num24;
                        str11 = str21;
                        str12 = str22;
                        num11 = num25;
                        str13 = str23;
                        str14 = str24;
                        l2 = l3;
                        priceDescVO2 = priceDescVO3;
                        break;
                    case MediaAttrUtils.TYPE_MENU /* 11 */:
                        lazyArr2 = lazyArr;
                        String str37 = str19;
                        num13 = num27;
                        bool4 = bool10;
                        num14 = num28;
                        str15 = str25;
                        i3 |= 2048;
                        Unit unit13 = Unit.INSTANCE;
                        num12 = (Integer) beginStructure.decodeNullableSerializableElement(serialDescriptor, 11, IntSerializer.INSTANCE, num26);
                        str19 = str37;
                        num21 = num21;
                        jsonObject6 = jsonObject8;
                        str10 = str20;
                        num10 = num24;
                        str11 = str21;
                        str12 = str22;
                        num11 = num25;
                        str13 = str23;
                        str14 = str24;
                        l2 = l3;
                        priceDescVO2 = priceDescVO3;
                        calendarRemindModel2 = calendarRemindModel4;
                        break;
                    case 12:
                        lazyArr2 = lazyArr;
                        String str38 = str19;
                        bool4 = bool10;
                        num14 = num28;
                        num13 = num27;
                        i3 |= 4096;
                        Unit unit14 = Unit.INSTANCE;
                        str15 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 12, StringSerializer.INSTANCE, str25);
                        str19 = str38;
                        num21 = num21;
                        jsonObject6 = jsonObject8;
                        str10 = str20;
                        num10 = num24;
                        str11 = str21;
                        str12 = str22;
                        num11 = num25;
                        str13 = str23;
                        str14 = str24;
                        l2 = l3;
                        priceDescVO2 = priceDescVO3;
                        calendarRemindModel2 = calendarRemindModel4;
                        num12 = num26;
                        break;
                    case 13:
                        lazyArr2 = lazyArr;
                        String str39 = str19;
                        num14 = num28;
                        bool4 = bool10;
                        i3 |= 8192;
                        Unit unit15 = Unit.INSTANCE;
                        num13 = (Integer) beginStructure.decodeNullableSerializableElement(serialDescriptor, 13, IntSerializer.INSTANCE, num27);
                        str19 = str39;
                        num21 = num21;
                        jsonObject6 = jsonObject8;
                        str10 = str20;
                        num10 = num24;
                        str11 = str21;
                        str12 = str22;
                        num11 = num25;
                        str13 = str23;
                        str14 = str24;
                        l2 = l3;
                        priceDescVO2 = priceDescVO3;
                        calendarRemindModel2 = calendarRemindModel4;
                        num12 = num26;
                        str15 = str25;
                        break;
                    case ConstantsKt.SPACER_14 /* 14 */:
                        lazyArr2 = lazyArr;
                        String str40 = str19;
                        num14 = num28;
                        i3 |= 16384;
                        Unit unit16 = Unit.INSTANCE;
                        bool4 = (Boolean) beginStructure.decodeNullableSerializableElement(serialDescriptor, 14, BooleanSerializer.INSTANCE, bool10);
                        str19 = str40;
                        num21 = num21;
                        jsonObject6 = jsonObject8;
                        str10 = str20;
                        num10 = num24;
                        str11 = str21;
                        str12 = str22;
                        num11 = num25;
                        str13 = str23;
                        str14 = str24;
                        l2 = l3;
                        priceDescVO2 = priceDescVO3;
                        calendarRemindModel2 = calendarRemindModel4;
                        num12 = num26;
                        str15 = str25;
                        num13 = num27;
                        break;
                    case 15:
                        lazyArr2 = lazyArr;
                        String str41 = str19;
                        i3 |= 32768;
                        Unit unit17 = Unit.INSTANCE;
                        num14 = (Integer) beginStructure.decodeNullableSerializableElement(serialDescriptor, 15, IntSerializer.INSTANCE, num28);
                        str19 = str41;
                        num21 = num21;
                        jsonObject6 = jsonObject8;
                        str10 = str20;
                        num10 = num24;
                        str11 = str21;
                        str12 = str22;
                        num11 = num25;
                        str13 = str23;
                        str14 = str24;
                        l2 = l3;
                        priceDescVO2 = priceDescVO3;
                        calendarRemindModel2 = calendarRemindModel4;
                        num12 = num26;
                        str15 = str25;
                        num13 = num27;
                        bool4 = bool10;
                        break;
                    case 16:
                        String str42 = str19;
                        lazyArr2 = lazyArr;
                        i3 |= 65536;
                        Unit unit18 = Unit.INSTANCE;
                        str19 = str42;
                        str10 = str20;
                        num10 = num24;
                        str11 = str21;
                        str12 = str22;
                        num11 = num25;
                        str13 = str23;
                        str14 = str24;
                        l2 = l3;
                        priceDescVO2 = priceDescVO3;
                        calendarRemindModel2 = calendarRemindModel4;
                        num12 = num26;
                        str15 = str25;
                        num13 = num27;
                        bool4 = bool10;
                        num14 = num28;
                        jsonObject6 = (JsonObject) beginStructure.decodeNullableSerializableElement(serialDescriptor, 16, JsonObjectSerializer.INSTANCE, jsonObject8);
                        num21 = num21;
                        break;
                    case 17:
                        str19 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 17, StringSerializer.INSTANCE, str19);
                        i3 |= 131072;
                        Unit unit19 = Unit.INSTANCE;
                        lazyArr2 = lazyArr;
                        num21 = num21;
                        str10 = str20;
                        num10 = num24;
                        str11 = str21;
                        str12 = str22;
                        num11 = num25;
                        str13 = str23;
                        str14 = str24;
                        l2 = l3;
                        priceDescVO2 = priceDescVO3;
                        calendarRemindModel2 = calendarRemindModel4;
                        num12 = num26;
                        str15 = str25;
                        num13 = num27;
                        bool4 = bool10;
                        num14 = num28;
                        jsonObject6 = jsonObject8;
                        break;
                    case 18:
                        str16 = str19;
                        i3 |= 262144;
                        Unit unit20 = Unit.INSTANCE;
                        lazyArr2 = lazyArr;
                        num22 = (Integer) beginStructure.decodeNullableSerializableElement(serialDescriptor, 18, IntSerializer.INSTANCE, num22);
                        str10 = str20;
                        num10 = num24;
                        str11 = str21;
                        str12 = str22;
                        num11 = num25;
                        str13 = str23;
                        str14 = str24;
                        l2 = l3;
                        priceDescVO2 = priceDescVO3;
                        calendarRemindModel2 = calendarRemindModel4;
                        num12 = num26;
                        str15 = str25;
                        num13 = num27;
                        bool4 = bool10;
                        num14 = num28;
                        jsonObject6 = jsonObject8;
                        str19 = str16;
                        break;
                    case 19:
                        str16 = str19;
                        i3 |= 524288;
                        Unit unit21 = Unit.INSTANCE;
                        lazyArr2 = lazyArr;
                        num23 = (Integer) beginStructure.decodeNullableSerializableElement(serialDescriptor, 19, IntSerializer.INSTANCE, num23);
                        str10 = str20;
                        num10 = num24;
                        str11 = str21;
                        str12 = str22;
                        num11 = num25;
                        str13 = str23;
                        str14 = str24;
                        l2 = l3;
                        priceDescVO2 = priceDescVO3;
                        calendarRemindModel2 = calendarRemindModel4;
                        num12 = num26;
                        str15 = str25;
                        num13 = num27;
                        bool4 = bool10;
                        num14 = num28;
                        jsonObject6 = jsonObject8;
                        str19 = str16;
                        break;
                    case 20:
                        str16 = str19;
                        i3 |= 1048576;
                        Unit unit22 = Unit.INSTANCE;
                        lazyArr2 = lazyArr;
                        bool9 = (Boolean) beginStructure.decodeNullableSerializableElement(serialDescriptor, 20, BooleanSerializer.INSTANCE, bool9);
                        str10 = str20;
                        num10 = num24;
                        str11 = str21;
                        str12 = str22;
                        num11 = num25;
                        str13 = str23;
                        str14 = str24;
                        l2 = l3;
                        priceDescVO2 = priceDescVO3;
                        calendarRemindModel2 = calendarRemindModel4;
                        num12 = num26;
                        str15 = str25;
                        num13 = num27;
                        bool4 = bool10;
                        num14 = num28;
                        jsonObject6 = jsonObject8;
                        str19 = str16;
                        break;
                    case 21:
                        str16 = str19;
                        i3 |= 2097152;
                        Unit unit23 = Unit.INSTANCE;
                        lazyArr2 = lazyArr;
                        bool8 = (Boolean) beginStructure.decodeNullableSerializableElement(serialDescriptor, 21, BooleanSerializer.INSTANCE, bool8);
                        str10 = str20;
                        num10 = num24;
                        str11 = str21;
                        str12 = str22;
                        num11 = num25;
                        str13 = str23;
                        str14 = str24;
                        l2 = l3;
                        priceDescVO2 = priceDescVO3;
                        calendarRemindModel2 = calendarRemindModel4;
                        num12 = num26;
                        str15 = str25;
                        num13 = num27;
                        bool4 = bool10;
                        num14 = num28;
                        jsonObject6 = jsonObject8;
                        str19 = str16;
                        break;
                    case 22:
                        str16 = str19;
                        list7 = (List) beginStructure.decodeNullableSerializableElement(serialDescriptor, 22, (DeserializationStrategy) lazyArr[22].getValue(), list7);
                        i2 = 4194304;
                        i3 |= i2;
                        Unit unit24 = Unit.INSTANCE;
                        lazyArr2 = lazyArr;
                        str10 = str20;
                        num10 = num24;
                        str11 = str21;
                        str12 = str22;
                        num11 = num25;
                        str13 = str23;
                        str14 = str24;
                        l2 = l3;
                        priceDescVO2 = priceDescVO3;
                        calendarRemindModel2 = calendarRemindModel4;
                        num12 = num26;
                        str15 = str25;
                        num13 = num27;
                        bool4 = bool10;
                        num14 = num28;
                        jsonObject6 = jsonObject8;
                        str19 = str16;
                        break;
                    case 23:
                        str16 = str19;
                        i3 |= 8388608;
                        Unit unit25 = Unit.INSTANCE;
                        lazyArr2 = lazyArr;
                        jsonObject7 = (JsonObject) beginStructure.decodeNullableSerializableElement(serialDescriptor, 23, JsonObjectSerializer.INSTANCE, jsonObject7);
                        str10 = str20;
                        num10 = num24;
                        str11 = str21;
                        str12 = str22;
                        num11 = num25;
                        str13 = str23;
                        str14 = str24;
                        l2 = l3;
                        priceDescVO2 = priceDescVO3;
                        calendarRemindModel2 = calendarRemindModel4;
                        num12 = num26;
                        str15 = str25;
                        num13 = num27;
                        bool4 = bool10;
                        num14 = num28;
                        jsonObject6 = jsonObject8;
                        str19 = str16;
                        break;
                    case 24:
                        str16 = str19;
                        num21 = (Integer) beginStructure.decodeNullableSerializableElement(serialDescriptor, 24, IntSerializer.INSTANCE, num21);
                        i3 |= 16777216;
                        Unit unit26 = Unit.INSTANCE;
                        lazyArr2 = lazyArr;
                        str10 = str20;
                        num10 = num24;
                        str11 = str21;
                        str12 = str22;
                        num11 = num25;
                        str13 = str23;
                        str14 = str24;
                        l2 = l3;
                        priceDescVO2 = priceDescVO3;
                        calendarRemindModel2 = calendarRemindModel4;
                        num12 = num26;
                        str15 = str25;
                        num13 = num27;
                        bool4 = bool10;
                        num14 = num28;
                        jsonObject6 = jsonObject8;
                        str19 = str16;
                        break;
                    case 25:
                        str16 = str19;
                        list6 = (List) beginStructure.decodeNullableSerializableElement(serialDescriptor, 25, (DeserializationStrategy) lazyArr[25].getValue(), list6);
                        i2 = 33554432;
                        i3 |= i2;
                        Unit unit242 = Unit.INSTANCE;
                        lazyArr2 = lazyArr;
                        str10 = str20;
                        num10 = num24;
                        str11 = str21;
                        str12 = str22;
                        num11 = num25;
                        str13 = str23;
                        str14 = str24;
                        l2 = l3;
                        priceDescVO2 = priceDescVO3;
                        calendarRemindModel2 = calendarRemindModel4;
                        num12 = num26;
                        str15 = str25;
                        num13 = num27;
                        bool4 = bool10;
                        num14 = num28;
                        jsonObject6 = jsonObject8;
                        str19 = str16;
                        break;
                    case 26:
                        str16 = str19;
                        i3 |= 67108864;
                        Unit unit27 = Unit.INSTANCE;
                        lazyArr2 = lazyArr;
                        str26 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 26, StringSerializer.INSTANCE, str26);
                        str10 = str20;
                        num10 = num24;
                        str11 = str21;
                        str12 = str22;
                        num11 = num25;
                        str13 = str23;
                        str14 = str24;
                        l2 = l3;
                        priceDescVO2 = priceDescVO3;
                        calendarRemindModel2 = calendarRemindModel4;
                        num12 = num26;
                        str15 = str25;
                        num13 = num27;
                        bool4 = bool10;
                        num14 = num28;
                        jsonObject6 = jsonObject8;
                        str19 = str16;
                        break;
                    case 27:
                        str16 = str19;
                        i3 |= 134217728;
                        Unit unit28 = Unit.INSTANCE;
                        lazyArr2 = lazyArr;
                        list8 = (List) beginStructure.decodeNullableSerializableElement(serialDescriptor, 27, (DeserializationStrategy) lazyArr[27].getValue(), list8);
                        str10 = str20;
                        num10 = num24;
                        str11 = str21;
                        str12 = str22;
                        num11 = num25;
                        str13 = str23;
                        str14 = str24;
                        l2 = l3;
                        priceDescVO2 = priceDescVO3;
                        calendarRemindModel2 = calendarRemindModel4;
                        num12 = num26;
                        str15 = str25;
                        num13 = num27;
                        bool4 = bool10;
                        num14 = num28;
                        jsonObject6 = jsonObject8;
                        str19 = str16;
                        break;
                    default:
                        throw new UnknownFieldException(decodeElementIndex);
                }
                lazyArr = lazyArr2;
                num28 = num14;
                bool10 = bool4;
                num27 = num13;
                str25 = str15;
                num26 = num12;
                str20 = str10;
                num24 = num10;
                str21 = str11;
                str22 = str12;
                num25 = num11;
                str23 = str13;
                str24 = str14;
                l3 = l2;
                priceDescVO3 = priceDescVO2;
                calendarRemindModel4 = calendarRemindModel2;
            }
            Integer num29 = num21;
            CountDownInfoVO countDownInfoVO3 = countDownInfoVO2;
            String str43 = str20;
            list = list8;
            str = str26;
            i = i3;
            num = num27;
            str2 = str25;
            num2 = num26;
            str3 = str24;
            calendarRemindModel = calendarRemindModel4;
            countDownInfoVO = countDownInfoVO3;
            list2 = list6;
            list3 = list7;
            num3 = num28;
            bool = bool10;
            l = l3;
            priceDescVO = priceDescVO3;
            jsonObject = jsonObject7;
            num4 = num29;
            str4 = str43;
            num5 = num25;
            bool2 = bool9;
            jsonObject2 = jsonObject6;
            str5 = str21;
            str6 = str23;
            num6 = num22;
            bool3 = bool8;
            num7 = num24;
            str7 = str19;
            num8 = num23;
            str8 = str22;
        }
        beginStructure.endStructure(serialDescriptor);
        return new FooterFloor.PurchaseButton(i, countDownInfoVO, str4, num7, str5, str8, num5, str6, str3, l, priceDescVO, calendarRemindModel, num2, str2, num, bool, num3, jsonObject2, str7, num6, num8, bool2, bool3, list3, jsonObject, num4, list2, str, list, (SerializationConstructorMarker) null);
    }

    public final void serialize(Encoder encoder, FooterFloor.PurchaseButton value) {
        Intrinsics.checkNotNullParameter(encoder, "encoder");
        Intrinsics.checkNotNullParameter(value, "value");
        SerialDescriptor serialDescriptor = descriptor;
        CompositeEncoder beginStructure = encoder.beginStructure(serialDescriptor);
        FooterFloor.PurchaseButton.write$Self$product_details_page_debug(value, beginStructure, serialDescriptor);
        beginStructure.endStructure(serialDescriptor);
    }

    public /* bridge */ KSerializer<?>[] typeParametersSerializers() {
        return GeneratedSerializer.DefaultImpls.typeParametersSerializers(this);
    }
}