package kntr.app.mall.product.details.page.api.model;

import com.bapis.bilibili.app.dynamic.v2.AdditionalButton;
import kntr.app.upcomingEpisode.ConstantsKt;
import kntr.watch.later.watchlater.edit.MediaAttrUtils;
import kotlin.Deprecated;
import kotlin.DeprecationLevel;
import kotlin.Metadata;
import kotlin.Unit;
import kotlin.jvm.internal.Intrinsics;
import kotlinx.serialization.KSerializer;
import kotlinx.serialization.UnknownFieldException;
import kotlinx.serialization.builtins.BuiltinSerializersKt;
import kotlinx.serialization.descriptors.SerialDescriptor;
import kotlinx.serialization.encoding.CompositeDecoder;
import kotlinx.serialization.encoding.CompositeEncoder;
import kotlinx.serialization.encoding.Decoder;
import kotlinx.serialization.encoding.Encoder;
import kotlinx.serialization.internal.DoubleSerializer;
import kotlinx.serialization.internal.GeneratedSerializer;
import kotlinx.serialization.internal.IntSerializer;
import kotlinx.serialization.internal.PluginGeneratedSerialDescriptor;
import kotlinx.serialization.internal.SerializationConstructorMarker;
import kotlinx.serialization.internal.StringSerializer;

/* compiled from: LabelObject.kt */
@Metadata(d1 = {"\u00006\n\u0000\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\b\u0003\n\u0002\u0010\u0011\n\u0002\u0018\u0002\n\u0002\b\u0003\n\u0002\u0018\u0002\n\u0000\n\u0002\u0010\u0002\n\u0000\n\u0002\u0018\u0002\n\u0002\b\u0002\n\u0002\u0018\u0002\n\u0002\b\u0003\bÇ\u0002\u0018\u00002\b\u0012\u0004\u0012\u00020\u00020\u0001B\t\b\u0002¢\u0006\u0004\b\u0003\u0010\u0004J\u0015\u0010\u0005\u001a\f\u0012\b\u0012\u0006\u0012\u0002\b\u00030\u00070\u0006¢\u0006\u0002\u0010\bJ\u000e\u0010\t\u001a\u00020\u00022\u0006\u0010\n\u001a\u00020\u000bJ\u0016\u0010\f\u001a\u00020\r2\u0006\u0010\u000e\u001a\u00020\u000f2\u0006\u0010\u0010\u001a\u00020\u0002R\u0011\u0010\u0011\u001a\u00020\u0012¢\u0006\b\n\u0000\u001a\u0004\b\u0013\u0010\u0014¨\u0006\u0015"}, d2 = {"kntr/app/mall/product/details/page/api/model/LabelObject.$serializer", "Lkotlinx/serialization/internal/GeneratedSerializer;", "Lkntr/app/mall/product/details/page/api/model/LabelObject;", "<init>", "()V", "childSerializers", "", "Lkotlinx/serialization/KSerializer;", "()[Lkotlinx/serialization/KSerializer;", "deserialize", "decoder", "Lkotlinx/serialization/encoding/Decoder;", "serialize", "", "encoder", "Lkotlinx/serialization/encoding/Encoder;", "value", "descriptor", "Lkotlinx/serialization/descriptors/SerialDescriptor;", "getDescriptor", "()Lkotlinx/serialization/descriptors/SerialDescriptor;", "product-details-page_debug"}, k = 1, mv = {2, 2, 0}, xi = ConstantsKt.OGV_UPDATE_CALENDAR_CARD_COVER_WIDTH)
@Deprecated(level = DeprecationLevel.HIDDEN, message = "This synthesized declaration should not be used directly")
public final /* synthetic */ class LabelObject$$serializer implements GeneratedSerializer<LabelObject> {
    public static final int $stable;
    public static final LabelObject$$serializer INSTANCE = new LabelObject$$serializer();
    private static final SerialDescriptor descriptor;

    public final SerialDescriptor getDescriptor() {
        return descriptor;
    }

    static {
        SerialDescriptor pluginGeneratedSerialDescriptor = new PluginGeneratedSerialDescriptor("kntr.app.mall.product.details.page.api.model.LabelObject", INSTANCE, 35);
        pluginGeneratedSerialDescriptor.addElement("rightIconImgUrl", true);
        pluginGeneratedSerialDescriptor.addElement("rightIconNightImgUrl", true);
        pluginGeneratedSerialDescriptor.addElement("rightIconImgWidth", true);
        pluginGeneratedSerialDescriptor.addElement("rightIconImgHeight", true);
        pluginGeneratedSerialDescriptor.addElement("backDayColor1", true);
        pluginGeneratedSerialDescriptor.addElement("backDayColor2", true);
        pluginGeneratedSerialDescriptor.addElement("backImgHeight", true);
        pluginGeneratedSerialDescriptor.addElement("backImgUrl", true);
        pluginGeneratedSerialDescriptor.addElement("backImgWidth", true);
        pluginGeneratedSerialDescriptor.addElement("backNightColor1", true);
        pluginGeneratedSerialDescriptor.addElement("backNightColor2", true);
        pluginGeneratedSerialDescriptor.addElement("backNightImgUrl", true);
        pluginGeneratedSerialDescriptor.addElement("boardDayColor1", true);
        pluginGeneratedSerialDescriptor.addElement("boardDayColor2", true);
        pluginGeneratedSerialDescriptor.addElement("boardNightColor1", true);
        pluginGeneratedSerialDescriptor.addElement("boardNightColor2", true);
        pluginGeneratedSerialDescriptor.addElement("cornerRadius", true);
        pluginGeneratedSerialDescriptor.addElement("tagType", true);
        pluginGeneratedSerialDescriptor.addElement("title", true);
        pluginGeneratedSerialDescriptor.addElement("titleDayColor1", true);
        pluginGeneratedSerialDescriptor.addElement("titleDayColor2", true);
        pluginGeneratedSerialDescriptor.addElement("titleNightColor1", true);
        pluginGeneratedSerialDescriptor.addElement("titleNightColor2", true);
        pluginGeneratedSerialDescriptor.addElement("useBoard", true);
        pluginGeneratedSerialDescriptor.addElement("backImgUrlDay", true);
        pluginGeneratedSerialDescriptor.addElement("backImgUrlNight", true);
        pluginGeneratedSerialDescriptor.addElement("location", true);
        pluginGeneratedSerialDescriptor.addElement("priority", true);
        pluginGeneratedSerialDescriptor.addElement("tagId", true);
        pluginGeneratedSerialDescriptor.addElement("tagVersion", true);
        pluginGeneratedSerialDescriptor.addElement("actionType", true);
        pluginGeneratedSerialDescriptor.addElement("targetUrl", true);
        pluginGeneratedSerialDescriptor.addElement("showImgUrl", true);
        pluginGeneratedSerialDescriptor.addElement("showImgUrlHeight", true);
        pluginGeneratedSerialDescriptor.addElement("showImgUrlWidth", true);
        descriptor = pluginGeneratedSerialDescriptor;
        $stable = 8;
    }

    private LabelObject$$serializer() {
    }

    public final KSerializer<?>[] childSerializers() {
        return new KSerializer[]{BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(DoubleSerializer.INSTANCE), BuiltinSerializersKt.getNullable(DoubleSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(DoubleSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(DoubleSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(IntSerializer.INSTANCE), BuiltinSerializersKt.getNullable(IntSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(IntSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(IntSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(IntSerializer.INSTANCE), BuiltinSerializersKt.getNullable(IntSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(DoubleSerializer.INSTANCE), BuiltinSerializersKt.getNullable(DoubleSerializer.INSTANCE)};
    }

    public final LabelObject deserialize(Decoder decoder) {
        String str;
        String str2;
        String str3;
        Double d;
        String str4;
        Integer num;
        Integer num2;
        String str5;
        String str6;
        String str7;
        Double d2;
        String str8;
        Integer num3;
        String str9;
        int i;
        String str10;
        Integer num4;
        String str11;
        int i2;
        String str12;
        String str13;
        Double d3;
        String str14;
        Integer num5;
        Double d4;
        String str15;
        Integer num6;
        Double d5;
        String str16;
        String str17;
        String str18;
        String str19;
        String str20;
        String str21;
        String str22;
        String str23;
        Double d6;
        String str24;
        Integer num7;
        Integer num8;
        String str25;
        Double d7;
        Double d8;
        String str26;
        String str27;
        Double d9;
        String str28;
        Double d10;
        String str29;
        String str30;
        String str31;
        String str32;
        String str33;
        String str34;
        String str35;
        Integer num9;
        Integer num10;
        String str36;
        String str37;
        String str38;
        Integer num11;
        String str39;
        String str40;
        Integer num12;
        Integer num13;
        int i3;
        Intrinsics.checkNotNullParameter(decoder, "decoder");
        SerialDescriptor serialDescriptor = descriptor;
        CompositeDecoder beginStructure = decoder.beginStructure(serialDescriptor);
        if (beginStructure.decodeSequentially()) {
            String str41 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 11, StringSerializer.INSTANCE, (Object) null);
            String str42 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 12, StringSerializer.INSTANCE, (Object) null);
            String str43 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 13, StringSerializer.INSTANCE, (Object) null);
            String str44 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 14, StringSerializer.INSTANCE, (Object) null);
            String str45 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 15, StringSerializer.INSTANCE, (Object) null);
            Integer num14 = (Integer) beginStructure.decodeNullableSerializableElement(serialDescriptor, 16, IntSerializer.INSTANCE, (Object) null);
            Integer num15 = (Integer) beginStructure.decodeNullableSerializableElement(serialDescriptor, 17, IntSerializer.INSTANCE, (Object) null);
            String str46 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 18, StringSerializer.INSTANCE, (Object) null);
            String str47 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 19, StringSerializer.INSTANCE, (Object) null);
            String str48 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 20, StringSerializer.INSTANCE, (Object) null);
            String str49 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 21, StringSerializer.INSTANCE, (Object) null);
            String str50 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 22, StringSerializer.INSTANCE, (Object) null);
            Integer num16 = (Integer) beginStructure.decodeNullableSerializableElement(serialDescriptor, 23, IntSerializer.INSTANCE, (Object) null);
            String str51 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 24, StringSerializer.INSTANCE, (Object) null);
            String str52 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 25, StringSerializer.INSTANCE, (Object) null);
            String str53 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 26, StringSerializer.INSTANCE, (Object) null);
            Integer num17 = (Integer) beginStructure.decodeNullableSerializableElement(serialDescriptor, 27, IntSerializer.INSTANCE, (Object) null);
            String str54 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 28, StringSerializer.INSTANCE, (Object) null);
            Integer num18 = (Integer) beginStructure.decodeNullableSerializableElement(serialDescriptor, 29, IntSerializer.INSTANCE, (Object) null);
            Integer num19 = (Integer) beginStructure.decodeNullableSerializableElement(serialDescriptor, 30, IntSerializer.INSTANCE, (Object) null);
            String str55 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 31, StringSerializer.INSTANCE, (Object) null);
            String str56 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 32, StringSerializer.INSTANCE, (Object) null);
            Double d11 = (Double) beginStructure.decodeNullableSerializableElement(serialDescriptor, 33, DoubleSerializer.INSTANCE, (Object) null);
            d2 = (Double) beginStructure.decodeNullableSerializableElement(serialDescriptor, 34, DoubleSerializer.INSTANCE, (Object) null);
            str14 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 9, StringSerializer.INSTANCE, (Object) null);
            str2 = str56;
            str10 = str50;
            num4 = num16;
            str6 = str51;
            str5 = str52;
            str11 = str53;
            num3 = num17;
            str3 = str54;
            num2 = num18;
            num = num19;
            str4 = str55;
            d = d11;
            str = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 0, StringSerializer.INSTANCE, (Object) null);
            str7 = str47;
            str12 = str46;
            num6 = num15;
            num5 = num14;
            str17 = str45;
            str21 = str44;
            str23 = str43;
            str19 = str42;
            str15 = str41;
            str8 = str48;
            str9 = str49;
            i = 7;
            d4 = (Double) beginStructure.decodeNullableSerializableElement(serialDescriptor, 3, DoubleSerializer.INSTANCE, (Object) null);
            d3 = (Double) beginStructure.decodeNullableSerializableElement(serialDescriptor, 8, DoubleSerializer.INSTANCE, (Object) null);
            str18 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 4, StringSerializer.INSTANCE, (Object) null);
            d5 = (Double) beginStructure.decodeNullableSerializableElement(serialDescriptor, 2, DoubleSerializer.INSTANCE, (Object) null);
            str13 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 1, StringSerializer.INSTANCE, (Object) null);
            str22 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 5, StringSerializer.INSTANCE, (Object) null);
            i2 = -1;
            str16 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 10, StringSerializer.INSTANCE, (Object) null);
            d6 = (Double) beginStructure.decodeNullableSerializableElement(serialDescriptor, 6, DoubleSerializer.INSTANCE, (Object) null);
            str20 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 7, StringSerializer.INSTANCE, (Object) null);
        } else {
            boolean z = true;
            int i4 = 0;
            String str57 = null;
            Integer num20 = null;
            String str58 = null;
            String str59 = null;
            Integer num21 = null;
            Double d12 = null;
            String str60 = null;
            Integer num22 = null;
            String str61 = null;
            String str62 = null;
            String str63 = null;
            Double d13 = null;
            String str64 = null;
            String str65 = null;
            Double d14 = null;
            Double d15 = null;
            String str66 = null;
            String str67 = null;
            Double d16 = null;
            String str68 = null;
            Double d17 = null;
            String str69 = null;
            String str70 = null;
            String str71 = null;
            String str72 = null;
            String str73 = null;
            String str74 = null;
            String str75 = null;
            Integer num23 = null;
            Integer num24 = null;
            String str76 = null;
            String str77 = null;
            String str78 = null;
            String str79 = null;
            Integer num25 = null;
            int i5 = 0;
            while (z) {
                String str80 = str63;
                int decodeElementIndex = beginStructure.decodeElementIndex(serialDescriptor);
                switch (decodeElementIndex) {
                    case -1:
                        str24 = str57;
                        num7 = num20;
                        num8 = num21;
                        str25 = str65;
                        d7 = d14;
                        d8 = d15;
                        str26 = str66;
                        str27 = str67;
                        d9 = d16;
                        str28 = str68;
                        d10 = d17;
                        str29 = str69;
                        str30 = str70;
                        str31 = str71;
                        str32 = str72;
                        str33 = str73;
                        str34 = str74;
                        str35 = str75;
                        num9 = num23;
                        num10 = num24;
                        str36 = str76;
                        str37 = str77;
                        Unit unit = Unit.INSTANCE;
                        z = false;
                        num21 = num8;
                        str57 = str24;
                        str39 = str37;
                        str63 = str80;
                        break;
                    case 0:
                        str24 = str57;
                        num7 = num20;
                        num8 = num21;
                        d7 = d14;
                        d8 = d15;
                        str26 = str66;
                        str27 = str67;
                        d9 = d16;
                        str28 = str68;
                        d10 = d17;
                        str29 = str69;
                        str30 = str70;
                        str31 = str71;
                        str32 = str72;
                        str33 = str73;
                        str34 = str74;
                        str35 = str75;
                        num9 = num23;
                        num10 = num24;
                        str36 = str76;
                        str37 = str77;
                        str25 = str65;
                        i5 |= 1;
                        Unit unit2 = Unit.INSTANCE;
                        str64 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 0, StringSerializer.INSTANCE, str64);
                        num21 = num8;
                        str57 = str24;
                        str39 = str37;
                        str63 = str80;
                        break;
                    case 1:
                        str38 = str57;
                        num7 = num20;
                        num11 = num21;
                        d8 = d15;
                        str26 = str66;
                        str27 = str67;
                        d9 = d16;
                        str28 = str68;
                        d10 = d17;
                        str29 = str69;
                        str30 = str70;
                        str31 = str71;
                        str32 = str72;
                        str33 = str73;
                        str34 = str74;
                        str35 = str75;
                        num9 = num23;
                        num10 = num24;
                        str36 = str76;
                        str37 = str77;
                        d7 = d14;
                        i5 |= 2;
                        Unit unit3 = Unit.INSTANCE;
                        str25 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 1, StringSerializer.INSTANCE, str65);
                        num21 = num11;
                        str57 = str38;
                        str39 = str37;
                        str63 = str80;
                        break;
                    case 2:
                        str38 = str57;
                        num7 = num20;
                        num11 = num21;
                        str26 = str66;
                        str27 = str67;
                        d9 = d16;
                        str28 = str68;
                        d10 = d17;
                        str29 = str69;
                        str30 = str70;
                        str31 = str71;
                        str32 = str72;
                        str33 = str73;
                        str34 = str74;
                        str35 = str75;
                        num9 = num23;
                        num10 = num24;
                        str36 = str76;
                        str37 = str77;
                        d8 = d15;
                        i5 |= 4;
                        Unit unit4 = Unit.INSTANCE;
                        d7 = (Double) beginStructure.decodeNullableSerializableElement(serialDescriptor, 2, DoubleSerializer.INSTANCE, d14);
                        str25 = str65;
                        num21 = num11;
                        str57 = str38;
                        str39 = str37;
                        str63 = str80;
                        break;
                    case 3:
                        str38 = str57;
                        num7 = num20;
                        num11 = num21;
                        str27 = str67;
                        d9 = d16;
                        str28 = str68;
                        d10 = d17;
                        str29 = str69;
                        str30 = str70;
                        str31 = str71;
                        str32 = str72;
                        str33 = str73;
                        str34 = str74;
                        str35 = str75;
                        num9 = num23;
                        num10 = num24;
                        str36 = str76;
                        str37 = str77;
                        str26 = str66;
                        i5 |= 8;
                        Unit unit5 = Unit.INSTANCE;
                        d8 = (Double) beginStructure.decodeNullableSerializableElement(serialDescriptor, 3, DoubleSerializer.INSTANCE, d15);
                        str25 = str65;
                        d7 = d14;
                        num21 = num11;
                        str57 = str38;
                        str39 = str37;
                        str63 = str80;
                        break;
                    case 4:
                        str38 = str57;
                        num7 = num20;
                        num11 = num21;
                        d9 = d16;
                        str28 = str68;
                        d10 = d17;
                        str29 = str69;
                        str30 = str70;
                        str31 = str71;
                        str32 = str72;
                        str33 = str73;
                        str34 = str74;
                        str35 = str75;
                        num9 = num23;
                        num10 = num24;
                        str36 = str76;
                        str37 = str77;
                        str27 = str67;
                        i5 |= 16;
                        Unit unit6 = Unit.INSTANCE;
                        str26 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 4, StringSerializer.INSTANCE, str66);
                        str25 = str65;
                        d7 = d14;
                        d8 = d15;
                        num21 = num11;
                        str57 = str38;
                        str39 = str37;
                        str63 = str80;
                        break;
                    case 5:
                        str38 = str57;
                        num7 = num20;
                        num11 = num21;
                        str28 = str68;
                        d10 = d17;
                        str29 = str69;
                        str30 = str70;
                        str31 = str71;
                        str32 = str72;
                        str33 = str73;
                        str34 = str74;
                        str35 = str75;
                        num9 = num23;
                        num10 = num24;
                        str36 = str76;
                        str37 = str77;
                        d9 = d16;
                        i5 |= 32;
                        Unit unit7 = Unit.INSTANCE;
                        str27 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 5, StringSerializer.INSTANCE, str67);
                        str25 = str65;
                        d7 = d14;
                        d8 = d15;
                        str26 = str66;
                        num21 = num11;
                        str57 = str38;
                        str39 = str37;
                        str63 = str80;
                        break;
                    case 6:
                        str38 = str57;
                        num7 = num20;
                        num11 = num21;
                        d10 = d17;
                        str29 = str69;
                        str30 = str70;
                        str31 = str71;
                        str32 = str72;
                        str33 = str73;
                        str34 = str74;
                        str35 = str75;
                        num9 = num23;
                        num10 = num24;
                        str36 = str76;
                        str37 = str77;
                        str28 = str68;
                        i5 |= 64;
                        Unit unit8 = Unit.INSTANCE;
                        d9 = (Double) beginStructure.decodeNullableSerializableElement(serialDescriptor, 6, DoubleSerializer.INSTANCE, d16);
                        str25 = str65;
                        d7 = d14;
                        d8 = d15;
                        str26 = str66;
                        str27 = str67;
                        num21 = num11;
                        str57 = str38;
                        str39 = str37;
                        str63 = str80;
                        break;
                    case AdditionalButton.CLICK_TYPE_FIELD_NUMBER /* 7 */:
                        str38 = str57;
                        num7 = num20;
                        num11 = num21;
                        str29 = str69;
                        str30 = str70;
                        str31 = str71;
                        str32 = str72;
                        str33 = str73;
                        str34 = str74;
                        str35 = str75;
                        num9 = num23;
                        num10 = num24;
                        str36 = str76;
                        str37 = str77;
                        d10 = d17;
                        i5 |= 128;
                        Unit unit9 = Unit.INSTANCE;
                        str28 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 7, StringSerializer.INSTANCE, str68);
                        str25 = str65;
                        d7 = d14;
                        d8 = d15;
                        str26 = str66;
                        str27 = str67;
                        d9 = d16;
                        num21 = num11;
                        str57 = str38;
                        str39 = str37;
                        str63 = str80;
                        break;
                    case 8:
                        str38 = str57;
                        num7 = num20;
                        num11 = num21;
                        str30 = str70;
                        str31 = str71;
                        str32 = str72;
                        str33 = str73;
                        str34 = str74;
                        str35 = str75;
                        num9 = num23;
                        num10 = num24;
                        str36 = str76;
                        str37 = str77;
                        str29 = str69;
                        i5 |= 256;
                        Unit unit10 = Unit.INSTANCE;
                        d10 = (Double) beginStructure.decodeNullableSerializableElement(serialDescriptor, 8, DoubleSerializer.INSTANCE, d17);
                        str25 = str65;
                        d7 = d14;
                        d8 = d15;
                        str26 = str66;
                        str27 = str67;
                        d9 = d16;
                        str28 = str68;
                        num21 = num11;
                        str57 = str38;
                        str39 = str37;
                        str63 = str80;
                        break;
                    case ConstantsKt.SPACER_9 /* 9 */:
                        str38 = str57;
                        num7 = num20;
                        num11 = num21;
                        str31 = str71;
                        str32 = str72;
                        str33 = str73;
                        str34 = str74;
                        str35 = str75;
                        num9 = num23;
                        num10 = num24;
                        str36 = str76;
                        str37 = str77;
                        str30 = str70;
                        i5 |= 512;
                        Unit unit11 = Unit.INSTANCE;
                        str29 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 9, StringSerializer.INSTANCE, str69);
                        str25 = str65;
                        d7 = d14;
                        d8 = d15;
                        str26 = str66;
                        str27 = str67;
                        d9 = d16;
                        str28 = str68;
                        d10 = d17;
                        num21 = num11;
                        str57 = str38;
                        str39 = str37;
                        str63 = str80;
                        break;
                    case 10:
                        str38 = str57;
                        num7 = num20;
                        num11 = num21;
                        str32 = str72;
                        str33 = str73;
                        str34 = str74;
                        str35 = str75;
                        num9 = num23;
                        num10 = num24;
                        str36 = str76;
                        str37 = str77;
                        str31 = str71;
                        i5 |= 1024;
                        Unit unit12 = Unit.INSTANCE;
                        str30 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 10, StringSerializer.INSTANCE, str70);
                        str25 = str65;
                        d7 = d14;
                        d8 = d15;
                        str26 = str66;
                        str27 = str67;
                        d9 = d16;
                        str28 = str68;
                        d10 = d17;
                        str29 = str69;
                        num21 = num11;
                        str57 = str38;
                        str39 = str37;
                        str63 = str80;
                        break;
                    case MediaAttrUtils.TYPE_MENU /* 11 */:
                        str38 = str57;
                        num7 = num20;
                        num11 = num21;
                        str33 = str73;
                        str34 = str74;
                        str35 = str75;
                        num9 = num23;
                        num10 = num24;
                        str36 = str76;
                        str37 = str77;
                        str32 = str72;
                        i5 |= 2048;
                        Unit unit13 = Unit.INSTANCE;
                        str31 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 11, StringSerializer.INSTANCE, str71);
                        str25 = str65;
                        d7 = d14;
                        d8 = d15;
                        str26 = str66;
                        str27 = str67;
                        d9 = d16;
                        str28 = str68;
                        d10 = d17;
                        str29 = str69;
                        str30 = str70;
                        num21 = num11;
                        str57 = str38;
                        str39 = str37;
                        str63 = str80;
                        break;
                    case 12:
                        str38 = str57;
                        num7 = num20;
                        num11 = num21;
                        str34 = str74;
                        str35 = str75;
                        num9 = num23;
                        num10 = num24;
                        str36 = str76;
                        str37 = str77;
                        str33 = str73;
                        i5 |= 4096;
                        Unit unit14 = Unit.INSTANCE;
                        str32 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 12, StringSerializer.INSTANCE, str72);
                        str25 = str65;
                        d7 = d14;
                        d8 = d15;
                        str26 = str66;
                        str27 = str67;
                        d9 = d16;
                        str28 = str68;
                        d10 = d17;
                        str29 = str69;
                        str30 = str70;
                        str31 = str71;
                        num21 = num11;
                        str57 = str38;
                        str39 = str37;
                        str63 = str80;
                        break;
                    case 13:
                        str38 = str57;
                        num7 = num20;
                        num11 = num21;
                        str35 = str75;
                        num9 = num23;
                        num10 = num24;
                        str36 = str76;
                        str37 = str77;
                        str34 = str74;
                        i5 |= 8192;
                        Unit unit15 = Unit.INSTANCE;
                        str33 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 13, StringSerializer.INSTANCE, str73);
                        str25 = str65;
                        d7 = d14;
                        d8 = d15;
                        str26 = str66;
                        str27 = str67;
                        d9 = d16;
                        str28 = str68;
                        d10 = d17;
                        str29 = str69;
                        str30 = str70;
                        str31 = str71;
                        str32 = str72;
                        num21 = num11;
                        str57 = str38;
                        str39 = str37;
                        str63 = str80;
                        break;
                    case ConstantsKt.SPACER_14 /* 14 */:
                        str38 = str57;
                        num7 = num20;
                        num11 = num21;
                        num9 = num23;
                        num10 = num24;
                        str36 = str76;
                        str37 = str77;
                        str35 = str75;
                        i5 |= 16384;
                        Unit unit16 = Unit.INSTANCE;
                        str34 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 14, StringSerializer.INSTANCE, str74);
                        str25 = str65;
                        d7 = d14;
                        d8 = d15;
                        str26 = str66;
                        str27 = str67;
                        d9 = d16;
                        str28 = str68;
                        d10 = d17;
                        str29 = str69;
                        str30 = str70;
                        str31 = str71;
                        str32 = str72;
                        str33 = str73;
                        num21 = num11;
                        str57 = str38;
                        str39 = str37;
                        str63 = str80;
                        break;
                    case 15:
                        str38 = str57;
                        num7 = num20;
                        num11 = num21;
                        num10 = num24;
                        str36 = str76;
                        str37 = str77;
                        num9 = num23;
                        i5 |= 32768;
                        Unit unit17 = Unit.INSTANCE;
                        str35 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 15, StringSerializer.INSTANCE, str75);
                        str25 = str65;
                        d7 = d14;
                        d8 = d15;
                        str26 = str66;
                        str27 = str67;
                        d9 = d16;
                        str28 = str68;
                        d10 = d17;
                        str29 = str69;
                        str30 = str70;
                        str31 = str71;
                        str32 = str72;
                        str33 = str73;
                        str34 = str74;
                        num21 = num11;
                        str57 = str38;
                        str39 = str37;
                        str63 = str80;
                        break;
                    case 16:
                        str38 = str57;
                        num7 = num20;
                        num11 = num21;
                        str36 = str76;
                        str37 = str77;
                        num10 = num24;
                        i5 |= 65536;
                        Unit unit18 = Unit.INSTANCE;
                        num9 = (Integer) beginStructure.decodeNullableSerializableElement(serialDescriptor, 16, IntSerializer.INSTANCE, num23);
                        str25 = str65;
                        d7 = d14;
                        d8 = d15;
                        str26 = str66;
                        str27 = str67;
                        d9 = d16;
                        str28 = str68;
                        d10 = d17;
                        str29 = str69;
                        str30 = str70;
                        str31 = str71;
                        str32 = str72;
                        str33 = str73;
                        str34 = str74;
                        str35 = str75;
                        num21 = num11;
                        str57 = str38;
                        str39 = str37;
                        str63 = str80;
                        break;
                    case 17:
                        str38 = str57;
                        num7 = num20;
                        num11 = num21;
                        str37 = str77;
                        str36 = str76;
                        i5 |= 131072;
                        Unit unit19 = Unit.INSTANCE;
                        num10 = (Integer) beginStructure.decodeNullableSerializableElement(serialDescriptor, 17, IntSerializer.INSTANCE, num24);
                        str25 = str65;
                        d7 = d14;
                        d8 = d15;
                        str26 = str66;
                        str27 = str67;
                        d9 = d16;
                        str28 = str68;
                        d10 = d17;
                        str29 = str69;
                        str30 = str70;
                        str31 = str71;
                        str32 = str72;
                        str33 = str73;
                        str34 = str74;
                        str35 = str75;
                        num9 = num23;
                        num21 = num11;
                        str57 = str38;
                        str39 = str37;
                        str63 = str80;
                        break;
                    case 18:
                        str38 = str57;
                        num11 = num21;
                        str37 = str77;
                        num7 = num20;
                        i5 |= 262144;
                        Unit unit20 = Unit.INSTANCE;
                        str36 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 18, StringSerializer.INSTANCE, str76);
                        str25 = str65;
                        d7 = d14;
                        d8 = d15;
                        str26 = str66;
                        str27 = str67;
                        d9 = d16;
                        str28 = str68;
                        d10 = d17;
                        str29 = str69;
                        str30 = str70;
                        str31 = str71;
                        str32 = str72;
                        str33 = str73;
                        str34 = str74;
                        str35 = str75;
                        num9 = num23;
                        num10 = num24;
                        num21 = num11;
                        str57 = str38;
                        str39 = str37;
                        str63 = str80;
                        break;
                    case 19:
                        i5 |= 524288;
                        Unit unit21 = Unit.INSTANCE;
                        num7 = num20;
                        str78 = str78;
                        str25 = str65;
                        d7 = d14;
                        d8 = d15;
                        str26 = str66;
                        str27 = str67;
                        d9 = d16;
                        str28 = str68;
                        d10 = d17;
                        str29 = str69;
                        str30 = str70;
                        str31 = str71;
                        str32 = str72;
                        str33 = str73;
                        str34 = str74;
                        str35 = str75;
                        num9 = num23;
                        num10 = num24;
                        str36 = str76;
                        str63 = str80;
                        str57 = str57;
                        str39 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 19, StringSerializer.INSTANCE, str77);
                        num21 = num21;
                        break;
                    case 20:
                        str40 = str57;
                        num12 = num21;
                        i5 |= 1048576;
                        Unit unit22 = Unit.INSTANCE;
                        str78 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 20, StringSerializer.INSTANCE, str78);
                        num7 = num20;
                        str25 = str65;
                        d7 = d14;
                        d8 = d15;
                        str26 = str66;
                        str27 = str67;
                        d9 = d16;
                        str28 = str68;
                        d10 = d17;
                        str29 = str69;
                        str30 = str70;
                        str31 = str71;
                        str32 = str72;
                        str33 = str73;
                        str34 = str74;
                        str35 = str75;
                        num9 = num23;
                        num10 = num24;
                        str36 = str76;
                        str39 = str77;
                        str63 = str80;
                        num21 = num12;
                        str57 = str40;
                        break;
                    case 21:
                        str40 = str57;
                        num12 = num21;
                        i5 |= 2097152;
                        Unit unit23 = Unit.INSTANCE;
                        str79 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 21, StringSerializer.INSTANCE, str79);
                        num7 = num20;
                        str25 = str65;
                        d7 = d14;
                        d8 = d15;
                        str26 = str66;
                        str27 = str67;
                        d9 = d16;
                        str28 = str68;
                        d10 = d17;
                        str29 = str69;
                        str30 = str70;
                        str31 = str71;
                        str32 = str72;
                        str33 = str73;
                        str34 = str74;
                        str35 = str75;
                        num9 = num23;
                        num10 = num24;
                        str36 = str76;
                        str39 = str77;
                        str63 = str80;
                        num21 = num12;
                        str57 = str40;
                        break;
                    case 22:
                        str40 = str57;
                        num12 = num21;
                        i5 |= 4194304;
                        Unit unit24 = Unit.INSTANCE;
                        str63 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 22, StringSerializer.INSTANCE, str80);
                        num7 = num20;
                        str25 = str65;
                        d7 = d14;
                        d8 = d15;
                        str26 = str66;
                        str27 = str67;
                        d9 = d16;
                        str28 = str68;
                        d10 = d17;
                        str29 = str69;
                        str30 = str70;
                        str31 = str71;
                        str32 = str72;
                        str33 = str73;
                        str34 = str74;
                        str35 = str75;
                        num9 = num23;
                        num10 = num24;
                        str36 = str76;
                        str39 = str77;
                        num21 = num12;
                        str57 = str40;
                        break;
                    case 23:
                        Integer num26 = num21;
                        str40 = str57;
                        i5 |= 8388608;
                        Unit unit25 = Unit.INSTANCE;
                        num21 = (Integer) beginStructure.decodeNullableSerializableElement(serialDescriptor, 23, IntSerializer.INSTANCE, num26);
                        num7 = num20;
                        str25 = str65;
                        d7 = d14;
                        d8 = d15;
                        str26 = str66;
                        str27 = str67;
                        d9 = d16;
                        str28 = str68;
                        d10 = d17;
                        str29 = str69;
                        str30 = str70;
                        str31 = str71;
                        str32 = str72;
                        str33 = str73;
                        str34 = str74;
                        str35 = str75;
                        num9 = num23;
                        num10 = num24;
                        str36 = str76;
                        str39 = str77;
                        str63 = str80;
                        str57 = str40;
                        break;
                    case 24:
                        num13 = num21;
                        i5 |= 16777216;
                        Unit unit26 = Unit.INSTANCE;
                        num7 = num20;
                        str62 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 24, StringSerializer.INSTANCE, str62);
                        str25 = str65;
                        d7 = d14;
                        d8 = d15;
                        str26 = str66;
                        str27 = str67;
                        d9 = d16;
                        str28 = str68;
                        d10 = d17;
                        str29 = str69;
                        str30 = str70;
                        str31 = str71;
                        str32 = str72;
                        str33 = str73;
                        str34 = str74;
                        str35 = str75;
                        num9 = num23;
                        num10 = num24;
                        str36 = str76;
                        str39 = str77;
                        str63 = str80;
                        num21 = num13;
                        break;
                    case 25:
                        num13 = num21;
                        i5 |= 33554432;
                        Unit unit27 = Unit.INSTANCE;
                        num7 = num20;
                        str61 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 25, StringSerializer.INSTANCE, str61);
                        str25 = str65;
                        d7 = d14;
                        d8 = d15;
                        str26 = str66;
                        str27 = str67;
                        d9 = d16;
                        str28 = str68;
                        d10 = d17;
                        str29 = str69;
                        str30 = str70;
                        str31 = str71;
                        str32 = str72;
                        str33 = str73;
                        str34 = str74;
                        str35 = str75;
                        num9 = num23;
                        num10 = num24;
                        str36 = str76;
                        str39 = str77;
                        str63 = str80;
                        num21 = num13;
                        break;
                    case 26:
                        num13 = num21;
                        str57 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 26, StringSerializer.INSTANCE, str57);
                        i3 = 67108864;
                        i5 |= i3;
                        Unit unit28 = Unit.INSTANCE;
                        num7 = num20;
                        str25 = str65;
                        d7 = d14;
                        d8 = d15;
                        str26 = str66;
                        str27 = str67;
                        d9 = d16;
                        str28 = str68;
                        d10 = d17;
                        str29 = str69;
                        str30 = str70;
                        str31 = str71;
                        str32 = str72;
                        str33 = str73;
                        str34 = str74;
                        str35 = str75;
                        num9 = num23;
                        num10 = num24;
                        str36 = str76;
                        str39 = str77;
                        str63 = str80;
                        num21 = num13;
                        break;
                    case 27:
                        num13 = num21;
                        num20 = (Integer) beginStructure.decodeNullableSerializableElement(serialDescriptor, 27, IntSerializer.INSTANCE, num20);
                        i3 = 134217728;
                        i5 |= i3;
                        Unit unit282 = Unit.INSTANCE;
                        num7 = num20;
                        str25 = str65;
                        d7 = d14;
                        d8 = d15;
                        str26 = str66;
                        str27 = str67;
                        d9 = d16;
                        str28 = str68;
                        d10 = d17;
                        str29 = str69;
                        str30 = str70;
                        str31 = str71;
                        str32 = str72;
                        str33 = str73;
                        str34 = str74;
                        str35 = str75;
                        num9 = num23;
                        num10 = num24;
                        str36 = str76;
                        str39 = str77;
                        str63 = str80;
                        num21 = num13;
                        break;
                    case 28:
                        num13 = num21;
                        str59 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 28, StringSerializer.INSTANCE, str59);
                        i3 = 268435456;
                        i5 |= i3;
                        Unit unit2822 = Unit.INSTANCE;
                        num7 = num20;
                        str25 = str65;
                        d7 = d14;
                        d8 = d15;
                        str26 = str66;
                        str27 = str67;
                        d9 = d16;
                        str28 = str68;
                        d10 = d17;
                        str29 = str69;
                        str30 = str70;
                        str31 = str71;
                        str32 = str72;
                        str33 = str73;
                        str34 = str74;
                        str35 = str75;
                        num9 = num23;
                        num10 = num24;
                        str36 = str76;
                        str39 = str77;
                        str63 = str80;
                        num21 = num13;
                        break;
                    case 29:
                        num13 = num21;
                        i5 |= 536870912;
                        Unit unit29 = Unit.INSTANCE;
                        num7 = num20;
                        num25 = (Integer) beginStructure.decodeNullableSerializableElement(serialDescriptor, 29, IntSerializer.INSTANCE, num25);
                        str25 = str65;
                        d7 = d14;
                        d8 = d15;
                        str26 = str66;
                        str27 = str67;
                        d9 = d16;
                        str28 = str68;
                        d10 = d17;
                        str29 = str69;
                        str30 = str70;
                        str31 = str71;
                        str32 = str72;
                        str33 = str73;
                        str34 = str74;
                        str35 = str75;
                        num9 = num23;
                        num10 = num24;
                        str36 = str76;
                        str39 = str77;
                        str63 = str80;
                        num21 = num13;
                        break;
                    case 30:
                        num13 = num21;
                        i5 |= 1073741824;
                        Unit unit30 = Unit.INSTANCE;
                        num7 = num20;
                        num22 = (Integer) beginStructure.decodeNullableSerializableElement(serialDescriptor, 30, IntSerializer.INSTANCE, num22);
                        str25 = str65;
                        d7 = d14;
                        d8 = d15;
                        str26 = str66;
                        str27 = str67;
                        d9 = d16;
                        str28 = str68;
                        d10 = d17;
                        str29 = str69;
                        str30 = str70;
                        str31 = str71;
                        str32 = str72;
                        str33 = str73;
                        str34 = str74;
                        str35 = str75;
                        num9 = num23;
                        num10 = num24;
                        str36 = str76;
                        str39 = str77;
                        str63 = str80;
                        num21 = num13;
                        break;
                    case ConstantsKt.UPDATE_CALENDAR_CARD_VIDEO_DURATION_WIDTH /* 31 */:
                        num13 = num21;
                        i5 |= Integer.MIN_VALUE;
                        Unit unit31 = Unit.INSTANCE;
                        num7 = num20;
                        str60 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 31, StringSerializer.INSTANCE, str60);
                        str25 = str65;
                        d7 = d14;
                        d8 = d15;
                        str26 = str66;
                        str27 = str67;
                        d9 = d16;
                        str28 = str68;
                        d10 = d17;
                        str29 = str69;
                        str30 = str70;
                        str31 = str71;
                        str32 = str72;
                        str33 = str73;
                        str34 = str74;
                        str35 = str75;
                        num9 = num23;
                        num10 = num24;
                        str36 = str76;
                        str39 = str77;
                        str63 = str80;
                        num21 = num13;
                        break;
                    case 32:
                        num13 = num21;
                        str58 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 32, StringSerializer.INSTANCE, str58);
                        i4 |= 1;
                        Unit unit28222 = Unit.INSTANCE;
                        num7 = num20;
                        str25 = str65;
                        d7 = d14;
                        d8 = d15;
                        str26 = str66;
                        str27 = str67;
                        d9 = d16;
                        str28 = str68;
                        d10 = d17;
                        str29 = str69;
                        str30 = str70;
                        str31 = str71;
                        str32 = str72;
                        str33 = str73;
                        str34 = str74;
                        str35 = str75;
                        num9 = num23;
                        num10 = num24;
                        str36 = str76;
                        str39 = str77;
                        str63 = str80;
                        num21 = num13;
                        break;
                    case 33:
                        num13 = num21;
                        i4 |= 2;
                        Unit unit32 = Unit.INSTANCE;
                        num7 = num20;
                        d12 = (Double) beginStructure.decodeNullableSerializableElement(serialDescriptor, 33, DoubleSerializer.INSTANCE, d12);
                        str25 = str65;
                        d7 = d14;
                        d8 = d15;
                        str26 = str66;
                        str27 = str67;
                        d9 = d16;
                        str28 = str68;
                        d10 = d17;
                        str29 = str69;
                        str30 = str70;
                        str31 = str71;
                        str32 = str72;
                        str33 = str73;
                        str34 = str74;
                        str35 = str75;
                        num9 = num23;
                        num10 = num24;
                        str36 = str76;
                        str39 = str77;
                        str63 = str80;
                        num21 = num13;
                        break;
                    case 34:
                        num13 = num21;
                        i4 |= 4;
                        Unit unit33 = Unit.INSTANCE;
                        num7 = num20;
                        d13 = (Double) beginStructure.decodeNullableSerializableElement(serialDescriptor, 34, DoubleSerializer.INSTANCE, d13);
                        str25 = str65;
                        d7 = d14;
                        d8 = d15;
                        str26 = str66;
                        str27 = str67;
                        d9 = d16;
                        str28 = str68;
                        d10 = d17;
                        str29 = str69;
                        str30 = str70;
                        str31 = str71;
                        str32 = str72;
                        str33 = str73;
                        str34 = str74;
                        str35 = str75;
                        num9 = num23;
                        num10 = num24;
                        str36 = str76;
                        str39 = str77;
                        str63 = str80;
                        num21 = num13;
                        break;
                    default:
                        throw new UnknownFieldException(decodeElementIndex);
                }
                str77 = str39;
                num20 = num7;
                str76 = str36;
                num24 = num10;
                num23 = num9;
                str75 = str35;
                str74 = str34;
                str73 = str33;
                str72 = str32;
                str65 = str25;
                d17 = d10;
                d14 = d7;
                d15 = d8;
                str66 = str26;
                str67 = str27;
                d16 = d9;
                str68 = str28;
                str69 = str29;
                str70 = str30;
                str71 = str31;
            }
            String str81 = str65;
            Double d18 = d14;
            Double d19 = d15;
            String str82 = str66;
            String str83 = str67;
            Double d20 = d16;
            String str84 = str68;
            Double d21 = d17;
            String str85 = str69;
            String str86 = str70;
            String str87 = str71;
            String str88 = str72;
            String str89 = str73;
            String str90 = str74;
            String str91 = str75;
            str = str64;
            str2 = str58;
            str3 = str59;
            d = d12;
            str4 = str60;
            num = num22;
            num2 = num25;
            str5 = str61;
            str6 = str62;
            str7 = str77;
            d2 = d13;
            str8 = str78;
            num3 = num20;
            str9 = str79;
            i = i4;
            str10 = str63;
            num4 = num21;
            str11 = str57;
            i2 = i5;
            str12 = str76;
            str13 = str81;
            d3 = d21;
            str14 = str85;
            num5 = num23;
            d4 = d19;
            str15 = str87;
            num6 = num24;
            d5 = d18;
            str16 = str86;
            str17 = str91;
            str18 = str82;
            str19 = str88;
            str20 = str84;
            str21 = str90;
            str22 = str83;
            str23 = str89;
            d6 = d20;
        }
        beginStructure.endStructure(serialDescriptor);
        return new LabelObject(i2, i, str, str13, d5, d4, str18, str22, d6, str20, d3, str14, str16, str15, str19, str23, str21, str17, num5, num6, str12, str7, str8, str9, str10, num4, str6, str5, str11, num3, str3, num2, num, str4, str2, d, d2, (SerializationConstructorMarker) null);
    }

    public final void serialize(Encoder encoder, LabelObject value) {
        Intrinsics.checkNotNullParameter(encoder, "encoder");
        Intrinsics.checkNotNullParameter(value, "value");
        SerialDescriptor serialDescriptor = descriptor;
        CompositeEncoder beginStructure = encoder.beginStructure(serialDescriptor);
        LabelObject.write$Self$product_details_page_debug(value, beginStructure, serialDescriptor);
        beginStructure.endStructure(serialDescriptor);
    }

    public /* bridge */ KSerializer<?>[] typeParametersSerializers() {
        return GeneratedSerializer.DefaultImpls.typeParametersSerializers(this);
    }
}