package kntr.app.mall.product.details.page.api.model;

import com.bapis.bilibili.app.dynamic.v2.AdditionalButton;
import java.util.List;
import kntr.app.mall.product.details.page.api.model.ShopItem;
import kntr.app.upcomingEpisode.ConstantsKt;
import kntr.watch.later.watchlater.edit.MediaAttrUtils;
import kotlin.Deprecated;
import kotlin.DeprecationLevel;
import kotlin.Lazy;
import kotlin.Metadata;
import kotlin.Unit;
import kotlin.jvm.internal.Intrinsics;
import kotlinx.serialization.DeserializationStrategy;
import kotlinx.serialization.KSerializer;
import kotlinx.serialization.UnknownFieldException;
import kotlinx.serialization.builtins.BuiltinSerializersKt;
import kotlinx.serialization.descriptors.SerialDescriptor;
import kotlinx.serialization.encoding.CompositeDecoder;
import kotlinx.serialization.encoding.CompositeEncoder;
import kotlinx.serialization.encoding.Decoder;
import kotlinx.serialization.encoding.Encoder;
import kotlinx.serialization.internal.BooleanSerializer;
import kotlinx.serialization.internal.GeneratedSerializer;
import kotlinx.serialization.internal.IntSerializer;
import kotlinx.serialization.internal.LongSerializer;
import kotlinx.serialization.internal.PluginGeneratedSerialDescriptor;
import kotlinx.serialization.internal.SerializationConstructorMarker;
import kotlinx.serialization.internal.StringSerializer;
import kotlinx.serialization.json.JsonObject;
import kotlinx.serialization.json.JsonObjectSerializer;

/* compiled from: ShopInfoFloor.kt */
@Metadata(d1 = {"\u00006\n\u0000\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\b\u0003\n\u0002\u0010\u0011\n\u0002\u0018\u0002\n\u0002\b\u0003\n\u0002\u0018\u0002\n\u0000\n\u0002\u0010\u0002\n\u0000\n\u0002\u0018\u0002\n\u0002\b\u0002\n\u0002\u0018\u0002\n\u0002\b\u0003\bÇ\u0002\u0018\u00002\b\u0012\u0004\u0012\u00020\u00020\u0001B\t\b\u0002¢\u0006\u0004\b\u0003\u0010\u0004J\u0015\u0010\u0005\u001a\f\u0012\b\u0012\u0006\u0012\u0002\b\u00030\u00070\u0006¢\u0006\u0002\u0010\bJ\u000e\u0010\t\u001a\u00020\u00022\u0006\u0010\n\u001a\u00020\u000bJ\u0016\u0010\f\u001a\u00020\r2\u0006\u0010\u000e\u001a\u00020\u000f2\u0006\u0010\u0010\u001a\u00020\u0002R\u0011\u0010\u0011\u001a\u00020\u0012¢\u0006\b\n\u0000\u001a\u0004\b\u0013\u0010\u0014¨\u0006\u0015"}, d2 = {"kntr/app/mall/product/details/page/api/model/ShopItem.$serializer", "Lkotlinx/serialization/internal/GeneratedSerializer;", "Lkntr/app/mall/product/details/page/api/model/ShopItem;", "<init>", "()V", "childSerializers", "", "Lkotlinx/serialization/KSerializer;", "()[Lkotlinx/serialization/KSerializer;", "deserialize", "decoder", "Lkotlinx/serialization/encoding/Decoder;", "serialize", "", "encoder", "Lkotlinx/serialization/encoding/Encoder;", "value", "descriptor", "Lkotlinx/serialization/descriptors/SerialDescriptor;", "getDescriptor", "()Lkotlinx/serialization/descriptors/SerialDescriptor;", "product-details-page_debug"}, k = 1, mv = {2, 2, 0}, xi = ConstantsKt.OGV_UPDATE_CALENDAR_CARD_COVER_WIDTH)
@Deprecated(level = DeprecationLevel.HIDDEN, message = "This synthesized declaration should not be used directly")
public final /* synthetic */ class ShopItem$$serializer implements GeneratedSerializer<ShopItem> {
    public static final int $stable;
    public static final ShopItem$$serializer INSTANCE = new ShopItem$$serializer();
    private static final SerialDescriptor descriptor;

    public final SerialDescriptor getDescriptor() {
        return descriptor;
    }

    static {
        SerialDescriptor pluginGeneratedSerialDescriptor = new PluginGeneratedSerialDescriptor("kntr.app.mall.product.details.page.api.model.ShopItem", INSTANCE, 33);
        pluginGeneratedSerialDescriptor.addElement("activityDTOList", true);
        pluginGeneratedSerialDescriptor.addElement("aid", true);
        pluginGeneratedSerialDescriptor.addElement("canAddCart", true);
        pluginGeneratedSerialDescriptor.addElement("coverVO", true);
        pluginGeneratedSerialDescriptor.addElement("feedLabel", true);
        pluginGeneratedSerialDescriptor.addElement("feedTag", true);
        pluginGeneratedSerialDescriptor.addElement("ichibanInfoVO", true);
        pluginGeneratedSerialDescriptor.addElement("itemCode", true);
        pluginGeneratedSerialDescriptor.addElement("itemsId", true);
        pluginGeneratedSerialDescriptor.addElement("itemsIndexDesc", true);
        pluginGeneratedSerialDescriptor.addElement("itemsName", true);
        pluginGeneratedSerialDescriptor.addElement("jumpUrlVO", true);
        pluginGeneratedSerialDescriptor.addElement("marketItemCard", true);
        pluginGeneratedSerialDescriptor.addElement("merchantId", true);
        pluginGeneratedSerialDescriptor.addElement("merchantInfo", true);
        pluginGeneratedSerialDescriptor.addElement("multiSku", true);
        pluginGeneratedSerialDescriptor.addElement("preSaleEndTime", true);
        pluginGeneratedSerialDescriptor.addElement("preSaleStartTime", true);
        pluginGeneratedSerialDescriptor.addElement("priceInfoVO", true);
        pluginGeneratedSerialDescriptor.addElement("promotionImgDto", true);
        pluginGeneratedSerialDescriptor.addElement("reportParams", true);
        pluginGeneratedSerialDescriptor.addElement("sellOut", true);
        pluginGeneratedSerialDescriptor.addElement("skuId", true);
        pluginGeneratedSerialDescriptor.addElement("soldCount", true);
        pluginGeneratedSerialDescriptor.addElement("soldCountDesc", true);
        pluginGeneratedSerialDescriptor.addElement("source", true);
        pluginGeneratedSerialDescriptor.addElement("sourceBizType", true);
        pluginGeneratedSerialDescriptor.addElement("sourceName", true);
        pluginGeneratedSerialDescriptor.addElement("status", true);
        pluginGeneratedSerialDescriptor.addElement("subTitle", true);
        pluginGeneratedSerialDescriptor.addElement("text", true);
        pluginGeneratedSerialDescriptor.addElement("vurl", true);
        pluginGeneratedSerialDescriptor.addElement("wishCount", true);
        descriptor = pluginGeneratedSerialDescriptor;
        $stable = 8;
    }

    private ShopItem$$serializer() {
    }

    public final KSerializer<?>[] childSerializers() {
        Lazy[] lazyArr;
        lazyArr = ShopItem.$childSerializers;
        return new KSerializer[]{BuiltinSerializersKt.getNullable((KSerializer) lazyArr[0].getValue()), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(BooleanSerializer.INSTANCE), BuiltinSerializersKt.getNullable(CoverVO$$serializer.INSTANCE), BuiltinSerializersKt.getNullable(ShopItem$LabelGroup$$serializer.INSTANCE), BuiltinSerializersKt.getNullable(ShopItem$LabelGroup$$serializer.INSTANCE), BuiltinSerializersKt.getNullable(ShopItem$IchibanInfoVO$$serializer.INSTANCE), BuiltinSerializersKt.getNullable(LongSerializer.INSTANCE), BuiltinSerializersKt.getNullable(LongSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(ShopItem$JumpUrlVO$$serializer.INSTANCE), BuiltinSerializersKt.getNullable(BooleanSerializer.INSTANCE), BuiltinSerializersKt.getNullable(LongSerializer.INSTANCE), BuiltinSerializersKt.getNullable(ShopItem$MerchantInfo$$serializer.INSTANCE), BuiltinSerializersKt.getNullable(BooleanSerializer.INSTANCE), BuiltinSerializersKt.getNullable(LongSerializer.INSTANCE), BuiltinSerializersKt.getNullable(LongSerializer.INSTANCE), BuiltinSerializersKt.getNullable(ShopItem$PriceInfoVO$$serializer.INSTANCE), BuiltinSerializersKt.getNullable(ShopItem$PromotionImg$$serializer.INSTANCE), BuiltinSerializersKt.getNullable(JsonObjectSerializer.INSTANCE), BuiltinSerializersKt.getNullable(BooleanSerializer.INSTANCE), BuiltinSerializersKt.getNullable(LongSerializer.INSTANCE), BuiltinSerializersKt.getNullable(IntSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(IntSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(IntSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(IntSerializer.INSTANCE)};
    }

    public final ShopItem deserialize(Decoder decoder) {
        Lazy[] lazyArr;
        String str;
        String str2;
        Integer num;
        String str3;
        Integer num2;
        String str4;
        Boolean bool;
        String str5;
        ShopItem.IchibanInfoVO ichibanInfoVO;
        String str6;
        int i;
        List list;
        Long l;
        String str7;
        ShopItem.PriceInfoVO priceInfoVO;
        Long l2;
        ShopItem.JumpUrlVO jumpUrlVO;
        ShopItem.LabelGroup labelGroup;
        Long l3;
        Long l4;
        Boolean bool2;
        Integer num3;
        int i2;
        String str8;
        Long l5;
        CoverVO coverVO;
        ShopItem.LabelGroup labelGroup2;
        String str9;
        JsonObject jsonObject;
        Integer num4;
        ShopItem.PromotionImg promotionImg;
        Boolean bool3;
        Boolean bool4;
        ShopItem.MerchantInfo merchantInfo;
        Long l6;
        Integer num5;
        String str10;
        Boolean bool5;
        String str11;
        Boolean bool6;
        CoverVO coverVO2;
        ShopItem.LabelGroup labelGroup3;
        ShopItem.LabelGroup labelGroup4;
        ShopItem.IchibanInfoVO ichibanInfoVO2;
        Long l7;
        Long l8;
        String str12;
        String str13;
        ShopItem.JumpUrlVO jumpUrlVO2;
        Boolean bool7;
        Long l9;
        ShopItem.MerchantInfo merchantInfo2;
        Boolean bool8;
        Long l10;
        Long l11;
        ShopItem.PriceInfoVO priceInfoVO2;
        Integer num6;
        int i3;
        Intrinsics.checkNotNullParameter(decoder, "decoder");
        SerialDescriptor serialDescriptor = descriptor;
        CompositeDecoder beginStructure = decoder.beginStructure(serialDescriptor);
        lazyArr = ShopItem.$childSerializers;
        if (beginStructure.decodeSequentially()) {
            ShopItem.JumpUrlVO jumpUrlVO3 = (ShopItem.JumpUrlVO) beginStructure.decodeNullableSerializableElement(serialDescriptor, 11, ShopItem$JumpUrlVO$$serializer.INSTANCE, (Object) null);
            Boolean bool9 = (Boolean) beginStructure.decodeNullableSerializableElement(serialDescriptor, 12, BooleanSerializer.INSTANCE, (Object) null);
            l6 = (Long) beginStructure.decodeNullableSerializableElement(serialDescriptor, 13, LongSerializer.INSTANCE, (Object) null);
            ShopItem.MerchantInfo merchantInfo3 = (ShopItem.MerchantInfo) beginStructure.decodeNullableSerializableElement(serialDescriptor, 14, ShopItem$MerchantInfo$$serializer.INSTANCE, (Object) null);
            Boolean bool10 = (Boolean) beginStructure.decodeNullableSerializableElement(serialDescriptor, 15, BooleanSerializer.INSTANCE, (Object) null);
            Long l12 = (Long) beginStructure.decodeNullableSerializableElement(serialDescriptor, 16, LongSerializer.INSTANCE, (Object) null);
            Long l13 = (Long) beginStructure.decodeNullableSerializableElement(serialDescriptor, 17, LongSerializer.INSTANCE, (Object) null);
            ShopItem.PriceInfoVO priceInfoVO3 = (ShopItem.PriceInfoVO) beginStructure.decodeNullableSerializableElement(serialDescriptor, 18, ShopItem$PriceInfoVO$$serializer.INSTANCE, (Object) null);
            ShopItem.PromotionImg promotionImg2 = (ShopItem.PromotionImg) beginStructure.decodeNullableSerializableElement(serialDescriptor, 19, ShopItem$PromotionImg$$serializer.INSTANCE, (Object) null);
            JsonObject jsonObject2 = (JsonObject) beginStructure.decodeNullableSerializableElement(serialDescriptor, 20, JsonObjectSerializer.INSTANCE, (Object) null);
            Boolean bool11 = (Boolean) beginStructure.decodeNullableSerializableElement(serialDescriptor, 21, BooleanSerializer.INSTANCE, (Object) null);
            Long l14 = (Long) beginStructure.decodeNullableSerializableElement(serialDescriptor, 22, LongSerializer.INSTANCE, (Object) null);
            Integer num7 = (Integer) beginStructure.decodeNullableSerializableElement(serialDescriptor, 23, IntSerializer.INSTANCE, (Object) null);
            String str14 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 24, StringSerializer.INSTANCE, (Object) null);
            Integer num8 = (Integer) beginStructure.decodeNullableSerializableElement(serialDescriptor, 25, IntSerializer.INSTANCE, (Object) null);
            String str15 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 26, StringSerializer.INSTANCE, (Object) null);
            String str16 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 27, StringSerializer.INSTANCE, (Object) null);
            Integer num9 = (Integer) beginStructure.decodeNullableSerializableElement(serialDescriptor, 28, IntSerializer.INSTANCE, (Object) null);
            String str17 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 29, StringSerializer.INSTANCE, (Object) null);
            String str18 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 30, StringSerializer.INSTANCE, (Object) null);
            String str19 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 31, StringSerializer.INSTANCE, (Object) null);
            num = (Integer) beginStructure.decodeNullableSerializableElement(serialDescriptor, 32, IntSerializer.INSTANCE, (Object) null);
            labelGroup = (ShopItem.LabelGroup) beginStructure.decodeNullableSerializableElement(serialDescriptor, 5, ShopItem$LabelGroup$$serializer.INSTANCE, (Object) null);
            str6 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 10, StringSerializer.INSTANCE, (Object) null);
            l2 = l13;
            str4 = str17;
            str3 = str18;
            str2 = str19;
            str5 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 1, StringSerializer.INSTANCE, (Object) null);
            l4 = (Long) beginStructure.decodeNullableSerializableElement(serialDescriptor, 8, LongSerializer.INSTANCE, (Object) null);
            i2 = -1;
            str7 = str15;
            str = str16;
            num2 = num9;
            coverVO = (CoverVO) beginStructure.decodeNullableSerializableElement(serialDescriptor, 3, CoverVO$$serializer.INSTANCE, (Object) null);
            num3 = num7;
            str8 = str14;
            num4 = num8;
            jsonObject = jsonObject2;
            bool2 = bool11;
            l = l14;
            promotionImg = promotionImg2;
            priceInfoVO = priceInfoVO3;
            l5 = l12;
            jumpUrlVO = jumpUrlVO3;
            ichibanInfoVO = (ShopItem.IchibanInfoVO) beginStructure.decodeNullableSerializableElement(serialDescriptor, 6, ShopItem$IchibanInfoVO$$serializer.INSTANCE, (Object) null);
            l3 = (Long) beginStructure.decodeNullableSerializableElement(serialDescriptor, 7, LongSerializer.INSTANCE, (Object) null);
            bool3 = bool10;
            bool = (Boolean) beginStructure.decodeNullableSerializableElement(serialDescriptor, 2, BooleanSerializer.INSTANCE, (Object) null);
            str9 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 9, StringSerializer.INSTANCE, (Object) null);
            list = (List) beginStructure.decodeNullableSerializableElement(serialDescriptor, 0, (DeserializationStrategy) lazyArr[0].getValue(), (Object) null);
            labelGroup2 = (ShopItem.LabelGroup) beginStructure.decodeNullableSerializableElement(serialDescriptor, 4, ShopItem$LabelGroup$$serializer.INSTANCE, (Object) null);
            i = 1;
            merchantInfo = merchantInfo3;
            bool4 = bool9;
        } else {
            int i4 = 0;
            Integer num10 = null;
            String str20 = null;
            String str21 = null;
            Boolean bool12 = null;
            JsonObject jsonObject3 = null;
            String str22 = null;
            Integer num11 = null;
            Integer num12 = null;
            String str23 = null;
            Integer num13 = null;
            String str24 = null;
            Long l15 = null;
            List list2 = null;
            String str25 = null;
            Boolean bool13 = null;
            CoverVO coverVO3 = null;
            ShopItem.LabelGroup labelGroup5 = null;
            ShopItem.LabelGroup labelGroup6 = null;
            ShopItem.IchibanInfoVO ichibanInfoVO3 = null;
            Long l16 = null;
            Long l17 = null;
            String str26 = null;
            String str27 = null;
            ShopItem.JumpUrlVO jumpUrlVO4 = null;
            Boolean bool14 = null;
            Long l18 = null;
            ShopItem.MerchantInfo merchantInfo4 = null;
            Boolean bool15 = null;
            Long l19 = null;
            Long l20 = null;
            ShopItem.PriceInfoVO priceInfoVO4 = null;
            ShopItem.PromotionImg promotionImg3 = null;
            boolean z = true;
            String str28 = null;
            int i5 = 0;
            while (z) {
                JsonObject jsonObject4 = jsonObject3;
                int decodeElementIndex = beginStructure.decodeElementIndex(serialDescriptor);
                switch (decodeElementIndex) {
                    case -1:
                        num5 = num10;
                        str10 = str20;
                        bool5 = bool12;
                        str11 = str25;
                        bool6 = bool13;
                        coverVO2 = coverVO3;
                        labelGroup3 = labelGroup5;
                        labelGroup4 = labelGroup6;
                        ichibanInfoVO2 = ichibanInfoVO3;
                        l7 = l16;
                        l8 = l17;
                        str12 = str26;
                        str13 = str27;
                        jumpUrlVO2 = jumpUrlVO4;
                        bool7 = bool14;
                        l9 = l18;
                        merchantInfo2 = merchantInfo4;
                        bool8 = bool15;
                        l10 = l19;
                        l11 = l20;
                        priceInfoVO2 = priceInfoVO4;
                        Unit unit = Unit.INSTANCE;
                        z = false;
                        break;
                    case 0:
                        num5 = num10;
                        str10 = str20;
                        bool5 = bool12;
                        bool6 = bool13;
                        coverVO2 = coverVO3;
                        labelGroup3 = labelGroup5;
                        labelGroup4 = labelGroup6;
                        ichibanInfoVO2 = ichibanInfoVO3;
                        l7 = l16;
                        l8 = l17;
                        str12 = str26;
                        str13 = str27;
                        jumpUrlVO2 = jumpUrlVO4;
                        bool7 = bool14;
                        l9 = l18;
                        merchantInfo2 = merchantInfo4;
                        bool8 = bool15;
                        l10 = l19;
                        l11 = l20;
                        priceInfoVO2 = priceInfoVO4;
                        DeserializationStrategy deserializationStrategy = (DeserializationStrategy) lazyArr[0].getValue();
                        str11 = str25;
                        i5 |= 1;
                        Unit unit2 = Unit.INSTANCE;
                        list2 = (List) beginStructure.decodeNullableSerializableElement(serialDescriptor, 0, deserializationStrategy, list2);
                        break;
                    case 1:
                        num6 = num10;
                        bool5 = bool12;
                        coverVO2 = coverVO3;
                        labelGroup3 = labelGroup5;
                        labelGroup4 = labelGroup6;
                        ichibanInfoVO2 = ichibanInfoVO3;
                        l7 = l16;
                        l8 = l17;
                        str12 = str26;
                        str13 = str27;
                        jumpUrlVO2 = jumpUrlVO4;
                        bool7 = bool14;
                        l9 = l18;
                        merchantInfo2 = merchantInfo4;
                        bool8 = bool15;
                        l10 = l19;
                        l11 = l20;
                        priceInfoVO2 = priceInfoVO4;
                        bool6 = bool13;
                        i5 |= 2;
                        Unit unit3 = Unit.INSTANCE;
                        str11 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 1, StringSerializer.INSTANCE, str25);
                        str20 = str20;
                        jsonObject3 = jsonObject4;
                        num10 = num6;
                        priceInfoVO4 = priceInfoVO2;
                        l19 = l10;
                        l20 = l11;
                        bool15 = bool8;
                        merchantInfo4 = merchantInfo2;
                        l18 = l9;
                        bool14 = bool7;
                        jumpUrlVO4 = jumpUrlVO2;
                        bool13 = bool6;
                        str25 = str11;
                        coverVO3 = coverVO2;
                        labelGroup5 = labelGroup3;
                        labelGroup6 = labelGroup4;
                        ichibanInfoVO3 = ichibanInfoVO2;
                        l16 = l7;
                        l17 = l8;
                        str26 = str12;
                        str27 = str13;
                        bool12 = bool5;
                    case 2:
                        num6 = num10;
                        bool5 = bool12;
                        labelGroup3 = labelGroup5;
                        labelGroup4 = labelGroup6;
                        ichibanInfoVO2 = ichibanInfoVO3;
                        l7 = l16;
                        l8 = l17;
                        str12 = str26;
                        str13 = str27;
                        jumpUrlVO2 = jumpUrlVO4;
                        bool7 = bool14;
                        l9 = l18;
                        merchantInfo2 = merchantInfo4;
                        bool8 = bool15;
                        l10 = l19;
                        l11 = l20;
                        priceInfoVO2 = priceInfoVO4;
                        coverVO2 = coverVO3;
                        i5 |= 4;
                        Unit unit4 = Unit.INSTANCE;
                        bool6 = (Boolean) beginStructure.decodeNullableSerializableElement(serialDescriptor, 2, BooleanSerializer.INSTANCE, bool13);
                        str20 = str20;
                        str11 = str25;
                        jsonObject3 = jsonObject4;
                        num10 = num6;
                        priceInfoVO4 = priceInfoVO2;
                        l19 = l10;
                        l20 = l11;
                        bool15 = bool8;
                        merchantInfo4 = merchantInfo2;
                        l18 = l9;
                        bool14 = bool7;
                        jumpUrlVO4 = jumpUrlVO2;
                        bool13 = bool6;
                        str25 = str11;
                        coverVO3 = coverVO2;
                        labelGroup5 = labelGroup3;
                        labelGroup6 = labelGroup4;
                        ichibanInfoVO3 = ichibanInfoVO2;
                        l16 = l7;
                        l17 = l8;
                        str26 = str12;
                        str27 = str13;
                        bool12 = bool5;
                    case 3:
                        num6 = num10;
                        bool5 = bool12;
                        labelGroup4 = labelGroup6;
                        ichibanInfoVO2 = ichibanInfoVO3;
                        l7 = l16;
                        l8 = l17;
                        str12 = str26;
                        str13 = str27;
                        jumpUrlVO2 = jumpUrlVO4;
                        bool7 = bool14;
                        l9 = l18;
                        merchantInfo2 = merchantInfo4;
                        bool8 = bool15;
                        l10 = l19;
                        l11 = l20;
                        priceInfoVO2 = priceInfoVO4;
                        labelGroup3 = labelGroup5;
                        i5 |= 8;
                        Unit unit5 = Unit.INSTANCE;
                        coverVO2 = (CoverVO) beginStructure.decodeNullableSerializableElement(serialDescriptor, 3, CoverVO$$serializer.INSTANCE, coverVO3);
                        str20 = str20;
                        str11 = str25;
                        bool6 = bool13;
                        jsonObject3 = jsonObject4;
                        num10 = num6;
                        priceInfoVO4 = priceInfoVO2;
                        l19 = l10;
                        l20 = l11;
                        bool15 = bool8;
                        merchantInfo4 = merchantInfo2;
                        l18 = l9;
                        bool14 = bool7;
                        jumpUrlVO4 = jumpUrlVO2;
                        bool13 = bool6;
                        str25 = str11;
                        coverVO3 = coverVO2;
                        labelGroup5 = labelGroup3;
                        labelGroup6 = labelGroup4;
                        ichibanInfoVO3 = ichibanInfoVO2;
                        l16 = l7;
                        l17 = l8;
                        str26 = str12;
                        str27 = str13;
                        bool12 = bool5;
                    case 4:
                        num6 = num10;
                        bool5 = bool12;
                        ichibanInfoVO2 = ichibanInfoVO3;
                        l7 = l16;
                        l8 = l17;
                        str12 = str26;
                        str13 = str27;
                        jumpUrlVO2 = jumpUrlVO4;
                        bool7 = bool14;
                        l9 = l18;
                        merchantInfo2 = merchantInfo4;
                        bool8 = bool15;
                        l10 = l19;
                        l11 = l20;
                        priceInfoVO2 = priceInfoVO4;
                        labelGroup4 = labelGroup6;
                        i5 |= 16;
                        Unit unit6 = Unit.INSTANCE;
                        labelGroup3 = (ShopItem.LabelGroup) beginStructure.decodeNullableSerializableElement(serialDescriptor, 4, ShopItem$LabelGroup$$serializer.INSTANCE, labelGroup5);
                        str20 = str20;
                        str11 = str25;
                        bool6 = bool13;
                        coverVO2 = coverVO3;
                        jsonObject3 = jsonObject4;
                        num10 = num6;
                        priceInfoVO4 = priceInfoVO2;
                        l19 = l10;
                        l20 = l11;
                        bool15 = bool8;
                        merchantInfo4 = merchantInfo2;
                        l18 = l9;
                        bool14 = bool7;
                        jumpUrlVO4 = jumpUrlVO2;
                        bool13 = bool6;
                        str25 = str11;
                        coverVO3 = coverVO2;
                        labelGroup5 = labelGroup3;
                        labelGroup6 = labelGroup4;
                        ichibanInfoVO3 = ichibanInfoVO2;
                        l16 = l7;
                        l17 = l8;
                        str26 = str12;
                        str27 = str13;
                        bool12 = bool5;
                    case 5:
                        num6 = num10;
                        bool5 = bool12;
                        l7 = l16;
                        l8 = l17;
                        str12 = str26;
                        str13 = str27;
                        jumpUrlVO2 = jumpUrlVO4;
                        bool7 = bool14;
                        l9 = l18;
                        merchantInfo2 = merchantInfo4;
                        bool8 = bool15;
                        l10 = l19;
                        l11 = l20;
                        priceInfoVO2 = priceInfoVO4;
                        ichibanInfoVO2 = ichibanInfoVO3;
                        i5 |= 32;
                        Unit unit7 = Unit.INSTANCE;
                        labelGroup4 = (ShopItem.LabelGroup) beginStructure.decodeNullableSerializableElement(serialDescriptor, 5, ShopItem$LabelGroup$$serializer.INSTANCE, labelGroup6);
                        str20 = str20;
                        str11 = str25;
                        bool6 = bool13;
                        coverVO2 = coverVO3;
                        labelGroup3 = labelGroup5;
                        jsonObject3 = jsonObject4;
                        num10 = num6;
                        priceInfoVO4 = priceInfoVO2;
                        l19 = l10;
                        l20 = l11;
                        bool15 = bool8;
                        merchantInfo4 = merchantInfo2;
                        l18 = l9;
                        bool14 = bool7;
                        jumpUrlVO4 = jumpUrlVO2;
                        bool13 = bool6;
                        str25 = str11;
                        coverVO3 = coverVO2;
                        labelGroup5 = labelGroup3;
                        labelGroup6 = labelGroup4;
                        ichibanInfoVO3 = ichibanInfoVO2;
                        l16 = l7;
                        l17 = l8;
                        str26 = str12;
                        str27 = str13;
                        bool12 = bool5;
                    case 6:
                        num6 = num10;
                        bool5 = bool12;
                        l8 = l17;
                        str12 = str26;
                        str13 = str27;
                        jumpUrlVO2 = jumpUrlVO4;
                        bool7 = bool14;
                        l9 = l18;
                        merchantInfo2 = merchantInfo4;
                        bool8 = bool15;
                        l10 = l19;
                        l11 = l20;
                        priceInfoVO2 = priceInfoVO4;
                        l7 = l16;
                        i5 |= 64;
                        Unit unit8 = Unit.INSTANCE;
                        ichibanInfoVO2 = (ShopItem.IchibanInfoVO) beginStructure.decodeNullableSerializableElement(serialDescriptor, 6, ShopItem$IchibanInfoVO$$serializer.INSTANCE, ichibanInfoVO3);
                        str20 = str20;
                        str11 = str25;
                        bool6 = bool13;
                        coverVO2 = coverVO3;
                        labelGroup3 = labelGroup5;
                        labelGroup4 = labelGroup6;
                        jsonObject3 = jsonObject4;
                        num10 = num6;
                        priceInfoVO4 = priceInfoVO2;
                        l19 = l10;
                        l20 = l11;
                        bool15 = bool8;
                        merchantInfo4 = merchantInfo2;
                        l18 = l9;
                        bool14 = bool7;
                        jumpUrlVO4 = jumpUrlVO2;
                        bool13 = bool6;
                        str25 = str11;
                        coverVO3 = coverVO2;
                        labelGroup5 = labelGroup3;
                        labelGroup6 = labelGroup4;
                        ichibanInfoVO3 = ichibanInfoVO2;
                        l16 = l7;
                        l17 = l8;
                        str26 = str12;
                        str27 = str13;
                        bool12 = bool5;
                    case AdditionalButton.CLICK_TYPE_FIELD_NUMBER /* 7 */:
                        num6 = num10;
                        bool5 = bool12;
                        str12 = str26;
                        str13 = str27;
                        jumpUrlVO2 = jumpUrlVO4;
                        bool7 = bool14;
                        l9 = l18;
                        merchantInfo2 = merchantInfo4;
                        bool8 = bool15;
                        l10 = l19;
                        l11 = l20;
                        priceInfoVO2 = priceInfoVO4;
                        l8 = l17;
                        i5 |= 128;
                        Unit unit9 = Unit.INSTANCE;
                        l7 = (Long) beginStructure.decodeNullableSerializableElement(serialDescriptor, 7, LongSerializer.INSTANCE, l16);
                        str20 = str20;
                        str11 = str25;
                        bool6 = bool13;
                        coverVO2 = coverVO3;
                        labelGroup3 = labelGroup5;
                        labelGroup4 = labelGroup6;
                        ichibanInfoVO2 = ichibanInfoVO3;
                        jsonObject3 = jsonObject4;
                        num10 = num6;
                        priceInfoVO4 = priceInfoVO2;
                        l19 = l10;
                        l20 = l11;
                        bool15 = bool8;
                        merchantInfo4 = merchantInfo2;
                        l18 = l9;
                        bool14 = bool7;
                        jumpUrlVO4 = jumpUrlVO2;
                        bool13 = bool6;
                        str25 = str11;
                        coverVO3 = coverVO2;
                        labelGroup5 = labelGroup3;
                        labelGroup6 = labelGroup4;
                        ichibanInfoVO3 = ichibanInfoVO2;
                        l16 = l7;
                        l17 = l8;
                        str26 = str12;
                        str27 = str13;
                        bool12 = bool5;
                    case 8:
                        num6 = num10;
                        bool5 = bool12;
                        str13 = str27;
                        jumpUrlVO2 = jumpUrlVO4;
                        bool7 = bool14;
                        l9 = l18;
                        merchantInfo2 = merchantInfo4;
                        bool8 = bool15;
                        l10 = l19;
                        l11 = l20;
                        priceInfoVO2 = priceInfoVO4;
                        str12 = str26;
                        i5 |= 256;
                        Unit unit10 = Unit.INSTANCE;
                        l8 = (Long) beginStructure.decodeNullableSerializableElement(serialDescriptor, 8, LongSerializer.INSTANCE, l17);
                        str20 = str20;
                        str11 = str25;
                        bool6 = bool13;
                        coverVO2 = coverVO3;
                        labelGroup3 = labelGroup5;
                        labelGroup4 = labelGroup6;
                        ichibanInfoVO2 = ichibanInfoVO3;
                        l7 = l16;
                        jsonObject3 = jsonObject4;
                        num10 = num6;
                        priceInfoVO4 = priceInfoVO2;
                        l19 = l10;
                        l20 = l11;
                        bool15 = bool8;
                        merchantInfo4 = merchantInfo2;
                        l18 = l9;
                        bool14 = bool7;
                        jumpUrlVO4 = jumpUrlVO2;
                        bool13 = bool6;
                        str25 = str11;
                        coverVO3 = coverVO2;
                        labelGroup5 = labelGroup3;
                        labelGroup6 = labelGroup4;
                        ichibanInfoVO3 = ichibanInfoVO2;
                        l16 = l7;
                        l17 = l8;
                        str26 = str12;
                        str27 = str13;
                        bool12 = bool5;
                    case ConstantsKt.SPACER_9 /* 9 */:
                        num6 = num10;
                        bool5 = bool12;
                        jumpUrlVO2 = jumpUrlVO4;
                        bool7 = bool14;
                        l9 = l18;
                        merchantInfo2 = merchantInfo4;
                        bool8 = bool15;
                        l10 = l19;
                        l11 = l20;
                        priceInfoVO2 = priceInfoVO4;
                        str13 = str27;
                        i5 |= 512;
                        Unit unit11 = Unit.INSTANCE;
                        str12 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 9, StringSerializer.INSTANCE, str26);
                        str20 = str20;
                        str11 = str25;
                        bool6 = bool13;
                        coverVO2 = coverVO3;
                        labelGroup3 = labelGroup5;
                        labelGroup4 = labelGroup6;
                        ichibanInfoVO2 = ichibanInfoVO3;
                        l7 = l16;
                        l8 = l17;
                        jsonObject3 = jsonObject4;
                        num10 = num6;
                        priceInfoVO4 = priceInfoVO2;
                        l19 = l10;
                        l20 = l11;
                        bool15 = bool8;
                        merchantInfo4 = merchantInfo2;
                        l18 = l9;
                        bool14 = bool7;
                        jumpUrlVO4 = jumpUrlVO2;
                        bool13 = bool6;
                        str25 = str11;
                        coverVO3 = coverVO2;
                        labelGroup5 = labelGroup3;
                        labelGroup6 = labelGroup4;
                        ichibanInfoVO3 = ichibanInfoVO2;
                        l16 = l7;
                        l17 = l8;
                        str26 = str12;
                        str27 = str13;
                        bool12 = bool5;
                    case 10:
                        num6 = num10;
                        bool5 = bool12;
                        bool7 = bool14;
                        l9 = l18;
                        merchantInfo2 = merchantInfo4;
                        bool8 = bool15;
                        l10 = l19;
                        l11 = l20;
                        priceInfoVO2 = priceInfoVO4;
                        jumpUrlVO2 = jumpUrlVO4;
                        i5 |= 1024;
                        Unit unit12 = Unit.INSTANCE;
                        str13 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 10, StringSerializer.INSTANCE, str27);
                        str20 = str20;
                        str11 = str25;
                        bool6 = bool13;
                        coverVO2 = coverVO3;
                        labelGroup3 = labelGroup5;
                        labelGroup4 = labelGroup6;
                        ichibanInfoVO2 = ichibanInfoVO3;
                        l7 = l16;
                        l8 = l17;
                        str12 = str26;
                        jsonObject3 = jsonObject4;
                        num10 = num6;
                        priceInfoVO4 = priceInfoVO2;
                        l19 = l10;
                        l20 = l11;
                        bool15 = bool8;
                        merchantInfo4 = merchantInfo2;
                        l18 = l9;
                        bool14 = bool7;
                        jumpUrlVO4 = jumpUrlVO2;
                        bool13 = bool6;
                        str25 = str11;
                        coverVO3 = coverVO2;
                        labelGroup5 = labelGroup3;
                        labelGroup6 = labelGroup4;
                        ichibanInfoVO3 = ichibanInfoVO2;
                        l16 = l7;
                        l17 = l8;
                        str26 = str12;
                        str27 = str13;
                        bool12 = bool5;
                    case MediaAttrUtils.TYPE_MENU /* 11 */:
                        num6 = num10;
                        bool5 = bool12;
                        l9 = l18;
                        merchantInfo2 = merchantInfo4;
                        bool8 = bool15;
                        l10 = l19;
                        l11 = l20;
                        priceInfoVO2 = priceInfoVO4;
                        bool7 = bool14;
                        i5 |= 2048;
                        Unit unit13 = Unit.INSTANCE;
                        jumpUrlVO2 = (ShopItem.JumpUrlVO) beginStructure.decodeNullableSerializableElement(serialDescriptor, 11, ShopItem$JumpUrlVO$$serializer.INSTANCE, jumpUrlVO4);
                        str20 = str20;
                        str11 = str25;
                        bool6 = bool13;
                        coverVO2 = coverVO3;
                        labelGroup3 = labelGroup5;
                        labelGroup4 = labelGroup6;
                        ichibanInfoVO2 = ichibanInfoVO3;
                        l7 = l16;
                        l8 = l17;
                        str12 = str26;
                        str13 = str27;
                        jsonObject3 = jsonObject4;
                        num10 = num6;
                        priceInfoVO4 = priceInfoVO2;
                        l19 = l10;
                        l20 = l11;
                        bool15 = bool8;
                        merchantInfo4 = merchantInfo2;
                        l18 = l9;
                        bool14 = bool7;
                        jumpUrlVO4 = jumpUrlVO2;
                        bool13 = bool6;
                        str25 = str11;
                        coverVO3 = coverVO2;
                        labelGroup5 = labelGroup3;
                        labelGroup6 = labelGroup4;
                        ichibanInfoVO3 = ichibanInfoVO2;
                        l16 = l7;
                        l17 = l8;
                        str26 = str12;
                        str27 = str13;
                        bool12 = bool5;
                    case 12:
                        num6 = num10;
                        bool5 = bool12;
                        merchantInfo2 = merchantInfo4;
                        bool8 = bool15;
                        l10 = l19;
                        l11 = l20;
                        priceInfoVO2 = priceInfoVO4;
                        l9 = l18;
                        i5 |= 4096;
                        Unit unit14 = Unit.INSTANCE;
                        bool7 = (Boolean) beginStructure.decodeNullableSerializableElement(serialDescriptor, 12, BooleanSerializer.INSTANCE, bool14);
                        str20 = str20;
                        str11 = str25;
                        bool6 = bool13;
                        coverVO2 = coverVO3;
                        labelGroup3 = labelGroup5;
                        labelGroup4 = labelGroup6;
                        ichibanInfoVO2 = ichibanInfoVO3;
                        l7 = l16;
                        l8 = l17;
                        str12 = str26;
                        str13 = str27;
                        jumpUrlVO2 = jumpUrlVO4;
                        jsonObject3 = jsonObject4;
                        num10 = num6;
                        priceInfoVO4 = priceInfoVO2;
                        l19 = l10;
                        l20 = l11;
                        bool15 = bool8;
                        merchantInfo4 = merchantInfo2;
                        l18 = l9;
                        bool14 = bool7;
                        jumpUrlVO4 = jumpUrlVO2;
                        bool13 = bool6;
                        str25 = str11;
                        coverVO3 = coverVO2;
                        labelGroup5 = labelGroup3;
                        labelGroup6 = labelGroup4;
                        ichibanInfoVO3 = ichibanInfoVO2;
                        l16 = l7;
                        l17 = l8;
                        str26 = str12;
                        str27 = str13;
                        bool12 = bool5;
                    case 13:
                        num6 = num10;
                        bool5 = bool12;
                        bool8 = bool15;
                        l10 = l19;
                        l11 = l20;
                        priceInfoVO2 = priceInfoVO4;
                        merchantInfo2 = merchantInfo4;
                        i5 |= 8192;
                        Unit unit15 = Unit.INSTANCE;
                        l9 = (Long) beginStructure.decodeNullableSerializableElement(serialDescriptor, 13, LongSerializer.INSTANCE, l18);
                        str20 = str20;
                        str11 = str25;
                        bool6 = bool13;
                        coverVO2 = coverVO3;
                        labelGroup3 = labelGroup5;
                        labelGroup4 = labelGroup6;
                        ichibanInfoVO2 = ichibanInfoVO3;
                        l7 = l16;
                        l8 = l17;
                        str12 = str26;
                        str13 = str27;
                        jumpUrlVO2 = jumpUrlVO4;
                        bool7 = bool14;
                        jsonObject3 = jsonObject4;
                        num10 = num6;
                        priceInfoVO4 = priceInfoVO2;
                        l19 = l10;
                        l20 = l11;
                        bool15 = bool8;
                        merchantInfo4 = merchantInfo2;
                        l18 = l9;
                        bool14 = bool7;
                        jumpUrlVO4 = jumpUrlVO2;
                        bool13 = bool6;
                        str25 = str11;
                        coverVO3 = coverVO2;
                        labelGroup5 = labelGroup3;
                        labelGroup6 = labelGroup4;
                        ichibanInfoVO3 = ichibanInfoVO2;
                        l16 = l7;
                        l17 = l8;
                        str26 = str12;
                        str27 = str13;
                        bool12 = bool5;
                    case ConstantsKt.SPACER_14 /* 14 */:
                        num6 = num10;
                        bool5 = bool12;
                        l10 = l19;
                        l11 = l20;
                        priceInfoVO2 = priceInfoVO4;
                        bool8 = bool15;
                        i5 |= 16384;
                        Unit unit16 = Unit.INSTANCE;
                        merchantInfo2 = (ShopItem.MerchantInfo) beginStructure.decodeNullableSerializableElement(serialDescriptor, 14, ShopItem$MerchantInfo$$serializer.INSTANCE, merchantInfo4);
                        str20 = str20;
                        str11 = str25;
                        bool6 = bool13;
                        coverVO2 = coverVO3;
                        labelGroup3 = labelGroup5;
                        labelGroup4 = labelGroup6;
                        ichibanInfoVO2 = ichibanInfoVO3;
                        l7 = l16;
                        l8 = l17;
                        str12 = str26;
                        str13 = str27;
                        jumpUrlVO2 = jumpUrlVO4;
                        bool7 = bool14;
                        l9 = l18;
                        jsonObject3 = jsonObject4;
                        num10 = num6;
                        priceInfoVO4 = priceInfoVO2;
                        l19 = l10;
                        l20 = l11;
                        bool15 = bool8;
                        merchantInfo4 = merchantInfo2;
                        l18 = l9;
                        bool14 = bool7;
                        jumpUrlVO4 = jumpUrlVO2;
                        bool13 = bool6;
                        str25 = str11;
                        coverVO3 = coverVO2;
                        labelGroup5 = labelGroup3;
                        labelGroup6 = labelGroup4;
                        ichibanInfoVO3 = ichibanInfoVO2;
                        l16 = l7;
                        l17 = l8;
                        str26 = str12;
                        str27 = str13;
                        bool12 = bool5;
                    case 15:
                        num6 = num10;
                        bool5 = bool12;
                        l11 = l20;
                        priceInfoVO2 = priceInfoVO4;
                        l10 = l19;
                        i5 |= 32768;
                        Unit unit17 = Unit.INSTANCE;
                        bool8 = (Boolean) beginStructure.decodeNullableSerializableElement(serialDescriptor, 15, BooleanSerializer.INSTANCE, bool15);
                        str20 = str20;
                        str11 = str25;
                        bool6 = bool13;
                        coverVO2 = coverVO3;
                        labelGroup3 = labelGroup5;
                        labelGroup4 = labelGroup6;
                        ichibanInfoVO2 = ichibanInfoVO3;
                        l7 = l16;
                        l8 = l17;
                        str12 = str26;
                        str13 = str27;
                        jumpUrlVO2 = jumpUrlVO4;
                        bool7 = bool14;
                        l9 = l18;
                        merchantInfo2 = merchantInfo4;
                        jsonObject3 = jsonObject4;
                        num10 = num6;
                        priceInfoVO4 = priceInfoVO2;
                        l19 = l10;
                        l20 = l11;
                        bool15 = bool8;
                        merchantInfo4 = merchantInfo2;
                        l18 = l9;
                        bool14 = bool7;
                        jumpUrlVO4 = jumpUrlVO2;
                        bool13 = bool6;
                        str25 = str11;
                        coverVO3 = coverVO2;
                        labelGroup5 = labelGroup3;
                        labelGroup6 = labelGroup4;
                        ichibanInfoVO3 = ichibanInfoVO2;
                        l16 = l7;
                        l17 = l8;
                        str26 = str12;
                        str27 = str13;
                        bool12 = bool5;
                    case 16:
                        num6 = num10;
                        bool5 = bool12;
                        priceInfoVO2 = priceInfoVO4;
                        l11 = l20;
                        i5 |= 65536;
                        Unit unit18 = Unit.INSTANCE;
                        l10 = (Long) beginStructure.decodeNullableSerializableElement(serialDescriptor, 16, LongSerializer.INSTANCE, l19);
                        str20 = str20;
                        str11 = str25;
                        bool6 = bool13;
                        coverVO2 = coverVO3;
                        labelGroup3 = labelGroup5;
                        labelGroup4 = labelGroup6;
                        ichibanInfoVO2 = ichibanInfoVO3;
                        l7 = l16;
                        l8 = l17;
                        str12 = str26;
                        str13 = str27;
                        jumpUrlVO2 = jumpUrlVO4;
                        bool7 = bool14;
                        l9 = l18;
                        merchantInfo2 = merchantInfo4;
                        bool8 = bool15;
                        jsonObject3 = jsonObject4;
                        num10 = num6;
                        priceInfoVO4 = priceInfoVO2;
                        l19 = l10;
                        l20 = l11;
                        bool15 = bool8;
                        merchantInfo4 = merchantInfo2;
                        l18 = l9;
                        bool14 = bool7;
                        jumpUrlVO4 = jumpUrlVO2;
                        bool13 = bool6;
                        str25 = str11;
                        coverVO3 = coverVO2;
                        labelGroup5 = labelGroup3;
                        labelGroup6 = labelGroup4;
                        ichibanInfoVO3 = ichibanInfoVO2;
                        l16 = l7;
                        l17 = l8;
                        str26 = str12;
                        str27 = str13;
                        bool12 = bool5;
                    case 17:
                        num6 = num10;
                        bool5 = bool12;
                        priceInfoVO2 = priceInfoVO4;
                        i5 |= 131072;
                        Unit unit19 = Unit.INSTANCE;
                        l11 = (Long) beginStructure.decodeNullableSerializableElement(serialDescriptor, 17, LongSerializer.INSTANCE, l20);
                        str20 = str20;
                        str11 = str25;
                        bool6 = bool13;
                        coverVO2 = coverVO3;
                        labelGroup3 = labelGroup5;
                        labelGroup4 = labelGroup6;
                        ichibanInfoVO2 = ichibanInfoVO3;
                        l7 = l16;
                        l8 = l17;
                        str12 = str26;
                        str13 = str27;
                        jumpUrlVO2 = jumpUrlVO4;
                        bool7 = bool14;
                        l9 = l18;
                        merchantInfo2 = merchantInfo4;
                        bool8 = bool15;
                        l10 = l19;
                        jsonObject3 = jsonObject4;
                        num10 = num6;
                        priceInfoVO4 = priceInfoVO2;
                        l19 = l10;
                        l20 = l11;
                        bool15 = bool8;
                        merchantInfo4 = merchantInfo2;
                        l18 = l9;
                        bool14 = bool7;
                        jumpUrlVO4 = jumpUrlVO2;
                        bool13 = bool6;
                        str25 = str11;
                        coverVO3 = coverVO2;
                        labelGroup5 = labelGroup3;
                        labelGroup6 = labelGroup4;
                        ichibanInfoVO3 = ichibanInfoVO2;
                        l16 = l7;
                        l17 = l8;
                        str26 = str12;
                        str27 = str13;
                        bool12 = bool5;
                    case 18:
                        num6 = num10;
                        bool5 = bool12;
                        i5 |= 262144;
                        Unit unit20 = Unit.INSTANCE;
                        priceInfoVO2 = (ShopItem.PriceInfoVO) beginStructure.decodeNullableSerializableElement(serialDescriptor, 18, ShopItem$PriceInfoVO$$serializer.INSTANCE, priceInfoVO4);
                        str20 = str20;
                        str11 = str25;
                        bool6 = bool13;
                        coverVO2 = coverVO3;
                        labelGroup3 = labelGroup5;
                        labelGroup4 = labelGroup6;
                        ichibanInfoVO2 = ichibanInfoVO3;
                        l7 = l16;
                        l8 = l17;
                        str12 = str26;
                        str13 = str27;
                        jumpUrlVO2 = jumpUrlVO4;
                        bool7 = bool14;
                        l9 = l18;
                        merchantInfo2 = merchantInfo4;
                        bool8 = bool15;
                        l10 = l19;
                        l11 = l20;
                        jsonObject3 = jsonObject4;
                        num10 = num6;
                        priceInfoVO4 = priceInfoVO2;
                        l19 = l10;
                        l20 = l11;
                        bool15 = bool8;
                        merchantInfo4 = merchantInfo2;
                        l18 = l9;
                        bool14 = bool7;
                        jumpUrlVO4 = jumpUrlVO2;
                        bool13 = bool6;
                        str25 = str11;
                        coverVO3 = coverVO2;
                        labelGroup5 = labelGroup3;
                        labelGroup6 = labelGroup4;
                        ichibanInfoVO3 = ichibanInfoVO2;
                        l16 = l7;
                        l17 = l8;
                        str26 = str12;
                        str27 = str13;
                        bool12 = bool5;
                    case 19:
                        num6 = num10;
                        bool5 = bool12;
                        i5 |= 524288;
                        Unit unit21 = Unit.INSTANCE;
                        promotionImg3 = (ShopItem.PromotionImg) beginStructure.decodeNullableSerializableElement(serialDescriptor, 19, ShopItem$PromotionImg$$serializer.INSTANCE, promotionImg3);
                        str11 = str25;
                        bool6 = bool13;
                        coverVO2 = coverVO3;
                        labelGroup3 = labelGroup5;
                        labelGroup4 = labelGroup6;
                        ichibanInfoVO2 = ichibanInfoVO3;
                        l7 = l16;
                        l8 = l17;
                        str12 = str26;
                        str13 = str27;
                        jumpUrlVO2 = jumpUrlVO4;
                        bool7 = bool14;
                        l9 = l18;
                        merchantInfo2 = merchantInfo4;
                        bool8 = bool15;
                        l10 = l19;
                        l11 = l20;
                        priceInfoVO2 = priceInfoVO4;
                        jsonObject3 = jsonObject4;
                        num10 = num6;
                        priceInfoVO4 = priceInfoVO2;
                        l19 = l10;
                        l20 = l11;
                        bool15 = bool8;
                        merchantInfo4 = merchantInfo2;
                        l18 = l9;
                        bool14 = bool7;
                        jumpUrlVO4 = jumpUrlVO2;
                        bool13 = bool6;
                        str25 = str11;
                        coverVO3 = coverVO2;
                        labelGroup5 = labelGroup3;
                        labelGroup6 = labelGroup4;
                        ichibanInfoVO3 = ichibanInfoVO2;
                        l16 = l7;
                        l17 = l8;
                        str26 = str12;
                        str27 = str13;
                        bool12 = bool5;
                    case 20:
                        num6 = num10;
                        bool5 = bool12;
                        i5 |= 1048576;
                        Unit unit22 = Unit.INSTANCE;
                        jsonObject3 = (JsonObject) beginStructure.decodeNullableSerializableElement(serialDescriptor, 20, JsonObjectSerializer.INSTANCE, jsonObject4);
                        str11 = str25;
                        bool6 = bool13;
                        coverVO2 = coverVO3;
                        labelGroup3 = labelGroup5;
                        labelGroup4 = labelGroup6;
                        ichibanInfoVO2 = ichibanInfoVO3;
                        l7 = l16;
                        l8 = l17;
                        str12 = str26;
                        str13 = str27;
                        jumpUrlVO2 = jumpUrlVO4;
                        bool7 = bool14;
                        l9 = l18;
                        merchantInfo2 = merchantInfo4;
                        bool8 = bool15;
                        l10 = l19;
                        l11 = l20;
                        priceInfoVO2 = priceInfoVO4;
                        num10 = num6;
                        priceInfoVO4 = priceInfoVO2;
                        l19 = l10;
                        l20 = l11;
                        bool15 = bool8;
                        merchantInfo4 = merchantInfo2;
                        l18 = l9;
                        bool14 = bool7;
                        jumpUrlVO4 = jumpUrlVO2;
                        bool13 = bool6;
                        str25 = str11;
                        coverVO3 = coverVO2;
                        labelGroup5 = labelGroup3;
                        labelGroup6 = labelGroup4;
                        ichibanInfoVO3 = ichibanInfoVO2;
                        l16 = l7;
                        l17 = l8;
                        str26 = str12;
                        str27 = str13;
                        bool12 = bool5;
                    case 21:
                        Boolean bool16 = bool12;
                        num6 = num10;
                        i5 |= 2097152;
                        Unit unit23 = Unit.INSTANCE;
                        bool5 = (Boolean) beginStructure.decodeNullableSerializableElement(serialDescriptor, 21, BooleanSerializer.INSTANCE, bool16);
                        str11 = str25;
                        bool6 = bool13;
                        coverVO2 = coverVO3;
                        labelGroup3 = labelGroup5;
                        labelGroup4 = labelGroup6;
                        ichibanInfoVO2 = ichibanInfoVO3;
                        l7 = l16;
                        l8 = l17;
                        str12 = str26;
                        str13 = str27;
                        jumpUrlVO2 = jumpUrlVO4;
                        bool7 = bool14;
                        l9 = l18;
                        merchantInfo2 = merchantInfo4;
                        bool8 = bool15;
                        l10 = l19;
                        l11 = l20;
                        priceInfoVO2 = priceInfoVO4;
                        jsonObject3 = jsonObject4;
                        num10 = num6;
                        priceInfoVO4 = priceInfoVO2;
                        l19 = l10;
                        l20 = l11;
                        bool15 = bool8;
                        merchantInfo4 = merchantInfo2;
                        l18 = l9;
                        bool14 = bool7;
                        jumpUrlVO4 = jumpUrlVO2;
                        bool13 = bool6;
                        str25 = str11;
                        coverVO3 = coverVO2;
                        labelGroup5 = labelGroup3;
                        labelGroup6 = labelGroup4;
                        ichibanInfoVO3 = ichibanInfoVO2;
                        l16 = l7;
                        l17 = l8;
                        str26 = str12;
                        str27 = str13;
                        bool12 = bool5;
                    case 22:
                        bool5 = bool12;
                        i5 |= 4194304;
                        Unit unit24 = Unit.INSTANCE;
                        l15 = (Long) beginStructure.decodeNullableSerializableElement(serialDescriptor, 22, LongSerializer.INSTANCE, l15);
                        str11 = str25;
                        bool6 = bool13;
                        coverVO2 = coverVO3;
                        labelGroup3 = labelGroup5;
                        labelGroup4 = labelGroup6;
                        ichibanInfoVO2 = ichibanInfoVO3;
                        l7 = l16;
                        l8 = l17;
                        str12 = str26;
                        str13 = str27;
                        jumpUrlVO2 = jumpUrlVO4;
                        bool7 = bool14;
                        l9 = l18;
                        merchantInfo2 = merchantInfo4;
                        bool8 = bool15;
                        l10 = l19;
                        l11 = l20;
                        priceInfoVO2 = priceInfoVO4;
                        jsonObject3 = jsonObject4;
                        priceInfoVO4 = priceInfoVO2;
                        l19 = l10;
                        l20 = l11;
                        bool15 = bool8;
                        merchantInfo4 = merchantInfo2;
                        l18 = l9;
                        bool14 = bool7;
                        jumpUrlVO4 = jumpUrlVO2;
                        bool13 = bool6;
                        str25 = str11;
                        coverVO3 = coverVO2;
                        labelGroup5 = labelGroup3;
                        labelGroup6 = labelGroup4;
                        ichibanInfoVO3 = ichibanInfoVO2;
                        l16 = l7;
                        l17 = l8;
                        str26 = str12;
                        str27 = str13;
                        bool12 = bool5;
                    case 23:
                        bool5 = bool12;
                        i5 |= 8388608;
                        Unit unit25 = Unit.INSTANCE;
                        num11 = (Integer) beginStructure.decodeNullableSerializableElement(serialDescriptor, 23, IntSerializer.INSTANCE, num11);
                        str11 = str25;
                        bool6 = bool13;
                        coverVO2 = coverVO3;
                        labelGroup3 = labelGroup5;
                        labelGroup4 = labelGroup6;
                        ichibanInfoVO2 = ichibanInfoVO3;
                        l7 = l16;
                        l8 = l17;
                        str12 = str26;
                        str13 = str27;
                        jumpUrlVO2 = jumpUrlVO4;
                        bool7 = bool14;
                        l9 = l18;
                        merchantInfo2 = merchantInfo4;
                        bool8 = bool15;
                        l10 = l19;
                        l11 = l20;
                        priceInfoVO2 = priceInfoVO4;
                        jsonObject3 = jsonObject4;
                        priceInfoVO4 = priceInfoVO2;
                        l19 = l10;
                        l20 = l11;
                        bool15 = bool8;
                        merchantInfo4 = merchantInfo2;
                        l18 = l9;
                        bool14 = bool7;
                        jumpUrlVO4 = jumpUrlVO2;
                        bool13 = bool6;
                        str25 = str11;
                        coverVO3 = coverVO2;
                        labelGroup5 = labelGroup3;
                        labelGroup6 = labelGroup4;
                        ichibanInfoVO3 = ichibanInfoVO2;
                        l16 = l7;
                        l17 = l8;
                        str26 = str12;
                        str27 = str13;
                        bool12 = bool5;
                    case 24:
                        bool5 = bool12;
                        i5 |= 16777216;
                        Unit unit26 = Unit.INSTANCE;
                        str24 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 24, StringSerializer.INSTANCE, str24);
                        str11 = str25;
                        bool6 = bool13;
                        coverVO2 = coverVO3;
                        labelGroup3 = labelGroup5;
                        labelGroup4 = labelGroup6;
                        ichibanInfoVO2 = ichibanInfoVO3;
                        l7 = l16;
                        l8 = l17;
                        str12 = str26;
                        str13 = str27;
                        jumpUrlVO2 = jumpUrlVO4;
                        bool7 = bool14;
                        l9 = l18;
                        merchantInfo2 = merchantInfo4;
                        bool8 = bool15;
                        l10 = l19;
                        l11 = l20;
                        priceInfoVO2 = priceInfoVO4;
                        jsonObject3 = jsonObject4;
                        priceInfoVO4 = priceInfoVO2;
                        l19 = l10;
                        l20 = l11;
                        bool15 = bool8;
                        merchantInfo4 = merchantInfo2;
                        l18 = l9;
                        bool14 = bool7;
                        jumpUrlVO4 = jumpUrlVO2;
                        bool13 = bool6;
                        str25 = str11;
                        coverVO3 = coverVO2;
                        labelGroup5 = labelGroup3;
                        labelGroup6 = labelGroup4;
                        ichibanInfoVO3 = ichibanInfoVO2;
                        l16 = l7;
                        l17 = l8;
                        str26 = str12;
                        str27 = str13;
                        bool12 = bool5;
                    case 25:
                        bool5 = bool12;
                        num10 = (Integer) beginStructure.decodeNullableSerializableElement(serialDescriptor, 25, IntSerializer.INSTANCE, num10);
                        i3 = 33554432;
                        i5 |= i3;
                        Unit unit27 = Unit.INSTANCE;
                        str11 = str25;
                        bool6 = bool13;
                        coverVO2 = coverVO3;
                        labelGroup3 = labelGroup5;
                        labelGroup4 = labelGroup6;
                        ichibanInfoVO2 = ichibanInfoVO3;
                        l7 = l16;
                        l8 = l17;
                        str12 = str26;
                        str13 = str27;
                        jumpUrlVO2 = jumpUrlVO4;
                        bool7 = bool14;
                        l9 = l18;
                        merchantInfo2 = merchantInfo4;
                        bool8 = bool15;
                        l10 = l19;
                        l11 = l20;
                        priceInfoVO2 = priceInfoVO4;
                        jsonObject3 = jsonObject4;
                        priceInfoVO4 = priceInfoVO2;
                        l19 = l10;
                        l20 = l11;
                        bool15 = bool8;
                        merchantInfo4 = merchantInfo2;
                        l18 = l9;
                        bool14 = bool7;
                        jumpUrlVO4 = jumpUrlVO2;
                        bool13 = bool6;
                        str25 = str11;
                        coverVO3 = coverVO2;
                        labelGroup5 = labelGroup3;
                        labelGroup6 = labelGroup4;
                        ichibanInfoVO3 = ichibanInfoVO2;
                        l16 = l7;
                        l17 = l8;
                        str26 = str12;
                        str27 = str13;
                        bool12 = bool5;
                    case 26:
                        bool5 = bool12;
                        str20 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 26, StringSerializer.INSTANCE, str20);
                        i3 = 67108864;
                        i5 |= i3;
                        Unit unit272 = Unit.INSTANCE;
                        str11 = str25;
                        bool6 = bool13;
                        coverVO2 = coverVO3;
                        labelGroup3 = labelGroup5;
                        labelGroup4 = labelGroup6;
                        ichibanInfoVO2 = ichibanInfoVO3;
                        l7 = l16;
                        l8 = l17;
                        str12 = str26;
                        str13 = str27;
                        jumpUrlVO2 = jumpUrlVO4;
                        bool7 = bool14;
                        l9 = l18;
                        merchantInfo2 = merchantInfo4;
                        bool8 = bool15;
                        l10 = l19;
                        l11 = l20;
                        priceInfoVO2 = priceInfoVO4;
                        jsonObject3 = jsonObject4;
                        priceInfoVO4 = priceInfoVO2;
                        l19 = l10;
                        l20 = l11;
                        bool15 = bool8;
                        merchantInfo4 = merchantInfo2;
                        l18 = l9;
                        bool14 = bool7;
                        jumpUrlVO4 = jumpUrlVO2;
                        bool13 = bool6;
                        str25 = str11;
                        coverVO3 = coverVO2;
                        labelGroup5 = labelGroup3;
                        labelGroup6 = labelGroup4;
                        ichibanInfoVO3 = ichibanInfoVO2;
                        l16 = l7;
                        l17 = l8;
                        str26 = str12;
                        str27 = str13;
                        bool12 = bool5;
                    case 27:
                        bool5 = bool12;
                        str21 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 27, StringSerializer.INSTANCE, str21);
                        i3 = 134217728;
                        i5 |= i3;
                        Unit unit2722 = Unit.INSTANCE;
                        str11 = str25;
                        bool6 = bool13;
                        coverVO2 = coverVO3;
                        labelGroup3 = labelGroup5;
                        labelGroup4 = labelGroup6;
                        ichibanInfoVO2 = ichibanInfoVO3;
                        l7 = l16;
                        l8 = l17;
                        str12 = str26;
                        str13 = str27;
                        jumpUrlVO2 = jumpUrlVO4;
                        bool7 = bool14;
                        l9 = l18;
                        merchantInfo2 = merchantInfo4;
                        bool8 = bool15;
                        l10 = l19;
                        l11 = l20;
                        priceInfoVO2 = priceInfoVO4;
                        jsonObject3 = jsonObject4;
                        priceInfoVO4 = priceInfoVO2;
                        l19 = l10;
                        l20 = l11;
                        bool15 = bool8;
                        merchantInfo4 = merchantInfo2;
                        l18 = l9;
                        bool14 = bool7;
                        jumpUrlVO4 = jumpUrlVO2;
                        bool13 = bool6;
                        str25 = str11;
                        coverVO3 = coverVO2;
                        labelGroup5 = labelGroup3;
                        labelGroup6 = labelGroup4;
                        ichibanInfoVO3 = ichibanInfoVO2;
                        l16 = l7;
                        l17 = l8;
                        str26 = str12;
                        str27 = str13;
                        bool12 = bool5;
                    case 28:
                        bool5 = bool12;
                        i5 |= 268435456;
                        Unit unit28 = Unit.INSTANCE;
                        num13 = (Integer) beginStructure.decodeNullableSerializableElement(serialDescriptor, 28, IntSerializer.INSTANCE, num13);
                        str11 = str25;
                        bool6 = bool13;
                        coverVO2 = coverVO3;
                        labelGroup3 = labelGroup5;
                        labelGroup4 = labelGroup6;
                        ichibanInfoVO2 = ichibanInfoVO3;
                        l7 = l16;
                        l8 = l17;
                        str12 = str26;
                        str13 = str27;
                        jumpUrlVO2 = jumpUrlVO4;
                        bool7 = bool14;
                        l9 = l18;
                        merchantInfo2 = merchantInfo4;
                        bool8 = bool15;
                        l10 = l19;
                        l11 = l20;
                        priceInfoVO2 = priceInfoVO4;
                        jsonObject3 = jsonObject4;
                        priceInfoVO4 = priceInfoVO2;
                        l19 = l10;
                        l20 = l11;
                        bool15 = bool8;
                        merchantInfo4 = merchantInfo2;
                        l18 = l9;
                        bool14 = bool7;
                        jumpUrlVO4 = jumpUrlVO2;
                        bool13 = bool6;
                        str25 = str11;
                        coverVO3 = coverVO2;
                        labelGroup5 = labelGroup3;
                        labelGroup6 = labelGroup4;
                        ichibanInfoVO3 = ichibanInfoVO2;
                        l16 = l7;
                        l17 = l8;
                        str26 = str12;
                        str27 = str13;
                        bool12 = bool5;
                    case 29:
                        bool5 = bool12;
                        i5 |= 536870912;
                        Unit unit29 = Unit.INSTANCE;
                        str28 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 29, StringSerializer.INSTANCE, str28);
                        str11 = str25;
                        bool6 = bool13;
                        coverVO2 = coverVO3;
                        labelGroup3 = labelGroup5;
                        labelGroup4 = labelGroup6;
                        ichibanInfoVO2 = ichibanInfoVO3;
                        l7 = l16;
                        l8 = l17;
                        str12 = str26;
                        str13 = str27;
                        jumpUrlVO2 = jumpUrlVO4;
                        bool7 = bool14;
                        l9 = l18;
                        merchantInfo2 = merchantInfo4;
                        bool8 = bool15;
                        l10 = l19;
                        l11 = l20;
                        priceInfoVO2 = priceInfoVO4;
                        jsonObject3 = jsonObject4;
                        priceInfoVO4 = priceInfoVO2;
                        l19 = l10;
                        l20 = l11;
                        bool15 = bool8;
                        merchantInfo4 = merchantInfo2;
                        l18 = l9;
                        bool14 = bool7;
                        jumpUrlVO4 = jumpUrlVO2;
                        bool13 = bool6;
                        str25 = str11;
                        coverVO3 = coverVO2;
                        labelGroup5 = labelGroup3;
                        labelGroup6 = labelGroup4;
                        ichibanInfoVO3 = ichibanInfoVO2;
                        l16 = l7;
                        l17 = l8;
                        str26 = str12;
                        str27 = str13;
                        bool12 = bool5;
                    case 30:
                        bool5 = bool12;
                        i5 |= 1073741824;
                        Unit unit30 = Unit.INSTANCE;
                        str23 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 30, StringSerializer.INSTANCE, str23);
                        str11 = str25;
                        bool6 = bool13;
                        coverVO2 = coverVO3;
                        labelGroup3 = labelGroup5;
                        labelGroup4 = labelGroup6;
                        ichibanInfoVO2 = ichibanInfoVO3;
                        l7 = l16;
                        l8 = l17;
                        str12 = str26;
                        str13 = str27;
                        jumpUrlVO2 = jumpUrlVO4;
                        bool7 = bool14;
                        l9 = l18;
                        merchantInfo2 = merchantInfo4;
                        bool8 = bool15;
                        l10 = l19;
                        l11 = l20;
                        priceInfoVO2 = priceInfoVO4;
                        jsonObject3 = jsonObject4;
                        priceInfoVO4 = priceInfoVO2;
                        l19 = l10;
                        l20 = l11;
                        bool15 = bool8;
                        merchantInfo4 = merchantInfo2;
                        l18 = l9;
                        bool14 = bool7;
                        jumpUrlVO4 = jumpUrlVO2;
                        bool13 = bool6;
                        str25 = str11;
                        coverVO3 = coverVO2;
                        labelGroup5 = labelGroup3;
                        labelGroup6 = labelGroup4;
                        ichibanInfoVO3 = ichibanInfoVO2;
                        l16 = l7;
                        l17 = l8;
                        str26 = str12;
                        str27 = str13;
                        bool12 = bool5;
                    case ConstantsKt.UPDATE_CALENDAR_CARD_VIDEO_DURATION_WIDTH /* 31 */:
                        bool5 = bool12;
                        i5 |= Integer.MIN_VALUE;
                        Unit unit31 = Unit.INSTANCE;
                        str22 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 31, StringSerializer.INSTANCE, str22);
                        str11 = str25;
                        bool6 = bool13;
                        coverVO2 = coverVO3;
                        labelGroup3 = labelGroup5;
                        labelGroup4 = labelGroup6;
                        ichibanInfoVO2 = ichibanInfoVO3;
                        l7 = l16;
                        l8 = l17;
                        str12 = str26;
                        str13 = str27;
                        jumpUrlVO2 = jumpUrlVO4;
                        bool7 = bool14;
                        l9 = l18;
                        merchantInfo2 = merchantInfo4;
                        bool8 = bool15;
                        l10 = l19;
                        l11 = l20;
                        priceInfoVO2 = priceInfoVO4;
                        jsonObject3 = jsonObject4;
                        priceInfoVO4 = priceInfoVO2;
                        l19 = l10;
                        l20 = l11;
                        bool15 = bool8;
                        merchantInfo4 = merchantInfo2;
                        l18 = l9;
                        bool14 = bool7;
                        jumpUrlVO4 = jumpUrlVO2;
                        bool13 = bool6;
                        str25 = str11;
                        coverVO3 = coverVO2;
                        labelGroup5 = labelGroup3;
                        labelGroup6 = labelGroup4;
                        ichibanInfoVO3 = ichibanInfoVO2;
                        l16 = l7;
                        l17 = l8;
                        str26 = str12;
                        str27 = str13;
                        bool12 = bool5;
                    case 32:
                        bool5 = bool12;
                        Unit unit32 = Unit.INSTANCE;
                        num12 = (Integer) beginStructure.decodeNullableSerializableElement(serialDescriptor, 32, IntSerializer.INSTANCE, num12);
                        str11 = str25;
                        bool6 = bool13;
                        coverVO2 = coverVO3;
                        labelGroup3 = labelGroup5;
                        labelGroup4 = labelGroup6;
                        ichibanInfoVO2 = ichibanInfoVO3;
                        l7 = l16;
                        l8 = l17;
                        str12 = str26;
                        str13 = str27;
                        jumpUrlVO2 = jumpUrlVO4;
                        bool7 = bool14;
                        l9 = l18;
                        merchantInfo2 = merchantInfo4;
                        bool8 = bool15;
                        l10 = l19;
                        l11 = l20;
                        priceInfoVO2 = priceInfoVO4;
                        jsonObject3 = jsonObject4;
                        i4 = 1;
                        continue;
                        priceInfoVO4 = priceInfoVO2;
                        l19 = l10;
                        l20 = l11;
                        bool15 = bool8;
                        merchantInfo4 = merchantInfo2;
                        l18 = l9;
                        bool14 = bool7;
                        jumpUrlVO4 = jumpUrlVO2;
                        bool13 = bool6;
                        str25 = str11;
                        coverVO3 = coverVO2;
                        labelGroup5 = labelGroup3;
                        labelGroup6 = labelGroup4;
                        ichibanInfoVO3 = ichibanInfoVO2;
                        l16 = l7;
                        l17 = l8;
                        str26 = str12;
                        str27 = str13;
                        bool12 = bool5;
                    default:
                        throw new UnknownFieldException(decodeElementIndex);
                }
                str20 = str10;
                jsonObject3 = jsonObject4;
                num10 = num5;
                priceInfoVO4 = priceInfoVO2;
                l19 = l10;
                l20 = l11;
                bool15 = bool8;
                merchantInfo4 = merchantInfo2;
                l18 = l9;
                bool14 = bool7;
                jumpUrlVO4 = jumpUrlVO2;
                bool13 = bool6;
                str25 = str11;
                coverVO3 = coverVO2;
                labelGroup5 = labelGroup3;
                labelGroup6 = labelGroup4;
                ichibanInfoVO3 = ichibanInfoVO2;
                l16 = l7;
                l17 = l8;
                str26 = str12;
                str27 = str13;
                bool12 = bool5;
            }
            String str29 = str20;
            List list3 = list2;
            String str30 = str25;
            Boolean bool17 = bool13;
            CoverVO coverVO4 = coverVO3;
            ShopItem.LabelGroup labelGroup7 = labelGroup5;
            str = str21;
            str2 = str22;
            num = num12;
            str3 = str23;
            num2 = num13;
            str4 = str28;
            bool = bool17;
            str5 = str30;
            ichibanInfoVO = ichibanInfoVO3;
            str6 = str27;
            i = i4;
            list = list3;
            l = l15;
            str7 = str29;
            priceInfoVO = priceInfoVO4;
            l2 = l20;
            jumpUrlVO = jumpUrlVO4;
            labelGroup = labelGroup6;
            l3 = l16;
            l4 = l17;
            bool2 = bool12;
            num3 = num11;
            i2 = i5;
            str8 = str24;
            l5 = l19;
            coverVO = coverVO4;
            labelGroup2 = labelGroup7;
            str9 = str26;
            jsonObject = jsonObject3;
            num4 = num10;
            promotionImg = promotionImg3;
            bool3 = bool15;
            bool4 = bool14;
            merchantInfo = merchantInfo4;
            l6 = l18;
        }
        beginStructure.endStructure(serialDescriptor);
        return new ShopItem(i2, i, list, str5, bool, coverVO, labelGroup2, labelGroup, ichibanInfoVO, l3, l4, str9, str6, jumpUrlVO, bool4, l6, merchantInfo, bool3, l5, l2, priceInfoVO, promotionImg, jsonObject, bool2, l, num3, str8, num4, str7, str, num2, str4, str3, str2, num, (SerializationConstructorMarker) null);
    }

    public final void serialize(Encoder encoder, ShopItem value) {
        Intrinsics.checkNotNullParameter(encoder, "encoder");
        Intrinsics.checkNotNullParameter(value, "value");
        SerialDescriptor serialDescriptor = descriptor;
        CompositeEncoder beginStructure = encoder.beginStructure(serialDescriptor);
        ShopItem.write$Self$product_details_page_debug(value, beginStructure, serialDescriptor);
        beginStructure.endStructure(serialDescriptor);
    }

    public /* bridge */ KSerializer<?>[] typeParametersSerializers() {
        return GeneratedSerializer.DefaultImpls.typeParametersSerializers(this);
    }
}