package kntr.app.mall.product.details.page.api.model;

import com.bapis.bilibili.app.dynamic.v2.AdditionalButton;
import java.util.List;
import kntr.app.mall.product.details.page.api.model.SkuInfoFloor;
import kntr.app.upcomingEpisode.ConstantsKt;
import kntr.watch.later.watchlater.edit.MediaAttrUtils;
import kotlin.Deprecated;
import kotlin.DeprecationLevel;
import kotlin.Lazy;
import kotlin.Metadata;
import kotlin.Unit;
import kotlin.jvm.internal.Intrinsics;
import kotlinx.serialization.DeserializationStrategy;
import kotlinx.serialization.KSerializer;
import kotlinx.serialization.UnknownFieldException;
import kotlinx.serialization.builtins.BuiltinSerializersKt;
import kotlinx.serialization.descriptors.SerialDescriptor;
import kotlinx.serialization.encoding.CompositeDecoder;
import kotlinx.serialization.encoding.CompositeEncoder;
import kotlinx.serialization.encoding.Decoder;
import kotlinx.serialization.encoding.Encoder;
import kotlinx.serialization.internal.BooleanSerializer;
import kotlinx.serialization.internal.ByteSerializer;
import kotlinx.serialization.internal.GeneratedSerializer;
import kotlinx.serialization.internal.IntSerializer;
import kotlinx.serialization.internal.LongSerializer;
import kotlinx.serialization.internal.PluginGeneratedSerialDescriptor;
import kotlinx.serialization.internal.SerializationConstructorMarker;
import kotlinx.serialization.internal.StringSerializer;

/* compiled from: SkuInfoFloor.kt */
@Metadata(d1 = {"\u00006\n\u0000\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\b\u0003\n\u0002\u0010\u0011\n\u0002\u0018\u0002\n\u0002\b\u0003\n\u0002\u0018\u0002\n\u0000\n\u0002\u0010\u0002\n\u0000\n\u0002\u0018\u0002\n\u0002\b\u0002\n\u0002\u0018\u0002\n\u0002\b\u0003\bÇ\u0002\u0018\u00002\b\u0012\u0004\u0012\u00020\u00020\u0001B\t\b\u0002¢\u0006\u0004\b\u0003\u0010\u0004J\u0015\u0010\u0005\u001a\f\u0012\b\u0012\u0006\u0012\u0002\b\u00030\u00070\u0006¢\u0006\u0002\u0010\bJ\u000e\u0010\t\u001a\u00020\u00022\u0006\u0010\n\u001a\u00020\u000bJ\u0016\u0010\f\u001a\u00020\r2\u0006\u0010\u000e\u001a\u00020\u000f2\u0006\u0010\u0010\u001a\u00020\u0002R\u0011\u0010\u0011\u001a\u00020\u0012¢\u0006\b\n\u0000\u001a\u0004\b\u0013\u0010\u0014¨\u0006\u0015"}, d2 = {"kntr/app/mall/product/details/page/api/model/SkuInfoFloor.ItemsSkuListVO.ItemsSkuListItem.$serializer", "Lkotlinx/serialization/internal/GeneratedSerializer;", "Lkntr/app/mall/product/details/page/api/model/SkuInfoFloor$ItemsSkuListVO$ItemsSkuListItem;", "<init>", "()V", "childSerializers", "", "Lkotlinx/serialization/KSerializer;", "()[Lkotlinx/serialization/KSerializer;", "deserialize", "decoder", "Lkotlinx/serialization/encoding/Decoder;", "serialize", "", "encoder", "Lkotlinx/serialization/encoding/Encoder;", "value", "descriptor", "Lkotlinx/serialization/descriptors/SerialDescriptor;", "getDescriptor", "()Lkotlinx/serialization/descriptors/SerialDescriptor;", "product-details-page_debug"}, k = 1, mv = {2, 2, 0}, xi = ConstantsKt.OGV_UPDATE_CALENDAR_CARD_COVER_WIDTH)
@Deprecated(level = DeprecationLevel.HIDDEN, message = "This synthesized declaration should not be used directly")
public final /* synthetic */ class SkuInfoFloor$ItemsSkuListVO$ItemsSkuListItem$$serializer implements GeneratedSerializer<SkuInfoFloor.ItemsSkuListVO.ItemsSkuListItem> {
    public static final int $stable;
    public static final SkuInfoFloor$ItemsSkuListVO$ItemsSkuListItem$$serializer INSTANCE = new SkuInfoFloor$ItemsSkuListVO$ItemsSkuListItem$$serializer();
    private static final SerialDescriptor descriptor;

    public final SerialDescriptor getDescriptor() {
        return descriptor;
    }

    static {
        SerialDescriptor pluginGeneratedSerialDescriptor = new PluginGeneratedSerialDescriptor("kntr.app.mall.product.details.page.api.model.SkuInfoFloor.ItemsSkuListVO.ItemsSkuListItem", INSTANCE, 30);
        pluginGeneratedSerialDescriptor.addElement("activityDeposit", true);
        pluginGeneratedSerialDescriptor.addElement("activityPrice", true);
        pluginGeneratedSerialDescriptor.addElement("activityRestriction", true);
        pluginGeneratedSerialDescriptor.addElement("activitySaleStatus", true);
        pluginGeneratedSerialDescriptor.addElement("activityStock", true);
        pluginGeneratedSerialDescriptor.addElement("activityType", true);
        pluginGeneratedSerialDescriptor.addElement("asyncSku", true);
        pluginGeneratedSerialDescriptor.addElement("autoOnSaleTime", true);
        pluginGeneratedSerialDescriptor.addElement("canAddCart", true);
        pluginGeneratedSerialDescriptor.addElement("deposit", true);
        pluginGeneratedSerialDescriptor.addElement("id", true);
        pluginGeneratedSerialDescriptor.addElement("img", true);
        pluginGeneratedSerialDescriptor.addElement("isShow", true);
        pluginGeneratedSerialDescriptor.addElement("itemsStep", true);
        pluginGeneratedSerialDescriptor.addElement("lessonId", true);
        pluginGeneratedSerialDescriptor.addElement("limitBuy", true);
        pluginGeneratedSerialDescriptor.addElement("linePrice", true);
        pluginGeneratedSerialDescriptor.addElement("preDepositPrice", true);
        pluginGeneratedSerialDescriptor.addElement("price", true);
        pluginGeneratedSerialDescriptor.addElement("referencePrice", true);
        pluginGeneratedSerialDescriptor.addElement("saleType", true);
        pluginGeneratedSerialDescriptor.addElement("skuTagVO", true);
        pluginGeneratedSerialDescriptor.addElement("specValueId", true);
        pluginGeneratedSerialDescriptor.addElement("specValues", true);
        pluginGeneratedSerialDescriptor.addElement("status", true);
        pluginGeneratedSerialDescriptor.addElement("stock", true);
        pluginGeneratedSerialDescriptor.addElement("stockLevel", true);
        pluginGeneratedSerialDescriptor.addElement("subStatus", true);
        pluginGeneratedSerialDescriptor.addElement("warnStock", true);
        pluginGeneratedSerialDescriptor.addElement("whiteListSku", true);
        descriptor = pluginGeneratedSerialDescriptor;
        $stable = 8;
    }

    private SkuInfoFloor$ItemsSkuListVO$ItemsSkuListItem$$serializer() {
    }

    public final KSerializer<?>[] childSerializers() {
        Lazy[] lazyArr;
        lazyArr = SkuInfoFloor.ItemsSkuListVO.ItemsSkuListItem.$childSerializers;
        return new KSerializer[]{BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(IntSerializer.INSTANCE), BuiltinSerializersKt.getNullable(IntSerializer.INSTANCE), BuiltinSerializersKt.getNullable(IntSerializer.INSTANCE), BuiltinSerializersKt.getNullable(ByteSerializer.INSTANCE), BuiltinSerializersKt.getNullable(BooleanSerializer.INSTANCE), BuiltinSerializersKt.getNullable(IntSerializer.INSTANCE), BuiltinSerializersKt.getNullable(ByteSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(LongSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(ByteSerializer.INSTANCE), BuiltinSerializersKt.getNullable(IntSerializer.INSTANCE), BuiltinSerializersKt.getNullable(LongSerializer.INSTANCE), BuiltinSerializersKt.getNullable(BooleanSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(ByteSerializer.INSTANCE), BuiltinSerializersKt.getNullable(SkuInfoFloor$ItemsSkuListVO$ItemsSkuListItem$SkuTag$$serializer.INSTANCE), BuiltinSerializersKt.getNullable(LongSerializer.INSTANCE), BuiltinSerializersKt.getNullable((KSerializer) lazyArr[23].getValue()), BuiltinSerializersKt.getNullable(ByteSerializer.INSTANCE), BuiltinSerializersKt.getNullable(IntSerializer.INSTANCE), BuiltinSerializersKt.getNullable(IntSerializer.INSTANCE), BuiltinSerializersKt.getNullable(ByteSerializer.INSTANCE), BuiltinSerializersKt.getNullable(IntSerializer.INSTANCE), BuiltinSerializersKt.getNullable(BooleanSerializer.INSTANCE)};
    }

    public final SkuInfoFloor.ItemsSkuListVO.ItemsSkuListItem deserialize(Decoder decoder) {
        Lazy[] lazyArr;
        Integer num;
        Boolean bool;
        Integer num2;
        Byte b;
        Integer num3;
        int i;
        Byte b2;
        String str;
        Byte b3;
        String str2;
        String str3;
        Boolean bool2;
        Integer num4;
        String str4;
        String str5;
        List list;
        Long l;
        Integer num5;
        Long l2;
        Byte b4;
        String str6;
        Integer num6;
        Integer num7;
        SkuInfoFloor.ItemsSkuListVO.ItemsSkuListItem.SkuTag skuTag;
        String str7;
        Integer num8;
        Boolean bool3;
        Byte b5;
        String str8;
        Byte b6;
        Long l3;
        Byte b7;
        Lazy[] lazyArr2;
        String str9;
        String str10;
        Integer num9;
        Integer num10;
        Integer num11;
        Byte b8;
        Boolean bool4;
        Integer num12;
        Byte b9;
        String str11;
        Long l4;
        String str12;
        Byte b10;
        Integer num13;
        Long l5;
        Boolean bool5;
        String str13;
        String str14;
        String str15;
        String str16;
        int i2;
        Intrinsics.checkNotNullParameter(decoder, "decoder");
        SerialDescriptor serialDescriptor = descriptor;
        CompositeDecoder beginStructure = decoder.beginStructure(serialDescriptor);
        lazyArr = SkuInfoFloor.ItemsSkuListVO.ItemsSkuListItem.$childSerializers;
        if (beginStructure.decodeSequentially()) {
            Long l6 = (Long) beginStructure.decodeNullableSerializableElement(serialDescriptor, 10, LongSerializer.INSTANCE, (Object) null);
            String str17 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 11, StringSerializer.INSTANCE, (Object) null);
            Byte b11 = (Byte) beginStructure.decodeNullableSerializableElement(serialDescriptor, 12, ByteSerializer.INSTANCE, (Object) null);
            Integer num14 = (Integer) beginStructure.decodeNullableSerializableElement(serialDescriptor, 13, IntSerializer.INSTANCE, (Object) null);
            Long l7 = (Long) beginStructure.decodeNullableSerializableElement(serialDescriptor, 14, LongSerializer.INSTANCE, (Object) null);
            Boolean bool6 = (Boolean) beginStructure.decodeNullableSerializableElement(serialDescriptor, 15, BooleanSerializer.INSTANCE, (Object) null);
            String str18 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 16, StringSerializer.INSTANCE, (Object) null);
            String str19 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 17, StringSerializer.INSTANCE, (Object) null);
            String str20 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 18, StringSerializer.INSTANCE, (Object) null);
            String str21 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 19, StringSerializer.INSTANCE, (Object) null);
            Byte b12 = (Byte) beginStructure.decodeNullableSerializableElement(serialDescriptor, 20, ByteSerializer.INSTANCE, (Object) null);
            SkuInfoFloor.ItemsSkuListVO.ItemsSkuListItem.SkuTag skuTag2 = (SkuInfoFloor.ItemsSkuListVO.ItemsSkuListItem.SkuTag) beginStructure.decodeNullableSerializableElement(serialDescriptor, 21, SkuInfoFloor$ItemsSkuListVO$ItemsSkuListItem$SkuTag$$serializer.INSTANCE, (Object) null);
            Long l8 = (Long) beginStructure.decodeNullableSerializableElement(serialDescriptor, 22, LongSerializer.INSTANCE, (Object) null);
            Byte b13 = (Byte) beginStructure.decodeNullableSerializableElement(serialDescriptor, 24, ByteSerializer.INSTANCE, (Object) null);
            Integer num15 = (Integer) beginStructure.decodeNullableSerializableElement(serialDescriptor, 25, IntSerializer.INSTANCE, (Object) null);
            Integer num16 = (Integer) beginStructure.decodeNullableSerializableElement(serialDescriptor, 26, IntSerializer.INSTANCE, (Object) null);
            Byte b14 = (Byte) beginStructure.decodeNullableSerializableElement(serialDescriptor, 27, ByteSerializer.INSTANCE, (Object) null);
            Integer num17 = (Integer) beginStructure.decodeNullableSerializableElement(serialDescriptor, 28, IntSerializer.INSTANCE, (Object) null);
            bool = (Boolean) beginStructure.decodeNullableSerializableElement(serialDescriptor, 29, BooleanSerializer.INSTANCE, (Object) null);
            list = (List) beginStructure.decodeNullableSerializableElement(serialDescriptor, 23, (DeserializationStrategy) lazyArr[23].getValue(), (Object) null);
            num8 = (Integer) beginStructure.decodeNullableSerializableElement(serialDescriptor, 3, IntSerializer.INSTANCE, (Object) null);
            l3 = l8;
            b4 = b13;
            num = num15;
            num3 = num16;
            b = b14;
            num2 = num17;
            str3 = str21;
            str7 = str20;
            str8 = str19;
            b2 = b11;
            str4 = str17;
            b5 = b12;
            skuTag = skuTag2;
            bool3 = (Boolean) beginStructure.decodeNullableSerializableElement(serialDescriptor, 6, BooleanSerializer.INSTANCE, (Object) null);
            b3 = (Byte) beginStructure.decodeNullableSerializableElement(serialDescriptor, 5, ByteSerializer.INSTANCE, (Object) null);
            num6 = (Integer) beginStructure.decodeNullableSerializableElement(serialDescriptor, 4, IntSerializer.INSTANCE, (Object) null);
            bool2 = bool6;
            str6 = str18;
            num4 = num14;
            l2 = l6;
            b6 = (Byte) beginStructure.decodeNullableSerializableElement(serialDescriptor, 8, ByteSerializer.INSTANCE, (Object) null);
            num7 = (Integer) beginStructure.decodeNullableSerializableElement(serialDescriptor, 7, IntSerializer.INSTANCE, (Object) null);
            l = l7;
            str2 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 0, StringSerializer.INSTANCE, (Object) null);
            str5 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 9, StringSerializer.INSTANCE, (Object) null);
            num5 = (Integer) beginStructure.decodeNullableSerializableElement(serialDescriptor, 2, IntSerializer.INSTANCE, (Object) null);
            str = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 1, StringSerializer.INSTANCE, (Object) null);
            i = 1073741823;
        } else {
            boolean z = true;
            Byte b15 = null;
            Integer num18 = null;
            Byte b16 = null;
            String str22 = null;
            Boolean bool7 = null;
            Long l9 = null;
            String str23 = null;
            Integer num19 = null;
            Byte b17 = null;
            List list2 = null;
            SkuInfoFloor.ItemsSkuListVO.ItemsSkuListItem.SkuTag skuTag3 = null;
            String str24 = null;
            String str25 = null;
            Integer num20 = null;
            Integer num21 = null;
            Integer num22 = null;
            Byte b18 = null;
            Boolean bool8 = null;
            Integer num23 = null;
            Byte b19 = null;
            String str26 = null;
            Long l10 = null;
            String str27 = null;
            Byte b20 = null;
            Integer num24 = null;
            Long l11 = null;
            Boolean bool9 = null;
            String str28 = null;
            String str29 = null;
            int i3 = 0;
            Integer num25 = null;
            while (z) {
                String str30 = str23;
                int decodeElementIndex = beginStructure.decodeElementIndex(serialDescriptor);
                switch (decodeElementIndex) {
                    case -1:
                        b7 = b15;
                        lazyArr2 = lazyArr;
                        str9 = str22;
                        str10 = str25;
                        num9 = num20;
                        num10 = num21;
                        num11 = num22;
                        b8 = b18;
                        bool4 = bool8;
                        num12 = num23;
                        b9 = b19;
                        str11 = str26;
                        l4 = l10;
                        str12 = str27;
                        b10 = b20;
                        num13 = num24;
                        l5 = l11;
                        bool5 = bool9;
                        str13 = str28;
                        str14 = str29;
                        str15 = str30;
                        Unit unit = Unit.INSTANCE;
                        z = false;
                        str22 = str9;
                        b15 = b7;
                        str23 = str15;
                        break;
                    case 0:
                        b7 = b15;
                        lazyArr2 = lazyArr;
                        str9 = str22;
                        num9 = num20;
                        num10 = num21;
                        num11 = num22;
                        b8 = b18;
                        bool4 = bool8;
                        num12 = num23;
                        b9 = b19;
                        str11 = str26;
                        l4 = l10;
                        str12 = str27;
                        b10 = b20;
                        num13 = num24;
                        l5 = l11;
                        bool5 = bool9;
                        str13 = str28;
                        str14 = str29;
                        str15 = str30;
                        str10 = str25;
                        i3 |= 1;
                        Unit unit2 = Unit.INSTANCE;
                        str24 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 0, StringSerializer.INSTANCE, str24);
                        str22 = str9;
                        b15 = b7;
                        str23 = str15;
                        break;
                    case 1:
                        lazyArr2 = lazyArr;
                        String str31 = str22;
                        num10 = num21;
                        num11 = num22;
                        b8 = b18;
                        bool4 = bool8;
                        num12 = num23;
                        b9 = b19;
                        str11 = str26;
                        l4 = l10;
                        str12 = str27;
                        b10 = b20;
                        num13 = num24;
                        l5 = l11;
                        bool5 = bool9;
                        str13 = str28;
                        str14 = str29;
                        num9 = num20;
                        i3 |= 2;
                        Unit unit3 = Unit.INSTANCE;
                        str10 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 1, StringSerializer.INSTANCE, str25);
                        str22 = str31;
                        b15 = b15;
                        str23 = str30;
                        break;
                    case 2:
                        lazyArr2 = lazyArr;
                        String str32 = str22;
                        num11 = num22;
                        b8 = b18;
                        bool4 = bool8;
                        num12 = num23;
                        b9 = b19;
                        str11 = str26;
                        l4 = l10;
                        str12 = str27;
                        b10 = b20;
                        num13 = num24;
                        l5 = l11;
                        bool5 = bool9;
                        str13 = str28;
                        str14 = str29;
                        num10 = num21;
                        i3 |= 4;
                        Unit unit4 = Unit.INSTANCE;
                        num9 = (Integer) beginStructure.decodeNullableSerializableElement(serialDescriptor, 2, IntSerializer.INSTANCE, num20);
                        str22 = str32;
                        b15 = b15;
                        str23 = str30;
                        str10 = str25;
                        break;
                    case 3:
                        lazyArr2 = lazyArr;
                        String str33 = str22;
                        b8 = b18;
                        bool4 = bool8;
                        num12 = num23;
                        b9 = b19;
                        str11 = str26;
                        l4 = l10;
                        str12 = str27;
                        b10 = b20;
                        num13 = num24;
                        l5 = l11;
                        bool5 = bool9;
                        str13 = str28;
                        str14 = str29;
                        num11 = num22;
                        i3 |= 8;
                        Unit unit5 = Unit.INSTANCE;
                        num10 = (Integer) beginStructure.decodeNullableSerializableElement(serialDescriptor, 3, IntSerializer.INSTANCE, num21);
                        str22 = str33;
                        b15 = b15;
                        str23 = str30;
                        str10 = str25;
                        num9 = num20;
                        break;
                    case 4:
                        lazyArr2 = lazyArr;
                        String str34 = str22;
                        bool4 = bool8;
                        num12 = num23;
                        b9 = b19;
                        str11 = str26;
                        l4 = l10;
                        str12 = str27;
                        b10 = b20;
                        num13 = num24;
                        l5 = l11;
                        bool5 = bool9;
                        str13 = str28;
                        str14 = str29;
                        b8 = b18;
                        i3 |= 16;
                        Unit unit6 = Unit.INSTANCE;
                        num11 = (Integer) beginStructure.decodeNullableSerializableElement(serialDescriptor, 4, IntSerializer.INSTANCE, num22);
                        str22 = str34;
                        b15 = b15;
                        str23 = str30;
                        str10 = str25;
                        num9 = num20;
                        num10 = num21;
                        break;
                    case 5:
                        lazyArr2 = lazyArr;
                        String str35 = str22;
                        num12 = num23;
                        b9 = b19;
                        str11 = str26;
                        l4 = l10;
                        str12 = str27;
                        b10 = b20;
                        num13 = num24;
                        l5 = l11;
                        bool5 = bool9;
                        str13 = str28;
                        str14 = str29;
                        bool4 = bool8;
                        i3 |= 32;
                        Unit unit7 = Unit.INSTANCE;
                        b8 = (Byte) beginStructure.decodeNullableSerializableElement(serialDescriptor, 5, ByteSerializer.INSTANCE, b18);
                        str22 = str35;
                        b15 = b15;
                        str23 = str30;
                        str10 = str25;
                        num9 = num20;
                        num10 = num21;
                        num11 = num22;
                        break;
                    case 6:
                        lazyArr2 = lazyArr;
                        String str36 = str22;
                        b9 = b19;
                        str11 = str26;
                        l4 = l10;
                        str12 = str27;
                        b10 = b20;
                        num13 = num24;
                        l5 = l11;
                        bool5 = bool9;
                        str13 = str28;
                        str14 = str29;
                        num12 = num23;
                        i3 |= 64;
                        Unit unit8 = Unit.INSTANCE;
                        bool4 = (Boolean) beginStructure.decodeNullableSerializableElement(serialDescriptor, 6, BooleanSerializer.INSTANCE, bool8);
                        str22 = str36;
                        b15 = b15;
                        str23 = str30;
                        str10 = str25;
                        num9 = num20;
                        num10 = num21;
                        num11 = num22;
                        b8 = b18;
                        break;
                    case AdditionalButton.CLICK_TYPE_FIELD_NUMBER /* 7 */:
                        lazyArr2 = lazyArr;
                        String str37 = str22;
                        str11 = str26;
                        l4 = l10;
                        str12 = str27;
                        b10 = b20;
                        num13 = num24;
                        l5 = l11;
                        bool5 = bool9;
                        str13 = str28;
                        str14 = str29;
                        b9 = b19;
                        i3 |= 128;
                        Unit unit9 = Unit.INSTANCE;
                        num12 = (Integer) beginStructure.decodeNullableSerializableElement(serialDescriptor, 7, IntSerializer.INSTANCE, num23);
                        str22 = str37;
                        b15 = b15;
                        str23 = str30;
                        str10 = str25;
                        num9 = num20;
                        num10 = num21;
                        num11 = num22;
                        b8 = b18;
                        bool4 = bool8;
                        break;
                    case 8:
                        lazyArr2 = lazyArr;
                        String str38 = str22;
                        l4 = l10;
                        str12 = str27;
                        b10 = b20;
                        num13 = num24;
                        l5 = l11;
                        bool5 = bool9;
                        str13 = str28;
                        str14 = str29;
                        str11 = str26;
                        i3 |= 256;
                        Unit unit10 = Unit.INSTANCE;
                        b9 = (Byte) beginStructure.decodeNullableSerializableElement(serialDescriptor, 8, ByteSerializer.INSTANCE, b19);
                        str22 = str38;
                        b15 = b15;
                        str23 = str30;
                        str10 = str25;
                        num9 = num20;
                        num10 = num21;
                        num11 = num22;
                        b8 = b18;
                        bool4 = bool8;
                        num12 = num23;
                        break;
                    case ConstantsKt.SPACER_9 /* 9 */:
                        lazyArr2 = lazyArr;
                        String str39 = str22;
                        str12 = str27;
                        b10 = b20;
                        num13 = num24;
                        l5 = l11;
                        bool5 = bool9;
                        str13 = str28;
                        str14 = str29;
                        l4 = l10;
                        i3 |= 512;
                        Unit unit11 = Unit.INSTANCE;
                        str11 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 9, StringSerializer.INSTANCE, str26);
                        str22 = str39;
                        b15 = b15;
                        str23 = str30;
                        str10 = str25;
                        num9 = num20;
                        num10 = num21;
                        num11 = num22;
                        b8 = b18;
                        bool4 = bool8;
                        num12 = num23;
                        b9 = b19;
                        break;
                    case 10:
                        lazyArr2 = lazyArr;
                        String str40 = str22;
                        b10 = b20;
                        num13 = num24;
                        l5 = l11;
                        bool5 = bool9;
                        str13 = str28;
                        str14 = str29;
                        str12 = str27;
                        i3 |= 1024;
                        Unit unit12 = Unit.INSTANCE;
                        l4 = (Long) beginStructure.decodeNullableSerializableElement(serialDescriptor, 10, LongSerializer.INSTANCE, l10);
                        str22 = str40;
                        b15 = b15;
                        str23 = str30;
                        str10 = str25;
                        num9 = num20;
                        num10 = num21;
                        num11 = num22;
                        b8 = b18;
                        bool4 = bool8;
                        num12 = num23;
                        b9 = b19;
                        str11 = str26;
                        break;
                    case MediaAttrUtils.TYPE_MENU /* 11 */:
                        lazyArr2 = lazyArr;
                        String str41 = str22;
                        num13 = num24;
                        l5 = l11;
                        bool5 = bool9;
                        str13 = str28;
                        str14 = str29;
                        b10 = b20;
                        i3 |= 2048;
                        Unit unit13 = Unit.INSTANCE;
                        str12 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 11, StringSerializer.INSTANCE, str27);
                        str22 = str41;
                        b15 = b15;
                        str23 = str30;
                        str10 = str25;
                        num9 = num20;
                        num10 = num21;
                        num11 = num22;
                        b8 = b18;
                        bool4 = bool8;
                        num12 = num23;
                        b9 = b19;
                        str11 = str26;
                        l4 = l10;
                        break;
                    case 12:
                        lazyArr2 = lazyArr;
                        String str42 = str22;
                        l5 = l11;
                        bool5 = bool9;
                        str13 = str28;
                        str14 = str29;
                        num13 = num24;
                        i3 |= 4096;
                        Unit unit14 = Unit.INSTANCE;
                        b10 = (Byte) beginStructure.decodeNullableSerializableElement(serialDescriptor, 12, ByteSerializer.INSTANCE, b20);
                        str22 = str42;
                        b15 = b15;
                        str23 = str30;
                        str10 = str25;
                        num9 = num20;
                        num10 = num21;
                        num11 = num22;
                        b8 = b18;
                        bool4 = bool8;
                        num12 = num23;
                        b9 = b19;
                        str11 = str26;
                        l4 = l10;
                        str12 = str27;
                        break;
                    case 13:
                        lazyArr2 = lazyArr;
                        String str43 = str22;
                        bool5 = bool9;
                        str13 = str28;
                        str14 = str29;
                        l5 = l11;
                        i3 |= 8192;
                        Unit unit15 = Unit.INSTANCE;
                        num13 = (Integer) beginStructure.decodeNullableSerializableElement(serialDescriptor, 13, IntSerializer.INSTANCE, num24);
                        str22 = str43;
                        b15 = b15;
                        str23 = str30;
                        str10 = str25;
                        num9 = num20;
                        num10 = num21;
                        num11 = num22;
                        b8 = b18;
                        bool4 = bool8;
                        num12 = num23;
                        b9 = b19;
                        str11 = str26;
                        l4 = l10;
                        str12 = str27;
                        b10 = b20;
                        break;
                    case ConstantsKt.SPACER_14 /* 14 */:
                        lazyArr2 = lazyArr;
                        String str44 = str22;
                        str13 = str28;
                        str14 = str29;
                        bool5 = bool9;
                        i3 |= 16384;
                        Unit unit16 = Unit.INSTANCE;
                        l5 = (Long) beginStructure.decodeNullableSerializableElement(serialDescriptor, 14, LongSerializer.INSTANCE, l11);
                        str22 = str44;
                        b15 = b15;
                        str23 = str30;
                        str10 = str25;
                        num9 = num20;
                        num10 = num21;
                        num11 = num22;
                        b8 = b18;
                        bool4 = bool8;
                        num12 = num23;
                        b9 = b19;
                        str11 = str26;
                        l4 = l10;
                        str12 = str27;
                        b10 = b20;
                        num13 = num24;
                        break;
                    case 15:
                        lazyArr2 = lazyArr;
                        String str45 = str22;
                        str14 = str29;
                        str13 = str28;
                        i3 |= 32768;
                        Unit unit17 = Unit.INSTANCE;
                        bool5 = (Boolean) beginStructure.decodeNullableSerializableElement(serialDescriptor, 15, BooleanSerializer.INSTANCE, bool9);
                        str22 = str45;
                        b15 = b15;
                        str23 = str30;
                        str10 = str25;
                        num9 = num20;
                        num10 = num21;
                        num11 = num22;
                        b8 = b18;
                        bool4 = bool8;
                        num12 = num23;
                        b9 = b19;
                        str11 = str26;
                        l4 = l10;
                        str12 = str27;
                        b10 = b20;
                        num13 = num24;
                        l5 = l11;
                        break;
                    case 16:
                        lazyArr2 = lazyArr;
                        String str46 = str22;
                        str14 = str29;
                        i3 |= 65536;
                        Unit unit18 = Unit.INSTANCE;
                        str13 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 16, StringSerializer.INSTANCE, str28);
                        str22 = str46;
                        b15 = b15;
                        str23 = str30;
                        str10 = str25;
                        num9 = num20;
                        num10 = num21;
                        num11 = num22;
                        b8 = b18;
                        bool4 = bool8;
                        num12 = num23;
                        b9 = b19;
                        str11 = str26;
                        l4 = l10;
                        str12 = str27;
                        b10 = b20;
                        num13 = num24;
                        l5 = l11;
                        bool5 = bool9;
                        break;
                    case 17:
                        lazyArr2 = lazyArr;
                        String str47 = str22;
                        i3 |= 131072;
                        Unit unit19 = Unit.INSTANCE;
                        str14 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 17, StringSerializer.INSTANCE, str29);
                        str22 = str47;
                        b15 = b15;
                        str23 = str30;
                        str10 = str25;
                        num9 = num20;
                        num10 = num21;
                        num11 = num22;
                        b8 = b18;
                        bool4 = bool8;
                        num12 = num23;
                        b9 = b19;
                        str11 = str26;
                        l4 = l10;
                        str12 = str27;
                        b10 = b20;
                        num13 = num24;
                        l5 = l11;
                        bool5 = bool9;
                        str13 = str28;
                        break;
                    case 18:
                        String str48 = str22;
                        lazyArr2 = lazyArr;
                        i3 |= 262144;
                        Unit unit20 = Unit.INSTANCE;
                        str22 = str48;
                        str10 = str25;
                        num9 = num20;
                        num10 = num21;
                        num11 = num22;
                        b8 = b18;
                        bool4 = bool8;
                        num12 = num23;
                        b9 = b19;
                        str11 = str26;
                        l4 = l10;
                        str12 = str27;
                        b10 = b20;
                        num13 = num24;
                        l5 = l11;
                        bool5 = bool9;
                        str13 = str28;
                        str14 = str29;
                        str23 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 18, StringSerializer.INSTANCE, str30);
                        b15 = b15;
                        break;
                    case 19:
                        str22 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 19, StringSerializer.INSTANCE, str22);
                        i3 |= 524288;
                        Unit unit21 = Unit.INSTANCE;
                        lazyArr2 = lazyArr;
                        b15 = b15;
                        str10 = str25;
                        num9 = num20;
                        num10 = num21;
                        num11 = num22;
                        b8 = b18;
                        bool4 = bool8;
                        num12 = num23;
                        b9 = b19;
                        str11 = str26;
                        l4 = l10;
                        str12 = str27;
                        b10 = b20;
                        num13 = num24;
                        l5 = l11;
                        bool5 = bool9;
                        str13 = str28;
                        str14 = str29;
                        str23 = str30;
                        break;
                    case 20:
                        str16 = str22;
                        b16 = (Byte) beginStructure.decodeNullableSerializableElement(serialDescriptor, 20, ByteSerializer.INSTANCE, b16);
                        i2 = 1048576;
                        i3 |= i2;
                        Unit unit22 = Unit.INSTANCE;
                        lazyArr2 = lazyArr;
                        str10 = str25;
                        num9 = num20;
                        num10 = num21;
                        num11 = num22;
                        b8 = b18;
                        bool4 = bool8;
                        num12 = num23;
                        b9 = b19;
                        str11 = str26;
                        l4 = l10;
                        str12 = str27;
                        b10 = b20;
                        num13 = num24;
                        l5 = l11;
                        bool5 = bool9;
                        str13 = str28;
                        str14 = str29;
                        str23 = str30;
                        str22 = str16;
                        break;
                    case 21:
                        str16 = str22;
                        i3 |= 2097152;
                        Unit unit23 = Unit.INSTANCE;
                        lazyArr2 = lazyArr;
                        skuTag3 = (SkuInfoFloor.ItemsSkuListVO.ItemsSkuListItem.SkuTag) beginStructure.decodeNullableSerializableElement(serialDescriptor, 21, SkuInfoFloor$ItemsSkuListVO$ItemsSkuListItem$SkuTag$$serializer.INSTANCE, skuTag3);
                        str10 = str25;
                        num9 = num20;
                        num10 = num21;
                        num11 = num22;
                        b8 = b18;
                        bool4 = bool8;
                        num12 = num23;
                        b9 = b19;
                        str11 = str26;
                        l4 = l10;
                        str12 = str27;
                        b10 = b20;
                        num13 = num24;
                        l5 = l11;
                        bool5 = bool9;
                        str13 = str28;
                        str14 = str29;
                        str23 = str30;
                        str22 = str16;
                        break;
                    case 22:
                        str16 = str22;
                        i3 |= 4194304;
                        Unit unit24 = Unit.INSTANCE;
                        lazyArr2 = lazyArr;
                        l9 = (Long) beginStructure.decodeNullableSerializableElement(serialDescriptor, 22, LongSerializer.INSTANCE, l9);
                        str10 = str25;
                        num9 = num20;
                        num10 = num21;
                        num11 = num22;
                        b8 = b18;
                        bool4 = bool8;
                        num12 = num23;
                        b9 = b19;
                        str11 = str26;
                        l4 = l10;
                        str12 = str27;
                        b10 = b20;
                        num13 = num24;
                        l5 = l11;
                        bool5 = bool9;
                        str13 = str28;
                        str14 = str29;
                        str23 = str30;
                        str22 = str16;
                        break;
                    case 23:
                        str16 = str22;
                        i3 |= 8388608;
                        Unit unit25 = Unit.INSTANCE;
                        lazyArr2 = lazyArr;
                        list2 = (List) beginStructure.decodeNullableSerializableElement(serialDescriptor, 23, (DeserializationStrategy) lazyArr[23].getValue(), list2);
                        str10 = str25;
                        num9 = num20;
                        num10 = num21;
                        num11 = num22;
                        b8 = b18;
                        bool4 = bool8;
                        num12 = num23;
                        b9 = b19;
                        str11 = str26;
                        l4 = l10;
                        str12 = str27;
                        b10 = b20;
                        num13 = num24;
                        l5 = l11;
                        bool5 = bool9;
                        str13 = str28;
                        str14 = str29;
                        str23 = str30;
                        str22 = str16;
                        break;
                    case 24:
                        str16 = str22;
                        b15 = (Byte) beginStructure.decodeNullableSerializableElement(serialDescriptor, 24, ByteSerializer.INSTANCE, b15);
                        i2 = 16777216;
                        i3 |= i2;
                        Unit unit222 = Unit.INSTANCE;
                        lazyArr2 = lazyArr;
                        str10 = str25;
                        num9 = num20;
                        num10 = num21;
                        num11 = num22;
                        b8 = b18;
                        bool4 = bool8;
                        num12 = num23;
                        b9 = b19;
                        str11 = str26;
                        l4 = l10;
                        str12 = str27;
                        b10 = b20;
                        num13 = num24;
                        l5 = l11;
                        bool5 = bool9;
                        str13 = str28;
                        str14 = str29;
                        str23 = str30;
                        str22 = str16;
                        break;
                    case 25:
                        str16 = str22;
                        num18 = (Integer) beginStructure.decodeNullableSerializableElement(serialDescriptor, 25, IntSerializer.INSTANCE, num18);
                        i2 = 33554432;
                        i3 |= i2;
                        Unit unit2222 = Unit.INSTANCE;
                        lazyArr2 = lazyArr;
                        str10 = str25;
                        num9 = num20;
                        num10 = num21;
                        num11 = num22;
                        b8 = b18;
                        bool4 = bool8;
                        num12 = num23;
                        b9 = b19;
                        str11 = str26;
                        l4 = l10;
                        str12 = str27;
                        b10 = b20;
                        num13 = num24;
                        l5 = l11;
                        bool5 = bool9;
                        str13 = str28;
                        str14 = str29;
                        str23 = str30;
                        str22 = str16;
                        break;
                    case 26:
                        str16 = str22;
                        i3 |= 67108864;
                        Unit unit26 = Unit.INSTANCE;
                        lazyArr2 = lazyArr;
                        num25 = (Integer) beginStructure.decodeNullableSerializableElement(serialDescriptor, 26, IntSerializer.INSTANCE, num25);
                        str10 = str25;
                        num9 = num20;
                        num10 = num21;
                        num11 = num22;
                        b8 = b18;
                        bool4 = bool8;
                        num12 = num23;
                        b9 = b19;
                        str11 = str26;
                        l4 = l10;
                        str12 = str27;
                        b10 = b20;
                        num13 = num24;
                        l5 = l11;
                        bool5 = bool9;
                        str13 = str28;
                        str14 = str29;
                        str23 = str30;
                        str22 = str16;
                        break;
                    case 27:
                        str16 = str22;
                        i3 |= 134217728;
                        Unit unit27 = Unit.INSTANCE;
                        lazyArr2 = lazyArr;
                        b17 = (Byte) beginStructure.decodeNullableSerializableElement(serialDescriptor, 27, ByteSerializer.INSTANCE, b17);
                        str10 = str25;
                        num9 = num20;
                        num10 = num21;
                        num11 = num22;
                        b8 = b18;
                        bool4 = bool8;
                        num12 = num23;
                        b9 = b19;
                        str11 = str26;
                        l4 = l10;
                        str12 = str27;
                        b10 = b20;
                        num13 = num24;
                        l5 = l11;
                        bool5 = bool9;
                        str13 = str28;
                        str14 = str29;
                        str23 = str30;
                        str22 = str16;
                        break;
                    case 28:
                        str16 = str22;
                        i3 |= 268435456;
                        Unit unit28 = Unit.INSTANCE;
                        lazyArr2 = lazyArr;
                        num19 = (Integer) beginStructure.decodeNullableSerializableElement(serialDescriptor, 28, IntSerializer.INSTANCE, num19);
                        str10 = str25;
                        num9 = num20;
                        num10 = num21;
                        num11 = num22;
                        b8 = b18;
                        bool4 = bool8;
                        num12 = num23;
                        b9 = b19;
                        str11 = str26;
                        l4 = l10;
                        str12 = str27;
                        b10 = b20;
                        num13 = num24;
                        l5 = l11;
                        bool5 = bool9;
                        str13 = str28;
                        str14 = str29;
                        str23 = str30;
                        str22 = str16;
                        break;
                    case 29:
                        str16 = str22;
                        i3 |= 536870912;
                        Unit unit29 = Unit.INSTANCE;
                        lazyArr2 = lazyArr;
                        bool7 = (Boolean) beginStructure.decodeNullableSerializableElement(serialDescriptor, 29, BooleanSerializer.INSTANCE, bool7);
                        str10 = str25;
                        num9 = num20;
                        num10 = num21;
                        num11 = num22;
                        b8 = b18;
                        bool4 = bool8;
                        num12 = num23;
                        b9 = b19;
                        str11 = str26;
                        l4 = l10;
                        str12 = str27;
                        b10 = b20;
                        num13 = num24;
                        l5 = l11;
                        bool5 = bool9;
                        str13 = str28;
                        str14 = str29;
                        str23 = str30;
                        str22 = str16;
                        break;
                    default:
                        throw new UnknownFieldException(decodeElementIndex);
                }
                lazyArr = lazyArr2;
                str28 = str13;
                str29 = str14;
                bool9 = bool5;
                l11 = l5;
                num24 = num13;
                b20 = b10;
                str27 = str12;
                str25 = str10;
                num20 = num9;
                num21 = num10;
                num22 = num11;
                b18 = b8;
                bool8 = bool4;
                num23 = num12;
                b19 = b9;
                str26 = str11;
                l10 = l4;
            }
            Byte b21 = b15;
            String str49 = str24;
            String str50 = str25;
            Integer num26 = num20;
            Integer num27 = num21;
            Integer num28 = num22;
            num = num18;
            bool = bool7;
            num2 = num19;
            b = b17;
            num3 = num25;
            i = i3;
            b2 = b20;
            str = str50;
            b3 = b18;
            str2 = str49;
            str3 = str22;
            bool2 = bool9;
            num4 = num24;
            str4 = str27;
            str5 = str26;
            list = list2;
            l = l11;
            num5 = num26;
            l2 = l10;
            b4 = b21;
            str6 = str28;
            num6 = num28;
            num7 = num23;
            skuTag = skuTag3;
            str7 = str23;
            num8 = num27;
            bool3 = bool8;
            b5 = b16;
            str8 = str29;
            b6 = b19;
            l3 = l9;
        }
        beginStructure.endStructure(serialDescriptor);
        return new SkuInfoFloor.ItemsSkuListVO.ItemsSkuListItem(i, str2, str, num5, num8, num6, b3, bool3, num7, b6, str5, l2, str4, b2, num4, l, bool2, str6, str8, str7, str3, b5, skuTag, l3, list, b4, num, num3, b, num2, bool, (SerializationConstructorMarker) null);
    }

    public final void serialize(Encoder encoder, SkuInfoFloor.ItemsSkuListVO.ItemsSkuListItem value) {
        Intrinsics.checkNotNullParameter(encoder, "encoder");
        Intrinsics.checkNotNullParameter(value, "value");
        SerialDescriptor serialDescriptor = descriptor;
        CompositeEncoder beginStructure = encoder.beginStructure(serialDescriptor);
        SkuInfoFloor.ItemsSkuListVO.ItemsSkuListItem.write$Self$product_details_page_debug(value, beginStructure, serialDescriptor);
        beginStructure.endStructure(serialDescriptor);
    }

    public /* bridge */ KSerializer<?>[] typeParametersSerializers() {
        return GeneratedSerializer.DefaultImpls.typeParametersSerializers(this);
    }
}