package kntr.app.mall.product.details.page.api;

import com.bapis.bilibili.app.dynamic.v2.AdditionalButton;
import java.util.List;
import kntr.app.mall.product.details.page.api.ProductShopDetailsMerchantInfo;
import kntr.app.upcomingEpisode.ConstantsKt;
import kntr.common.upper.trace.config.AppKey;
import kntr.watch.later.watchlater.edit.MediaAttrUtils;
import kotlin.Deprecated;
import kotlin.DeprecationLevel;
import kotlin.Lazy;
import kotlin.Metadata;
import kotlin.Unit;
import kotlin.jvm.internal.Intrinsics;
import kotlinx.serialization.DeserializationStrategy;
import kotlinx.serialization.KSerializer;
import kotlinx.serialization.UnknownFieldException;
import kotlinx.serialization.builtins.BuiltinSerializersKt;
import kotlinx.serialization.descriptors.SerialDescriptor;
import kotlinx.serialization.encoding.CompositeDecoder;
import kotlinx.serialization.encoding.CompositeEncoder;
import kotlinx.serialization.encoding.Decoder;
import kotlinx.serialization.encoding.Encoder;
import kotlinx.serialization.internal.BooleanSerializer;
import kotlinx.serialization.internal.GeneratedSerializer;
import kotlinx.serialization.internal.IntSerializer;
import kotlinx.serialization.internal.LongSerializer;
import kotlinx.serialization.internal.PluginGeneratedSerialDescriptor;
import kotlinx.serialization.internal.SerializationConstructorMarker;
import kotlinx.serialization.internal.StringSerializer;
import kotlinx.serialization.json.JsonElement;
import kotlinx.serialization.json.JsonElementSerializer;

/* compiled from: ProductShopApiService.kt */
@Metadata(d1 = {"\u00006\n\u0000\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\b\u0003\n\u0002\u0010\u0011\n\u0002\u0018\u0002\n\u0002\b\u0003\n\u0002\u0018\u0002\n\u0000\n\u0002\u0010\u0002\n\u0000\n\u0002\u0018\u0002\n\u0002\b\u0002\n\u0002\u0018\u0002\n\u0002\b\u0003\bÇ\u0002\u0018\u00002\b\u0012\u0004\u0012\u00020\u00020\u0001B\t\b\u0002¢\u0006\u0004\b\u0003\u0010\u0004J\u0015\u0010\u0005\u001a\f\u0012\b\u0012\u0006\u0012\u0002\b\u00030\u00070\u0006¢\u0006\u0002\u0010\bJ\u000e\u0010\t\u001a\u00020\u00022\u0006\u0010\n\u001a\u00020\u000bJ\u0016\u0010\f\u001a\u00020\r2\u0006\u0010\u000e\u001a\u00020\u000f2\u0006\u0010\u0010\u001a\u00020\u0002R\u0011\u0010\u0011\u001a\u00020\u0012¢\u0006\b\n\u0000\u001a\u0004\b\u0013\u0010\u0014¨\u0006\u0015"}, d2 = {"kntr/app/mall/product/details/page/api/ProductShopDetailsMerchantInfo.$serializer", "Lkotlinx/serialization/internal/GeneratedSerializer;", "Lkntr/app/mall/product/details/page/api/ProductShopDetailsMerchantInfo;", "<init>", "()V", "childSerializers", "", "Lkotlinx/serialization/KSerializer;", "()[Lkotlinx/serialization/KSerializer;", "deserialize", "decoder", "Lkotlinx/serialization/encoding/Decoder;", "serialize", "", "encoder", "Lkotlinx/serialization/encoding/Encoder;", "value", "descriptor", "Lkotlinx/serialization/descriptors/SerialDescriptor;", "getDescriptor", "()Lkotlinx/serialization/descriptors/SerialDescriptor;", "product-details-page_debug"}, k = 1, mv = {2, 2, 0}, xi = ConstantsKt.OGV_UPDATE_CALENDAR_CARD_COVER_WIDTH)
@Deprecated(level = DeprecationLevel.HIDDEN, message = "This synthesized declaration should not be used directly")
public final /* synthetic */ class ProductShopDetailsMerchantInfo$$serializer implements GeneratedSerializer<ProductShopDetailsMerchantInfo> {
    public static final int $stable;
    public static final ProductShopDetailsMerchantInfo$$serializer INSTANCE = new ProductShopDetailsMerchantInfo$$serializer();
    private static final SerialDescriptor descriptor;

    public final SerialDescriptor getDescriptor() {
        return descriptor;
    }

    static {
        SerialDescriptor pluginGeneratedSerialDescriptor = new PluginGeneratedSerialDescriptor("kntr.app.mall.product.details.page.api.ProductShopDetailsMerchantInfo", INSTANCE, 30);
        pluginGeneratedSerialDescriptor.addElement("assemblyComputerMerchant", true);
        pluginGeneratedSerialDescriptor.addElement("bindUp", true);
        pluginGeneratedSerialDescriptor.addElement("businessLicenseUrl", true);
        pluginGeneratedSerialDescriptor.addElement("customerLink", true);
        pluginGeneratedSerialDescriptor.addElement("fans", true);
        pluginGeneratedSerialDescriptor.addElement("h5CustomerLink", true);
        pluginGeneratedSerialDescriptor.addElement("itemsNum", true);
        pluginGeneratedSerialDescriptor.addElement("merchantAdvisers", true);
        pluginGeneratedSerialDescriptor.addElement("merchantDecor", true);
        pluginGeneratedSerialDescriptor.addElement("merchantIcon", true);
        pluginGeneratedSerialDescriptor.addElement("merchantId", true);
        pluginGeneratedSerialDescriptor.addElement("merchantNoticeVo", true);
        pluginGeneratedSerialDescriptor.addElement("merchantShopFace", true);
        pluginGeneratedSerialDescriptor.addElement("merchantShopName", true);
        pluginGeneratedSerialDescriptor.addElement("merchantType", true);
        pluginGeneratedSerialDescriptor.addElement("myCartUrl", true);
        pluginGeneratedSerialDescriptor.addElement("myOrderUrl", true);
        pluginGeneratedSerialDescriptor.addElement("noticed", true);
        pluginGeneratedSerialDescriptor.addElement("positiveRatio", true);
        pluginGeneratedSerialDescriptor.addElement("positiveRatioStr", true);
        pluginGeneratedSerialDescriptor.addElement("qualificationList", true);
        pluginGeneratedSerialDescriptor.addElement("shareInfo", true);
        pluginGeneratedSerialDescriptor.addElement("shopSales", true);
        pluginGeneratedSerialDescriptor.addElement("tagNames", true);
        pluginGeneratedSerialDescriptor.addElement(AppKey.UID, true);
        pluginGeneratedSerialDescriptor.addElement("shopJumpLink", true);
        pluginGeneratedSerialDescriptor.addElement("upJumpLink", true);
        pluginGeneratedSerialDescriptor.addElement("upName", true);
        pluginGeneratedSerialDescriptor.addElement("upOfficialType", true);
        pluginGeneratedSerialDescriptor.addElement("upPortrait", true);
        descriptor = pluginGeneratedSerialDescriptor;
        $stable = 8;
    }

    private ProductShopDetailsMerchantInfo$$serializer() {
    }

    public final KSerializer<?>[] childSerializers() {
        Lazy[] lazyArr;
        lazyArr = ProductShopDetailsMerchantInfo.$childSerializers;
        return new KSerializer[]{BuiltinSerializersKt.getNullable(BooleanSerializer.INSTANCE), BuiltinSerializersKt.getNullable(BooleanSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(LongSerializer.INSTANCE), BuiltinSerializersKt.getNullable((KSerializer) lazyArr[7].getValue()), BuiltinSerializersKt.getNullable((KSerializer) lazyArr[8].getValue()), BuiltinSerializersKt.getNullable(ProductShopDetailsMerchantInfo$MerchantIcon$$serializer.INSTANCE), BuiltinSerializersKt.getNullable(IntSerializer.INSTANCE), BuiltinSerializersKt.getNullable(ProductShopDetailsMerchantInfo$MerchantNotice$$serializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(IntSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(BooleanSerializer.INSTANCE), BuiltinSerializersKt.getNullable(JsonElementSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable((KSerializer) lazyArr[20].getValue()), BuiltinSerializersKt.getNullable(ProductShopDetailsMerchantInfo$ShareInfo$$serializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable((KSerializer) lazyArr[23].getValue()), BuiltinSerializersKt.getNullable(LongSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(IntSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE)};
    }

    public final ProductShopDetailsMerchantInfo deserialize(Decoder decoder) {
        Lazy[] lazyArr;
        Integer num;
        String str;
        Integer num2;
        List list;
        String str2;
        String str3;
        String str4;
        List list2;
        Long l;
        ProductShopDetailsMerchantInfo.ShareInfo shareInfo;
        int i;
        String str5;
        String str6;
        ProductShopDetailsMerchantInfo.MerchantNotice merchantNotice;
        String str7;
        Integer num3;
        String str8;
        List list3;
        Boolean bool;
        Boolean bool2;
        String str9;
        ProductShopDetailsMerchantInfo.MerchantIcon merchantIcon;
        String str10;
        String str11;
        JsonElement jsonElement;
        String str12;
        String str13;
        Boolean bool3;
        Long l2;
        String str14;
        List list4;
        Long l3;
        Lazy[] lazyArr2;
        String str15;
        String str16;
        Boolean bool4;
        String str17;
        String str18;
        String str19;
        String str20;
        Long l4;
        List list5;
        List list6;
        ProductShopDetailsMerchantInfo.MerchantIcon merchantIcon2;
        Integer num4;
        ProductShopDetailsMerchantInfo.MerchantNotice merchantNotice2;
        String str21;
        String str22;
        Integer num5;
        String str23;
        String str24;
        Boolean bool5;
        JsonElement jsonElement2;
        Long l5;
        String str25;
        int i2;
        Intrinsics.checkNotNullParameter(decoder, "decoder");
        SerialDescriptor serialDescriptor = descriptor;
        CompositeDecoder beginStructure = decoder.beginStructure(serialDescriptor);
        lazyArr = ProductShopDetailsMerchantInfo.$childSerializers;
        if (beginStructure.decodeSequentially()) {
            bool2 = (Boolean) beginStructure.decodeNullableSerializableElement(serialDescriptor, 1, BooleanSerializer.INSTANCE, (Object) null);
            Integer num6 = (Integer) beginStructure.decodeNullableSerializableElement(serialDescriptor, 10, IntSerializer.INSTANCE, (Object) null);
            ProductShopDetailsMerchantInfo.MerchantNotice merchantNotice3 = (ProductShopDetailsMerchantInfo.MerchantNotice) beginStructure.decodeNullableSerializableElement(serialDescriptor, 11, ProductShopDetailsMerchantInfo$MerchantNotice$$serializer.INSTANCE, (Object) null);
            String str26 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 12, StringSerializer.INSTANCE, (Object) null);
            String str27 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 13, StringSerializer.INSTANCE, (Object) null);
            Integer num7 = (Integer) beginStructure.decodeNullableSerializableElement(serialDescriptor, 14, IntSerializer.INSTANCE, (Object) null);
            String str28 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 15, StringSerializer.INSTANCE, (Object) null);
            String str29 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 16, StringSerializer.INSTANCE, (Object) null);
            Boolean bool6 = (Boolean) beginStructure.decodeNullableSerializableElement(serialDescriptor, 17, BooleanSerializer.INSTANCE, (Object) null);
            JsonElement jsonElement3 = (JsonElement) beginStructure.decodeNullableSerializableElement(serialDescriptor, 18, JsonElementSerializer.INSTANCE, (Object) null);
            String str30 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 19, StringSerializer.INSTANCE, (Object) null);
            List list7 = (List) beginStructure.decodeNullableSerializableElement(serialDescriptor, 20, (DeserializationStrategy) lazyArr[20].getValue(), (Object) null);
            ProductShopDetailsMerchantInfo.ShareInfo shareInfo2 = (ProductShopDetailsMerchantInfo.ShareInfo) beginStructure.decodeNullableSerializableElement(serialDescriptor, 21, ProductShopDetailsMerchantInfo$ShareInfo$$serializer.INSTANCE, (Object) null);
            String str31 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 22, StringSerializer.INSTANCE, (Object) null);
            Long l6 = (Long) beginStructure.decodeNullableSerializableElement(serialDescriptor, 24, LongSerializer.INSTANCE, (Object) null);
            String str32 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 25, StringSerializer.INSTANCE, (Object) null);
            String str33 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 26, StringSerializer.INSTANCE, (Object) null);
            String str34 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 27, StringSerializer.INSTANCE, (Object) null);
            Integer num8 = (Integer) beginStructure.decodeNullableSerializableElement(serialDescriptor, 28, IntSerializer.INSTANCE, (Object) null);
            str = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 29, StringSerializer.INSTANCE, (Object) null);
            l2 = (Long) beginStructure.decodeNullableSerializableElement(serialDescriptor, 6, LongSerializer.INSTANCE, (Object) null);
            str14 = str32;
            str11 = str33;
            str8 = str34;
            num2 = num8;
            list = (List) beginStructure.decodeNullableSerializableElement(serialDescriptor, 23, (DeserializationStrategy) lazyArr[23].getValue(), (Object) null);
            str9 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 5, StringSerializer.INSTANCE, (Object) null);
            str10 = str31;
            str3 = str26;
            shareInfo = shareInfo2;
            l = l6;
            str12 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 2, StringSerializer.INSTANCE, (Object) null);
            str6 = str28;
            list3 = list7;
            str2 = str27;
            num3 = num6;
            str13 = str30;
            jsonElement = jsonElement3;
            bool = bool6;
            num = num7;
            merchantNotice = merchantNotice3;
            list2 = (List) beginStructure.decodeNullableSerializableElement(serialDescriptor, 7, (DeserializationStrategy) lazyArr[7].getValue(), (Object) null);
            list4 = (List) beginStructure.decodeNullableSerializableElement(serialDescriptor, 8, (DeserializationStrategy) lazyArr[8].getValue(), (Object) null);
            i = 1073741823;
            str5 = str29;
            bool3 = (Boolean) beginStructure.decodeNullableSerializableElement(serialDescriptor, 0, BooleanSerializer.INSTANCE, (Object) null);
            str7 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 3, StringSerializer.INSTANCE, (Object) null);
            merchantIcon = (ProductShopDetailsMerchantInfo.MerchantIcon) beginStructure.decodeNullableSerializableElement(serialDescriptor, 9, ProductShopDetailsMerchantInfo$MerchantIcon$$serializer.INSTANCE, (Object) null);
            str4 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 4, StringSerializer.INSTANCE, (Object) null);
        } else {
            boolean z = true;
            Long l7 = null;
            String str35 = null;
            String str36 = null;
            JsonElement jsonElement4 = null;
            Integer num9 = null;
            ProductShopDetailsMerchantInfo.ShareInfo shareInfo3 = null;
            String str37 = null;
            String str38 = null;
            List list8 = null;
            List list9 = null;
            String str39 = null;
            Boolean bool7 = null;
            Boolean bool8 = null;
            String str40 = null;
            String str41 = null;
            String str42 = null;
            String str43 = null;
            Long l8 = null;
            List list10 = null;
            List list11 = null;
            ProductShopDetailsMerchantInfo.MerchantIcon merchantIcon3 = null;
            Integer num10 = null;
            ProductShopDetailsMerchantInfo.MerchantNotice merchantNotice4 = null;
            String str44 = null;
            String str45 = null;
            Integer num11 = null;
            String str46 = null;
            String str47 = null;
            Boolean bool9 = null;
            int i3 = 0;
            String str48 = null;
            while (z) {
                JsonElement jsonElement5 = jsonElement4;
                int decodeElementIndex = beginStructure.decodeElementIndex(serialDescriptor);
                switch (decodeElementIndex) {
                    case -1:
                        l3 = l7;
                        lazyArr2 = lazyArr;
                        str15 = str35;
                        str16 = str39;
                        bool4 = bool8;
                        str17 = str40;
                        str18 = str41;
                        str19 = str42;
                        str20 = str43;
                        l4 = l8;
                        list5 = list10;
                        list6 = list11;
                        merchantIcon2 = merchantIcon3;
                        num4 = num10;
                        merchantNotice2 = merchantNotice4;
                        str21 = str44;
                        str22 = str45;
                        num5 = num11;
                        str23 = str46;
                        str24 = str47;
                        bool5 = bool9;
                        jsonElement2 = jsonElement5;
                        Unit unit = Unit.INSTANCE;
                        z = false;
                        l5 = l4;
                        jsonElement4 = jsonElement2;
                        str35 = str15;
                        str39 = str16;
                        l8 = l5;
                        bool9 = bool5;
                        str47 = str24;
                        str46 = str23;
                        num11 = num5;
                        str45 = str22;
                        str44 = str21;
                        merchantNotice4 = merchantNotice2;
                        bool8 = bool4;
                        str40 = str17;
                        str41 = str18;
                        str42 = str19;
                        str43 = str20;
                        lazyArr = lazyArr2;
                        list10 = list5;
                        list11 = list6;
                        merchantIcon3 = merchantIcon2;
                        num10 = num4;
                        l7 = l3;
                    case 0:
                        l3 = l7;
                        lazyArr2 = lazyArr;
                        str15 = str35;
                        str16 = str39;
                        str17 = str40;
                        str18 = str41;
                        str19 = str42;
                        str20 = str43;
                        l4 = l8;
                        list5 = list10;
                        list6 = list11;
                        merchantIcon2 = merchantIcon3;
                        num4 = num10;
                        merchantNotice2 = merchantNotice4;
                        str21 = str44;
                        str22 = str45;
                        num5 = num11;
                        str23 = str46;
                        str24 = str47;
                        bool5 = bool9;
                        jsonElement2 = jsonElement5;
                        bool4 = bool8;
                        i3 |= 1;
                        Unit unit2 = Unit.INSTANCE;
                        bool7 = (Boolean) beginStructure.decodeNullableSerializableElement(serialDescriptor, 0, BooleanSerializer.INSTANCE, bool7);
                        l5 = l4;
                        jsonElement4 = jsonElement2;
                        str35 = str15;
                        str39 = str16;
                        l8 = l5;
                        bool9 = bool5;
                        str47 = str24;
                        str46 = str23;
                        num11 = num5;
                        str45 = str22;
                        str44 = str21;
                        merchantNotice4 = merchantNotice2;
                        bool8 = bool4;
                        str40 = str17;
                        str41 = str18;
                        str42 = str19;
                        str43 = str20;
                        lazyArr = lazyArr2;
                        list10 = list5;
                        list11 = list6;
                        merchantIcon3 = merchantIcon2;
                        num10 = num4;
                        l7 = l3;
                    case 1:
                        l3 = l7;
                        lazyArr2 = lazyArr;
                        str25 = str39;
                        str18 = str41;
                        str19 = str42;
                        str20 = str43;
                        list5 = list10;
                        list6 = list11;
                        merchantIcon2 = merchantIcon3;
                        num4 = num10;
                        merchantNotice2 = merchantNotice4;
                        str21 = str44;
                        str22 = str45;
                        num5 = num11;
                        str23 = str46;
                        str24 = str47;
                        bool5 = bool9;
                        str17 = str40;
                        i3 |= 2;
                        Unit unit3 = Unit.INSTANCE;
                        bool4 = (Boolean) beginStructure.decodeNullableSerializableElement(serialDescriptor, 1, BooleanSerializer.INSTANCE, bool8);
                        l5 = l8;
                        jsonElement4 = jsonElement5;
                        str35 = str35;
                        str39 = str25;
                        l8 = l5;
                        bool9 = bool5;
                        str47 = str24;
                        str46 = str23;
                        num11 = num5;
                        str45 = str22;
                        str44 = str21;
                        merchantNotice4 = merchantNotice2;
                        bool8 = bool4;
                        str40 = str17;
                        str41 = str18;
                        str42 = str19;
                        str43 = str20;
                        lazyArr = lazyArr2;
                        list10 = list5;
                        list11 = list6;
                        merchantIcon3 = merchantIcon2;
                        num10 = num4;
                        l7 = l3;
                    case 2:
                        l3 = l7;
                        lazyArr2 = lazyArr;
                        str25 = str39;
                        str19 = str42;
                        str20 = str43;
                        list5 = list10;
                        list6 = list11;
                        merchantIcon2 = merchantIcon3;
                        num4 = num10;
                        merchantNotice2 = merchantNotice4;
                        str21 = str44;
                        str22 = str45;
                        num5 = num11;
                        str23 = str46;
                        str24 = str47;
                        bool5 = bool9;
                        str18 = str41;
                        i3 |= 4;
                        Unit unit4 = Unit.INSTANCE;
                        str17 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 2, StringSerializer.INSTANCE, str40);
                        l5 = l8;
                        jsonElement4 = jsonElement5;
                        str35 = str35;
                        bool4 = bool8;
                        str39 = str25;
                        l8 = l5;
                        bool9 = bool5;
                        str47 = str24;
                        str46 = str23;
                        num11 = num5;
                        str45 = str22;
                        str44 = str21;
                        merchantNotice4 = merchantNotice2;
                        bool8 = bool4;
                        str40 = str17;
                        str41 = str18;
                        str42 = str19;
                        str43 = str20;
                        lazyArr = lazyArr2;
                        list10 = list5;
                        list11 = list6;
                        merchantIcon3 = merchantIcon2;
                        num10 = num4;
                        l7 = l3;
                    case 3:
                        l3 = l7;
                        lazyArr2 = lazyArr;
                        str25 = str39;
                        str20 = str43;
                        list5 = list10;
                        list6 = list11;
                        merchantIcon2 = merchantIcon3;
                        num4 = num10;
                        merchantNotice2 = merchantNotice4;
                        str21 = str44;
                        str22 = str45;
                        num5 = num11;
                        str23 = str46;
                        str24 = str47;
                        bool5 = bool9;
                        str19 = str42;
                        i3 |= 8;
                        Unit unit5 = Unit.INSTANCE;
                        str18 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 3, StringSerializer.INSTANCE, str41);
                        l5 = l8;
                        jsonElement4 = jsonElement5;
                        str35 = str35;
                        bool4 = bool8;
                        str17 = str40;
                        str39 = str25;
                        l8 = l5;
                        bool9 = bool5;
                        str47 = str24;
                        str46 = str23;
                        num11 = num5;
                        str45 = str22;
                        str44 = str21;
                        merchantNotice4 = merchantNotice2;
                        bool8 = bool4;
                        str40 = str17;
                        str41 = str18;
                        str42 = str19;
                        str43 = str20;
                        lazyArr = lazyArr2;
                        list10 = list5;
                        list11 = list6;
                        merchantIcon3 = merchantIcon2;
                        num10 = num4;
                        l7 = l3;
                    case 4:
                        l3 = l7;
                        lazyArr2 = lazyArr;
                        str25 = str39;
                        list5 = list10;
                        list6 = list11;
                        merchantIcon2 = merchantIcon3;
                        num4 = num10;
                        merchantNotice2 = merchantNotice4;
                        str21 = str44;
                        str22 = str45;
                        num5 = num11;
                        str23 = str46;
                        str24 = str47;
                        bool5 = bool9;
                        str20 = str43;
                        i3 |= 16;
                        Unit unit6 = Unit.INSTANCE;
                        str19 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 4, StringSerializer.INSTANCE, str42);
                        l5 = l8;
                        jsonElement4 = jsonElement5;
                        str35 = str35;
                        bool4 = bool8;
                        str17 = str40;
                        str18 = str41;
                        str39 = str25;
                        l8 = l5;
                        bool9 = bool5;
                        str47 = str24;
                        str46 = str23;
                        num11 = num5;
                        str45 = str22;
                        str44 = str21;
                        merchantNotice4 = merchantNotice2;
                        bool8 = bool4;
                        str40 = str17;
                        str41 = str18;
                        str42 = str19;
                        str43 = str20;
                        lazyArr = lazyArr2;
                        list10 = list5;
                        list11 = list6;
                        merchantIcon3 = merchantIcon2;
                        num10 = num4;
                        l7 = l3;
                    case 5:
                        l3 = l7;
                        str25 = str39;
                        list5 = list10;
                        list6 = list11;
                        merchantIcon2 = merchantIcon3;
                        num4 = num10;
                        merchantNotice2 = merchantNotice4;
                        str21 = str44;
                        str22 = str45;
                        num5 = num11;
                        str23 = str46;
                        str24 = str47;
                        bool5 = bool9;
                        lazyArr2 = lazyArr;
                        i3 |= 32;
                        Unit unit7 = Unit.INSTANCE;
                        str20 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 5, StringSerializer.INSTANCE, str43);
                        l5 = l8;
                        jsonElement4 = jsonElement5;
                        str35 = str35;
                        bool4 = bool8;
                        str17 = str40;
                        str18 = str41;
                        str19 = str42;
                        str39 = str25;
                        l8 = l5;
                        bool9 = bool5;
                        str47 = str24;
                        str46 = str23;
                        num11 = num5;
                        str45 = str22;
                        str44 = str21;
                        merchantNotice4 = merchantNotice2;
                        bool8 = bool4;
                        str40 = str17;
                        str41 = str18;
                        str42 = str19;
                        str43 = str20;
                        lazyArr = lazyArr2;
                        list10 = list5;
                        list11 = list6;
                        merchantIcon3 = merchantIcon2;
                        num10 = num4;
                        l7 = l3;
                    case 6:
                        l3 = l7;
                        str25 = str39;
                        list6 = list11;
                        merchantIcon2 = merchantIcon3;
                        num4 = num10;
                        merchantNotice2 = merchantNotice4;
                        str21 = str44;
                        str22 = str45;
                        num5 = num11;
                        str23 = str46;
                        str24 = str47;
                        bool5 = bool9;
                        list5 = list10;
                        i3 |= 64;
                        Unit unit8 = Unit.INSTANCE;
                        lazyArr2 = lazyArr;
                        l5 = (Long) beginStructure.decodeNullableSerializableElement(serialDescriptor, 6, LongSerializer.INSTANCE, l8);
                        jsonElement4 = jsonElement5;
                        str35 = str35;
                        bool4 = bool8;
                        str17 = str40;
                        str18 = str41;
                        str19 = str42;
                        str20 = str43;
                        str39 = str25;
                        l8 = l5;
                        bool9 = bool5;
                        str47 = str24;
                        str46 = str23;
                        num11 = num5;
                        str45 = str22;
                        str44 = str21;
                        merchantNotice4 = merchantNotice2;
                        bool8 = bool4;
                        str40 = str17;
                        str41 = str18;
                        str42 = str19;
                        str43 = str20;
                        lazyArr = lazyArr2;
                        list10 = list5;
                        list11 = list6;
                        merchantIcon3 = merchantIcon2;
                        num10 = num4;
                        l7 = l3;
                    case AdditionalButton.CLICK_TYPE_FIELD_NUMBER /* 7 */:
                        l3 = l7;
                        str25 = str39;
                        merchantIcon2 = merchantIcon3;
                        num4 = num10;
                        merchantNotice2 = merchantNotice4;
                        str21 = str44;
                        str22 = str45;
                        num5 = num11;
                        str23 = str46;
                        str24 = str47;
                        bool5 = bool9;
                        DeserializationStrategy deserializationStrategy = (DeserializationStrategy) lazyArr[7].getValue();
                        list6 = list11;
                        i3 |= 128;
                        Unit unit9 = Unit.INSTANCE;
                        list5 = (List) beginStructure.decodeNullableSerializableElement(serialDescriptor, 7, deserializationStrategy, list10);
                        lazyArr2 = lazyArr;
                        jsonElement4 = jsonElement5;
                        str35 = str35;
                        bool4 = bool8;
                        str17 = str40;
                        str18 = str41;
                        str19 = str42;
                        str20 = str43;
                        l5 = l8;
                        str39 = str25;
                        l8 = l5;
                        bool9 = bool5;
                        str47 = str24;
                        str46 = str23;
                        num11 = num5;
                        str45 = str22;
                        str44 = str21;
                        merchantNotice4 = merchantNotice2;
                        bool8 = bool4;
                        str40 = str17;
                        str41 = str18;
                        str42 = str19;
                        str43 = str20;
                        lazyArr = lazyArr2;
                        list10 = list5;
                        list11 = list6;
                        merchantIcon3 = merchantIcon2;
                        num10 = num4;
                        l7 = l3;
                    case 8:
                        l3 = l7;
                        String str49 = str35;
                        str25 = str39;
                        num4 = num10;
                        merchantNotice2 = merchantNotice4;
                        str21 = str44;
                        str22 = str45;
                        num5 = num11;
                        str23 = str46;
                        str24 = str47;
                        bool5 = bool9;
                        DeserializationStrategy deserializationStrategy2 = (DeserializationStrategy) lazyArr[8].getValue();
                        merchantIcon2 = merchantIcon3;
                        i3 |= 256;
                        Unit unit10 = Unit.INSTANCE;
                        list6 = (List) beginStructure.decodeNullableSerializableElement(serialDescriptor, 8, deserializationStrategy2, list11);
                        lazyArr2 = lazyArr;
                        jsonElement4 = jsonElement5;
                        str35 = str49;
                        bool4 = bool8;
                        str17 = str40;
                        str18 = str41;
                        str19 = str42;
                        str20 = str43;
                        l5 = l8;
                        list5 = list10;
                        str39 = str25;
                        l8 = l5;
                        bool9 = bool5;
                        str47 = str24;
                        str46 = str23;
                        num11 = num5;
                        str45 = str22;
                        str44 = str21;
                        merchantNotice4 = merchantNotice2;
                        bool8 = bool4;
                        str40 = str17;
                        str41 = str18;
                        str42 = str19;
                        str43 = str20;
                        lazyArr = lazyArr2;
                        list10 = list5;
                        list11 = list6;
                        merchantIcon3 = merchantIcon2;
                        num10 = num4;
                        l7 = l3;
                    case ConstantsKt.SPACER_9 /* 9 */:
                        l3 = l7;
                        str25 = str39;
                        merchantNotice2 = merchantNotice4;
                        str21 = str44;
                        str22 = str45;
                        num5 = num11;
                        str23 = str46;
                        str24 = str47;
                        bool5 = bool9;
                        num4 = num10;
                        i3 |= 512;
                        Unit unit11 = Unit.INSTANCE;
                        merchantIcon2 = (ProductShopDetailsMerchantInfo.MerchantIcon) beginStructure.decodeNullableSerializableElement(serialDescriptor, 9, ProductShopDetailsMerchantInfo$MerchantIcon$$serializer.INSTANCE, merchantIcon3);
                        lazyArr2 = lazyArr;
                        jsonElement4 = jsonElement5;
                        str35 = str35;
                        bool4 = bool8;
                        str17 = str40;
                        str18 = str41;
                        str19 = str42;
                        str20 = str43;
                        l5 = l8;
                        list5 = list10;
                        list6 = list11;
                        str39 = str25;
                        l8 = l5;
                        bool9 = bool5;
                        str47 = str24;
                        str46 = str23;
                        num11 = num5;
                        str45 = str22;
                        str44 = str21;
                        merchantNotice4 = merchantNotice2;
                        bool8 = bool4;
                        str40 = str17;
                        str41 = str18;
                        str42 = str19;
                        str43 = str20;
                        lazyArr = lazyArr2;
                        list10 = list5;
                        list11 = list6;
                        merchantIcon3 = merchantIcon2;
                        num10 = num4;
                        l7 = l3;
                    case 10:
                        l3 = l7;
                        str25 = str39;
                        str21 = str44;
                        str22 = str45;
                        num5 = num11;
                        str23 = str46;
                        str24 = str47;
                        bool5 = bool9;
                        merchantNotice2 = merchantNotice4;
                        i3 |= 1024;
                        Unit unit12 = Unit.INSTANCE;
                        lazyArr2 = lazyArr;
                        num4 = (Integer) beginStructure.decodeNullableSerializableElement(serialDescriptor, 10, IntSerializer.INSTANCE, num10);
                        jsonElement4 = jsonElement5;
                        str35 = str35;
                        bool4 = bool8;
                        str17 = str40;
                        str18 = str41;
                        str19 = str42;
                        str20 = str43;
                        l5 = l8;
                        list5 = list10;
                        list6 = list11;
                        merchantIcon2 = merchantIcon3;
                        str39 = str25;
                        l8 = l5;
                        bool9 = bool5;
                        str47 = str24;
                        str46 = str23;
                        num11 = num5;
                        str45 = str22;
                        str44 = str21;
                        merchantNotice4 = merchantNotice2;
                        bool8 = bool4;
                        str40 = str17;
                        str41 = str18;
                        str42 = str19;
                        str43 = str20;
                        lazyArr = lazyArr2;
                        list10 = list5;
                        list11 = list6;
                        merchantIcon3 = merchantIcon2;
                        num10 = num4;
                        l7 = l3;
                    case MediaAttrUtils.TYPE_MENU /* 11 */:
                        l3 = l7;
                        str25 = str39;
                        str22 = str45;
                        num5 = num11;
                        str23 = str46;
                        str24 = str47;
                        bool5 = bool9;
                        str21 = str44;
                        i3 |= 2048;
                        Unit unit13 = Unit.INSTANCE;
                        merchantNotice2 = (ProductShopDetailsMerchantInfo.MerchantNotice) beginStructure.decodeNullableSerializableElement(serialDescriptor, 11, ProductShopDetailsMerchantInfo$MerchantNotice$$serializer.INSTANCE, merchantNotice4);
                        lazyArr2 = lazyArr;
                        jsonElement4 = jsonElement5;
                        str35 = str35;
                        bool4 = bool8;
                        str17 = str40;
                        str18 = str41;
                        str19 = str42;
                        str20 = str43;
                        l5 = l8;
                        list5 = list10;
                        list6 = list11;
                        merchantIcon2 = merchantIcon3;
                        num4 = num10;
                        str39 = str25;
                        l8 = l5;
                        bool9 = bool5;
                        str47 = str24;
                        str46 = str23;
                        num11 = num5;
                        str45 = str22;
                        str44 = str21;
                        merchantNotice4 = merchantNotice2;
                        bool8 = bool4;
                        str40 = str17;
                        str41 = str18;
                        str42 = str19;
                        str43 = str20;
                        lazyArr = lazyArr2;
                        list10 = list5;
                        list11 = list6;
                        merchantIcon3 = merchantIcon2;
                        num10 = num4;
                        l7 = l3;
                    case 12:
                        l3 = l7;
                        str25 = str39;
                        num5 = num11;
                        str23 = str46;
                        str24 = str47;
                        bool5 = bool9;
                        str22 = str45;
                        i3 |= 4096;
                        Unit unit14 = Unit.INSTANCE;
                        lazyArr2 = lazyArr;
                        str21 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 12, StringSerializer.INSTANCE, str44);
                        jsonElement4 = jsonElement5;
                        str35 = str35;
                        bool4 = bool8;
                        str17 = str40;
                        str18 = str41;
                        str19 = str42;
                        str20 = str43;
                        l5 = l8;
                        list5 = list10;
                        list6 = list11;
                        merchantIcon2 = merchantIcon3;
                        num4 = num10;
                        merchantNotice2 = merchantNotice4;
                        str39 = str25;
                        l8 = l5;
                        bool9 = bool5;
                        str47 = str24;
                        str46 = str23;
                        num11 = num5;
                        str45 = str22;
                        str44 = str21;
                        merchantNotice4 = merchantNotice2;
                        bool8 = bool4;
                        str40 = str17;
                        str41 = str18;
                        str42 = str19;
                        str43 = str20;
                        lazyArr = lazyArr2;
                        list10 = list5;
                        list11 = list6;
                        merchantIcon3 = merchantIcon2;
                        num10 = num4;
                        l7 = l3;
                    case 13:
                        l3 = l7;
                        str25 = str39;
                        str23 = str46;
                        str24 = str47;
                        bool5 = bool9;
                        num5 = num11;
                        i3 |= 8192;
                        Unit unit15 = Unit.INSTANCE;
                        str22 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 13, StringSerializer.INSTANCE, str45);
                        lazyArr2 = lazyArr;
                        jsonElement4 = jsonElement5;
                        str35 = str35;
                        bool4 = bool8;
                        str17 = str40;
                        str18 = str41;
                        str19 = str42;
                        str20 = str43;
                        l5 = l8;
                        list5 = list10;
                        list6 = list11;
                        merchantIcon2 = merchantIcon3;
                        num4 = num10;
                        merchantNotice2 = merchantNotice4;
                        str21 = str44;
                        str39 = str25;
                        l8 = l5;
                        bool9 = bool5;
                        str47 = str24;
                        str46 = str23;
                        num11 = num5;
                        str45 = str22;
                        str44 = str21;
                        merchantNotice4 = merchantNotice2;
                        bool8 = bool4;
                        str40 = str17;
                        str41 = str18;
                        str42 = str19;
                        str43 = str20;
                        lazyArr = lazyArr2;
                        list10 = list5;
                        list11 = list6;
                        merchantIcon3 = merchantIcon2;
                        num10 = num4;
                        l7 = l3;
                    case ConstantsKt.SPACER_14 /* 14 */:
                        l3 = l7;
                        str25 = str39;
                        str24 = str47;
                        bool5 = bool9;
                        str23 = str46;
                        i3 |= 16384;
                        Unit unit16 = Unit.INSTANCE;
                        lazyArr2 = lazyArr;
                        num5 = (Integer) beginStructure.decodeNullableSerializableElement(serialDescriptor, 14, IntSerializer.INSTANCE, num11);
                        jsonElement4 = jsonElement5;
                        str35 = str35;
                        bool4 = bool8;
                        str17 = str40;
                        str18 = str41;
                        str19 = str42;
                        str20 = str43;
                        l5 = l8;
                        list5 = list10;
                        list6 = list11;
                        merchantIcon2 = merchantIcon3;
                        num4 = num10;
                        merchantNotice2 = merchantNotice4;
                        str21 = str44;
                        str22 = str45;
                        str39 = str25;
                        l8 = l5;
                        bool9 = bool5;
                        str47 = str24;
                        str46 = str23;
                        num11 = num5;
                        str45 = str22;
                        str44 = str21;
                        merchantNotice4 = merchantNotice2;
                        bool8 = bool4;
                        str40 = str17;
                        str41 = str18;
                        str42 = str19;
                        str43 = str20;
                        lazyArr = lazyArr2;
                        list10 = list5;
                        list11 = list6;
                        merchantIcon3 = merchantIcon2;
                        num10 = num4;
                        l7 = l3;
                    case 15:
                        l3 = l7;
                        str25 = str39;
                        bool5 = bool9;
                        str24 = str47;
                        i3 |= 32768;
                        Unit unit17 = Unit.INSTANCE;
                        str23 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 15, StringSerializer.INSTANCE, str46);
                        lazyArr2 = lazyArr;
                        jsonElement4 = jsonElement5;
                        str35 = str35;
                        bool4 = bool8;
                        str17 = str40;
                        str18 = str41;
                        str19 = str42;
                        str20 = str43;
                        l5 = l8;
                        list5 = list10;
                        list6 = list11;
                        merchantIcon2 = merchantIcon3;
                        num4 = num10;
                        merchantNotice2 = merchantNotice4;
                        str21 = str44;
                        str22 = str45;
                        num5 = num11;
                        str39 = str25;
                        l8 = l5;
                        bool9 = bool5;
                        str47 = str24;
                        str46 = str23;
                        num11 = num5;
                        str45 = str22;
                        str44 = str21;
                        merchantNotice4 = merchantNotice2;
                        bool8 = bool4;
                        str40 = str17;
                        str41 = str18;
                        str42 = str19;
                        str43 = str20;
                        lazyArr = lazyArr2;
                        list10 = list5;
                        list11 = list6;
                        merchantIcon3 = merchantIcon2;
                        num10 = num4;
                        l7 = l3;
                    case 16:
                        l3 = l7;
                        str25 = str39;
                        bool5 = bool9;
                        i3 |= 65536;
                        Unit unit18 = Unit.INSTANCE;
                        lazyArr2 = lazyArr;
                        str24 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 16, StringSerializer.INSTANCE, str47);
                        jsonElement4 = jsonElement5;
                        str35 = str35;
                        bool4 = bool8;
                        str17 = str40;
                        str18 = str41;
                        str19 = str42;
                        str20 = str43;
                        l5 = l8;
                        list5 = list10;
                        list6 = list11;
                        merchantIcon2 = merchantIcon3;
                        num4 = num10;
                        merchantNotice2 = merchantNotice4;
                        str21 = str44;
                        str22 = str45;
                        num5 = num11;
                        str23 = str46;
                        str39 = str25;
                        l8 = l5;
                        bool9 = bool5;
                        str47 = str24;
                        str46 = str23;
                        num11 = num5;
                        str45 = str22;
                        str44 = str21;
                        merchantNotice4 = merchantNotice2;
                        bool8 = bool4;
                        str40 = str17;
                        str41 = str18;
                        str42 = str19;
                        str43 = str20;
                        lazyArr = lazyArr2;
                        list10 = list5;
                        list11 = list6;
                        merchantIcon3 = merchantIcon2;
                        num10 = num4;
                        l7 = l3;
                    case 17:
                        l3 = l7;
                        str25 = str39;
                        i3 |= 131072;
                        Unit unit19 = Unit.INSTANCE;
                        bool5 = (Boolean) beginStructure.decodeNullableSerializableElement(serialDescriptor, 17, BooleanSerializer.INSTANCE, bool9);
                        lazyArr2 = lazyArr;
                        jsonElement4 = jsonElement5;
                        str35 = str35;
                        bool4 = bool8;
                        str17 = str40;
                        str18 = str41;
                        str19 = str42;
                        str20 = str43;
                        l5 = l8;
                        list5 = list10;
                        list6 = list11;
                        merchantIcon2 = merchantIcon3;
                        num4 = num10;
                        merchantNotice2 = merchantNotice4;
                        str21 = str44;
                        str22 = str45;
                        num5 = num11;
                        str23 = str46;
                        str24 = str47;
                        str39 = str25;
                        l8 = l5;
                        bool9 = bool5;
                        str47 = str24;
                        str46 = str23;
                        num11 = num5;
                        str45 = str22;
                        str44 = str21;
                        merchantNotice4 = merchantNotice2;
                        bool8 = bool4;
                        str40 = str17;
                        str41 = str18;
                        str42 = str19;
                        str43 = str20;
                        lazyArr = lazyArr2;
                        list10 = list5;
                        list11 = list6;
                        merchantIcon3 = merchantIcon2;
                        num10 = num4;
                        l7 = l3;
                    case 18:
                        l3 = l7;
                        str25 = str39;
                        jsonElement4 = (JsonElement) beginStructure.decodeNullableSerializableElement(serialDescriptor, 18, JsonElementSerializer.INSTANCE, jsonElement5);
                        i3 |= 262144;
                        Unit unit20 = Unit.INSTANCE;
                        lazyArr2 = lazyArr;
                        bool4 = bool8;
                        str17 = str40;
                        str18 = str41;
                        str19 = str42;
                        str20 = str43;
                        l5 = l8;
                        list5 = list10;
                        list6 = list11;
                        merchantIcon2 = merchantIcon3;
                        num4 = num10;
                        merchantNotice2 = merchantNotice4;
                        str21 = str44;
                        str22 = str45;
                        num5 = num11;
                        str23 = str46;
                        str24 = str47;
                        bool5 = bool9;
                        str39 = str25;
                        l8 = l5;
                        bool9 = bool5;
                        str47 = str24;
                        str46 = str23;
                        num11 = num5;
                        str45 = str22;
                        str44 = str21;
                        merchantNotice4 = merchantNotice2;
                        bool8 = bool4;
                        str40 = str17;
                        str41 = str18;
                        str42 = str19;
                        str43 = str20;
                        lazyArr = lazyArr2;
                        list10 = list5;
                        list11 = list6;
                        merchantIcon3 = merchantIcon2;
                        num10 = num4;
                        l7 = l3;
                    case 19:
                        DeserializationStrategy deserializationStrategy3 = StringSerializer.INSTANCE;
                        l3 = l7;
                        i3 |= 524288;
                        Unit unit21 = Unit.INSTANCE;
                        str39 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 19, deserializationStrategy3, str39);
                        lazyArr2 = lazyArr;
                        bool4 = bool8;
                        str17 = str40;
                        str18 = str41;
                        str19 = str42;
                        str20 = str43;
                        l5 = l8;
                        list5 = list10;
                        list6 = list11;
                        merchantIcon2 = merchantIcon3;
                        num4 = num10;
                        merchantNotice2 = merchantNotice4;
                        str21 = str44;
                        str22 = str45;
                        num5 = num11;
                        str23 = str46;
                        str24 = str47;
                        bool5 = bool9;
                        jsonElement4 = jsonElement5;
                        l8 = l5;
                        bool9 = bool5;
                        str47 = str24;
                        str46 = str23;
                        num11 = num5;
                        str45 = str22;
                        str44 = str21;
                        merchantNotice4 = merchantNotice2;
                        bool8 = bool4;
                        str40 = str17;
                        str41 = str18;
                        str42 = str19;
                        str43 = str20;
                        lazyArr = lazyArr2;
                        list10 = list5;
                        list11 = list6;
                        merchantIcon3 = merchantIcon2;
                        num10 = num4;
                        l7 = l3;
                    case 20:
                        str25 = str39;
                        i3 |= 1048576;
                        Unit unit22 = Unit.INSTANCE;
                        l3 = l7;
                        lazyArr2 = lazyArr;
                        list9 = (List) beginStructure.decodeNullableSerializableElement(serialDescriptor, 20, (DeserializationStrategy) lazyArr[20].getValue(), list9);
                        bool4 = bool8;
                        str17 = str40;
                        str18 = str41;
                        str19 = str42;
                        str20 = str43;
                        l5 = l8;
                        list5 = list10;
                        list6 = list11;
                        merchantIcon2 = merchantIcon3;
                        num4 = num10;
                        merchantNotice2 = merchantNotice4;
                        str21 = str44;
                        str22 = str45;
                        num5 = num11;
                        str23 = str46;
                        str24 = str47;
                        bool5 = bool9;
                        jsonElement4 = jsonElement5;
                        str39 = str25;
                        l8 = l5;
                        bool9 = bool5;
                        str47 = str24;
                        str46 = str23;
                        num11 = num5;
                        str45 = str22;
                        str44 = str21;
                        merchantNotice4 = merchantNotice2;
                        bool8 = bool4;
                        str40 = str17;
                        str41 = str18;
                        str42 = str19;
                        str43 = str20;
                        lazyArr = lazyArr2;
                        list10 = list5;
                        list11 = list6;
                        merchantIcon3 = merchantIcon2;
                        num10 = num4;
                        l7 = l3;
                    case 21:
                        str25 = str39;
                        i3 |= 2097152;
                        Unit unit23 = Unit.INSTANCE;
                        l3 = l7;
                        lazyArr2 = lazyArr;
                        shareInfo3 = (ProductShopDetailsMerchantInfo.ShareInfo) beginStructure.decodeNullableSerializableElement(serialDescriptor, 21, ProductShopDetailsMerchantInfo$ShareInfo$$serializer.INSTANCE, shareInfo3);
                        bool4 = bool8;
                        str17 = str40;
                        str18 = str41;
                        str19 = str42;
                        str20 = str43;
                        l5 = l8;
                        list5 = list10;
                        list6 = list11;
                        merchantIcon2 = merchantIcon3;
                        num4 = num10;
                        merchantNotice2 = merchantNotice4;
                        str21 = str44;
                        str22 = str45;
                        num5 = num11;
                        str23 = str46;
                        str24 = str47;
                        bool5 = bool9;
                        jsonElement4 = jsonElement5;
                        str39 = str25;
                        l8 = l5;
                        bool9 = bool5;
                        str47 = str24;
                        str46 = str23;
                        num11 = num5;
                        str45 = str22;
                        str44 = str21;
                        merchantNotice4 = merchantNotice2;
                        bool8 = bool4;
                        str40 = str17;
                        str41 = str18;
                        str42 = str19;
                        str43 = str20;
                        lazyArr = lazyArr2;
                        list10 = list5;
                        list11 = list6;
                        merchantIcon3 = merchantIcon2;
                        num10 = num4;
                        l7 = l3;
                    case 22:
                        str25 = str39;
                        i3 |= 4194304;
                        Unit unit24 = Unit.INSTANCE;
                        l3 = l7;
                        lazyArr2 = lazyArr;
                        str37 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 22, StringSerializer.INSTANCE, str37);
                        bool4 = bool8;
                        str17 = str40;
                        str18 = str41;
                        str19 = str42;
                        str20 = str43;
                        l5 = l8;
                        list5 = list10;
                        list6 = list11;
                        merchantIcon2 = merchantIcon3;
                        num4 = num10;
                        merchantNotice2 = merchantNotice4;
                        str21 = str44;
                        str22 = str45;
                        num5 = num11;
                        str23 = str46;
                        str24 = str47;
                        bool5 = bool9;
                        jsonElement4 = jsonElement5;
                        str39 = str25;
                        l8 = l5;
                        bool9 = bool5;
                        str47 = str24;
                        str46 = str23;
                        num11 = num5;
                        str45 = str22;
                        str44 = str21;
                        merchantNotice4 = merchantNotice2;
                        bool8 = bool4;
                        str40 = str17;
                        str41 = str18;
                        str42 = str19;
                        str43 = str20;
                        lazyArr = lazyArr2;
                        list10 = list5;
                        list11 = list6;
                        merchantIcon3 = merchantIcon2;
                        num10 = num4;
                        l7 = l3;
                    case 23:
                        str25 = str39;
                        i3 |= 8388608;
                        Unit unit25 = Unit.INSTANCE;
                        l3 = l7;
                        lazyArr2 = lazyArr;
                        list8 = (List) beginStructure.decodeNullableSerializableElement(serialDescriptor, 23, (DeserializationStrategy) lazyArr[23].getValue(), list8);
                        bool4 = bool8;
                        str17 = str40;
                        str18 = str41;
                        str19 = str42;
                        str20 = str43;
                        l5 = l8;
                        list5 = list10;
                        list6 = list11;
                        merchantIcon2 = merchantIcon3;
                        num4 = num10;
                        merchantNotice2 = merchantNotice4;
                        str21 = str44;
                        str22 = str45;
                        num5 = num11;
                        str23 = str46;
                        str24 = str47;
                        bool5 = bool9;
                        jsonElement4 = jsonElement5;
                        str39 = str25;
                        l8 = l5;
                        bool9 = bool5;
                        str47 = str24;
                        str46 = str23;
                        num11 = num5;
                        str45 = str22;
                        str44 = str21;
                        merchantNotice4 = merchantNotice2;
                        bool8 = bool4;
                        str40 = str17;
                        str41 = str18;
                        str42 = str19;
                        str43 = str20;
                        lazyArr = lazyArr2;
                        list10 = list5;
                        list11 = list6;
                        merchantIcon3 = merchantIcon2;
                        num10 = num4;
                        l7 = l3;
                    case 24:
                        str25 = str39;
                        l7 = (Long) beginStructure.decodeNullableSerializableElement(serialDescriptor, 24, LongSerializer.INSTANCE, l7);
                        i2 = 16777216;
                        i3 |= i2;
                        Unit unit26 = Unit.INSTANCE;
                        l3 = l7;
                        lazyArr2 = lazyArr;
                        bool4 = bool8;
                        str17 = str40;
                        str18 = str41;
                        str19 = str42;
                        str20 = str43;
                        l5 = l8;
                        list5 = list10;
                        list6 = list11;
                        merchantIcon2 = merchantIcon3;
                        num4 = num10;
                        merchantNotice2 = merchantNotice4;
                        str21 = str44;
                        str22 = str45;
                        num5 = num11;
                        str23 = str46;
                        str24 = str47;
                        bool5 = bool9;
                        jsonElement4 = jsonElement5;
                        str39 = str25;
                        l8 = l5;
                        bool9 = bool5;
                        str47 = str24;
                        str46 = str23;
                        num11 = num5;
                        str45 = str22;
                        str44 = str21;
                        merchantNotice4 = merchantNotice2;
                        bool8 = bool4;
                        str40 = str17;
                        str41 = str18;
                        str42 = str19;
                        str43 = str20;
                        lazyArr = lazyArr2;
                        list10 = list5;
                        list11 = list6;
                        merchantIcon3 = merchantIcon2;
                        num10 = num4;
                        l7 = l3;
                    case 25:
                        str25 = str39;
                        str35 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 25, StringSerializer.INSTANCE, str35);
                        i2 = 33554432;
                        i3 |= i2;
                        Unit unit262 = Unit.INSTANCE;
                        l3 = l7;
                        lazyArr2 = lazyArr;
                        bool4 = bool8;
                        str17 = str40;
                        str18 = str41;
                        str19 = str42;
                        str20 = str43;
                        l5 = l8;
                        list5 = list10;
                        list6 = list11;
                        merchantIcon2 = merchantIcon3;
                        num4 = num10;
                        merchantNotice2 = merchantNotice4;
                        str21 = str44;
                        str22 = str45;
                        num5 = num11;
                        str23 = str46;
                        str24 = str47;
                        bool5 = bool9;
                        jsonElement4 = jsonElement5;
                        str39 = str25;
                        l8 = l5;
                        bool9 = bool5;
                        str47 = str24;
                        str46 = str23;
                        num11 = num5;
                        str45 = str22;
                        str44 = str21;
                        merchantNotice4 = merchantNotice2;
                        bool8 = bool4;
                        str40 = str17;
                        str41 = str18;
                        str42 = str19;
                        str43 = str20;
                        lazyArr = lazyArr2;
                        list10 = list5;
                        list11 = list6;
                        merchantIcon3 = merchantIcon2;
                        num10 = num4;
                        l7 = l3;
                    case 26:
                        str25 = str39;
                        i3 |= 67108864;
                        Unit unit27 = Unit.INSTANCE;
                        l3 = l7;
                        lazyArr2 = lazyArr;
                        str48 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 26, StringSerializer.INSTANCE, str48);
                        bool4 = bool8;
                        str17 = str40;
                        str18 = str41;
                        str19 = str42;
                        str20 = str43;
                        l5 = l8;
                        list5 = list10;
                        list6 = list11;
                        merchantIcon2 = merchantIcon3;
                        num4 = num10;
                        merchantNotice2 = merchantNotice4;
                        str21 = str44;
                        str22 = str45;
                        num5 = num11;
                        str23 = str46;
                        str24 = str47;
                        bool5 = bool9;
                        jsonElement4 = jsonElement5;
                        str39 = str25;
                        l8 = l5;
                        bool9 = bool5;
                        str47 = str24;
                        str46 = str23;
                        num11 = num5;
                        str45 = str22;
                        str44 = str21;
                        merchantNotice4 = merchantNotice2;
                        bool8 = bool4;
                        str40 = str17;
                        str41 = str18;
                        str42 = str19;
                        str43 = str20;
                        lazyArr = lazyArr2;
                        list10 = list5;
                        list11 = list6;
                        merchantIcon3 = merchantIcon2;
                        num10 = num4;
                        l7 = l3;
                    case 27:
                        str25 = str39;
                        i3 |= 134217728;
                        Unit unit28 = Unit.INSTANCE;
                        l3 = l7;
                        lazyArr2 = lazyArr;
                        str38 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 27, StringSerializer.INSTANCE, str38);
                        bool4 = bool8;
                        str17 = str40;
                        str18 = str41;
                        str19 = str42;
                        str20 = str43;
                        l5 = l8;
                        list5 = list10;
                        list6 = list11;
                        merchantIcon2 = merchantIcon3;
                        num4 = num10;
                        merchantNotice2 = merchantNotice4;
                        str21 = str44;
                        str22 = str45;
                        num5 = num11;
                        str23 = str46;
                        str24 = str47;
                        bool5 = bool9;
                        jsonElement4 = jsonElement5;
                        str39 = str25;
                        l8 = l5;
                        bool9 = bool5;
                        str47 = str24;
                        str46 = str23;
                        num11 = num5;
                        str45 = str22;
                        str44 = str21;
                        merchantNotice4 = merchantNotice2;
                        bool8 = bool4;
                        str40 = str17;
                        str41 = str18;
                        str42 = str19;
                        str43 = str20;
                        lazyArr = lazyArr2;
                        list10 = list5;
                        list11 = list6;
                        merchantIcon3 = merchantIcon2;
                        num10 = num4;
                        l7 = l3;
                    case 28:
                        str25 = str39;
                        i3 |= 268435456;
                        Unit unit29 = Unit.INSTANCE;
                        l3 = l7;
                        lazyArr2 = lazyArr;
                        num9 = (Integer) beginStructure.decodeNullableSerializableElement(serialDescriptor, 28, IntSerializer.INSTANCE, num9);
                        bool4 = bool8;
                        str17 = str40;
                        str18 = str41;
                        str19 = str42;
                        str20 = str43;
                        l5 = l8;
                        list5 = list10;
                        list6 = list11;
                        merchantIcon2 = merchantIcon3;
                        num4 = num10;
                        merchantNotice2 = merchantNotice4;
                        str21 = str44;
                        str22 = str45;
                        num5 = num11;
                        str23 = str46;
                        str24 = str47;
                        bool5 = bool9;
                        jsonElement4 = jsonElement5;
                        str39 = str25;
                        l8 = l5;
                        bool9 = bool5;
                        str47 = str24;
                        str46 = str23;
                        num11 = num5;
                        str45 = str22;
                        str44 = str21;
                        merchantNotice4 = merchantNotice2;
                        bool8 = bool4;
                        str40 = str17;
                        str41 = str18;
                        str42 = str19;
                        str43 = str20;
                        lazyArr = lazyArr2;
                        list10 = list5;
                        list11 = list6;
                        merchantIcon3 = merchantIcon2;
                        num10 = num4;
                        l7 = l3;
                    case 29:
                        str25 = str39;
                        str36 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 29, StringSerializer.INSTANCE, str36);
                        i2 = 536870912;
                        i3 |= i2;
                        Unit unit2622 = Unit.INSTANCE;
                        l3 = l7;
                        lazyArr2 = lazyArr;
                        bool4 = bool8;
                        str17 = str40;
                        str18 = str41;
                        str19 = str42;
                        str20 = str43;
                        l5 = l8;
                        list5 = list10;
                        list6 = list11;
                        merchantIcon2 = merchantIcon3;
                        num4 = num10;
                        merchantNotice2 = merchantNotice4;
                        str21 = str44;
                        str22 = str45;
                        num5 = num11;
                        str23 = str46;
                        str24 = str47;
                        bool5 = bool9;
                        jsonElement4 = jsonElement5;
                        str39 = str25;
                        l8 = l5;
                        bool9 = bool5;
                        str47 = str24;
                        str46 = str23;
                        num11 = num5;
                        str45 = str22;
                        str44 = str21;
                        merchantNotice4 = merchantNotice2;
                        bool8 = bool4;
                        str40 = str17;
                        str41 = str18;
                        str42 = str19;
                        str43 = str20;
                        lazyArr = lazyArr2;
                        list10 = list5;
                        list11 = list6;
                        merchantIcon3 = merchantIcon2;
                        num10 = num4;
                        l7 = l3;
                    default:
                        throw new UnknownFieldException(decodeElementIndex);
                }
            }
            Boolean bool10 = bool7;
            Boolean bool11 = bool8;
            num = num11;
            str = str36;
            num2 = num9;
            list = list8;
            str2 = str45;
            str3 = str44;
            str4 = str42;
            list2 = list10;
            l = l7;
            shareInfo = shareInfo3;
            i = i3;
            str5 = str47;
            str6 = str46;
            merchantNotice = merchantNotice4;
            str7 = str41;
            num3 = num10;
            str8 = str38;
            list3 = list9;
            bool = bool9;
            bool2 = bool11;
            str9 = str43;
            merchantIcon = merchantIcon3;
            str10 = str37;
            str11 = str48;
            jsonElement = jsonElement4;
            str12 = str40;
            str13 = str39;
            bool3 = bool10;
            l2 = l8;
            str14 = str35;
            list4 = list11;
        }
        beginStructure.endStructure(serialDescriptor);
        return new ProductShopDetailsMerchantInfo(i, bool3, bool2, str12, str7, str4, str9, l2, list2, list4, merchantIcon, num3, merchantNotice, str3, str2, num, str6, str5, bool, jsonElement, str13, list3, shareInfo, str10, list, l, str14, str11, str8, num2, str, (SerializationConstructorMarker) null);
    }

    public final void serialize(Encoder encoder, ProductShopDetailsMerchantInfo value) {
        Intrinsics.checkNotNullParameter(encoder, "encoder");
        Intrinsics.checkNotNullParameter(value, "value");
        SerialDescriptor serialDescriptor = descriptor;
        CompositeEncoder beginStructure = encoder.beginStructure(serialDescriptor);
        ProductShopDetailsMerchantInfo.write$Self$product_details_page_debug(value, beginStructure, serialDescriptor);
        beginStructure.endStructure(serialDescriptor);
    }

    public /* bridge */ KSerializer<?>[] typeParametersSerializers() {
        return GeneratedSerializer.DefaultImpls.typeParametersSerializers(this);
    }
}