package kntr.app.mall.product.details.page.api;

import com.bapis.bilibili.app.dynamic.v2.AdditionalButton;
import java.util.List;
import kntr.app.mall.product.details.page.api.ProductShopDetailsHotItem;
import kntr.app.upcomingEpisode.ConstantsKt;
import kntr.watch.later.watchlater.edit.MediaAttrUtils;
import kotlin.Deprecated;
import kotlin.DeprecationLevel;
import kotlin.Lazy;
import kotlin.Metadata;
import kotlin.Unit;
import kotlin.jvm.internal.Intrinsics;
import kotlinx.serialization.DeserializationStrategy;
import kotlinx.serialization.KSerializer;
import kotlinx.serialization.UnknownFieldException;
import kotlinx.serialization.builtins.BuiltinSerializersKt;
import kotlinx.serialization.descriptors.SerialDescriptor;
import kotlinx.serialization.encoding.CompositeDecoder;
import kotlinx.serialization.encoding.CompositeEncoder;
import kotlinx.serialization.encoding.Decoder;
import kotlinx.serialization.encoding.Encoder;
import kotlinx.serialization.internal.ByteSerializer;
import kotlinx.serialization.internal.GeneratedSerializer;
import kotlinx.serialization.internal.IntSerializer;
import kotlinx.serialization.internal.LongSerializer;
import kotlinx.serialization.internal.PluginGeneratedSerialDescriptor;
import kotlinx.serialization.internal.SerializationConstructorMarker;
import kotlinx.serialization.internal.StringSerializer;

/* compiled from: ProductShopApiService.kt */
@Metadata(d1 = {"\u00006\n\u0000\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\b\u0003\n\u0002\u0010\u0011\n\u0002\u0018\u0002\n\u0002\b\u0003\n\u0002\u0018\u0002\n\u0000\n\u0002\u0010\u0002\n\u0000\n\u0002\u0018\u0002\n\u0002\b\u0002\n\u0002\u0018\u0002\n\u0002\b\u0003\bÇ\u0002\u0018\u00002\b\u0012\u0004\u0012\u00020\u00020\u0001B\t\b\u0002¢\u0006\u0004\b\u0003\u0010\u0004J\u0015\u0010\u0005\u001a\f\u0012\b\u0012\u0006\u0012\u0002\b\u00030\u00070\u0006¢\u0006\u0002\u0010\bJ\u000e\u0010\t\u001a\u00020\u00022\u0006\u0010\n\u001a\u00020\u000bJ\u0016\u0010\f\u001a\u00020\r2\u0006\u0010\u000e\u001a\u00020\u000f2\u0006\u0010\u0010\u001a\u00020\u0002R\u0011\u0010\u0011\u001a\u00020\u0012¢\u0006\b\n\u0000\u001a\u0004\b\u0013\u0010\u0014¨\u0006\u0015"}, d2 = {"kntr/app/mall/product/details/page/api/ProductShopDetailsHotItem.$serializer", "Lkotlinx/serialization/internal/GeneratedSerializer;", "Lkntr/app/mall/product/details/page/api/ProductShopDetailsHotItem;", "<init>", "()V", "childSerializers", "", "Lkotlinx/serialization/KSerializer;", "()[Lkotlinx/serialization/KSerializer;", "deserialize", "decoder", "Lkotlinx/serialization/encoding/Decoder;", "serialize", "", "encoder", "Lkotlinx/serialization/encoding/Encoder;", "value", "descriptor", "Lkotlinx/serialization/descriptors/SerialDescriptor;", "getDescriptor", "()Lkotlinx/serialization/descriptors/SerialDescriptor;", "product-details-page_debug"}, k = 1, mv = {2, 2, 0}, xi = ConstantsKt.OGV_UPDATE_CALENDAR_CARD_COVER_WIDTH)
@Deprecated(level = DeprecationLevel.HIDDEN, message = "This synthesized declaration should not be used directly")
public final /* synthetic */ class ProductShopDetailsHotItem$$serializer implements GeneratedSerializer<ProductShopDetailsHotItem> {
    public static final int $stable;
    public static final ProductShopDetailsHotItem$$serializer INSTANCE = new ProductShopDetailsHotItem$$serializer();
    private static final SerialDescriptor descriptor;

    public final SerialDescriptor getDescriptor() {
        return descriptor;
    }

    static {
        SerialDescriptor pluginGeneratedSerialDescriptor = new PluginGeneratedSerialDescriptor("kntr.app.mall.product.details.page.api.ProductShopDetailsHotItem", INSTANCE, 28);
        pluginGeneratedSerialDescriptor.addElement("coin", true);
        pluginGeneratedSerialDescriptor.addElement("d7Pv", true);
        pluginGeneratedSerialDescriptor.addElement("depositType", true);
        pluginGeneratedSerialDescriptor.addElement("img", true);
        pluginGeneratedSerialDescriptor.addElement("isMagnetic", true);
        pluginGeneratedSerialDescriptor.addElement("itemsAttrList", true);
        pluginGeneratedSerialDescriptor.addElement("itemsId", true);
        pluginGeneratedSerialDescriptor.addElement("itemsTagVO", true);
        pluginGeneratedSerialDescriptor.addElement("itemsType", true);
        pluginGeneratedSerialDescriptor.addElement("jumpUrl", true);
        pluginGeneratedSerialDescriptor.addElement("lastRewardPrice", true);
        pluginGeneratedSerialDescriptor.addElement("like", true);
        pluginGeneratedSerialDescriptor.addElement("logData", true);
        pluginGeneratedSerialDescriptor.addElement("maxPrice", true);
        pluginGeneratedSerialDescriptor.addElement("name", true);
        pluginGeneratedSerialDescriptor.addElement("payType", true);
        pluginGeneratedSerialDescriptor.addElement("price", true);
        pluginGeneratedSerialDescriptor.addElement("priceDesc", true);
        pluginGeneratedSerialDescriptor.addElement("pricePrefix", true);
        pluginGeneratedSerialDescriptor.addElement("priceSymbol", true);
        pluginGeneratedSerialDescriptor.addElement("pubTime", true);
        pluginGeneratedSerialDescriptor.addElement("rareNum", true);
        pluginGeneratedSerialDescriptor.addElement("recId", true);
        pluginGeneratedSerialDescriptor.addElement("saleType", true);
        pluginGeneratedSerialDescriptor.addElement("shopId", true);
        pluginGeneratedSerialDescriptor.addElement("subSaleType", true);
        pluginGeneratedSerialDescriptor.addElement("totalNum", true);
        pluginGeneratedSerialDescriptor.addElement("wishSuccessNum", true);
        descriptor = pluginGeneratedSerialDescriptor;
        $stable = 8;
    }

    private ProductShopDetailsHotItem$$serializer() {
    }

    public final KSerializer<?>[] childSerializers() {
        Lazy[] lazyArr;
        lazyArr = ProductShopDetailsHotItem.$childSerializers;
        return new KSerializer[]{BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(LongSerializer.INSTANCE), BuiltinSerializersKt.getNullable(IntSerializer.INSTANCE), BuiltinSerializersKt.getNullable((KSerializer) lazyArr[3].getValue()), BuiltinSerializersKt.getNullable(ByteSerializer.INSTANCE), BuiltinSerializersKt.getNullable((KSerializer) lazyArr[5].getValue()), BuiltinSerializersKt.getNullable(LongSerializer.INSTANCE), BuiltinSerializersKt.getNullable(ProductShopDetailsHotItem$ItemsTag$$serializer.INSTANCE), BuiltinSerializersKt.getNullable(IntSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(IntSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(ByteSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable((KSerializer) lazyArr[17].getValue()), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(IntSerializer.INSTANCE), BuiltinSerializersKt.getNullable(IntSerializer.INSTANCE), BuiltinSerializersKt.getNullable(StringSerializer.INSTANCE), BuiltinSerializersKt.getNullable(ByteSerializer.INSTANCE), BuiltinSerializersKt.getNullable(IntSerializer.INSTANCE), BuiltinSerializersKt.getNullable(ByteSerializer.INSTANCE), BuiltinSerializersKt.getNullable(IntSerializer.INSTANCE), BuiltinSerializersKt.getNullable(LongSerializer.INSTANCE)};
    }

    public final ProductShopDetailsHotItem deserialize(Decoder decoder) {
        Lazy[] lazyArr;
        String str;
        String str2;
        Long l;
        Integer num;
        Integer num2;
        Long l2;
        List list;
        Long l3;
        String str3;
        Integer num3;
        String str4;
        Integer num4;
        Byte b;
        String str5;
        Byte b2;
        int i;
        Byte b3;
        Integer num5;
        String str6;
        Integer num6;
        List list2;
        ProductShopDetailsHotItem.ItemsTag itemsTag;
        Integer num7;
        String str7;
        Byte b4;
        List list3;
        String str8;
        String str9;
        String str10;
        Integer num8;
        Lazy[] lazyArr2;
        Byte b5;
        List list4;
        Long l4;
        Integer num9;
        List list5;
        Byte b6;
        List list6;
        Long l5;
        ProductShopDetailsHotItem.ItemsTag itemsTag2;
        Integer num10;
        String str11;
        String str12;
        Integer num11;
        String str13;
        String str14;
        String str15;
        Byte b7;
        Byte b8;
        List list7;
        int i2;
        Intrinsics.checkNotNullParameter(decoder, "decoder");
        SerialDescriptor serialDescriptor = descriptor;
        CompositeDecoder beginStructure = decoder.beginStructure(serialDescriptor);
        lazyArr = ProductShopDetailsHotItem.$childSerializers;
        if (beginStructure.decodeSequentially()) {
            String str16 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 10, StringSerializer.INSTANCE, (Object) null);
            Integer num12 = (Integer) beginStructure.decodeNullableSerializableElement(serialDescriptor, 11, IntSerializer.INSTANCE, (Object) null);
            String str17 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 12, StringSerializer.INSTANCE, (Object) null);
            String str18 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 13, StringSerializer.INSTANCE, (Object) null);
            String str19 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 14, StringSerializer.INSTANCE, (Object) null);
            Byte b9 = (Byte) beginStructure.decodeNullableSerializableElement(serialDescriptor, 15, ByteSerializer.INSTANCE, (Object) null);
            String str20 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 16, StringSerializer.INSTANCE, (Object) null);
            String str21 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 18, StringSerializer.INSTANCE, (Object) null);
            String str22 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 19, StringSerializer.INSTANCE, (Object) null);
            Integer num13 = (Integer) beginStructure.decodeNullableSerializableElement(serialDescriptor, 20, IntSerializer.INSTANCE, (Object) null);
            Integer num14 = (Integer) beginStructure.decodeNullableSerializableElement(serialDescriptor, 21, IntSerializer.INSTANCE, (Object) null);
            String str23 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 22, StringSerializer.INSTANCE, (Object) null);
            Byte b10 = (Byte) beginStructure.decodeNullableSerializableElement(serialDescriptor, 23, ByteSerializer.INSTANCE, (Object) null);
            Integer num15 = (Integer) beginStructure.decodeNullableSerializableElement(serialDescriptor, 24, IntSerializer.INSTANCE, (Object) null);
            Byte b11 = (Byte) beginStructure.decodeNullableSerializableElement(serialDescriptor, 25, ByteSerializer.INSTANCE, (Object) null);
            Integer num16 = (Integer) beginStructure.decodeNullableSerializableElement(serialDescriptor, 26, IntSerializer.INSTANCE, (Object) null);
            l = (Long) beginStructure.decodeNullableSerializableElement(serialDescriptor, 27, LongSerializer.INSTANCE, (Object) null);
            b2 = (Byte) beginStructure.decodeNullableSerializableElement(serialDescriptor, 4, ByteSerializer.INSTANCE, (Object) null);
            num4 = num14;
            num2 = num12;
            str7 = str23;
            b4 = b10;
            num6 = num15;
            b3 = b11;
            num = num16;
            list2 = (List) beginStructure.decodeNullableSerializableElement(serialDescriptor, 17, (DeserializationStrategy) lazyArr[17].getValue(), (Object) null);
            num3 = num13;
            str2 = str22;
            str8 = str21;
            str4 = str20;
            str10 = str19;
            str5 = str16;
            l3 = (Long) beginStructure.decodeNullableSerializableElement(serialDescriptor, 6, LongSerializer.INSTANCE, (Object) null);
            num7 = (Integer) beginStructure.decodeNullableSerializableElement(serialDescriptor, 8, IntSerializer.INSTANCE, (Object) null);
            list = (List) beginStructure.decodeNullableSerializableElement(serialDescriptor, 5, (DeserializationStrategy) lazyArr[5].getValue(), (Object) null);
            itemsTag = (ProductShopDetailsHotItem.ItemsTag) beginStructure.decodeNullableSerializableElement(serialDescriptor, 7, ProductShopDetailsHotItem$ItemsTag$$serializer.INSTANCE, (Object) null);
            b = b9;
            l2 = (Long) beginStructure.decodeNullableSerializableElement(serialDescriptor, 1, LongSerializer.INSTANCE, (Object) null);
            str6 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 9, StringSerializer.INSTANCE, (Object) null);
            str3 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 0, StringSerializer.INSTANCE, (Object) null);
            list3 = (List) beginStructure.decodeNullableSerializableElement(serialDescriptor, 3, (DeserializationStrategy) lazyArr[3].getValue(), (Object) null);
            i = 268435455;
            num5 = (Integer) beginStructure.decodeNullableSerializableElement(serialDescriptor, 2, IntSerializer.INSTANCE, (Object) null);
            str9 = str17;
            str = str18;
        } else {
            boolean z = true;
            Integer num17 = null;
            Byte b12 = null;
            Integer num18 = null;
            String str24 = null;
            String str25 = null;
            String str26 = null;
            String str27 = null;
            List list8 = null;
            Long l6 = null;
            Byte b13 = null;
            Integer num19 = null;
            String str28 = null;
            Long l7 = null;
            Integer num20 = null;
            List list9 = null;
            Byte b14 = null;
            List list10 = null;
            Long l8 = null;
            ProductShopDetailsHotItem.ItemsTag itemsTag3 = null;
            Integer num21 = null;
            String str29 = null;
            String str30 = null;
            Integer num22 = null;
            String str31 = null;
            String str32 = null;
            String str33 = null;
            Byte b15 = null;
            int i3 = 0;
            Integer num23 = null;
            while (z) {
                String str34 = str26;
                int decodeElementIndex = beginStructure.decodeElementIndex(serialDescriptor);
                switch (decodeElementIndex) {
                    case -1:
                        num8 = num17;
                        lazyArr2 = lazyArr;
                        b5 = b12;
                        list4 = list8;
                        l4 = l7;
                        num9 = num20;
                        list5 = list9;
                        b6 = b14;
                        list6 = list10;
                        l5 = l8;
                        itemsTag2 = itemsTag3;
                        num10 = num21;
                        str11 = str29;
                        str12 = str30;
                        num11 = num22;
                        str13 = str31;
                        str14 = str32;
                        str15 = str33;
                        b7 = b15;
                        str26 = str34;
                        Unit unit = Unit.INSTANCE;
                        z = false;
                        num17 = num8;
                        b12 = b5;
                        b8 = b6;
                        list8 = list4;
                        b14 = b8;
                        b15 = b7;
                        str33 = str15;
                        str32 = str14;
                        str31 = str13;
                        num22 = num11;
                        l7 = l4;
                        num20 = num9;
                        list9 = list5;
                        lazyArr = lazyArr2;
                        list10 = list6;
                        l8 = l5;
                        itemsTag3 = itemsTag2;
                        num21 = num10;
                        str29 = str11;
                        str30 = str12;
                    case 0:
                        num8 = num17;
                        lazyArr2 = lazyArr;
                        b5 = b12;
                        list4 = list8;
                        num9 = num20;
                        list5 = list9;
                        b6 = b14;
                        list6 = list10;
                        l5 = l8;
                        itemsTag2 = itemsTag3;
                        num10 = num21;
                        str11 = str29;
                        str12 = str30;
                        num11 = num22;
                        str13 = str31;
                        str14 = str32;
                        str15 = str33;
                        b7 = b15;
                        str26 = str34;
                        l4 = l7;
                        i3 |= 1;
                        Unit unit2 = Unit.INSTANCE;
                        str28 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 0, StringSerializer.INSTANCE, str28);
                        num17 = num8;
                        b12 = b5;
                        b8 = b6;
                        list8 = list4;
                        b14 = b8;
                        b15 = b7;
                        str33 = str15;
                        str32 = str14;
                        str31 = str13;
                        num22 = num11;
                        l7 = l4;
                        num20 = num9;
                        list9 = list5;
                        lazyArr = lazyArr2;
                        list10 = list6;
                        l8 = l5;
                        itemsTag3 = itemsTag2;
                        num21 = num10;
                        str29 = str11;
                        str30 = str12;
                    case 1:
                        lazyArr2 = lazyArr;
                        Byte b16 = b12;
                        list4 = list8;
                        list5 = list9;
                        b6 = b14;
                        list6 = list10;
                        l5 = l8;
                        itemsTag2 = itemsTag3;
                        num10 = num21;
                        str11 = str29;
                        str12 = str30;
                        num11 = num22;
                        str13 = str31;
                        str14 = str32;
                        str15 = str33;
                        b7 = b15;
                        str26 = str34;
                        num9 = num20;
                        i3 |= 2;
                        Unit unit3 = Unit.INSTANCE;
                        l4 = (Long) beginStructure.decodeNullableSerializableElement(serialDescriptor, 1, LongSerializer.INSTANCE, l7);
                        num17 = num17;
                        b12 = b16;
                        b8 = b6;
                        list8 = list4;
                        b14 = b8;
                        b15 = b7;
                        str33 = str15;
                        str32 = str14;
                        str31 = str13;
                        num22 = num11;
                        l7 = l4;
                        num20 = num9;
                        list9 = list5;
                        lazyArr = lazyArr2;
                        list10 = list6;
                        l8 = l5;
                        itemsTag3 = itemsTag2;
                        num21 = num10;
                        str29 = str11;
                        str30 = str12;
                    case 2:
                        lazyArr2 = lazyArr;
                        Byte b17 = b12;
                        list4 = list8;
                        b6 = b14;
                        list6 = list10;
                        l5 = l8;
                        itemsTag2 = itemsTag3;
                        num10 = num21;
                        str11 = str29;
                        str12 = str30;
                        num11 = num22;
                        str13 = str31;
                        str14 = str32;
                        str15 = str33;
                        b7 = b15;
                        str26 = str34;
                        list5 = list9;
                        i3 |= 4;
                        Unit unit4 = Unit.INSTANCE;
                        num9 = (Integer) beginStructure.decodeNullableSerializableElement(serialDescriptor, 2, IntSerializer.INSTANCE, num20);
                        num17 = num17;
                        b12 = b17;
                        l4 = l7;
                        b8 = b6;
                        list8 = list4;
                        b14 = b8;
                        b15 = b7;
                        str33 = str15;
                        str32 = str14;
                        str31 = str13;
                        num22 = num11;
                        l7 = l4;
                        num20 = num9;
                        list9 = list5;
                        lazyArr = lazyArr2;
                        list10 = list6;
                        l8 = l5;
                        itemsTag3 = itemsTag2;
                        num21 = num10;
                        str29 = str11;
                        str30 = str12;
                    case 3:
                        Byte b18 = b12;
                        list4 = list8;
                        b6 = b14;
                        list6 = list10;
                        l5 = l8;
                        itemsTag2 = itemsTag3;
                        num10 = num21;
                        str11 = str29;
                        str12 = str30;
                        num11 = num22;
                        str13 = str31;
                        str14 = str32;
                        str15 = str33;
                        b7 = b15;
                        str26 = str34;
                        DeserializationStrategy deserializationStrategy = (DeserializationStrategy) lazyArr[3].getValue();
                        lazyArr2 = lazyArr;
                        i3 |= 8;
                        Unit unit5 = Unit.INSTANCE;
                        list5 = (List) beginStructure.decodeNullableSerializableElement(serialDescriptor, 3, deserializationStrategy, list9);
                        num17 = num17;
                        b12 = b18;
                        l4 = l7;
                        num9 = num20;
                        b8 = b6;
                        list8 = list4;
                        b14 = b8;
                        b15 = b7;
                        str33 = str15;
                        str32 = str14;
                        str31 = str13;
                        num22 = num11;
                        l7 = l4;
                        num20 = num9;
                        list9 = list5;
                        lazyArr = lazyArr2;
                        list10 = list6;
                        l8 = l5;
                        itemsTag3 = itemsTag2;
                        num21 = num10;
                        str29 = str11;
                        str30 = str12;
                    case 4:
                        List list11 = list8;
                        l5 = l8;
                        itemsTag2 = itemsTag3;
                        num10 = num21;
                        str11 = str29;
                        str12 = str30;
                        num11 = num22;
                        str13 = str31;
                        str14 = str32;
                        str15 = str33;
                        b7 = b15;
                        str26 = str34;
                        list6 = list10;
                        i3 |= 16;
                        Unit unit6 = Unit.INSTANCE;
                        lazyArr2 = lazyArr;
                        list8 = list11;
                        b12 = b12;
                        l4 = l7;
                        num9 = num20;
                        list5 = list9;
                        b8 = (Byte) beginStructure.decodeNullableSerializableElement(serialDescriptor, 4, ByteSerializer.INSTANCE, b14);
                        num17 = num17;
                        continue;
                        b14 = b8;
                        b15 = b7;
                        str33 = str15;
                        str32 = str14;
                        str31 = str13;
                        num22 = num11;
                        l7 = l4;
                        num20 = num9;
                        list9 = list5;
                        lazyArr = lazyArr2;
                        list10 = list6;
                        l8 = l5;
                        itemsTag3 = itemsTag2;
                        num21 = num10;
                        str29 = str11;
                        str30 = str12;
                    case 5:
                        Integer num24 = num17;
                        Byte b19 = b12;
                        itemsTag2 = itemsTag3;
                        num10 = num21;
                        str11 = str29;
                        str12 = str30;
                        num11 = num22;
                        str13 = str31;
                        str14 = str32;
                        str15 = str33;
                        b7 = b15;
                        str26 = str34;
                        DeserializationStrategy deserializationStrategy2 = (DeserializationStrategy) lazyArr[5].getValue();
                        l5 = l8;
                        i3 |= 32;
                        Unit unit7 = Unit.INSTANCE;
                        list6 = (List) beginStructure.decodeNullableSerializableElement(serialDescriptor, 5, deserializationStrategy2, list10);
                        lazyArr2 = lazyArr;
                        num17 = num24;
                        list8 = list8;
                        b12 = b19;
                        l4 = l7;
                        num9 = num20;
                        list5 = list9;
                        b8 = b14;
                        break;
                    case 6:
                        List list12 = list8;
                        num10 = num21;
                        str11 = str29;
                        str12 = str30;
                        num11 = num22;
                        str13 = str31;
                        str14 = str32;
                        str15 = str33;
                        b7 = b15;
                        str26 = str34;
                        itemsTag2 = itemsTag3;
                        i3 |= 64;
                        Unit unit8 = Unit.INSTANCE;
                        lazyArr2 = lazyArr;
                        l5 = (Long) beginStructure.decodeNullableSerializableElement(serialDescriptor, 6, LongSerializer.INSTANCE, l8);
                        num17 = num17;
                        list8 = list12;
                        b12 = b12;
                        l4 = l7;
                        num9 = num20;
                        list5 = list9;
                        b8 = b14;
                        list6 = list10;
                        break;
                    case AdditionalButton.CLICK_TYPE_FIELD_NUMBER /* 7 */:
                        List list13 = list8;
                        str11 = str29;
                        str12 = str30;
                        num11 = num22;
                        str13 = str31;
                        str14 = str32;
                        str15 = str33;
                        b7 = b15;
                        str26 = str34;
                        num10 = num21;
                        i3 |= 128;
                        Unit unit9 = Unit.INSTANCE;
                        itemsTag2 = (ProductShopDetailsHotItem.ItemsTag) beginStructure.decodeNullableSerializableElement(serialDescriptor, 7, ProductShopDetailsHotItem$ItemsTag$$serializer.INSTANCE, itemsTag3);
                        lazyArr2 = lazyArr;
                        num17 = num17;
                        list8 = list13;
                        b12 = b12;
                        l4 = l7;
                        num9 = num20;
                        list5 = list9;
                        b8 = b14;
                        list6 = list10;
                        l5 = l8;
                        break;
                    case 8:
                        List list14 = list8;
                        str12 = str30;
                        num11 = num22;
                        str13 = str31;
                        str14 = str32;
                        str15 = str33;
                        b7 = b15;
                        str26 = str34;
                        str11 = str29;
                        i3 |= 256;
                        Unit unit10 = Unit.INSTANCE;
                        lazyArr2 = lazyArr;
                        num10 = (Integer) beginStructure.decodeNullableSerializableElement(serialDescriptor, 8, IntSerializer.INSTANCE, num21);
                        num17 = num17;
                        list8 = list14;
                        b12 = b12;
                        l4 = l7;
                        num9 = num20;
                        list5 = list9;
                        b8 = b14;
                        list6 = list10;
                        l5 = l8;
                        itemsTag2 = itemsTag3;
                        break;
                    case ConstantsKt.SPACER_9 /* 9 */:
                        List list15 = list8;
                        num11 = num22;
                        str13 = str31;
                        str14 = str32;
                        str15 = str33;
                        b7 = b15;
                        str26 = str34;
                        str12 = str30;
                        i3 |= 512;
                        Unit unit11 = Unit.INSTANCE;
                        str11 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 9, StringSerializer.INSTANCE, str29);
                        lazyArr2 = lazyArr;
                        num17 = num17;
                        list8 = list15;
                        b12 = b12;
                        l4 = l7;
                        num9 = num20;
                        list5 = list9;
                        b8 = b14;
                        list6 = list10;
                        l5 = l8;
                        itemsTag2 = itemsTag3;
                        num10 = num21;
                        break;
                    case 10:
                        List list16 = list8;
                        str13 = str31;
                        str14 = str32;
                        str15 = str33;
                        b7 = b15;
                        str26 = str34;
                        num11 = num22;
                        i3 |= 1024;
                        Unit unit12 = Unit.INSTANCE;
                        lazyArr2 = lazyArr;
                        str12 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 10, StringSerializer.INSTANCE, str30);
                        num17 = num17;
                        list8 = list16;
                        b12 = b12;
                        l4 = l7;
                        num9 = num20;
                        list5 = list9;
                        b8 = b14;
                        list6 = list10;
                        l5 = l8;
                        itemsTag2 = itemsTag3;
                        num10 = num21;
                        str11 = str29;
                        break;
                    case MediaAttrUtils.TYPE_MENU /* 11 */:
                        List list17 = list8;
                        str14 = str32;
                        str15 = str33;
                        b7 = b15;
                        str26 = str34;
                        str13 = str31;
                        i3 |= 2048;
                        Unit unit13 = Unit.INSTANCE;
                        num11 = (Integer) beginStructure.decodeNullableSerializableElement(serialDescriptor, 11, IntSerializer.INSTANCE, num22);
                        lazyArr2 = lazyArr;
                        num17 = num17;
                        list8 = list17;
                        b12 = b12;
                        l4 = l7;
                        num9 = num20;
                        list5 = list9;
                        b8 = b14;
                        list6 = list10;
                        l5 = l8;
                        itemsTag2 = itemsTag3;
                        num10 = num21;
                        str11 = str29;
                        str12 = str30;
                        break;
                    case 12:
                        List list18 = list8;
                        str15 = str33;
                        b7 = b15;
                        str26 = str34;
                        str14 = str32;
                        i3 |= 4096;
                        Unit unit14 = Unit.INSTANCE;
                        lazyArr2 = lazyArr;
                        str13 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 12, StringSerializer.INSTANCE, str31);
                        num17 = num17;
                        list8 = list18;
                        b12 = b12;
                        l4 = l7;
                        num9 = num20;
                        list5 = list9;
                        b8 = b14;
                        list6 = list10;
                        l5 = l8;
                        itemsTag2 = itemsTag3;
                        num10 = num21;
                        str11 = str29;
                        str12 = str30;
                        num11 = num22;
                        break;
                    case 13:
                        List list19 = list8;
                        b7 = b15;
                        str26 = str34;
                        str15 = str33;
                        i3 |= 8192;
                        Unit unit15 = Unit.INSTANCE;
                        str14 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 13, StringSerializer.INSTANCE, str32);
                        lazyArr2 = lazyArr;
                        num17 = num17;
                        list8 = list19;
                        b12 = b12;
                        l4 = l7;
                        num9 = num20;
                        list5 = list9;
                        b8 = b14;
                        list6 = list10;
                        l5 = l8;
                        itemsTag2 = itemsTag3;
                        num10 = num21;
                        str11 = str29;
                        str12 = str30;
                        num11 = num22;
                        str13 = str31;
                        break;
                    case ConstantsKt.SPACER_14 /* 14 */:
                        List list20 = list8;
                        str26 = str34;
                        b7 = b15;
                        i3 |= 16384;
                        Unit unit16 = Unit.INSTANCE;
                        lazyArr2 = lazyArr;
                        str15 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 14, StringSerializer.INSTANCE, str33);
                        num17 = num17;
                        list8 = list20;
                        b12 = b12;
                        l4 = l7;
                        num9 = num20;
                        list5 = list9;
                        b8 = b14;
                        list6 = list10;
                        l5 = l8;
                        itemsTag2 = itemsTag3;
                        num10 = num21;
                        str11 = str29;
                        str12 = str30;
                        num11 = num22;
                        str13 = str31;
                        str14 = str32;
                        break;
                    case 15:
                        List list21 = list8;
                        str26 = str34;
                        i3 |= 32768;
                        Unit unit17 = Unit.INSTANCE;
                        b7 = (Byte) beginStructure.decodeNullableSerializableElement(serialDescriptor, 15, ByteSerializer.INSTANCE, b15);
                        lazyArr2 = lazyArr;
                        num17 = num17;
                        list8 = list21;
                        b12 = b12;
                        l4 = l7;
                        num9 = num20;
                        list5 = list9;
                        b8 = b14;
                        list6 = list10;
                        l5 = l8;
                        itemsTag2 = itemsTag3;
                        num10 = num21;
                        str11 = str29;
                        str12 = str30;
                        num11 = num22;
                        str13 = str31;
                        str14 = str32;
                        str15 = str33;
                        break;
                    case 16:
                        Integer num25 = num17;
                        List list22 = list8;
                        str26 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 16, StringSerializer.INSTANCE, str34);
                        i3 |= 65536;
                        Unit unit18 = Unit.INSTANCE;
                        lazyArr2 = lazyArr;
                        num17 = num25;
                        list8 = list22;
                        l4 = l7;
                        num9 = num20;
                        list5 = list9;
                        b8 = b14;
                        list6 = list10;
                        l5 = l8;
                        itemsTag2 = itemsTag3;
                        num10 = num21;
                        str11 = str29;
                        str12 = str30;
                        num11 = num22;
                        str13 = str31;
                        str14 = str32;
                        str15 = str33;
                        b7 = b15;
                        break;
                    case 17:
                        List list23 = list8;
                        DeserializationStrategy deserializationStrategy3 = (DeserializationStrategy) lazyArr[17].getValue();
                        i3 |= 131072;
                        Unit unit19 = Unit.INSTANCE;
                        list8 = (List) beginStructure.decodeNullableSerializableElement(serialDescriptor, 17, deserializationStrategy3, list23);
                        lazyArr2 = lazyArr;
                        num17 = num17;
                        l4 = l7;
                        num9 = num20;
                        list5 = list9;
                        b8 = b14;
                        list6 = list10;
                        l5 = l8;
                        itemsTag2 = itemsTag3;
                        num10 = num21;
                        str11 = str29;
                        str12 = str30;
                        num11 = num22;
                        str13 = str31;
                        str14 = str32;
                        str15 = str33;
                        b7 = b15;
                        str26 = str34;
                        break;
                    case 18:
                        list7 = list8;
                        str24 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 18, StringSerializer.INSTANCE, str24);
                        i2 = 262144;
                        i3 |= i2;
                        Unit unit20 = Unit.INSTANCE;
                        lazyArr2 = lazyArr;
                        l4 = l7;
                        num9 = num20;
                        list5 = list9;
                        b8 = b14;
                        list6 = list10;
                        l5 = l8;
                        itemsTag2 = itemsTag3;
                        num10 = num21;
                        str11 = str29;
                        str12 = str30;
                        num11 = num22;
                        str13 = str31;
                        str14 = str32;
                        str15 = str33;
                        b7 = b15;
                        str26 = str34;
                        list8 = list7;
                        break;
                    case 19:
                        list7 = list8;
                        i3 |= 524288;
                        Unit unit21 = Unit.INSTANCE;
                        lazyArr2 = lazyArr;
                        str27 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 19, StringSerializer.INSTANCE, str27);
                        l4 = l7;
                        num9 = num20;
                        list5 = list9;
                        b8 = b14;
                        list6 = list10;
                        l5 = l8;
                        itemsTag2 = itemsTag3;
                        num10 = num21;
                        str11 = str29;
                        str12 = str30;
                        num11 = num22;
                        str13 = str31;
                        str14 = str32;
                        str15 = str33;
                        b7 = b15;
                        str26 = str34;
                        list8 = list7;
                        break;
                    case 20:
                        list7 = list8;
                        num18 = (Integer) beginStructure.decodeNullableSerializableElement(serialDescriptor, 20, IntSerializer.INSTANCE, num18);
                        i2 = 1048576;
                        i3 |= i2;
                        Unit unit202 = Unit.INSTANCE;
                        lazyArr2 = lazyArr;
                        l4 = l7;
                        num9 = num20;
                        list5 = list9;
                        b8 = b14;
                        list6 = list10;
                        l5 = l8;
                        itemsTag2 = itemsTag3;
                        num10 = num21;
                        str11 = str29;
                        str12 = str30;
                        num11 = num22;
                        str13 = str31;
                        str14 = str32;
                        str15 = str33;
                        b7 = b15;
                        str26 = str34;
                        list8 = list7;
                        break;
                    case 21:
                        list7 = list8;
                        i3 |= 2097152;
                        Unit unit22 = Unit.INSTANCE;
                        lazyArr2 = lazyArr;
                        num19 = (Integer) beginStructure.decodeNullableSerializableElement(serialDescriptor, 21, IntSerializer.INSTANCE, num19);
                        l4 = l7;
                        num9 = num20;
                        list5 = list9;
                        b8 = b14;
                        list6 = list10;
                        l5 = l8;
                        itemsTag2 = itemsTag3;
                        num10 = num21;
                        str11 = str29;
                        str12 = str30;
                        num11 = num22;
                        str13 = str31;
                        str14 = str32;
                        str15 = str33;
                        b7 = b15;
                        str26 = str34;
                        list8 = list7;
                        break;
                    case 22:
                        list7 = list8;
                        str25 = (String) beginStructure.decodeNullableSerializableElement(serialDescriptor, 22, StringSerializer.INSTANCE, str25);
                        i2 = 4194304;
                        i3 |= i2;
                        Unit unit2022 = Unit.INSTANCE;
                        lazyArr2 = lazyArr;
                        l4 = l7;
                        num9 = num20;
                        list5 = list9;
                        b8 = b14;
                        list6 = list10;
                        l5 = l8;
                        itemsTag2 = itemsTag3;
                        num10 = num21;
                        str11 = str29;
                        str12 = str30;
                        num11 = num22;
                        str13 = str31;
                        str14 = str32;
                        str15 = str33;
                        b7 = b15;
                        str26 = str34;
                        list8 = list7;
                        break;
                    case 23:
                        list7 = list8;
                        i3 |= 8388608;
                        Unit unit23 = Unit.INSTANCE;
                        lazyArr2 = lazyArr;
                        b13 = (Byte) beginStructure.decodeNullableSerializableElement(serialDescriptor, 23, ByteSerializer.INSTANCE, b13);
                        l4 = l7;
                        num9 = num20;
                        list5 = list9;
                        b8 = b14;
                        list6 = list10;
                        l5 = l8;
                        itemsTag2 = itemsTag3;
                        num10 = num21;
                        str11 = str29;
                        str12 = str30;
                        num11 = num22;
                        str13 = str31;
                        str14 = str32;
                        str15 = str33;
                        b7 = b15;
                        str26 = str34;
                        list8 = list7;
                        break;
                    case 24:
                        list7 = list8;
                        num17 = (Integer) beginStructure.decodeNullableSerializableElement(serialDescriptor, 24, IntSerializer.INSTANCE, num17);
                        i2 = 16777216;
                        i3 |= i2;
                        Unit unit20222 = Unit.INSTANCE;
                        lazyArr2 = lazyArr;
                        l4 = l7;
                        num9 = num20;
                        list5 = list9;
                        b8 = b14;
                        list6 = list10;
                        l5 = l8;
                        itemsTag2 = itemsTag3;
                        num10 = num21;
                        str11 = str29;
                        str12 = str30;
                        num11 = num22;
                        str13 = str31;
                        str14 = str32;
                        str15 = str33;
                        b7 = b15;
                        str26 = str34;
                        list8 = list7;
                        break;
                    case 25:
                        list7 = list8;
                        b12 = (Byte) beginStructure.decodeNullableSerializableElement(serialDescriptor, 25, ByteSerializer.INSTANCE, b12);
                        i2 = 33554432;
                        i3 |= i2;
                        Unit unit202222 = Unit.INSTANCE;
                        lazyArr2 = lazyArr;
                        l4 = l7;
                        num9 = num20;
                        list5 = list9;
                        b8 = b14;
                        list6 = list10;
                        l5 = l8;
                        itemsTag2 = itemsTag3;
                        num10 = num21;
                        str11 = str29;
                        str12 = str30;
                        num11 = num22;
                        str13 = str31;
                        str14 = str32;
                        str15 = str33;
                        b7 = b15;
                        str26 = str34;
                        list8 = list7;
                        break;
                    case 26:
                        list7 = list8;
                        i3 |= 67108864;
                        Unit unit24 = Unit.INSTANCE;
                        lazyArr2 = lazyArr;
                        num23 = (Integer) beginStructure.decodeNullableSerializableElement(serialDescriptor, 26, IntSerializer.INSTANCE, num23);
                        l4 = l7;
                        num9 = num20;
                        list5 = list9;
                        b8 = b14;
                        list6 = list10;
                        l5 = l8;
                        itemsTag2 = itemsTag3;
                        num10 = num21;
                        str11 = str29;
                        str12 = str30;
                        num11 = num22;
                        str13 = str31;
                        str14 = str32;
                        str15 = str33;
                        b7 = b15;
                        str26 = str34;
                        list8 = list7;
                        break;
                    case 27:
                        list7 = list8;
                        i3 |= 134217728;
                        Unit unit25 = Unit.INSTANCE;
                        lazyArr2 = lazyArr;
                        l6 = (Long) beginStructure.decodeNullableSerializableElement(serialDescriptor, 27, LongSerializer.INSTANCE, l6);
                        l4 = l7;
                        num9 = num20;
                        list5 = list9;
                        b8 = b14;
                        list6 = list10;
                        l5 = l8;
                        itemsTag2 = itemsTag3;
                        num10 = num21;
                        str11 = str29;
                        str12 = str30;
                        num11 = num22;
                        str13 = str31;
                        str14 = str32;
                        str15 = str33;
                        b7 = b15;
                        str26 = str34;
                        list8 = list7;
                        break;
                    default:
                        throw new UnknownFieldException(decodeElementIndex);
                }
                b14 = b8;
                b15 = b7;
                str33 = str15;
                str32 = str14;
                str31 = str13;
                num22 = num11;
                l7 = l4;
                num20 = num9;
                list9 = list5;
                lazyArr = lazyArr2;
                list10 = list6;
                l8 = l5;
                itemsTag3 = itemsTag2;
                num21 = num10;
                str29 = str11;
                str30 = str12;
            }
            Integer num26 = num17;
            List list24 = list8;
            String str35 = str28;
            Long l9 = l7;
            str = str32;
            str2 = str27;
            l = l6;
            num = num23;
            num2 = num22;
            l2 = l9;
            list = list10;
            l3 = l8;
            str3 = str35;
            num3 = num18;
            str4 = str26;
            num4 = num19;
            b = b15;
            str5 = str30;
            b2 = b14;
            i = i3;
            b3 = b12;
            num5 = num20;
            str6 = str29;
            num6 = num26;
            list2 = list24;
            itemsTag = itemsTag3;
            num7 = num21;
            str7 = str25;
            b4 = b13;
            list3 = list9;
            str8 = str24;
            str9 = str31;
            str10 = str33;
        }
        beginStructure.endStructure(serialDescriptor);
        return new ProductShopDetailsHotItem(i, str3, l2, num5, list3, b2, list, l3, itemsTag, num7, str6, str5, num2, str9, str, str10, b, str4, list2, str8, str2, num3, num4, str7, b4, num6, b3, num, l, (SerializationConstructorMarker) null);
    }

    public final void serialize(Encoder encoder, ProductShopDetailsHotItem value) {
        Intrinsics.checkNotNullParameter(encoder, "encoder");
        Intrinsics.checkNotNullParameter(value, "value");
        SerialDescriptor serialDescriptor = descriptor;
        CompositeEncoder beginStructure = encoder.beginStructure(serialDescriptor);
        ProductShopDetailsHotItem.write$Self$product_details_page_debug(value, beginStructure, serialDescriptor);
        beginStructure.endStructure(serialDescriptor);
    }

    public /* bridge */ KSerializer<?>[] typeParametersSerializers() {
        return GeneratedSerializer.DefaultImpls.typeParametersSerializers(this);
    }
}